// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdl_model_fixed\Subsystem_ip2_src_MATLAB_Fun.v
// Created: 2024-12-21 14:39:09
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_ip2_src_MATLAB_Fun
// Source Path: hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/MATLAB Function
// Hierarchy Level: 2
// Model version: 1.110
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_ip2_src_MATLAB_Fun
          (clk,
           reset,
           enb,
           input_data,
           reset_1,
           min_out);


  input   clk;
  input   reset;
  input   enb;
  input   signed [11:0] input_data;  // sfix12_En11
  input   reset_1;
  output  signed [11:0] min_out;  // sfix12_En11


  reg signed [11:0] min_out_1;  // sfix12_En11
  reg signed [11:0] current_min;  // sfix12
  reg signed [11:0] current_min_next;  // sfix12_En11
  reg signed [11:0] current_min_temp;  // sfix12_En11


  always @(posedge clk)
    begin : MATLAB_Function_process
      if (reset == 1'b1) begin
        current_min <= 12'sb010000000000;
      end
      else begin
        if (enb) begin
          current_min <= current_min_next;
        end
      end
    end

  always @(current_min, input_data, reset_1) begin
    current_min_temp = current_min;
    // input_data: Input data stream (e.g., 16-bit integer)
    // reset: Reset signal (active high)
    // clk: Clock signal for sequential logic
    // Persistent variable to hold the current minimum value
    // Initialize persistent variable if it's the first time the function is called
    // On reset, set the minimum value back to infinity
    if (reset_1) begin
      current_min_temp = 12'sb010000000000;
    end
    else begin
      // Update the current minimum on each clock cycle
      if (input_data < current_min) begin
        current_min_temp = input_data;
      end
    end
    // Output the current minimum value
    min_out_1 = current_min_temp;
    current_min_next = current_min_temp;
  end



  assign min_out = min_out_1;

endmodule  // Subsystem_ip2_src_MATLAB_Fun

