// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdl_model_fixed\Subsystem_ip2_src_Upcast_Wor.v
// Created: 2024-12-21 14:39:10
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_ip2_src_Upcast_Wor

// Source Path: hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Upcast 
// Wordlengt
// Hierarchy Level: 4
// Model version: 1.110
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_ip2_src_Upcast_Wor
          (x_x,
           y_y,
           u_u,
           v_v);


  input   signed [16:0] x_x;  // sfix17_En14
  input   signed [16:0] y_y;  // sfix17_En14
  output  signed [16:0] u_u;  // sfix17_En14
  output  signed [16:0] v_v;  // sfix17_En14




  // Copyright 2019 The MathWorks, Inc.
  assign u_u = x_x;
  assign v_v = y_y;



endmodule  // Subsystem_ip2_src_Upcast_Wor

