// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdl_model_fixed\Subsystem_ip2_src_cordicSqua_block1.v
// Created: 2024-12-21 14:39:10
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_ip2_src_cordicSqua_block1

// Source Path: hdl_model_fixed/Subsystem1/myRMS/CORDIC Square Root HDL Optimized/Synchronous Subsystem/cordicSquareRootHDL
// Hierarchy Level: 4
// Model version: 1.110
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_ip2_src_cordicSqua_block1
          (clk,
           reset,
           enb,
           u_u,
           validIn,
           restart,
           dataOut,
           eOut,
           isZero,
           validOut);


  input   clk;
  input   reset;
  input   enb;
  input   [19:0] u_u;  // ufix20_En11
  input   validIn;
  input   restart;
  output  signed [19:0] dataOut;  // sfix20_En18
  output  signed [31:0] eOut;  // int32
  output  isZero;
  output  validOut;


  reg  [4:0] delayMatch_reg;  // ufix1 [5]
  wire restart_1;
  wire stateControl_1;
  reg  [4:0] delayMatch1_reg;  // ufix1 [5]
  wire stateControl_2;
  wire enb_gated;
  reg signed [19:0] dataOut_1;  // sfix20_En18
  reg signed [31:0] eOut_1;  // int32
  reg  isZero_1;
  reg  validOut_1;
  reg [19:0] xRegNorm [0:5];  // ufix20 [6]
  reg signed [19:0] xRegCORDIC [0:20];  // sfix20 [21]
  reg signed [19:0] yReg [0:20];  // sfix20 [21]
  reg [4:0] eRegNorm [0:5];  // ufix5 [6]
  reg signed [31:0] eRegCORDIC [0:20];  // sfix32 [21]
  reg  [27:0] validReg_1;  // boolean [28]
  reg signed [19:0] dataOutReg;  // sfix20
  reg signed [31:0] eOutReg;  // sfix32
  reg  [27:0] isZeroReg_1;  // boolean [28]
  reg [19:0] xRegNorm_next [0:5];  // ufix20 [6]
  reg signed [19:0] xRegCORDIC_next [0:20];  // sfix20_En18 [21]
  reg signed [19:0] yReg_next [0:20];  // sfix20_En18 [21]
  reg [4:0] eRegNorm_next [0:5];  // ufix5 [6]
  reg signed [31:0] eRegCORDIC_next [0:20];  // sfix32 [21]
  reg  [27:0] validReg_next;  // boolean [28]
  reg signed [19:0] dataOutReg_next;  // sfix20_En18
  reg signed [31:0] eOutReg_next;  // sfix32
  reg  [27:0] isZeroReg_next;  // boolean [28]
  reg [19:0] uInt;  // ufix20
  reg  [27:0] validReg;  // boolean [28]
  reg  [27:0] isZeroReg;  // boolean [28]
  reg [19:0] yy;  // ufix20_En11
  reg signed [31:0] kk;  // int32
  reg signed [19:0] xInt [0:1];  // sfix20_En18 [2]
  reg signed [19:0] yInt [0:1];  // sfix20_En18 [2]
  reg signed [19:0] xInt_0 [0:1];  // sfix20_En18 [2]
  reg signed [19:0] yInt_0 [0:1];  // sfix20_En18 [2]
  reg signed [19:0] sub_temp;  // sfix20_En18
  reg signed [19:0] sub_temp_0;  // sfix20_En18
  reg signed [19:0] xInt_1 [0:1];  // sfix20_En18 [2]
  reg signed [19:0] yInt_1 [0:1];  // sfix20_En18 [2]
  reg signed [19:0] sub_temp_1;  // sfix20_En18
  reg signed [19:0] sub_temp_2;  // sfix20_En18
  reg signed [19:0] xInt_2 [0:1];  // sfix20_En18 [2]
  reg signed [19:0] yInt_2 [0:1];  // sfix20_En18 [2]
  reg signed [19:0] sub_temp_3;  // sfix20_En18
  reg signed [19:0] sub_temp_4;  // sfix20_En18
  reg signed [19:0] xInt_3 [0:1];  // sfix20_En18 [2]
  reg signed [19:0] yInt_3 [0:1];  // sfix20_En18 [2]
  reg signed [19:0] sub_temp_5;  // sfix20_En18
  reg signed [19:0] sub_temp_6;  // sfix20_En18
  reg signed [19:0] xInt_4 [0:1];  // sfix20_En18 [2]
  reg signed [19:0] yInt_4 [0:1];  // sfix20_En18 [2]
  reg signed [19:0] sub_temp_7;  // sfix20_En18
  reg signed [19:0] sub_temp_8;  // sfix20_En18
  reg signed [19:0] xInt_5 [0:1];  // sfix20_En18 [2]
  reg signed [19:0] yInt_5 [0:1];  // sfix20_En18 [2]
  reg signed [19:0] sub_temp_9;  // sfix20_En18
  reg signed [19:0] sub_temp_10;  // sfix20_En18
  reg signed [19:0] xInt_6 [0:1];  // sfix20_En18 [2]
  reg signed [19:0] yInt_6 [0:1];  // sfix20_En18 [2]
  reg signed [19:0] sub_temp_11;  // sfix20_En18
  reg signed [19:0] sub_temp_12;  // sfix20_En18
  reg signed [19:0] xInt_7 [0:1];  // sfix20_En18 [2]
  reg signed [19:0] yInt_7 [0:1];  // sfix20_En18 [2]
  reg signed [19:0] sub_temp_13;  // sfix20_En18
  reg signed [19:0] sub_temp_14;  // sfix20_En18
  reg signed [19:0] xInt_8 [0:1];  // sfix20_En18 [2]
  reg signed [19:0] yInt_8 [0:1];  // sfix20_En18 [2]
  reg signed [19:0] sub_temp_15;  // sfix20_En18
  reg signed [19:0] sub_temp_16;  // sfix20_En18
  reg signed [19:0] xInt_9 [0:1];  // sfix20_En18 [2]
  reg signed [19:0] yInt_9 [0:1];  // sfix20_En18 [2]
  reg signed [19:0] sub_temp_17;  // sfix20_En18
  reg signed [19:0] sub_temp_18;  // sfix20_En18
  reg signed [19:0] xInt_10 [0:1];  // sfix20_En18 [2]
  reg signed [19:0] yInt_10 [0:1];  // sfix20_En18 [2]
  reg signed [19:0] sub_temp_19;  // sfix20_En18
  reg signed [19:0] sub_temp_20;  // sfix20_En18
  reg signed [19:0] xInt_11 [0:1];  // sfix20_En18 [2]
  reg signed [19:0] yInt_11 [0:1];  // sfix20_En18 [2]
  reg signed [19:0] sub_temp_21;  // sfix20_En18
  reg signed [19:0] sub_temp_22;  // sfix20_En18
  reg signed [19:0] xInt_12 [0:1];  // sfix20_En18 [2]
  reg signed [19:0] yInt_12 [0:1];  // sfix20_En18 [2]
  reg signed [19:0] sub_temp_23;  // sfix20_En18
  reg signed [19:0] sub_temp_24;  // sfix20_En18
  reg signed [19:0] xInt_13 [0:1];  // sfix20_En18 [2]
  reg signed [19:0] yInt_13 [0:1];  // sfix20_En18 [2]
  reg signed [19:0] sub_temp_25;  // sfix20_En18
  reg signed [19:0] sub_temp_26;  // sfix20_En18
  reg signed [19:0] xInt_14 [0:1];  // sfix20_En18 [2]
  reg signed [19:0] yInt_14 [0:1];  // sfix20_En18 [2]
  reg signed [19:0] sub_temp_27;  // sfix20_En18
  reg signed [19:0] sub_temp_28;  // sfix20_En18
  reg signed [19:0] xInt_15 [0:1];  // sfix20_En18 [2]
  reg signed [19:0] yInt_15 [0:1];  // sfix20_En18 [2]
  reg signed [19:0] sub_temp_29;  // sfix20_En18
  reg signed [19:0] sub_temp_30;  // sfix20_En18
  reg signed [19:0] xInt_16 [0:1];  // sfix20_En18 [2]
  reg signed [19:0] yInt_16 [0:1];  // sfix20_En18 [2]
  reg signed [19:0] sub_temp_31;  // sfix20_En18
  reg signed [19:0] sub_temp_32;  // sfix20_En18
  reg signed [19:0] xInt_17 [0:1];  // sfix20_En18 [2]
  reg signed [19:0] yInt_17 [0:1];  // sfix20_En18 [2]
  reg signed [19:0] sub_temp_33;  // sfix20_En18
  reg signed [19:0] sub_temp_34;  // sfix20_En18
  reg signed [19:0] xInt_18 [0:1];  // sfix20_En18 [2]
  reg signed [19:0] yInt_18 [0:1];  // sfix20_En18 [2]
  reg signed [19:0] sub_temp_35;  // sfix20_En18
  reg signed [19:0] sub_temp_36;  // sfix20_En18
  reg [19:0] xNormInt;  // ufix20
  reg [4:0] eNormInt;  // ufix5
  reg signed [31:0] eInt;  // sfix32
  reg signed [31:0] ee;  // sfix32
  reg signed [19:0] y_0;  // sfix20_En18
  reg signed [19:0] uShift;  // sfix20
  reg signed [19:0] xInt_19 [0:1];  // sfix20_En18 [2]
  reg signed [19:0] yInt_19 [0:1];  // sfix20_En18 [2]
  reg signed [19:0] sub_temp_37;  // sfix20_En18
  reg signed [19:0] sub_temp_38;  // sfix20_En18
  reg [19:0] xNormInt_0 [0:1];  // ufix20 [2]
  reg [4:0] eNormInt_0 [0:1];  // ufix5 [2]
  reg [19:0] xNormInt_1 [0:1];  // ufix20 [2]
  reg [4:0] eNormInt_1 [0:1];  // ufix5 [2]
  reg [19:0] xNormInt_2 [0:1];  // ufix20 [2]
  reg [4:0] eNormInt_2 [0:1];  // ufix5 [2]
  reg [19:0] xNormInt_3 [0:1];  // ufix20 [2]
  reg [4:0] eNormInt_3 [0:1];  // ufix5 [2]
  reg [19:0] xNormInt_4 [0:1];  // ufix20 [2]
  reg [4:0] eNormInt_4 [0:1];  // ufix5 [2]
  reg signed [19:0] aa;  // sfix20_En18
  reg signed [19:0] cc;  // sfix20_En18
  reg signed [19:0] a_0;  // sfix20_En18
  reg signed [19:0] c_0;  // sfix20_En18
  reg signed [19:0] a_1;  // sfix20_En18
  reg signed [19:0] c_1;  // sfix20_En18
  reg signed [19:0] a_2;  // sfix20_En18
  reg signed [19:0] c_2;  // sfix20_En18
  reg signed [19:0] a_3;  // sfix20_En18
  reg signed [19:0] c_3;  // sfix20_En18
  reg signed [19:0] a_4;  // sfix20_En18
  reg signed [19:0] c_4;  // sfix20_En18
  reg signed [19:0] a_5;  // sfix20_En18
  reg signed [19:0] c_5;  // sfix20_En18
  reg signed [19:0] a_6;  // sfix20_En18
  reg signed [19:0] c_6;  // sfix20_En18
  reg signed [19:0] a_7;  // sfix20_En18
  reg signed [19:0] c_7;  // sfix20_En18
  reg signed [19:0] a_8;  // sfix20_En18
  reg signed [19:0] c_8;  // sfix20_En18
  reg signed [19:0] a_9;  // sfix20_En18
  reg signed [19:0] c_9;  // sfix20_En18
  reg signed [19:0] a_10;  // sfix20_En18
  reg signed [19:0] c_10;  // sfix20_En18
  reg signed [19:0] a_11;  // sfix20_En18
  reg signed [19:0] c_11;  // sfix20_En18
  reg signed [19:0] a_12;  // sfix20_En18
  reg signed [19:0] c_12;  // sfix20_En18
  reg signed [19:0] a_13;  // sfix20_En18
  reg signed [19:0] c_13;  // sfix20_En18
  reg signed [19:0] a_14;  // sfix20_En18
  reg signed [19:0] c_14;  // sfix20_En18
  reg signed [19:0] a_15;  // sfix20_En18
  reg signed [19:0] c_15;  // sfix20_En18
  reg signed [19:0] a_16;  // sfix20_En18
  reg signed [19:0] c_16;  // sfix20_En18
  reg signed [19:0] a_17;  // sfix20_En18
  reg signed [19:0] c_17;  // sfix20_En18
  reg signed [19:0] a_18;  // sfix20_En18
  reg signed [19:0] c_18;  // sfix20_En18
  reg signed [19:0] a_19;  // sfix20_En18
  reg signed [19:0] c_19;  // sfix20_En18
  reg signed [19:0] a_20;  // sfix20_En18
  reg signed [19:0] c_20;  // sfix20_En18
  reg signed [19:0] a_21;  // sfix20_En18
  reg signed [19:0] c_21;  // sfix20_En18
  reg signed [19:0] a_22;  // sfix20_En18
  reg signed [19:0] c_22;  // sfix20_En18
  reg signed [19:0] a_23;  // sfix20_En18
  reg signed [19:0] c_23;  // sfix20_En18
  reg signed [19:0] a_24;  // sfix20_En18
  reg signed [19:0] c_24;  // sfix20_En18
  reg signed [19:0] a_25;  // sfix20_En18
  reg signed [19:0] c_25;  // sfix20_En18
  reg signed [19:0] a_26;  // sfix20_En18
  reg signed [19:0] c_26;  // sfix20_En18
  reg signed [19:0] a_27;  // sfix20_En18
  reg signed [19:0] c_27;  // sfix20_En18
  reg signed [19:0] a_28;  // sfix20_En18
  reg signed [19:0] c_28;  // sfix20_En18
  reg signed [19:0] a_29;  // sfix20_En18
  reg signed [19:0] c_29;  // sfix20_En18
  reg signed [19:0] a_30;  // sfix20_En18
  reg signed [19:0] c_30;  // sfix20_En18
  reg signed [19:0] a_31;  // sfix20_En18
  reg signed [19:0] c_31;  // sfix20_En18
  reg signed [19:0] a_32;  // sfix20_En18
  reg signed [19:0] c_32;  // sfix20_En18
  reg signed [19:0] a_33;  // sfix20_En18
  reg signed [19:0] c_33;  // sfix20_En18
  reg signed [19:0] a_34;  // sfix20_En18
  reg signed [19:0] c_34;  // sfix20_En18
  reg signed [19:0] a_35;  // sfix20_En18
  reg signed [19:0] c_35;  // sfix20_En18
  reg signed [19:0] a_36;  // sfix20_En18
  reg signed [19:0] c_36;  // sfix20_En18
  reg [19:0] c_37;  // ufix20
  reg signed [31:0] c_38;  // sfix32
  reg signed [19:0] c_39;  // sfix20
  reg [19:0] a_37;  // ufix20
  reg [19:0] c_40;  // ufix20
  reg [19:0] a_38;  // ufix20
  reg [19:0] c_41;  // ufix20
  reg [19:0] a_39;  // ufix20
  reg [19:0] c_42;  // ufix20
  reg [19:0] a_40;  // ufix20
  reg [19:0] c_43;  // ufix20
  reg [19:0] a_41;  // ufix20
  reg [19:0] c_44;  // ufix20
  reg signed [19:0] a_42;  // sfix20_En18
  reg signed [19:0] c_45;  // sfix20_En18
  reg signed [19:0] a_43;  // sfix20_En18
  reg signed [19:0] c_46;  // sfix20_En18
  reg signed [31:0] t_0;  // int32
  reg signed [31:0] t_1;  // int32
  reg signed [31:0] t_2;  // int32
  reg signed [39:0] mul_temp;  // sfix40_En36
  reg signed [31:0] t_3;  // int32
  reg signed [37:0] t_4;  // sfix38
  reg signed [39:0] t_5;  // sfix40
  reg signed [34:0] t_6;  // sfix35
  reg signed [39:0] t_7;  // sfix40
  reg signed [33:0] t_8;  // sfix34
  reg signed [39:0] t_9;  // sfix40
  reg signed [31:0] t_10;  // sfix32
  reg signed [39:0] t_11;  // sfix40
  reg signed [29:0] t_12;  // sfix30
  reg signed [39:0] t_13;  // sfix40
  reg signed [26:0] t_14;  // sfix27
  reg signed [39:0] t_15;  // sfix40
  reg signed [22:0] t_16;  // sfix23
  reg signed [39:0] t_17;  // sfix40
  reg signed [20:0] t_18;  // sfix21
  reg signed [39:0] t_19;  // sfix40
  reg signed [31:0] t_0_0;  // int32
  reg signed [31:0] t_1_0;  // int32
  reg signed [31:0] t_2_0;  // int32
  reg signed [31:0] t_3_0;  // int32
  reg signed [31:0] t_4_0;  // int32
  reg signed [31:0] t_5_0;  // int32
  reg signed [31:0] t_6_0;  // int32
  reg signed [31:0] t_7_0;  // int32
  reg signed [31:0] t_8_0;  // int32
  reg signed [31:0] t_9_0;  // int32


  always @(posedge clk)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        delayMatch_reg <= {5{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg[0] <= restart;
          delayMatch_reg[32'sd4:32'sd1] <= delayMatch_reg[32'sd3:32'sd0];
        end
      end
    end

  assign restart_1 = delayMatch_reg[4];



  assign stateControl_1 = 1'b1;



  always @(posedge clk)
    begin : delayMatch1_process
      if (reset == 1'b1) begin
        delayMatch1_reg <= {5{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch1_reg[0] <= stateControl_1;
          delayMatch1_reg[32'sd4:32'sd1] <= delayMatch1_reg[32'sd3:32'sd0];
        end
      end
    end

  assign stateControl_2 = delayMatch1_reg[4];



  assign enb_gated = stateControl_2 && enb;

  always @(posedge clk)
    begin : embmathops_c2_svA684MOYugZkgHyA2vefI1
      if (reset == 1'b1) begin

        for(t_5_0 = 32'sd0; t_5_0 <= 32'sd5; t_5_0 = t_5_0 + 32'sd1) begin
          xRegNorm[t_5_0] <= 20'b00000000000000000000;
        end


        for(t_6_0 = 32'sd0; t_6_0 <= 32'sd20; t_6_0 = t_6_0 + 32'sd1) begin
          xRegCORDIC[t_6_0] <= 20'sb00000000000000000000;
          yReg[t_6_0] <= 20'sb00000000000000000000;
        end


        for(t_7_0 = 32'sd0; t_7_0 <= 32'sd5; t_7_0 = t_7_0 + 32'sd1) begin
          eRegNorm[t_7_0] <= 5'b00000;
        end


        for(t_8_0 = 32'sd0; t_8_0 <= 32'sd20; t_8_0 = t_8_0 + 32'sd1) begin
          eRegCORDIC[t_8_0] <= 32'sb00000000000000000000000000000000;
        end

        dataOutReg <= 20'sb00000000000000000000;
        eOutReg <= 32'sb00000000000000000000000000000000;

        for(t_9_0 = 32'sd0; t_9_0 <= 32'sd27; t_9_0 = t_9_0 + 32'sd1) begin
          validReg_1[t_9_0] <= 1'b0;
          isZeroReg_1[t_9_0] <= 1'b0;
        end

      end
      else begin
        if (enb_gated) begin

          for(t_0_0 = 32'sd0; t_0_0 <= 32'sd5; t_0_0 = t_0_0 + 32'sd1) begin
            xRegNorm[t_0_0] <= xRegNorm_next[t_0_0];
          end


          for(t_1_0 = 32'sd0; t_1_0 <= 32'sd20; t_1_0 = t_1_0 + 32'sd1) begin
            xRegCORDIC[t_1_0] <= xRegCORDIC_next[t_1_0];
            yReg[t_1_0] <= yReg_next[t_1_0];
          end


          for(t_2_0 = 32'sd0; t_2_0 <= 32'sd5; t_2_0 = t_2_0 + 32'sd1) begin
            eRegNorm[t_2_0] <= eRegNorm_next[t_2_0];
          end


          for(t_3_0 = 32'sd0; t_3_0 <= 32'sd20; t_3_0 = t_3_0 + 32'sd1) begin
            eRegCORDIC[t_3_0] <= eRegCORDIC_next[t_3_0];
          end

          dataOutReg <= dataOutReg_next;
          eOutReg <= eOutReg_next;

          for(t_4_0 = 32'sd0; t_4_0 <= 32'sd27; t_4_0 = t_4_0 + 32'sd1) begin
            validReg_1[t_4_0] <= validReg_next[t_4_0];
            isZeroReg_1[t_4_0] <= isZeroReg_next[t_4_0];
          end

        end
      end
    end

  always @* begin
    a_37 = 20'b00000000000000000000;
    a_38 = 20'b00000000000000000000;
    a_39 = 20'b00000000000000000000;
    a_40 = 20'b00000000000000000000;
    a_41 = 20'b00000000000000000000;
    c_39 = 20'sb00000000000000000000;
    c_40 = 20'b00000000000000000000;
    c_41 = 20'b00000000000000000000;
    c_42 = 20'b00000000000000000000;
    c_43 = 20'b00000000000000000000;
    c_44 = 20'b00000000000000000000;
    // [dataOut,eOut,validOut] = cordicSquareRootHDL(u,validIn,restart,maximumShiftValue,nIterPerReg)
    // This function computes the normalized square root of input data u
    // based on CORDIC hyperbolic vectoring mode. eOut is the bit shift
    // value to be used during denormalization.
    //
    // This function first performs normalization of input u and then
    // computes square root of normalized u using CORDIC hyperbolic
    // vectoring mode.
    //   Copyright 2023 The MathWorks, Inc.
    //    %% Constants
    //    %% Run CORDIC square root workflow
    yy = u_u;
    uInt = yy;
    // CORDIC datatype and corresponding fimath
    // Allocate registers
    //        %% Registers
    //        %% Assign outputs
    //        %% Update registers

    for(t_0 = 32'sd0; t_0 <= 32'sd27; t_0 = t_0 + 32'sd1) begin
      isZeroReg[t_0] = isZeroReg_1[t_0];
      validReg[t_0] = validReg_1[t_0];
    end

    if (restart_1) begin
      for(t_1 = 32'sd0; t_1 <= 32'sd27; t_1 = t_1 + 32'sd1) begin
        validReg[t_1] = 1'b0;
        isZeroReg[t_1] = 1'b0;
      end
    end
    else begin

      for(kk = 32'sd0; kk <= 32'sd26; kk = kk + 32'sd1) begin
        validReg[32'sd27 - kk] = validReg[32'sd26 - kk];
        isZeroReg[32'sd27 - kk] = isZeroReg[32'sd26 - kk];
      end

      validReg[0] = validIn;
      isZeroReg[0] = yy == 20'b00000000000000000000;
    end
    xInt[0] = xRegCORDIC[19];
    yInt[0] = yReg[19];
    yInt[1] = yInt[0];
    xInt[1] = xInt[0];
    xRegCORDIC_next[20] = xInt[1];
    yReg_next[20] = yInt[1];
    eRegCORDIC_next[20] = eRegCORDIC[19];
    xInt_0[0] = xRegCORDIC[18];
    yInt_0[0] = yReg[18];
    aa = xInt_0[0];
    cc = aa >>> 8'd18;
    a_0 = yInt_0[0];
    c_0 = a_0 >>> 8'd18;
    if (yInt_0[0] < 20'sb00000000000000000000) begin
      sub_temp = xInt_0[0] + c_0;
      sub_temp_0 = yInt_0[0] + cc;
    end
    else begin
      sub_temp = xInt_0[0] - c_0;
      sub_temp_0 = yInt_0[0] - cc;
    end
    xInt_0[1] = sub_temp;
    yInt_0[1] = sub_temp_0;
    xRegCORDIC_next[19] = xInt_0[1];
    yReg_next[19] = yInt_0[1];
    eRegCORDIC_next[19] = eRegCORDIC[18];
    xInt_1[0] = xRegCORDIC[17];
    yInt_1[0] = yReg[17];
    a_1 = xInt_1[0];
    c_1 = a_1 >>> 8'd17;
    a_2 = yInt_1[0];
    c_2 = a_2 >>> 8'd17;
    if (yInt_1[0] < 20'sb00000000000000000000) begin
      sub_temp_1 = xInt_1[0] + c_2;
      sub_temp_2 = yInt_1[0] + c_1;
    end
    else begin
      sub_temp_1 = xInt_1[0] - c_2;
      sub_temp_2 = yInt_1[0] - c_1;
    end
    xInt_1[1] = sub_temp_1;
    yInt_1[1] = sub_temp_2;
    xRegCORDIC_next[18] = xInt_1[1];
    yReg_next[18] = yInt_1[1];
    eRegCORDIC_next[18] = eRegCORDIC[17];
    xInt_2[0] = xRegCORDIC[16];
    yInt_2[0] = yReg[16];
    a_3 = xInt_2[0];
    c_3 = a_3 >>> 8'd16;
    a_4 = yInt_2[0];
    c_4 = a_4 >>> 8'd16;
    if (yInt_2[0] < 20'sb00000000000000000000) begin
      sub_temp_3 = xInt_2[0] + c_4;
      sub_temp_4 = yInt_2[0] + c_3;
    end
    else begin
      sub_temp_3 = xInt_2[0] - c_4;
      sub_temp_4 = yInt_2[0] - c_3;
    end
    xInt_2[1] = sub_temp_3;
    yInt_2[1] = sub_temp_4;
    xRegCORDIC_next[17] = xInt_2[1];
    yReg_next[17] = yInt_2[1];
    eRegCORDIC_next[17] = eRegCORDIC[16];
    xInt_3[0] = xRegCORDIC[15];
    yInt_3[0] = yReg[15];
    a_5 = xInt_3[0];
    c_5 = a_5 >>> 8'd15;
    a_6 = yInt_3[0];
    c_6 = a_6 >>> 8'd15;
    if (yInt_3[0] < 20'sb00000000000000000000) begin
      sub_temp_5 = xInt_3[0] + c_6;
      sub_temp_6 = yInt_3[0] + c_5;
    end
    else begin
      sub_temp_5 = xInt_3[0] - c_6;
      sub_temp_6 = yInt_3[0] - c_5;
    end
    xInt_3[1] = sub_temp_5;
    yInt_3[1] = sub_temp_6;
    xRegCORDIC_next[16] = xInt_3[1];
    yReg_next[16] = yInt_3[1];
    eRegCORDIC_next[16] = eRegCORDIC[15];
    xInt_4[0] = xRegCORDIC[14];
    yInt_4[0] = yReg[14];
    a_7 = xInt_4[0];
    c_7 = a_7 >>> 8'd14;
    a_8 = yInt_4[0];
    c_8 = a_8 >>> 8'd14;
    if (yInt_4[0] < 20'sb00000000000000000000) begin
      sub_temp_7 = xInt_4[0] + c_8;
      sub_temp_8 = yInt_4[0] + c_7;
    end
    else begin
      sub_temp_7 = xInt_4[0] - c_8;
      sub_temp_8 = yInt_4[0] - c_7;
    end
    xInt_4[1] = sub_temp_7;
    yInt_4[1] = sub_temp_8;
    xRegCORDIC_next[15] = xInt_4[1];
    yReg_next[15] = yInt_4[1];
    eRegCORDIC_next[15] = eRegCORDIC[14];
    xInt_5[0] = xRegCORDIC[13];
    yInt_5[0] = yReg[13];
    a_9 = xInt_5[0];
    c_9 = a_9 >>> 8'd13;
    a_10 = yInt_5[0];
    c_10 = a_10 >>> 8'd13;
    if (yInt_5[0] < 20'sb00000000000000000000) begin
      sub_temp_9 = xInt_5[0] + c_10;
      sub_temp_10 = yInt_5[0] + c_9;
    end
    else begin
      sub_temp_9 = xInt_5[0] - c_10;
      sub_temp_10 = yInt_5[0] - c_9;
    end
    xInt_5[1] = sub_temp_9;
    yInt_5[1] = sub_temp_10;
    xRegCORDIC_next[14] = xInt_5[1];
    yReg_next[14] = yInt_5[1];
    eRegCORDIC_next[14] = eRegCORDIC[13];
    xInt_6[0] = xRegCORDIC[12];
    yInt_6[0] = yReg[12];
    a_11 = xInt_6[0];
    c_11 = a_11 >>> 8'd13;
    a_12 = yInt_6[0];
    c_12 = a_12 >>> 8'd13;
    if (yInt_6[0] < 20'sb00000000000000000000) begin
      sub_temp_11 = xInt_6[0] + c_12;
      sub_temp_12 = yInt_6[0] + c_11;
    end
    else begin
      sub_temp_11 = xInt_6[0] - c_12;
      sub_temp_12 = yInt_6[0] - c_11;
    end
    xInt_6[1] = sub_temp_11;
    yInt_6[1] = sub_temp_12;
    xRegCORDIC_next[13] = xInt_6[1];
    yReg_next[13] = yInt_6[1];
    eRegCORDIC_next[13] = eRegCORDIC[12];
    xInt_7[0] = xRegCORDIC[11];
    yInt_7[0] = yReg[11];
    a_13 = xInt_7[0];
    c_13 = a_13 >>> 8'd12;
    a_14 = yInt_7[0];
    c_14 = a_14 >>> 8'd12;
    if (yInt_7[0] < 20'sb00000000000000000000) begin
      sub_temp_13 = xInt_7[0] + c_14;
      sub_temp_14 = yInt_7[0] + c_13;
    end
    else begin
      sub_temp_13 = xInt_7[0] - c_14;
      sub_temp_14 = yInt_7[0] - c_13;
    end
    xInt_7[1] = sub_temp_13;
    yInt_7[1] = sub_temp_14;
    xRegCORDIC_next[12] = xInt_7[1];
    yReg_next[12] = yInt_7[1];
    eRegCORDIC_next[12] = eRegCORDIC[11];
    xInt_8[0] = xRegCORDIC[10];
    yInt_8[0] = yReg[10];
    a_15 = xInt_8[0];
    c_15 = a_15 >>> 8'd11;
    a_16 = yInt_8[0];
    c_16 = a_16 >>> 8'd11;
    if (yInt_8[0] < 20'sb00000000000000000000) begin
      sub_temp_15 = xInt_8[0] + c_16;
      sub_temp_16 = yInt_8[0] + c_15;
    end
    else begin
      sub_temp_15 = xInt_8[0] - c_16;
      sub_temp_16 = yInt_8[0] - c_15;
    end
    xInt_8[1] = sub_temp_15;
    yInt_8[1] = sub_temp_16;
    xRegCORDIC_next[11] = xInt_8[1];
    yReg_next[11] = yInt_8[1];
    eRegCORDIC_next[11] = eRegCORDIC[10];
    xInt_9[0] = xRegCORDIC[9];
    yInt_9[0] = yReg[9];
    a_17 = xInt_9[0];
    c_17 = a_17 >>> 8'd10;
    a_18 = yInt_9[0];
    c_18 = a_18 >>> 8'd10;
    if (yInt_9[0] < 20'sb00000000000000000000) begin
      sub_temp_17 = xInt_9[0] + c_18;
      sub_temp_18 = yInt_9[0] + c_17;
    end
    else begin
      sub_temp_17 = xInt_9[0] - c_18;
      sub_temp_18 = yInt_9[0] - c_17;
    end
    xInt_9[1] = sub_temp_17;
    yInt_9[1] = sub_temp_18;
    xRegCORDIC_next[10] = xInt_9[1];
    yReg_next[10] = yInt_9[1];
    eRegCORDIC_next[10] = eRegCORDIC[9];
    xInt_10[0] = xRegCORDIC[8];
    yInt_10[0] = yReg[8];
    a_19 = xInt_10[0];
    c_19 = a_19 >>> 8'd9;
    a_20 = yInt_10[0];
    c_20 = a_20 >>> 8'd9;
    if (yInt_10[0] < 20'sb00000000000000000000) begin
      sub_temp_19 = xInt_10[0] + c_20;
      sub_temp_20 = yInt_10[0] + c_19;
    end
    else begin
      sub_temp_19 = xInt_10[0] - c_20;
      sub_temp_20 = yInt_10[0] - c_19;
    end
    xInt_10[1] = sub_temp_19;
    yInt_10[1] = sub_temp_20;
    xRegCORDIC_next[9] = xInt_10[1];
    yReg_next[9] = yInt_10[1];
    eRegCORDIC_next[9] = eRegCORDIC[8];
    xInt_11[0] = xRegCORDIC[7];
    yInt_11[0] = yReg[7];
    a_21 = xInt_11[0];
    c_21 = a_21 >>> 8'd8;
    a_22 = yInt_11[0];
    c_22 = a_22 >>> 8'd8;
    if (yInt_11[0] < 20'sb00000000000000000000) begin
      sub_temp_21 = xInt_11[0] + c_22;
      sub_temp_22 = yInt_11[0] + c_21;
    end
    else begin
      sub_temp_21 = xInt_11[0] - c_22;
      sub_temp_22 = yInt_11[0] - c_21;
    end
    xInt_11[1] = sub_temp_21;
    yInt_11[1] = sub_temp_22;
    xRegCORDIC_next[8] = xInt_11[1];
    yReg_next[8] = yInt_11[1];
    eRegCORDIC_next[8] = eRegCORDIC[7];
    xInt_12[0] = xRegCORDIC[6];
    yInt_12[0] = yReg[6];
    a_23 = xInt_12[0];
    c_23 = a_23 >>> 8'd7;
    a_24 = yInt_12[0];
    c_24 = a_24 >>> 8'd7;
    if (yInt_12[0] < 20'sb00000000000000000000) begin
      sub_temp_23 = xInt_12[0] + c_24;
      sub_temp_24 = yInt_12[0] + c_23;
    end
    else begin
      sub_temp_23 = xInt_12[0] - c_24;
      sub_temp_24 = yInt_12[0] - c_23;
    end
    xInt_12[1] = sub_temp_23;
    yInt_12[1] = sub_temp_24;
    xRegCORDIC_next[7] = xInt_12[1];
    yReg_next[7] = yInt_12[1];
    eRegCORDIC_next[7] = eRegCORDIC[6];
    xInt_13[0] = xRegCORDIC[5];
    yInt_13[0] = yReg[5];
    a_25 = xInt_13[0];
    c_25 = a_25 >>> 8'd6;
    a_26 = yInt_13[0];
    c_26 = a_26 >>> 8'd6;
    if (yInt_13[0] < 20'sb00000000000000000000) begin
      sub_temp_25 = xInt_13[0] + c_26;
      sub_temp_26 = yInt_13[0] + c_25;
    end
    else begin
      sub_temp_25 = xInt_13[0] - c_26;
      sub_temp_26 = yInt_13[0] - c_25;
    end
    xInt_13[1] = sub_temp_25;
    yInt_13[1] = sub_temp_26;
    xRegCORDIC_next[6] = xInt_13[1];
    yReg_next[6] = yInt_13[1];
    eRegCORDIC_next[6] = eRegCORDIC[5];
    xInt_14[0] = xRegCORDIC[4];
    yInt_14[0] = yReg[4];
    a_27 = xInt_14[0];
    c_27 = a_27 >>> 8'd5;
    a_28 = yInt_14[0];
    c_28 = a_28 >>> 8'd5;
    if (yInt_14[0] < 20'sb00000000000000000000) begin
      sub_temp_27 = xInt_14[0] + c_28;
      sub_temp_28 = yInt_14[0] + c_27;
    end
    else begin
      sub_temp_27 = xInt_14[0] - c_28;
      sub_temp_28 = yInt_14[0] - c_27;
    end
    xInt_14[1] = sub_temp_27;
    yInt_14[1] = sub_temp_28;
    xRegCORDIC_next[5] = xInt_14[1];
    yReg_next[5] = yInt_14[1];
    eRegCORDIC_next[5] = eRegCORDIC[4];
    xInt_15[0] = xRegCORDIC[3];
    yInt_15[0] = yReg[3];
    a_29 = xInt_15[0];
    c_29 = a_29 >>> 8'd4;
    a_30 = yInt_15[0];
    c_30 = a_30 >>> 8'd4;
    if (yInt_15[0] < 20'sb00000000000000000000) begin
      sub_temp_29 = xInt_15[0] + c_30;
      sub_temp_30 = yInt_15[0] + c_29;
    end
    else begin
      sub_temp_29 = xInt_15[0] - c_30;
      sub_temp_30 = yInt_15[0] - c_29;
    end
    xInt_15[1] = sub_temp_29;
    yInt_15[1] = sub_temp_30;
    xRegCORDIC_next[4] = xInt_15[1];
    yReg_next[4] = yInt_15[1];
    eRegCORDIC_next[4] = eRegCORDIC[3];
    xInt_16[0] = xRegCORDIC[2];
    yInt_16[0] = yReg[2];
    a_31 = xInt_16[0];
    c_31 = a_31 >>> 8'd4;
    a_32 = yInt_16[0];
    c_32 = a_32 >>> 8'd4;
    if (yInt_16[0] < 20'sb00000000000000000000) begin
      sub_temp_31 = xInt_16[0] + c_32;
      sub_temp_32 = yInt_16[0] + c_31;
    end
    else begin
      sub_temp_31 = xInt_16[0] - c_32;
      sub_temp_32 = yInt_16[0] - c_31;
    end
    xInt_16[1] = sub_temp_31;
    yInt_16[1] = sub_temp_32;
    xRegCORDIC_next[3] = xInt_16[1];
    yReg_next[3] = yInt_16[1];
    eRegCORDIC_next[3] = eRegCORDIC[2];
    xInt_17[0] = xRegCORDIC[1];
    yInt_17[0] = yReg[1];
    a_33 = xInt_17[0];
    c_33 = a_33 >>> 8'd3;
    a_34 = yInt_17[0];
    c_34 = a_34 >>> 8'd3;
    if (yInt_17[0] < 20'sb00000000000000000000) begin
      sub_temp_33 = xInt_17[0] + c_34;
      sub_temp_34 = yInt_17[0] + c_33;
    end
    else begin
      sub_temp_33 = xInt_17[0] - c_34;
      sub_temp_34 = yInt_17[0] - c_33;
    end
    xInt_17[1] = sub_temp_33;
    yInt_17[1] = sub_temp_34;
    xRegCORDIC_next[2] = xInt_17[1];
    yReg_next[2] = yInt_17[1];
    eRegCORDIC_next[2] = eRegCORDIC[1];
    xInt_18[0] = xRegCORDIC[0];
    yInt_18[0] = yReg[0];
    a_35 = xInt_18[0];
    c_35 = a_35 >>> 8'd2;
    a_36 = yInt_18[0];
    c_36 = a_36 >>> 8'd2;
    if (yInt_18[0] < 20'sb00000000000000000000) begin
      sub_temp_35 = xInt_18[0] + c_36;
      sub_temp_36 = yInt_18[0] + c_35;
    end
    else begin
      sub_temp_35 = xInt_18[0] - c_36;
      sub_temp_36 = yInt_18[0] - c_35;
    end
    xInt_18[1] = sub_temp_35;
    yInt_18[1] = sub_temp_36;
    xRegCORDIC_next[1] = xInt_18[1];
    yReg_next[1] = yInt_18[1];
    eRegCORDIC_next[1] = eRegCORDIC[0];
    xNormInt = xRegNorm[5];
    eNormInt = eRegNorm[5];
    t_3 = {27'b0, eNormInt};
    eInt = t_3 - 32'sd8;
    ee = eInt - 32'sb00000000000000000000000000000001;
    c_37 = xNormInt >>> 8'd2;
    uShift = c_37;
    if (ee[0] != 1'b0) begin
      ee = ee - 32'sb00000000000000000000000000000001;
      c_39 = uShift >>> 8'd1;
      y_0 = c_39;
    end
    else begin
      y_0 = uShift;
    end
    c_38 = ee >>> 8'd1;
    xInt_19[0] = y_0 + 20'sb00010000000000000000;
    yInt_19[0] = y_0 - 20'sb00010000000000000000;
    a_42 = xInt_19[0];
    c_45 = a_42 >>> 8'd1;
    a_43 = yInt_19[0];
    c_46 = a_43 >>> 8'd1;
    if (yInt_19[0] < 20'sb00000000000000000000) begin
      sub_temp_37 = xInt_19[0] + c_46;
      sub_temp_38 = yInt_19[0] + c_45;
    end
    else begin
      sub_temp_37 = xInt_19[0] - c_46;
      sub_temp_38 = yInt_19[0] - c_45;
    end
    xInt_19[1] = sub_temp_37;
    yInt_19[1] = sub_temp_38;
    xRegCORDIC_next[0] = xInt_19[1];
    yReg_next[0] = yInt_19[1];
    eRegCORDIC_next[0] = c_38;
    xNormInt_0[0] = xRegNorm[4];
    eNormInt_0[0] = eRegNorm[4];
    if ((xNormInt_0[0] & 20'b10000000000000000000) == 20'b00000000000000000000) begin
      eNormInt_0[1] = eNormInt_0[0] | 5'b00001;
      a_37 = xNormInt_0[0];
      c_40 = a_37 <<< 8'd1;
      xNormInt_0[1] = c_40;
    end
    else begin
      xNormInt_0[1] = xNormInt_0[0];
      eNormInt_0[1] = eNormInt_0[0];
    end
    xRegNorm_next[5] = xNormInt_0[1];
    eRegNorm_next[5] = eNormInt_0[1];
    xNormInt_1[0] = xRegNorm[3];
    eNormInt_1[0] = eRegNorm[3];
    if ((xNormInt_1[0] & 20'b11000000000000000000) == 20'b00000000000000000000) begin
      eNormInt_1[1] = eNormInt_1[0] | 5'b00010;
      a_38 = xNormInt_1[0];
      c_41 = a_38 <<< 8'd2;
      xNormInt_1[1] = c_41;
    end
    else begin
      xNormInt_1[1] = xNormInt_1[0];
      eNormInt_1[1] = eNormInt_1[0];
    end
    xRegNorm_next[4] = xNormInt_1[1];
    eRegNorm_next[4] = eNormInt_1[1];
    xNormInt_2[0] = xRegNorm[2];
    eNormInt_2[0] = eRegNorm[2];
    if ((xNormInt_2[0] & 20'b11110000000000000000) == 20'b00000000000000000000) begin
      eNormInt_2[1] = eNormInt_2[0] | 5'b00100;
      a_39 = xNormInt_2[0];
      c_42 = a_39 <<< 8'd4;
      xNormInt_2[1] = c_42;
    end
    else begin
      xNormInt_2[1] = xNormInt_2[0];
      eNormInt_2[1] = eNormInt_2[0];
    end
    xRegNorm_next[3] = xNormInt_2[1];
    eRegNorm_next[3] = eNormInt_2[1];
    xNormInt_3[0] = xRegNorm[1];
    eNormInt_3[0] = eRegNorm[1];
    if ((xNormInt_3[0] & 20'b11111111000000000000) == 20'b00000000000000000000) begin
      eNormInt_3[1] = eNormInt_3[0] | 5'b01000;
      a_40 = xNormInt_3[0];
      c_43 = a_40 <<< 8'd8;
      xNormInt_3[1] = c_43;
    end
    else begin
      xNormInt_3[1] = xNormInt_3[0];
      eNormInt_3[1] = eNormInt_3[0];
    end
    xRegNorm_next[2] = xNormInt_3[1];
    eRegNorm_next[2] = eNormInt_3[1];
    xNormInt_4[0] = xRegNorm[0];
    eNormInt_4[0] = eRegNorm[0];
    if ((xNormInt_4[0] & 20'b11111111111111110000) == 20'b00000000000000000000) begin
      eNormInt_4[1] = eNormInt_4[0] | 5'b10000;
      a_41 = xNormInt_4[0];
      c_44 = a_41 <<< 8'd16;
      xNormInt_4[1] = c_44;
    end
    else begin
      xNormInt_4[1] = xNormInt_4[0];
      eNormInt_4[1] = eNormInt_4[0];
    end
    xRegNorm_next[1] = xNormInt_4[1];
    eRegNorm_next[1] = eNormInt_4[1];
    eRegNorm_next[0] = 5'b00000;
    xRegNorm_next[0] = uInt;
    // CSD Encoding (316538) : 01001101010010001'010; Cost (Adders) = 7
    t_4 = {xRegCORDIC[20], 18'b000000000000000000};
    t_5 = {{2{t_4[37]}}, t_4};
    t_6 = {xRegCORDIC[20], 15'b000000000000000};
    t_7 = {{5{t_6[34]}}, t_6};
    t_8 = {xRegCORDIC[20], 14'b00000000000000};
    t_9 = {{6{t_8[33]}}, t_8};
    t_10 = {xRegCORDIC[20], 12'b000000000000};
    t_11 = {{8{t_10[31]}}, t_10};
    t_12 = {xRegCORDIC[20], 10'b0000000000};
    t_13 = {{10{t_12[29]}}, t_12};
    t_14 = {xRegCORDIC[20], 7'b0000000};
    t_15 = {{13{t_14[26]}}, t_14};
    t_16 = {xRegCORDIC[20], 3'b000};
    t_17 = {{17{t_16[22]}}, t_16};
    t_18 = {xRegCORDIC[20], 1'b0};
    t_19 = {{19{t_18[20]}}, t_18};
    mul_temp = ((((((t_5 + t_7) + t_9) + t_11) + t_13) + t_15) - t_17) + t_19;
    dataOutReg_next = mul_temp[37:18];
    eOutReg_next = eRegCORDIC[20];

    for(t_2 = 32'sd0; t_2 <= 32'sd27; t_2 = t_2 + 32'sd1) begin
      validReg_next[t_2] = validReg[t_2];
      isZeroReg_next[t_2] = isZeroReg[t_2];
    end

    // % Inputs
    // %Registers
    // % Constants for algorithms
    // Constants for partition algorithms
    dataOut_1 = dataOutReg;
    eOut_1 = eOutReg;
    isZero_1 = isZeroReg_1[27];
    validOut_1 = validReg_1[27];
  end



  assign dataOut = dataOut_1;

  assign eOut = eOut_1;

  assign isZero = isZero_1;

  assign validOut = validOut_1;

endmodule  // Subsystem_ip2_src_cordicSqua_block1

