// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdl_model_fixed\Subsystem_ip2_src_FFT.v
// Created: 2024-12-21 14:39:09
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_ip2_src_FFT
// Source Path: hdl_model_fixed/Subsystem1/Subsystem/FFT
// Hierarchy Level: 2
// Model version: 1.110
// 
// FFT
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_ip2_src_FFT
          (clk,
           reset,
           enb,
           dataIn,
           validIn,
           syncReset,
           dataOut_re,
           dataOut_im,
           validOut);


  input   clk;
  input   reset;
  input   enb;
  input   signed [11:0] dataIn;  // sfix12_En11
  input   validIn;
  input   syncReset;
  output  signed [22:0] dataOut_re;  // sfix23_En11
  output  signed [22:0] dataOut_im;  // sfix23_En11
  output  validOut;


  reg signed [11:0] intdelay_reg [0:2];  // sfix12 [3]
  reg signed [11:0] intdelay_reg_next [0:2];  // sfix12_En11 [3]
  reg signed [11:0] din_1_1_re_dly;  // sfix12_En11
  wire signed [11:0] dtc_im;  // sfix12_En11
  reg signed [11:0] intdelay_reg_1 [0:2];  // sfix12 [3]
  reg signed [11:0] intdelay_reg_next_1 [0:2];  // sfix12_En11 [3]
  reg signed [11:0] din_1_1_im_dly;  // sfix12_En11
  reg  [2:0] intdelay_reg_2;  // ufix1 [3]
  wire din_1_vld_dly;
  wire dinXTwdl_1_1_vld;
  wire [9:0] rd_1_Addr;  // ufix10
  wire rd_1_Enb;
  wire proc_1_enb;
  wire signed [12:0] dout_1_1_re;  // sfix13_En11
  wire signed [12:0] dout_1_1_im;  // sfix13_En11
  wire dout_1_1_vld;
  wire dinXTwdl_2_1_vld;
  wire [8:0] rd_2_Addr;  // ufix9
  wire rd_2_Enb;
  wire proc_2_enb;
  wire multiply_2_J;
  wire signed [13:0] dout_2_1_re;  // sfix14_En11
  wire signed [13:0] dout_2_1_im;  // sfix14_En11
  wire dout_2_1_vld;
  reg signed [13:0] intdelay_reg_3 [0:2];  // sfix14 [3]
  reg signed [13:0] intdelay_reg_next_2 [0:2];  // sfix14_En11 [3]
  reg signed [13:0] din_3_1_re_dly;  // sfix14_En11
  reg signed [13:0] intdelay_reg_4 [0:2];  // sfix14 [3]
  reg signed [13:0] intdelay_reg_next_3 [0:2];  // sfix14_En11 [3]
  reg signed [13:0] din_3_1_im_dly;  // sfix14_En11
  reg  [2:0] intdelay_reg_5;  // ufix1 [3]
  wire din_3_vld_dly;
  wire signed [11:0] twdl_3_1_re;  // sfix12_En10
  wire signed [11:0] twdl_3_1_im;  // sfix12_En10
  wire dinXTwdl_3_1_vld;
  wire [7:0] rd_3_Addr;  // ufix8
  wire rd_3_Enb;
  wire proc_3_enb;
  wire signed [14:0] dout_3_1_re;  // sfix15_En11
  wire signed [14:0] dout_3_1_im;  // sfix15_En11
  wire dout_3_1_vld;
  wire dinXTwdl_4_1_vld;
  wire [6:0] rd_4_Addr;  // ufix7
  wire rd_4_Enb;
  wire proc_4_enb;
  wire multiply_4_J;
  wire signed [15:0] dout_4_1_re;  // sfix16_En11
  wire signed [15:0] dout_4_1_im;  // sfix16_En11
  wire dout_4_1_vld;
  reg signed [15:0] intdelay_reg_6 [0:2];  // sfix16 [3]
  reg signed [15:0] intdelay_reg_next_4 [0:2];  // sfix16_En11 [3]
  reg signed [15:0] din_5_1_re_dly;  // sfix16_En11
  reg signed [15:0] intdelay_reg_7 [0:2];  // sfix16 [3]
  reg signed [15:0] intdelay_reg_next_5 [0:2];  // sfix16_En11 [3]
  reg signed [15:0] din_5_1_im_dly;  // sfix16_En11
  reg  [2:0] intdelay_reg_8;  // ufix1 [3]
  wire din_5_vld_dly;
  wire signed [11:0] twdl_5_1_re;  // sfix12_En10
  wire signed [11:0] twdl_5_1_im;  // sfix12_En10
  wire dinXTwdl_5_1_vld;
  wire [5:0] rd_5_Addr;  // ufix6
  wire rd_5_Enb;
  wire proc_5_enb;
  wire signed [16:0] dout_5_1_re;  // sfix17_En11
  wire signed [16:0] dout_5_1_im;  // sfix17_En11
  wire dout_5_1_vld;
  wire dinXTwdl_6_1_vld;
  wire [4:0] rd_6_Addr;  // ufix5
  wire rd_6_Enb;
  wire proc_6_enb;
  wire multiply_6_J;
  wire signed [17:0] dout_6_1_re;  // sfix18_En11
  wire signed [17:0] dout_6_1_im;  // sfix18_En11
  wire dout_6_1_vld;
  reg signed [17:0] intdelay_reg_9 [0:2];  // sfix18 [3]
  reg signed [17:0] intdelay_reg_next_6 [0:2];  // sfix18_En11 [3]
  reg signed [17:0] din_7_1_re_dly;  // sfix18_En11
  reg signed [17:0] intdelay_reg_10 [0:2];  // sfix18 [3]
  reg signed [17:0] intdelay_reg_next_7 [0:2];  // sfix18_En11 [3]
  reg signed [17:0] din_7_1_im_dly;  // sfix18_En11
  reg  [2:0] intdelay_reg_11;  // ufix1 [3]
  wire din_7_vld_dly;
  wire signed [11:0] twdl_7_1_re;  // sfix12_En10
  wire signed [11:0] twdl_7_1_im;  // sfix12_En10
  wire dinXTwdl_7_1_vld;
  wire [3:0] rd_7_Addr;  // ufix4
  wire rd_7_Enb;
  wire proc_7_enb;
  wire signed [18:0] dout_7_1_re;  // sfix19_En11
  wire signed [18:0] dout_7_1_im;  // sfix19_En11
  wire dout_7_1_vld;
  wire dinXTwdl_8_1_vld;
  wire [2:0] rd_8_Addr;  // ufix3
  wire rd_8_Enb;
  wire proc_8_enb;
  wire multiply_8_J;
  wire signed [19:0] dout_8_1_re;  // sfix20_En11
  wire signed [19:0] dout_8_1_im;  // sfix20_En11
  wire dout_8_1_vld;
  reg signed [19:0] intdelay_reg_12 [0:2];  // sfix20 [3]
  reg signed [19:0] intdelay_reg_next_8 [0:2];  // sfix20_En11 [3]
  reg signed [19:0] din_9_1_re_dly;  // sfix20_En11
  reg signed [19:0] intdelay_reg_13 [0:2];  // sfix20 [3]
  reg signed [19:0] intdelay_reg_next_9 [0:2];  // sfix20_En11 [3]
  reg signed [19:0] din_9_1_im_dly;  // sfix20_En11
  reg  [2:0] intdelay_reg_14;  // ufix1 [3]
  wire din_9_vld_dly;
  wire signed [11:0] twdl_9_1_re;  // sfix12_En10
  wire signed [11:0] twdl_9_1_im;  // sfix12_En10
  wire dinXTwdl_9_1_vld;
  wire [1:0] rd_9_Addr;  // ufix2
  wire rd_9_Enb;
  wire proc_9_enb;
  wire signed [20:0] dout_9_1_re;  // sfix21_En11
  wire signed [20:0] dout_9_1_im;  // sfix21_En11
  wire dout_9_1_vld;
  wire dinXTwdl_10_1_vld;
  wire rd_10_Addr;  // ufix1
  wire rd_10_Enb;
  wire proc_10_enb;
  wire multiply_10_J;
  wire signed [21:0] dout_10_1_re;  // sfix22_En11
  wire signed [21:0] dout_10_1_im;  // sfix22_En11
  wire dout_10_1_vld;
  reg signed [21:0] intdelay_reg_15 [0:2];  // sfix22 [3]
  reg signed [21:0] intdelay_reg_next_10 [0:2];  // sfix22_En11 [3]
  reg signed [21:0] din_11_re_dly;  // sfix22_En11
  reg signed [21:0] intdelay_reg_16 [0:2];  // sfix22 [3]
  reg signed [21:0] intdelay_reg_next_11 [0:2];  // sfix22_En11 [3]
  reg signed [21:0] din_11_im_dly;  // sfix22_En11
  reg  [2:0] intdelay_reg_17;  // ufix1 [3]
  wire din_11_vld_dly;
  wire signed [11:0] twdl_11_re;  // sfix12_En10
  wire signed [11:0] twdl_11_im;  // sfix12_En10
  wire rd_11_Enb;
  reg  rd_11_Enb_dly;
  wire dinXTwdl_11_vld;
  wire rd_11_Addr;
  wire proc_11_enb;
  wire signed [22:0] dout_11_re;  // sfix23_En11
  wire signed [22:0] dout_11_im;  // sfix23_En11
  wire dout_11_vld;
  wire signed [22:0] dout_re1;  // sfix23_En11
  wire signed [22:0] dout_im1;  // sfix23_En11
  wire dout_vld1;
  reg signed [31:0] intdelay_t_0_0;  // int32
  reg signed [31:0] intdelay_t_0_1;  // int32
  reg signed [31:0] intdelay_t_1;  // int32
  reg signed [31:0] intdelay_t_0_01;  // int32
  reg signed [31:0] intdelay_t_0_02;  // int32
  reg signed [31:0] intdelay_t_0_1_1;  // int32
  reg signed [31:0] intdelay_t_1_1;  // int32
  reg signed [31:0] intdelay_t_0_03;  // int32
  reg signed [31:0] intdelay_t_0_1_2;  // int32
  reg signed [31:0] intdelay_t_1_2;  // int32
  reg signed [31:0] intdelay_t_0_04;  // int32
  reg signed [31:0] intdelay_t_0_1_3;  // int32
  reg signed [31:0] intdelay_t_1_3;  // int32
  reg signed [31:0] intdelay_t_0_05;  // int32
  reg signed [31:0] intdelay_t_0_1_4;  // int32
  reg signed [31:0] intdelay_t_1_4;  // int32
  reg signed [31:0] intdelay_t_0_06;  // int32
  reg signed [31:0] intdelay_t_0_1_5;  // int32
  reg signed [31:0] intdelay_t_1_5;  // int32
  reg signed [31:0] intdelay_t_0_07;  // int32
  reg signed [31:0] intdelay_t_0_1_6;  // int32
  reg signed [31:0] intdelay_t_1_6;  // int32
  reg signed [31:0] intdelay_t_0_08;  // int32
  reg signed [31:0] intdelay_t_0_1_7;  // int32
  reg signed [31:0] intdelay_t_1_7;  // int32
  reg signed [31:0] intdelay_t_0_09;  // int32
  reg signed [31:0] intdelay_t_0_1_8;  // int32
  reg signed [31:0] intdelay_t_1_8;  // int32
  reg signed [31:0] intdelay_t_0_010;  // int32
  reg signed [31:0] intdelay_t_0_1_9;  // int32
  reg signed [31:0] intdelay_t_1_9;  // int32
  reg signed [31:0] intdelay_t_0_011;  // int32
  reg signed [31:0] intdelay_t_0_1_10;  // int32
  reg signed [31:0] intdelay_t_1_10;  // int32


  always @(posedge clk)
    begin : intdelay_process
      if (reset == 1'b1) begin
        for(intdelay_t_1 = 32'sd0; intdelay_t_1 <= 32'sd2; intdelay_t_1 = intdelay_t_1 + 32'sd1) begin
          intdelay_reg[intdelay_t_1] <= 12'sb000000000000;
        end
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            for(intdelay_t_1 = 32'sd0; intdelay_t_1 <= 32'sd2; intdelay_t_1 = intdelay_t_1 + 32'sd1) begin
              intdelay_reg[intdelay_t_1] <= 12'sb000000000000;
            end
          end
          else begin
            for(intdelay_t_0_1 = 32'sd0; intdelay_t_0_1 <= 32'sd2; intdelay_t_0_1 = intdelay_t_0_1 + 32'sd1) 
              begin
              intdelay_reg[intdelay_t_0_1] <= intdelay_reg_next[intdelay_t_0_1];
            end
          end
        end
      end
    end

  always @* begin
    din_1_1_re_dly = intdelay_reg[2];
    intdelay_reg_next[0] = dataIn;

    for(intdelay_t_0_0 = 32'sd0; intdelay_t_0_0 <= 32'sd1; intdelay_t_0_0 = intdelay_t_0_0 + 32'sd1) begin
      intdelay_reg_next[intdelay_t_0_0 + 32'sd1] = intdelay_reg[intdelay_t_0_0];
    end

  end



  assign dtc_im = 12'sb000000000000;



  always @(posedge clk)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        for(intdelay_t_1 = 32'sd0; intdelay_t_1 <= 32'sd2; intdelay_t_1 = intdelay_t_1 + 32'sd1) begin
          intdelay_reg_1[intdelay_t_1] <= 12'sb000000000000;
        end
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            for(intdelay_t_1 = 32'sd0; intdelay_t_1 <= 32'sd2; intdelay_t_1 = intdelay_t_1 + 32'sd1) begin
              intdelay_reg_1[intdelay_t_1] <= 12'sb000000000000;
            end
          end
          else begin
            for(intdelay_t_0_1 = 32'sd0; intdelay_t_0_1 <= 32'sd2; intdelay_t_0_1 = intdelay_t_0_1 + 32'sd1) 
              begin
              intdelay_reg_1[intdelay_t_0_1] <= intdelay_reg_next_1[intdelay_t_0_1];
            end
          end
        end
      end
    end

  always @* begin
    din_1_1_im_dly = intdelay_reg_1[2];
    intdelay_reg_next_1[0] = dtc_im;

    for(intdelay_t_0_01 = 32'sd0; intdelay_t_0_01 <= 32'sd1; intdelay_t_0_01 = intdelay_t_0_01 + 32'sd1) begin
      intdelay_reg_next_1[intdelay_t_0_01 + 32'sd1] = intdelay_reg_1[intdelay_t_0_01];
    end

  end



  always @(posedge clk)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        intdelay_reg_2 <= {3{1'b0}};
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            intdelay_reg_2 <= {3{1'b0}};
          end
          else begin
            intdelay_reg_2[0] <= validIn;
            intdelay_reg_2[32'sd2:32'sd1] <= intdelay_reg_2[32'sd1:32'sd0];
          end
        end
      end
    end

  assign din_1_vld_dly = intdelay_reg_2[2];



  Subsystem_ip2_src_RADIX22FFT_block CTRL1_1_1_1 (.clk(clk),
                                                  .reset(reset),
                                                  .enb(enb),
                                                  .dinXTwdl_1_1_vld(dinXTwdl_1_1_vld),
                                                  .dinXTwdl_1_1_vld_1(dinXTwdl_1_1_vld),
                                                  .syncReset(syncReset),
                                                  .rd_1_Addr(rd_1_Addr),  // ufix10
                                                  .rd_1_Enb(rd_1_Enb),
                                                  .proc_1_enb(proc_1_enb)
                                                  );

  Subsystem_ip2_src_RADIX22FFT SDF1_1_1_1 (.clk(clk),
                                           .reset(reset),
                                           .enb(enb),
                                           .din_1_1_re_dly(din_1_1_re_dly),  // sfix12_En11
                                           .din_1_1_im_dly(din_1_1_im_dly),  // sfix12_En11
                                           .din_1_vld_dly(din_1_vld_dly),
                                           .rd_1_Addr(rd_1_Addr),  // ufix10
                                           .rd_1_Enb(rd_1_Enb),
                                           .proc_1_enb(proc_1_enb),
                                           .syncReset(syncReset),
                                           .dout_1_1_re(dout_1_1_re),  // sfix13_En11
                                           .dout_1_1_im(dout_1_1_im),  // sfix13_En11
                                           .dout_1_1_vld(dout_1_1_vld),
                                           .dinXTwdl_1_1_vld(dinXTwdl_1_1_vld)
                                           );

  Subsystem_ip2_src_RADIX22FFT_block2 CTRL2_2_1_1 (.clk(clk),
                                                   .reset(reset),
                                                   .enb(enb),
                                                   .dout_1_1_vld(dout_1_1_vld),
                                                   .dinXTwdl_2_1_vld(dinXTwdl_2_1_vld),
                                                   .syncReset(syncReset),
                                                   .rd_2_Addr(rd_2_Addr),  // ufix9
                                                   .rd_2_Enb(rd_2_Enb),
                                                   .proc_2_enb(proc_2_enb),
                                                   .multiply_2_J(multiply_2_J)
                                                   );

  Subsystem_ip2_src_RADIX22FFT_block1 SDF2_2_1_1 (.clk(clk),
                                                  .reset(reset),
                                                  .enb(enb),
                                                  .dout_1_1_re(dout_1_1_re),  // sfix13_En11
                                                  .dout_1_1_im(dout_1_1_im),  // sfix13_En11
                                                  .dout_1_1_vld(dout_1_1_vld),
                                                  .rd_2_Addr(rd_2_Addr),  // ufix9
                                                  .rd_2_Enb(rd_2_Enb),
                                                  .proc_2_enb(proc_2_enb),
                                                  .multiply_2_J(multiply_2_J),
                                                  .syncReset(syncReset),
                                                  .dout_2_1_re(dout_2_1_re),  // sfix14_En11
                                                  .dout_2_1_im(dout_2_1_im),  // sfix14_En11
                                                  .dout_2_1_vld(dout_2_1_vld),
                                                  .dinXTwdl_2_1_vld(dinXTwdl_2_1_vld)
                                                  );

  always @(posedge clk)
    begin : intdelay_3_process
      if (reset == 1'b1) begin
        for(intdelay_t_1_1 = 32'sd0; intdelay_t_1_1 <= 32'sd2; intdelay_t_1_1 = intdelay_t_1_1 + 32'sd1) begin
          intdelay_reg_3[intdelay_t_1_1] <= 14'sb00000000000000;
        end
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            for(intdelay_t_1_1 = 32'sd0; intdelay_t_1_1 <= 32'sd2; intdelay_t_1_1 = intdelay_t_1_1 + 32'sd1) 
              begin
              intdelay_reg_3[intdelay_t_1_1] <= 14'sb00000000000000;
            end
          end
          else begin
            for(intdelay_t_0_1_1 = 32'sd0; intdelay_t_0_1_1 <= 32'sd2; intdelay_t_0_1_1 = intdelay_t_0_1_1 + 
              32'sd1) begin
              intdelay_reg_3[intdelay_t_0_1_1] <= intdelay_reg_next_2[intdelay_t_0_1_1];
            end
          end
        end
      end
    end

  always @* begin
    din_3_1_re_dly = intdelay_reg_3[2];
    intdelay_reg_next_2[0] = dout_2_1_re;

    for(intdelay_t_0_02 = 32'sd0; intdelay_t_0_02 <= 32'sd1; intdelay_t_0_02 = intdelay_t_0_02 + 32'sd1) begin
      intdelay_reg_next_2[intdelay_t_0_02 + 32'sd1] = intdelay_reg_3[intdelay_t_0_02];
    end

  end



  always @(posedge clk)
    begin : intdelay_4_process
      if (reset == 1'b1) begin
        for(intdelay_t_1_2 = 32'sd0; intdelay_t_1_2 <= 32'sd2; intdelay_t_1_2 = intdelay_t_1_2 + 32'sd1) begin
          intdelay_reg_4[intdelay_t_1_2] <= 14'sb00000000000000;
        end
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            for(intdelay_t_1_2 = 32'sd0; intdelay_t_1_2 <= 32'sd2; intdelay_t_1_2 = intdelay_t_1_2 + 32'sd1) 
              begin
              intdelay_reg_4[intdelay_t_1_2] <= 14'sb00000000000000;
            end
          end
          else begin
            for(intdelay_t_0_1_2 = 32'sd0; intdelay_t_0_1_2 <= 32'sd2; intdelay_t_0_1_2 = intdelay_t_0_1_2 + 
              32'sd1) begin
              intdelay_reg_4[intdelay_t_0_1_2] <= intdelay_reg_next_3[intdelay_t_0_1_2];
            end
          end
        end
      end
    end

  always @* begin
    din_3_1_im_dly = intdelay_reg_4[2];
    intdelay_reg_next_3[0] = dout_2_1_im;

    for(intdelay_t_0_03 = 32'sd0; intdelay_t_0_03 <= 32'sd1; intdelay_t_0_03 = intdelay_t_0_03 + 32'sd1) begin
      intdelay_reg_next_3[intdelay_t_0_03 + 32'sd1] = intdelay_reg_4[intdelay_t_0_03];
    end

  end



  always @(posedge clk)
    begin : intdelay_5_process
      if (reset == 1'b1) begin
        intdelay_reg_5 <= {3{1'b0}};
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            intdelay_reg_5 <= {3{1'b0}};
          end
          else begin
            intdelay_reg_5[0] <= dout_2_1_vld;
            intdelay_reg_5[32'sd2:32'sd1] <= intdelay_reg_5[32'sd1:32'sd0];
          end
        end
      end
    end

  assign din_3_vld_dly = intdelay_reg_5[2];



  Subsystem_ip2_src_TWDLROM_3 twdlROM_3_1_1 (.clk(clk),
                                             .reset(reset),
                                             .enb(enb),
                                             .dout_2_1_vld(dout_2_1_vld),
                                             .syncReset(syncReset),
                                             .twdl_3_1_re(twdl_3_1_re),  // sfix12_En10
                                             .twdl_3_1_im(twdl_3_1_im)  // sfix12_En10
                                             );

  Subsystem_ip2_src_RADIX22FFT_block4 CTRL1_3_1_1 (.clk(clk),
                                                   .reset(reset),
                                                   .enb(enb),
                                                   .dinXTwdl_3_1_vld(dinXTwdl_3_1_vld),
                                                   .dinXTwdl_3_1_vld_1(dinXTwdl_3_1_vld),
                                                   .syncReset(syncReset),
                                                   .rd_3_Addr(rd_3_Addr),  // ufix8
                                                   .rd_3_Enb(rd_3_Enb),
                                                   .proc_3_enb(proc_3_enb)
                                                   );

  Subsystem_ip2_src_RADIX22FFT_block3 SDF1_3_1_1 (.clk(clk),
                                                  .reset(reset),
                                                  .enb(enb),
                                                  .din_3_1_re_dly(din_3_1_re_dly),  // sfix14_En11
                                                  .din_3_1_im_dly(din_3_1_im_dly),  // sfix14_En11
                                                  .din_3_vld_dly(din_3_vld_dly),
                                                  .rd_3_Addr(rd_3_Addr),  // ufix8
                                                  .rd_3_Enb(rd_3_Enb),
                                                  .twdl_3_1_re(twdl_3_1_re),  // sfix12_En10
                                                  .twdl_3_1_im(twdl_3_1_im),  // sfix12_En10
                                                  .proc_3_enb(proc_3_enb),
                                                  .syncReset(syncReset),
                                                  .dout_3_1_re(dout_3_1_re),  // sfix15_En11
                                                  .dout_3_1_im(dout_3_1_im),  // sfix15_En11
                                                  .dout_3_1_vld(dout_3_1_vld),
                                                  .dinXTwdl_3_1_vld(dinXTwdl_3_1_vld)
                                                  );

  Subsystem_ip2_src_RADIX22FFT_block6 CTRL2_4_1_1 (.clk(clk),
                                                   .reset(reset),
                                                   .enb(enb),
                                                   .dout_3_1_vld(dout_3_1_vld),
                                                   .dinXTwdl_4_1_vld(dinXTwdl_4_1_vld),
                                                   .syncReset(syncReset),
                                                   .rd_4_Addr(rd_4_Addr),  // ufix7
                                                   .rd_4_Enb(rd_4_Enb),
                                                   .proc_4_enb(proc_4_enb),
                                                   .multiply_4_J(multiply_4_J)
                                                   );

  Subsystem_ip2_src_RADIX22FFT_block5 SDF2_4_1_1 (.clk(clk),
                                                  .reset(reset),
                                                  .enb(enb),
                                                  .dout_3_1_re(dout_3_1_re),  // sfix15_En11
                                                  .dout_3_1_im(dout_3_1_im),  // sfix15_En11
                                                  .dout_3_1_vld(dout_3_1_vld),
                                                  .rd_4_Addr(rd_4_Addr),  // ufix7
                                                  .rd_4_Enb(rd_4_Enb),
                                                  .proc_4_enb(proc_4_enb),
                                                  .multiply_4_J(multiply_4_J),
                                                  .syncReset(syncReset),
                                                  .dout_4_1_re(dout_4_1_re),  // sfix16_En11
                                                  .dout_4_1_im(dout_4_1_im),  // sfix16_En11
                                                  .dout_4_1_vld(dout_4_1_vld),
                                                  .dinXTwdl_4_1_vld(dinXTwdl_4_1_vld)
                                                  );

  always @(posedge clk)
    begin : intdelay_6_process
      if (reset == 1'b1) begin
        for(intdelay_t_1_3 = 32'sd0; intdelay_t_1_3 <= 32'sd2; intdelay_t_1_3 = intdelay_t_1_3 + 32'sd1) begin
          intdelay_reg_6[intdelay_t_1_3] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            for(intdelay_t_1_3 = 32'sd0; intdelay_t_1_3 <= 32'sd2; intdelay_t_1_3 = intdelay_t_1_3 + 32'sd1) 
              begin
              intdelay_reg_6[intdelay_t_1_3] <= 16'sb0000000000000000;
            end
          end
          else begin
            for(intdelay_t_0_1_3 = 32'sd0; intdelay_t_0_1_3 <= 32'sd2; intdelay_t_0_1_3 = intdelay_t_0_1_3 + 
              32'sd1) begin
              intdelay_reg_6[intdelay_t_0_1_3] <= intdelay_reg_next_4[intdelay_t_0_1_3];
            end
          end
        end
      end
    end

  always @* begin
    din_5_1_re_dly = intdelay_reg_6[2];
    intdelay_reg_next_4[0] = dout_4_1_re;

    for(intdelay_t_0_04 = 32'sd0; intdelay_t_0_04 <= 32'sd1; intdelay_t_0_04 = intdelay_t_0_04 + 32'sd1) begin
      intdelay_reg_next_4[intdelay_t_0_04 + 32'sd1] = intdelay_reg_6[intdelay_t_0_04];
    end

  end



  always @(posedge clk)
    begin : intdelay_7_process
      if (reset == 1'b1) begin
        for(intdelay_t_1_4 = 32'sd0; intdelay_t_1_4 <= 32'sd2; intdelay_t_1_4 = intdelay_t_1_4 + 32'sd1) begin
          intdelay_reg_7[intdelay_t_1_4] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            for(intdelay_t_1_4 = 32'sd0; intdelay_t_1_4 <= 32'sd2; intdelay_t_1_4 = intdelay_t_1_4 + 32'sd1) 
              begin
              intdelay_reg_7[intdelay_t_1_4] <= 16'sb0000000000000000;
            end
          end
          else begin
            for(intdelay_t_0_1_4 = 32'sd0; intdelay_t_0_1_4 <= 32'sd2; intdelay_t_0_1_4 = intdelay_t_0_1_4 + 
              32'sd1) begin
              intdelay_reg_7[intdelay_t_0_1_4] <= intdelay_reg_next_5[intdelay_t_0_1_4];
            end
          end
        end
      end
    end

  always @* begin
    din_5_1_im_dly = intdelay_reg_7[2];
    intdelay_reg_next_5[0] = dout_4_1_im;

    for(intdelay_t_0_05 = 32'sd0; intdelay_t_0_05 <= 32'sd1; intdelay_t_0_05 = intdelay_t_0_05 + 32'sd1) begin
      intdelay_reg_next_5[intdelay_t_0_05 + 32'sd1] = intdelay_reg_7[intdelay_t_0_05];
    end

  end



  always @(posedge clk)
    begin : intdelay_8_process
      if (reset == 1'b1) begin
        intdelay_reg_8 <= {3{1'b0}};
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            intdelay_reg_8 <= {3{1'b0}};
          end
          else begin
            intdelay_reg_8[0] <= dout_4_1_vld;
            intdelay_reg_8[32'sd2:32'sd1] <= intdelay_reg_8[32'sd1:32'sd0];
          end
        end
      end
    end

  assign din_5_vld_dly = intdelay_reg_8[2];



  Subsystem_ip2_src_TWDLROM_5 twdlROM_5_1_1 (.clk(clk),
                                             .reset(reset),
                                             .enb(enb),
                                             .dout_4_1_vld(dout_4_1_vld),
                                             .syncReset(syncReset),
                                             .twdl_5_1_re(twdl_5_1_re),  // sfix12_En10
                                             .twdl_5_1_im(twdl_5_1_im)  // sfix12_En10
                                             );

  Subsystem_ip2_src_RADIX22FFT_block8 CTRL1_5_1_1 (.clk(clk),
                                                   .reset(reset),
                                                   .enb(enb),
                                                   .dinXTwdl_5_1_vld(dinXTwdl_5_1_vld),
                                                   .dinXTwdl_5_1_vld_1(dinXTwdl_5_1_vld),
                                                   .syncReset(syncReset),
                                                   .rd_5_Addr(rd_5_Addr),  // ufix6
                                                   .rd_5_Enb(rd_5_Enb),
                                                   .proc_5_enb(proc_5_enb)
                                                   );

  Subsystem_ip2_src_RADIX22FFT_block7 SDF1_5_1_1 (.clk(clk),
                                                  .reset(reset),
                                                  .enb(enb),
                                                  .din_5_1_re_dly(din_5_1_re_dly),  // sfix16_En11
                                                  .din_5_1_im_dly(din_5_1_im_dly),  // sfix16_En11
                                                  .din_5_vld_dly(din_5_vld_dly),
                                                  .rd_5_Addr(rd_5_Addr),  // ufix6
                                                  .rd_5_Enb(rd_5_Enb),
                                                  .twdl_5_1_re(twdl_5_1_re),  // sfix12_En10
                                                  .twdl_5_1_im(twdl_5_1_im),  // sfix12_En10
                                                  .proc_5_enb(proc_5_enb),
                                                  .syncReset(syncReset),
                                                  .dout_5_1_re(dout_5_1_re),  // sfix17_En11
                                                  .dout_5_1_im(dout_5_1_im),  // sfix17_En11
                                                  .dout_5_1_vld(dout_5_1_vld),
                                                  .dinXTwdl_5_1_vld(dinXTwdl_5_1_vld)
                                                  );

  Subsystem_ip2_src_RADIX22FFT_block10 CTRL2_6_1_1 (.clk(clk),
                                                    .reset(reset),
                                                    .enb(enb),
                                                    .dout_5_1_vld(dout_5_1_vld),
                                                    .dinXTwdl_6_1_vld(dinXTwdl_6_1_vld),
                                                    .syncReset(syncReset),
                                                    .rd_6_Addr(rd_6_Addr),  // ufix5
                                                    .rd_6_Enb(rd_6_Enb),
                                                    .proc_6_enb(proc_6_enb),
                                                    .multiply_6_J(multiply_6_J)
                                                    );

  Subsystem_ip2_src_RADIX22FFT_block9 SDF2_6_1_1 (.clk(clk),
                                                  .reset(reset),
                                                  .enb(enb),
                                                  .dout_5_1_re(dout_5_1_re),  // sfix17_En11
                                                  .dout_5_1_im(dout_5_1_im),  // sfix17_En11
                                                  .dout_5_1_vld(dout_5_1_vld),
                                                  .rd_6_Addr(rd_6_Addr),  // ufix5
                                                  .rd_6_Enb(rd_6_Enb),
                                                  .proc_6_enb(proc_6_enb),
                                                  .multiply_6_J(multiply_6_J),
                                                  .syncReset(syncReset),
                                                  .dout_6_1_re(dout_6_1_re),  // sfix18_En11
                                                  .dout_6_1_im(dout_6_1_im),  // sfix18_En11
                                                  .dout_6_1_vld(dout_6_1_vld),
                                                  .dinXTwdl_6_1_vld(dinXTwdl_6_1_vld)
                                                  );

  always @(posedge clk)
    begin : intdelay_9_process
      if (reset == 1'b1) begin
        for(intdelay_t_1_5 = 32'sd0; intdelay_t_1_5 <= 32'sd2; intdelay_t_1_5 = intdelay_t_1_5 + 32'sd1) begin
          intdelay_reg_9[intdelay_t_1_5] <= 18'sb000000000000000000;
        end
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            for(intdelay_t_1_5 = 32'sd0; intdelay_t_1_5 <= 32'sd2; intdelay_t_1_5 = intdelay_t_1_5 + 32'sd1) 
              begin
              intdelay_reg_9[intdelay_t_1_5] <= 18'sb000000000000000000;
            end
          end
          else begin
            for(intdelay_t_0_1_5 = 32'sd0; intdelay_t_0_1_5 <= 32'sd2; intdelay_t_0_1_5 = intdelay_t_0_1_5 + 
              32'sd1) begin
              intdelay_reg_9[intdelay_t_0_1_5] <= intdelay_reg_next_6[intdelay_t_0_1_5];
            end
          end
        end
      end
    end

  always @* begin
    din_7_1_re_dly = intdelay_reg_9[2];
    intdelay_reg_next_6[0] = dout_6_1_re;

    for(intdelay_t_0_06 = 32'sd0; intdelay_t_0_06 <= 32'sd1; intdelay_t_0_06 = intdelay_t_0_06 + 32'sd1) begin
      intdelay_reg_next_6[intdelay_t_0_06 + 32'sd1] = intdelay_reg_9[intdelay_t_0_06];
    end

  end



  always @(posedge clk)
    begin : intdelay_10_process
      if (reset == 1'b1) begin
        for(intdelay_t_1_6 = 32'sd0; intdelay_t_1_6 <= 32'sd2; intdelay_t_1_6 = intdelay_t_1_6 + 32'sd1) begin
          intdelay_reg_10[intdelay_t_1_6] <= 18'sb000000000000000000;
        end
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            for(intdelay_t_1_6 = 32'sd0; intdelay_t_1_6 <= 32'sd2; intdelay_t_1_6 = intdelay_t_1_6 + 32'sd1) 
              begin
              intdelay_reg_10[intdelay_t_1_6] <= 18'sb000000000000000000;
            end
          end
          else begin
            for(intdelay_t_0_1_6 = 32'sd0; intdelay_t_0_1_6 <= 32'sd2; intdelay_t_0_1_6 = intdelay_t_0_1_6 + 
              32'sd1) begin
              intdelay_reg_10[intdelay_t_0_1_6] <= intdelay_reg_next_7[intdelay_t_0_1_6];
            end
          end
        end
      end
    end

  always @* begin
    din_7_1_im_dly = intdelay_reg_10[2];
    intdelay_reg_next_7[0] = dout_6_1_im;

    for(intdelay_t_0_07 = 32'sd0; intdelay_t_0_07 <= 32'sd1; intdelay_t_0_07 = intdelay_t_0_07 + 32'sd1) begin
      intdelay_reg_next_7[intdelay_t_0_07 + 32'sd1] = intdelay_reg_10[intdelay_t_0_07];
    end

  end



  always @(posedge clk)
    begin : intdelay_11_process
      if (reset == 1'b1) begin
        intdelay_reg_11 <= {3{1'b0}};
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            intdelay_reg_11 <= {3{1'b0}};
          end
          else begin
            intdelay_reg_11[0] <= dout_6_1_vld;
            intdelay_reg_11[32'sd2:32'sd1] <= intdelay_reg_11[32'sd1:32'sd0];
          end
        end
      end
    end

  assign din_7_vld_dly = intdelay_reg_11[2];



  Subsystem_ip2_src_TWDLROM_7 twdlROM_7_1_1 (.clk(clk),
                                             .reset(reset),
                                             .enb(enb),
                                             .dout_6_1_vld(dout_6_1_vld),
                                             .syncReset(syncReset),
                                             .twdl_7_1_re(twdl_7_1_re),  // sfix12_En10
                                             .twdl_7_1_im(twdl_7_1_im)  // sfix12_En10
                                             );

  Subsystem_ip2_src_RADIX22FFT_block12 CTRL1_7_1_1 (.clk(clk),
                                                    .reset(reset),
                                                    .enb(enb),
                                                    .dinXTwdl_7_1_vld(dinXTwdl_7_1_vld),
                                                    .dinXTwdl_7_1_vld_1(dinXTwdl_7_1_vld),
                                                    .syncReset(syncReset),
                                                    .rd_7_Addr(rd_7_Addr),  // ufix4
                                                    .rd_7_Enb(rd_7_Enb),
                                                    .proc_7_enb(proc_7_enb)
                                                    );

  Subsystem_ip2_src_RADIX22FFT_block11 SDF1_7_1_1 (.clk(clk),
                                                   .reset(reset),
                                                   .enb(enb),
                                                   .din_7_1_re_dly(din_7_1_re_dly),  // sfix18_En11
                                                   .din_7_1_im_dly(din_7_1_im_dly),  // sfix18_En11
                                                   .din_7_vld_dly(din_7_vld_dly),
                                                   .rd_7_Addr(rd_7_Addr),  // ufix4
                                                   .rd_7_Enb(rd_7_Enb),
                                                   .twdl_7_1_re(twdl_7_1_re),  // sfix12_En10
                                                   .twdl_7_1_im(twdl_7_1_im),  // sfix12_En10
                                                   .proc_7_enb(proc_7_enb),
                                                   .syncReset(syncReset),
                                                   .dout_7_1_re(dout_7_1_re),  // sfix19_En11
                                                   .dout_7_1_im(dout_7_1_im),  // sfix19_En11
                                                   .dout_7_1_vld(dout_7_1_vld),
                                                   .dinXTwdl_7_1_vld(dinXTwdl_7_1_vld)
                                                   );

  Subsystem_ip2_src_RADIX22FFT_block14 CTRL2_8_1_1 (.clk(clk),
                                                    .reset(reset),
                                                    .enb(enb),
                                                    .dout_7_1_vld(dout_7_1_vld),
                                                    .dinXTwdl_8_1_vld(dinXTwdl_8_1_vld),
                                                    .syncReset(syncReset),
                                                    .rd_8_Addr(rd_8_Addr),  // ufix3
                                                    .rd_8_Enb(rd_8_Enb),
                                                    .proc_8_enb(proc_8_enb),
                                                    .multiply_8_J(multiply_8_J)
                                                    );

  Subsystem_ip2_src_RADIX22FFT_block13 SDF2_8_1_1 (.clk(clk),
                                                   .reset(reset),
                                                   .enb(enb),
                                                   .dout_7_1_re(dout_7_1_re),  // sfix19_En11
                                                   .dout_7_1_im(dout_7_1_im),  // sfix19_En11
                                                   .dout_7_1_vld(dout_7_1_vld),
                                                   .rd_8_Addr(rd_8_Addr),  // ufix3
                                                   .rd_8_Enb(rd_8_Enb),
                                                   .proc_8_enb(proc_8_enb),
                                                   .multiply_8_J(multiply_8_J),
                                                   .syncReset(syncReset),
                                                   .dout_8_1_re(dout_8_1_re),  // sfix20_En11
                                                   .dout_8_1_im(dout_8_1_im),  // sfix20_En11
                                                   .dout_8_1_vld(dout_8_1_vld),
                                                   .dinXTwdl_8_1_vld(dinXTwdl_8_1_vld)
                                                   );

  always @(posedge clk)
    begin : intdelay_12_process
      if (reset == 1'b1) begin
        for(intdelay_t_1_7 = 32'sd0; intdelay_t_1_7 <= 32'sd2; intdelay_t_1_7 = intdelay_t_1_7 + 32'sd1) begin
          intdelay_reg_12[intdelay_t_1_7] <= 20'sb00000000000000000000;
        end
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            for(intdelay_t_1_7 = 32'sd0; intdelay_t_1_7 <= 32'sd2; intdelay_t_1_7 = intdelay_t_1_7 + 32'sd1) 
              begin
              intdelay_reg_12[intdelay_t_1_7] <= 20'sb00000000000000000000;
            end
          end
          else begin
            for(intdelay_t_0_1_7 = 32'sd0; intdelay_t_0_1_7 <= 32'sd2; intdelay_t_0_1_7 = intdelay_t_0_1_7 + 
              32'sd1) begin
              intdelay_reg_12[intdelay_t_0_1_7] <= intdelay_reg_next_8[intdelay_t_0_1_7];
            end
          end
        end
      end
    end

  always @* begin
    din_9_1_re_dly = intdelay_reg_12[2];
    intdelay_reg_next_8[0] = dout_8_1_re;

    for(intdelay_t_0_08 = 32'sd0; intdelay_t_0_08 <= 32'sd1; intdelay_t_0_08 = intdelay_t_0_08 + 32'sd1) begin
      intdelay_reg_next_8[intdelay_t_0_08 + 32'sd1] = intdelay_reg_12[intdelay_t_0_08];
    end

  end



  always @(posedge clk)
    begin : intdelay_13_process
      if (reset == 1'b1) begin
        for(intdelay_t_1_8 = 32'sd0; intdelay_t_1_8 <= 32'sd2; intdelay_t_1_8 = intdelay_t_1_8 + 32'sd1) begin
          intdelay_reg_13[intdelay_t_1_8] <= 20'sb00000000000000000000;
        end
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            for(intdelay_t_1_8 = 32'sd0; intdelay_t_1_8 <= 32'sd2; intdelay_t_1_8 = intdelay_t_1_8 + 32'sd1) 
              begin
              intdelay_reg_13[intdelay_t_1_8] <= 20'sb00000000000000000000;
            end
          end
          else begin
            for(intdelay_t_0_1_8 = 32'sd0; intdelay_t_0_1_8 <= 32'sd2; intdelay_t_0_1_8 = intdelay_t_0_1_8 + 
              32'sd1) begin
              intdelay_reg_13[intdelay_t_0_1_8] <= intdelay_reg_next_9[intdelay_t_0_1_8];
            end
          end
        end
      end
    end

  always @* begin
    din_9_1_im_dly = intdelay_reg_13[2];
    intdelay_reg_next_9[0] = dout_8_1_im;

    for(intdelay_t_0_09 = 32'sd0; intdelay_t_0_09 <= 32'sd1; intdelay_t_0_09 = intdelay_t_0_09 + 32'sd1) begin
      intdelay_reg_next_9[intdelay_t_0_09 + 32'sd1] = intdelay_reg_13[intdelay_t_0_09];
    end

  end



  always @(posedge clk)
    begin : intdelay_14_process
      if (reset == 1'b1) begin
        intdelay_reg_14 <= {3{1'b0}};
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            intdelay_reg_14 <= {3{1'b0}};
          end
          else begin
            intdelay_reg_14[0] <= dout_8_1_vld;
            intdelay_reg_14[32'sd2:32'sd1] <= intdelay_reg_14[32'sd1:32'sd0];
          end
        end
      end
    end

  assign din_9_vld_dly = intdelay_reg_14[2];



  Subsystem_ip2_src_TWDLROM_9 twdlROM_9_1_1 (.clk(clk),
                                             .reset(reset),
                                             .enb(enb),
                                             .dout_8_1_vld(dout_8_1_vld),
                                             .syncReset(syncReset),
                                             .twdl_9_1_re(twdl_9_1_re),  // sfix12_En10
                                             .twdl_9_1_im(twdl_9_1_im)  // sfix12_En10
                                             );

  Subsystem_ip2_src_RADIX22FFT_block16 CTRL1_9_1_1 (.clk(clk),
                                                    .reset(reset),
                                                    .enb(enb),
                                                    .dinXTwdl_9_1_vld(dinXTwdl_9_1_vld),
                                                    .dinXTwdl_9_1_vld_1(dinXTwdl_9_1_vld),
                                                    .syncReset(syncReset),
                                                    .rd_9_Addr(rd_9_Addr),  // ufix2
                                                    .rd_9_Enb(rd_9_Enb),
                                                    .proc_9_enb(proc_9_enb)
                                                    );

  Subsystem_ip2_src_RADIX22FFT_block15 SDF1_9_1_1 (.clk(clk),
                                                   .reset(reset),
                                                   .enb(enb),
                                                   .din_9_1_re_dly(din_9_1_re_dly),  // sfix20_En11
                                                   .din_9_1_im_dly(din_9_1_im_dly),  // sfix20_En11
                                                   .din_9_vld_dly(din_9_vld_dly),
                                                   .rd_9_Addr(rd_9_Addr),  // ufix2
                                                   .rd_9_Enb(rd_9_Enb),
                                                   .twdl_9_1_re(twdl_9_1_re),  // sfix12_En10
                                                   .twdl_9_1_im(twdl_9_1_im),  // sfix12_En10
                                                   .proc_9_enb(proc_9_enb),
                                                   .syncReset(syncReset),
                                                   .dout_9_1_re(dout_9_1_re),  // sfix21_En11
                                                   .dout_9_1_im(dout_9_1_im),  // sfix21_En11
                                                   .dout_9_1_vld(dout_9_1_vld),
                                                   .dinXTwdl_9_1_vld(dinXTwdl_9_1_vld)
                                                   );

  Subsystem_ip2_src_RADIX22FFT_block18 CTRL2_10_1_1 (.clk(clk),
                                                     .reset(reset),
                                                     .enb(enb),
                                                     .dout_9_1_vld(dout_9_1_vld),
                                                     .dinXTwdl_10_1_vld(dinXTwdl_10_1_vld),
                                                     .syncReset(syncReset),
                                                     .rd_10_Addr(rd_10_Addr),  // ufix1
                                                     .rd_10_Enb(rd_10_Enb),
                                                     .proc_10_enb(proc_10_enb),
                                                     .multiply_10_J(multiply_10_J)
                                                     );

  Subsystem_ip2_src_RADIX22FFT_block17 SDF2_10_1_1 (.clk(clk),
                                                    .reset(reset),
                                                    .enb(enb),
                                                    .dout_9_1_re(dout_9_1_re),  // sfix21_En11
                                                    .dout_9_1_im(dout_9_1_im),  // sfix21_En11
                                                    .dout_9_1_vld(dout_9_1_vld),
                                                    .rd_10_Addr(rd_10_Addr),  // ufix1
                                                    .rd_10_Enb(rd_10_Enb),
                                                    .proc_10_enb(proc_10_enb),
                                                    .multiply_10_J(multiply_10_J),
                                                    .syncReset(syncReset),
                                                    .dout_10_1_re(dout_10_1_re),  // sfix22_En11
                                                    .dout_10_1_im(dout_10_1_im),  // sfix22_En11
                                                    .dout_10_1_vld(dout_10_1_vld),
                                                    .dinXTwdl_10_1_vld(dinXTwdl_10_1_vld)
                                                    );

  always @(posedge clk)
    begin : intdelay_15_process
      if (reset == 1'b1) begin
        for(intdelay_t_1_9 = 32'sd0; intdelay_t_1_9 <= 32'sd2; intdelay_t_1_9 = intdelay_t_1_9 + 32'sd1) begin
          intdelay_reg_15[intdelay_t_1_9] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            for(intdelay_t_1_9 = 32'sd0; intdelay_t_1_9 <= 32'sd2; intdelay_t_1_9 = intdelay_t_1_9 + 32'sd1) 
              begin
              intdelay_reg_15[intdelay_t_1_9] <= 22'sb0000000000000000000000;
            end
          end
          else begin
            for(intdelay_t_0_1_9 = 32'sd0; intdelay_t_0_1_9 <= 32'sd2; intdelay_t_0_1_9 = intdelay_t_0_1_9 + 
              32'sd1) begin
              intdelay_reg_15[intdelay_t_0_1_9] <= intdelay_reg_next_10[intdelay_t_0_1_9];
            end
          end
        end
      end
    end

  always @* begin
    din_11_re_dly = intdelay_reg_15[2];
    intdelay_reg_next_10[0] = dout_10_1_re;

    for(intdelay_t_0_010 = 32'sd0; intdelay_t_0_010 <= 32'sd1; intdelay_t_0_010 = intdelay_t_0_010 + 32'sd1) 
      begin
      intdelay_reg_next_10[intdelay_t_0_010 + 32'sd1] = intdelay_reg_15[intdelay_t_0_010];
    end

  end



  always @(posedge clk)
    begin : intdelay_16_process
      if (reset == 1'b1) begin
        for(intdelay_t_1_10 = 32'sd0; intdelay_t_1_10 <= 32'sd2; intdelay_t_1_10 = intdelay_t_1_10 + 32'sd1) 
          begin
          intdelay_reg_16[intdelay_t_1_10] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            for(intdelay_t_1_10 = 32'sd0; intdelay_t_1_10 <= 32'sd2; intdelay_t_1_10 = intdelay_t_1_10 + 
              32'sd1) begin
              intdelay_reg_16[intdelay_t_1_10] <= 22'sb0000000000000000000000;
            end
          end
          else begin
            for(intdelay_t_0_1_10 = 32'sd0; intdelay_t_0_1_10 <= 32'sd2; intdelay_t_0_1_10 = 
              intdelay_t_0_1_10 + 32'sd1) begin
              intdelay_reg_16[intdelay_t_0_1_10] <= intdelay_reg_next_11[intdelay_t_0_1_10];
            end
          end
        end
      end
    end

  always @* begin
    din_11_im_dly = intdelay_reg_16[2];
    intdelay_reg_next_11[0] = dout_10_1_im;

    for(intdelay_t_0_011 = 32'sd0; intdelay_t_0_011 <= 32'sd1; intdelay_t_0_011 = intdelay_t_0_011 + 32'sd1) 
      begin
      intdelay_reg_next_11[intdelay_t_0_011 + 32'sd1] = intdelay_reg_16[intdelay_t_0_011];
    end

  end



  always @(posedge clk)
    begin : intdelay_17_process
      if (reset == 1'b1) begin
        intdelay_reg_17 <= {3{1'b0}};
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            intdelay_reg_17 <= {3{1'b0}};
          end
          else begin
            intdelay_reg_17[0] <= dout_10_1_vld;
            intdelay_reg_17[32'sd2:32'sd1] <= intdelay_reg_17[32'sd1:32'sd0];
          end
        end
      end
    end

  assign din_11_vld_dly = intdelay_reg_17[2];



  Subsystem_ip2_src_TWDLROM_11 twdlROM_11_1 (.clk(clk),
                                             .reset(reset),
                                             .enb(enb),
                                             .dout_10_1_vld(dout_10_1_vld),
                                             .syncReset(syncReset),
                                             .twdl_11_re(twdl_11_re),  // sfix12_En10
                                             .twdl_11_im(twdl_11_im)  // sfix12_En10
                                             );

  always @(posedge clk)
    begin : intdelay_18_process
      if (reset == 1'b1) begin
        rd_11_Enb_dly <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            rd_11_Enb_dly <= 1'b0;
          end
          else begin
            rd_11_Enb_dly <= rd_11_Enb;
          end
        end
      end
    end



  Subsystem_ip2_src_RADIX22FFT_block20 CTRLRX2_1 (.clk(clk),
                                                  .reset(reset),
                                                  .enb(enb),
                                                  .dinXTwdl_11_vld(dinXTwdl_11_vld),
                                                  .dinXTwdl_11_vld_1(dinXTwdl_11_vld),
                                                  .syncReset(syncReset),
                                                  .rd_11_Addr(rd_11_Addr),
                                                  .rd_11_Enb(rd_11_Enb),
                                                  .proc_11_enb(proc_11_enb)
                                                  );

  Subsystem_ip2_src_RADIX22FFT_block19 RADIX2_1 (.clk(clk),
                                                 .reset(reset),
                                                 .enb(enb),
                                                 .din_11_re_dly(din_11_re_dly),  // sfix22_En11
                                                 .din_11_im_dly(din_11_im_dly),  // sfix22_En11
                                                 .din_11_vld_dly(din_11_vld_dly),
                                                 .rd_11_Addr(rd_11_Addr),
                                                 .rd_11_Enb_dly(rd_11_Enb_dly),
                                                 .twdl_11_re(twdl_11_re),  // sfix12_En10
                                                 .twdl_11_im(twdl_11_im),  // sfix12_En10
                                                 .proc_11_enb(proc_11_enb),
                                                 .syncReset(syncReset),
                                                 .dout_11_re(dout_11_re),  // sfix23_En11
                                                 .dout_11_im(dout_11_im),  // sfix23_En11
                                                 .dout_11_vld(dout_11_vld),
                                                 .dinXTwdl_11_vld(dinXTwdl_11_vld)
                                                 );

  Subsystem_ip2_src_RADIX2FFT NaturalOrder_Stage_1 (.clk(clk),
                                                    .reset(reset),
                                                    .enb(enb),
                                                    .dout_11_re(dout_11_re),  // sfix23_En11
                                                    .dout_11_im(dout_11_im),  // sfix23_En11
                                                    .dout_11_vld(dout_11_vld),
                                                    .syncReset(syncReset),
                                                    .dout_re1(dout_re1),  // sfix23_En11
                                                    .dout_im1(dout_im1),  // sfix23_En11
                                                    .dout_vld1(dout_vld1)
                                                    );

  assign dataOut_re = dout_re1;

  assign dataOut_im = dout_im1;

  assign validOut = dout_vld1;

endmodule  // Subsystem_ip2_src_FFT

