// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdl_model_fixed\Subsystem_ip2_src_Cast_to_Un.v
// Created: 2024-12-21 14:39:09
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_ip2_src_Cast_to_Un

// Source Path: hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex/CORDIC Square Root HDL Optimized1/Cast 
// to Union of Type
// Hierarchy Level: 4
// Model version: 1.110
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_ip2_src_Cast_to_Un
          (Xref,
           Cin,
           Cout);


  input   signed [23:0] Xref;  // sfix24_En22
  input   signed [23:0] Cin;  // sfix24_En22
  output  signed [23:0] Cout;  // sfix24_En22




  //castToUnionType Cast second input to union of the two types
  assign Cout = Cin;



endmodule  // Subsystem_ip2_src_Cast_to_Un

