// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdl_model_fixed\Subsystem_ip2_src_RADIX22FFT_block9.v
// Created: 2024-12-21 14:39:09
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_ip2_src_RADIX22FFT_block9
// Source Path: hdl_model_fixed/Subsystem1/Subsystem/FFT/RADIX22FFT_SDF2_6
// Hierarchy Level: 3
// Model version: 1.110
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_ip2_src_RADIX22FFT_block9
          (clk,
           reset,
           enb,
           dout_5_1_re,
           dout_5_1_im,
           dout_5_1_vld,
           rd_6_Addr,
           rd_6_Enb,
           proc_6_enb,
           multiply_6_J,
           syncReset,
           dout_6_1_re,
           dout_6_1_im,
           dout_6_1_vld,
           dinXTwdl_6_1_vld);


  input   clk;
  input   reset;
  input   enb;
  input   signed [16:0] dout_5_1_re;  // sfix17_En11
  input   signed [16:0] dout_5_1_im;  // sfix17_En11
  input   dout_5_1_vld;
  input   [4:0] rd_6_Addr;  // ufix5
  input   rd_6_Enb;
  input   proc_6_enb;
  input   multiply_6_J;
  input   syncReset;
  output  signed [17:0] dout_6_1_re;  // sfix18_En11
  output  signed [17:0] dout_6_1_im;  // sfix18_En11
  output  dout_6_1_vld;
  output  dinXTwdl_6_1_vld;


  wire signed [17:0] din_re;  // sfix18_En11
  wire signed [17:0] din_im;  // sfix18_En11
  wire btfin_vld;
  wire saveEnb;
  wire dinVld;
  reg  x_vld;
  reg  x_vld_dly;
  wire signed [17:0] wrData_im;  // sfix18_En11
  wire [4:0] wrAddr;  // ufix5
  wire wrEnb;
  wire signed [17:0] x_im;  // sfix18_En11
  reg signed [17:0] x_im_dly;  // sfix18_En11
  wire signed [17:0] wrData_re;  // sfix18_En11
  wire signed [17:0] x_re;  // sfix18_En11
  reg signed [17:0] x_re_dly;  // sfix18_En11
  reg  Radix22ButterflyG2_procEnb_dly;
  reg  Radix22ButterflyG2_procEnb_dly1;
  reg  Radix22ButterflyG2_procEnb_dly2;
  reg signed [18:0] Radix22ButterflyG2_btf1_re_reg;  // sfix19
  reg signed [18:0] Radix22ButterflyG2_btf1_im_reg;  // sfix19
  reg signed [18:0] Radix22ButterflyG2_btf2_re_reg;  // sfix19
  reg signed [18:0] Radix22ButterflyG2_btf2_im_reg;  // sfix19
  reg signed [17:0] Radix22ButterflyG2_din_re_dly;  // sfix18
  reg signed [17:0] Radix22ButterflyG2_din_im_dly;  // sfix18
  reg  Radix22ButterflyG2_din_vld_dly;
  reg signed [17:0] Radix22ButterflyG2_x_re_dly;  // sfix18
  reg signed [17:0] Radix22ButterflyG2_x_im_dly;  // sfix18
  reg  Radix22ButterflyG2_x_vld_dly;
  reg signed [17:0] Radix22ButterflyG2_dinXTwdl_re_dly1;  // sfix18
  reg signed [17:0] Radix22ButterflyG2_dinXTwdl_im_dly1;  // sfix18
  reg signed [17:0] Radix22ButterflyG2_dinXTwdl_re_dly2;  // sfix18
  reg signed [17:0] Radix22ButterflyG2_dinXTwdl_im_dly2;  // sfix18
  reg  Radix22ButterflyG2_multiply_J_dly1;
  reg  Radix22ButterflyG2_procEnb_dly_next;
  reg  Radix22ButterflyG2_procEnb_dly1_next;
  reg  Radix22ButterflyG2_procEnb_dly2_next;
  reg signed [18:0] Radix22ButterflyG2_btf1_re_reg_next;  // sfix19_En11
  reg signed [18:0] Radix22ButterflyG2_btf1_im_reg_next;  // sfix19_En11
  reg signed [18:0] Radix22ButterflyG2_btf2_re_reg_next;  // sfix19_En11
  reg signed [18:0] Radix22ButterflyG2_btf2_im_reg_next;  // sfix19_En11
  reg signed [17:0] Radix22ButterflyG2_din_re_dly_next;  // sfix18_En11
  reg signed [17:0] Radix22ButterflyG2_din_im_dly_next;  // sfix18_En11
  reg  Radix22ButterflyG2_din_vld_dly_next;
  reg signed [17:0] Radix22ButterflyG2_x_re_dly_next;  // sfix18_En11
  reg signed [17:0] Radix22ButterflyG2_x_im_dly_next;  // sfix18_En11
  reg  Radix22ButterflyG2_x_vld_dly_next;
  reg signed [17:0] Radix22ButterflyG2_dinXTwdl_re_dly1_1;  // sfix18_En11
  reg signed [17:0] Radix22ButterflyG2_dinXTwdl_im_dly1_1;  // sfix18_En11
  reg signed [17:0] Radix22ButterflyG2_dinXTwdl_re_dly2_1;  // sfix18_En11
  reg signed [17:0] Radix22ButterflyG2_dinXTwdl_im_dly2_1;  // sfix18_En11
  reg  Radix22ButterflyG2_multiply_J_dly1_n;
  reg signed [17:0] xf_re;  // sfix18_En11
  reg signed [17:0] xf_im;  // sfix18_En11
  reg  xf_vld;
  reg signed [17:0] dinf_re;  // sfix18_En11
  reg signed [17:0] dinf_im;  // sfix18_En11
  reg  dinf_vld;
  reg signed [17:0] btf1_re;  // sfix18_En11
  reg signed [17:0] btf1_im;  // sfix18_En11
  reg signed [17:0] btf2_re;  // sfix18_En11
  reg signed [17:0] btf2_im;  // sfix18_En11
  reg  btfout_vld;
  reg signed [18:0] Radix22ButterflyG2_add_cast;  // sfix19_En11
  reg signed [18:0] Radix22ButterflyG2_add_cast_0;  // sfix19_En11
  reg signed [18:0] Radix22ButterflyG2_add_cast_1;  // sfix19_En11
  reg signed [18:0] Radix22ButterflyG2_add_cast_2;  // sfix19_En11
  reg signed [18:0] Radix22ButterflyG2_sub_cast;  // sfix19_En11
  reg signed [18:0] Radix22ButterflyG2_sub_cast_0;  // sfix19_En11
  reg signed [18:0] Radix22ButterflyG2_sub_cast_1;  // sfix19_En11
  reg signed [18:0] Radix22ButterflyG2_sub_cast_2;  // sfix19_En11
  reg signed [18:0] Radix22ButterflyG2_add_cast_3;  // sfix19_En11
  reg signed [18:0] Radix22ButterflyG2_add_cast_4;  // sfix19_En11
  reg signed [18:0] Radix22ButterflyG2_add_cast_5;  // sfix19_En11
  reg signed [18:0] Radix22ButterflyG2_add_cast_6;  // sfix19_En11
  reg signed [18:0] Radix22ButterflyG2_sub_cast_3;  // sfix19_En11
  reg signed [18:0] Radix22ButterflyG2_sub_cast_4;  // sfix19_En11
  reg signed [18:0] Radix22ButterflyG2_sub_cast_5;  // sfix19_En11
  reg signed [18:0] Radix22ButterflyG2_sub_cast_6;  // sfix19_En11


  assign din_re = {dout_5_1_re[16], dout_5_1_re};



  assign din_im = {dout_5_1_im[16], dout_5_1_im};



  assign btfin_vld = dout_5_1_vld & proc_6_enb;



  assign saveEnb =  ~ btfin_vld;



  assign dinVld = dout_5_1_vld & saveEnb;



  always @(posedge clk)
    begin : intdelay_process
      if (reset == 1'b1) begin
        x_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            x_vld <= 1'b0;
          end
          else begin
            x_vld <= rd_6_Enb;
          end
        end
      end
    end



  always @(posedge clk)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        x_vld_dly <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            x_vld_dly <= 1'b0;
          end
          else begin
            x_vld_dly <= x_vld;
          end
        end
      end
    end



  Subsystem_ip2_src_SimpleDual #(.AddrWidth(5),
                                 .DataWidth(18)
                                 )
                               dataMEM_im_0_6_1 (.clk(clk),
                                                 .enb(enb),
                                                 .wr_din(wrData_im),
                                                 .wr_addr(wrAddr),
                                                 .wr_en(wrEnb),
                                                 .rd_addr(rd_6_Addr),
                                                 .dout(x_im)
                                                 );

  always @(posedge clk)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        x_im_dly <= 18'sb000000000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            x_im_dly <= 18'sb000000000000000000;
          end
          else begin
            x_im_dly <= x_im;
          end
        end
      end
    end



  Subsystem_ip2_src_SimpleDual #(.AddrWidth(5),
                                 .DataWidth(18)
                                 )
                               dataMEM_re_0_6_1 (.clk(clk),
                                                 .enb(enb),
                                                 .wr_din(wrData_re),
                                                 .wr_addr(wrAddr),
                                                 .wr_en(wrEnb),
                                                 .rd_addr(rd_6_Addr),
                                                 .dout(x_re)
                                                 );

  always @(posedge clk)
    begin : intdelay_3_process
      if (reset == 1'b1) begin
        x_re_dly <= 18'sb000000000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            x_re_dly <= 18'sb000000000000000000;
          end
          else begin
            x_re_dly <= x_re;
          end
        end
      end
    end



  // Radix22ButterflyG2
  always @(posedge clk)
    begin : Radix22ButterflyG2_process
      if (reset == 1'b1) begin
        Radix22ButterflyG2_procEnb_dly <= 1'b0;
        Radix22ButterflyG2_procEnb_dly1 <= 1'b0;
        Radix22ButterflyG2_procEnb_dly2 <= 1'b0;
        Radix22ButterflyG2_btf1_re_reg <= 19'sb0000000000000000000;
        Radix22ButterflyG2_btf1_im_reg <= 19'sb0000000000000000000;
        Radix22ButterflyG2_btf2_re_reg <= 19'sb0000000000000000000;
        Radix22ButterflyG2_btf2_im_reg <= 19'sb0000000000000000000;
        Radix22ButterflyG2_din_re_dly <= 18'sb000000000000000000;
        Radix22ButterflyG2_din_im_dly <= 18'sb000000000000000000;
        Radix22ButterflyG2_din_vld_dly <= 1'b0;
        Radix22ButterflyG2_x_re_dly <= 18'sb000000000000000000;
        Radix22ButterflyG2_x_im_dly <= 18'sb000000000000000000;
        Radix22ButterflyG2_x_vld_dly <= 1'b0;
        Radix22ButterflyG2_dinXTwdl_re_dly1 <= 18'sb000000000000000000;
        Radix22ButterflyG2_dinXTwdl_im_dly1 <= 18'sb000000000000000000;
        Radix22ButterflyG2_dinXTwdl_re_dly2 <= 18'sb000000000000000000;
        Radix22ButterflyG2_dinXTwdl_im_dly2 <= 18'sb000000000000000000;
        Radix22ButterflyG2_multiply_J_dly1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            Radix22ButterflyG2_procEnb_dly <= 1'b0;
            Radix22ButterflyG2_procEnb_dly1 <= 1'b0;
            Radix22ButterflyG2_procEnb_dly2 <= 1'b0;
            Radix22ButterflyG2_btf1_re_reg <= 19'sb0000000000000000000;
            Radix22ButterflyG2_btf1_im_reg <= 19'sb0000000000000000000;
            Radix22ButterflyG2_btf2_re_reg <= 19'sb0000000000000000000;
            Radix22ButterflyG2_btf2_im_reg <= 19'sb0000000000000000000;
            Radix22ButterflyG2_din_re_dly <= 18'sb000000000000000000;
            Radix22ButterflyG2_din_im_dly <= 18'sb000000000000000000;
            Radix22ButterflyG2_din_vld_dly <= 1'b0;
            Radix22ButterflyG2_x_re_dly <= 18'sb000000000000000000;
            Radix22ButterflyG2_x_im_dly <= 18'sb000000000000000000;
            Radix22ButterflyG2_x_vld_dly <= 1'b0;
            Radix22ButterflyG2_dinXTwdl_re_dly1 <= 18'sb000000000000000000;
            Radix22ButterflyG2_dinXTwdl_im_dly1 <= 18'sb000000000000000000;
            Radix22ButterflyG2_dinXTwdl_re_dly2 <= 18'sb000000000000000000;
            Radix22ButterflyG2_dinXTwdl_im_dly2 <= 18'sb000000000000000000;
            Radix22ButterflyG2_multiply_J_dly1 <= 1'b0;
          end
          else begin
            Radix22ButterflyG2_procEnb_dly <= Radix22ButterflyG2_procEnb_dly_next;
            Radix22ButterflyG2_procEnb_dly1 <= Radix22ButterflyG2_procEnb_dly1_next;
            Radix22ButterflyG2_procEnb_dly2 <= Radix22ButterflyG2_procEnb_dly2_next;
            Radix22ButterflyG2_btf1_re_reg <= Radix22ButterflyG2_btf1_re_reg_next;
            Radix22ButterflyG2_btf1_im_reg <= Radix22ButterflyG2_btf1_im_reg_next;
            Radix22ButterflyG2_btf2_re_reg <= Radix22ButterflyG2_btf2_re_reg_next;
            Radix22ButterflyG2_btf2_im_reg <= Radix22ButterflyG2_btf2_im_reg_next;
            Radix22ButterflyG2_din_re_dly <= Radix22ButterflyG2_din_re_dly_next;
            Radix22ButterflyG2_din_im_dly <= Radix22ButterflyG2_din_im_dly_next;
            Radix22ButterflyG2_din_vld_dly <= Radix22ButterflyG2_din_vld_dly_next;
            Radix22ButterflyG2_x_re_dly <= Radix22ButterflyG2_x_re_dly_next;
            Radix22ButterflyG2_x_im_dly <= Radix22ButterflyG2_x_im_dly_next;
            Radix22ButterflyG2_x_vld_dly <= Radix22ButterflyG2_x_vld_dly_next;
            Radix22ButterflyG2_dinXTwdl_re_dly1 <= Radix22ButterflyG2_dinXTwdl_re_dly1_1;
            Radix22ButterflyG2_dinXTwdl_im_dly1 <= Radix22ButterflyG2_dinXTwdl_im_dly1_1;
            Radix22ButterflyG2_dinXTwdl_re_dly2 <= Radix22ButterflyG2_dinXTwdl_re_dly2_1;
            Radix22ButterflyG2_dinXTwdl_im_dly2 <= Radix22ButterflyG2_dinXTwdl_im_dly2_1;
            Radix22ButterflyG2_multiply_J_dly1 <= Radix22ButterflyG2_multiply_J_dly1_n;
          end
        end
      end
    end

  always @(Radix22ButterflyG2_btf1_im_reg, Radix22ButterflyG2_btf1_re_reg,
       Radix22ButterflyG2_btf2_im_reg, Radix22ButterflyG2_btf2_re_reg,
       Radix22ButterflyG2_dinXTwdl_im_dly1, Radix22ButterflyG2_dinXTwdl_im_dly2,
       Radix22ButterflyG2_dinXTwdl_re_dly1, Radix22ButterflyG2_dinXTwdl_re_dly2,
       Radix22ButterflyG2_din_im_dly, Radix22ButterflyG2_din_re_dly,
       Radix22ButterflyG2_din_vld_dly, Radix22ButterflyG2_multiply_J_dly1,
       Radix22ButterflyG2_procEnb_dly, Radix22ButterflyG2_procEnb_dly1,
       Radix22ButterflyG2_procEnb_dly2, Radix22ButterflyG2_x_im_dly,
       Radix22ButterflyG2_x_re_dly, Radix22ButterflyG2_x_vld_dly, btfin_vld,
       dinVld, din_im, din_re, multiply_6_J, x_im_dly, x_re_dly, x_vld_dly) begin
    Radix22ButterflyG2_add_cast_1 = 19'sb0000000000000000000;
    Radix22ButterflyG2_add_cast_2 = 19'sb0000000000000000000;
    Radix22ButterflyG2_sub_cast_1 = 19'sb0000000000000000000;
    Radix22ButterflyG2_sub_cast_2 = 19'sb0000000000000000000;
    Radix22ButterflyG2_add_cast_5 = 19'sb0000000000000000000;
    Radix22ButterflyG2_add_cast_6 = 19'sb0000000000000000000;
    Radix22ButterflyG2_sub_cast_5 = 19'sb0000000000000000000;
    Radix22ButterflyG2_sub_cast_6 = 19'sb0000000000000000000;
    Radix22ButterflyG2_add_cast = 19'sb0000000000000000000;
    Radix22ButterflyG2_add_cast_0 = 19'sb0000000000000000000;
    Radix22ButterflyG2_sub_cast = 19'sb0000000000000000000;
    Radix22ButterflyG2_sub_cast_0 = 19'sb0000000000000000000;
    Radix22ButterflyG2_add_cast_3 = 19'sb0000000000000000000;
    Radix22ButterflyG2_add_cast_4 = 19'sb0000000000000000000;
    Radix22ButterflyG2_sub_cast_3 = 19'sb0000000000000000000;
    Radix22ButterflyG2_sub_cast_4 = 19'sb0000000000000000000;
    Radix22ButterflyG2_x_re_dly_next = x_re_dly;
    Radix22ButterflyG2_x_im_dly_next = x_im_dly;
    Radix22ButterflyG2_x_vld_dly_next = x_vld_dly;
    Radix22ButterflyG2_din_re_dly_next = din_re;
    Radix22ButterflyG2_din_im_dly_next = din_im;
    Radix22ButterflyG2_din_vld_dly_next = dinVld;
    Radix22ButterflyG2_procEnb_dly2_next = Radix22ButterflyG2_procEnb_dly1;
    Radix22ButterflyG2_procEnb_dly1_next = Radix22ButterflyG2_procEnb_dly;
    Radix22ButterflyG2_procEnb_dly_next = btfin_vld;
    if (Radix22ButterflyG2_multiply_J_dly1) begin
      Radix22ButterflyG2_add_cast_1 = {x_re_dly[17], x_re_dly};
      Radix22ButterflyG2_add_cast_2 = {Radix22ButterflyG2_dinXTwdl_im_dly2[17], 
        Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf1_re_reg_next = Radix22ButterflyG2_add_cast_1 + Radix22ButterflyG2_add_cast_2;
      Radix22ButterflyG2_sub_cast_1 = {x_re_dly[17], x_re_dly};
      Radix22ButterflyG2_sub_cast_2 = {Radix22ButterflyG2_dinXTwdl_im_dly2[17], 
        Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf2_re_reg_next = Radix22ButterflyG2_sub_cast_1 - Radix22ButterflyG2_sub_cast_2;
      Radix22ButterflyG2_add_cast_5 = {x_im_dly[17], x_im_dly};
      Radix22ButterflyG2_add_cast_6 = {Radix22ButterflyG2_dinXTwdl_re_dly2[17], 
        Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf2_im_reg_next = Radix22ButterflyG2_add_cast_5 + Radix22ButterflyG2_add_cast_6;
      Radix22ButterflyG2_sub_cast_5 = {x_im_dly[17], x_im_dly};
      Radix22ButterflyG2_sub_cast_6 = {Radix22ButterflyG2_dinXTwdl_re_dly2[17], 
        Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf1_im_reg_next = Radix22ButterflyG2_sub_cast_5 - Radix22ButterflyG2_sub_cast_6;
    end
    else begin
      Radix22ButterflyG2_add_cast = {x_re_dly[17], x_re_dly};
      Radix22ButterflyG2_add_cast_0 = {Radix22ButterflyG2_dinXTwdl_re_dly2[17], 
        Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf1_re_reg_next = Radix22ButterflyG2_add_cast + Radix22ButterflyG2_add_cast_0;
      Radix22ButterflyG2_sub_cast = {x_re_dly[17], x_re_dly};
      Radix22ButterflyG2_sub_cast_0 = {Radix22ButterflyG2_dinXTwdl_re_dly2[17], 
        Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf2_re_reg_next = Radix22ButterflyG2_sub_cast - Radix22ButterflyG2_sub_cast_0;
      Radix22ButterflyG2_add_cast_3 = {x_im_dly[17], x_im_dly};
      Radix22ButterflyG2_add_cast_4 = {Radix22ButterflyG2_dinXTwdl_im_dly2[17], 
        Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf1_im_reg_next = Radix22ButterflyG2_add_cast_3 + Radix22ButterflyG2_add_cast_4;
      Radix22ButterflyG2_sub_cast_3 = {x_im_dly[17], x_im_dly};
      Radix22ButterflyG2_sub_cast_4 = {Radix22ButterflyG2_dinXTwdl_im_dly2[17], 
        Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf2_im_reg_next = Radix22ButterflyG2_sub_cast_3 - Radix22ButterflyG2_sub_cast_4;
    end
    Radix22ButterflyG2_dinXTwdl_re_dly2_1 = Radix22ButterflyG2_dinXTwdl_re_dly1;
    Radix22ButterflyG2_dinXTwdl_im_dly2_1 = Radix22ButterflyG2_dinXTwdl_im_dly1;
    Radix22ButterflyG2_dinXTwdl_re_dly1_1 = din_re;
    Radix22ButterflyG2_dinXTwdl_im_dly1_1 = din_im;
    Radix22ButterflyG2_multiply_J_dly1_n = multiply_6_J;
    xf_re = Radix22ButterflyG2_x_re_dly;
    xf_im = Radix22ButterflyG2_x_im_dly;
    xf_vld = Radix22ButterflyG2_x_vld_dly;
    dinf_re = Radix22ButterflyG2_din_re_dly;
    dinf_im = Radix22ButterflyG2_din_im_dly;
    dinf_vld = Radix22ButterflyG2_din_vld_dly;
    btf1_re = Radix22ButterflyG2_btf1_re_reg[17:0];
    btf1_im = Radix22ButterflyG2_btf1_im_reg[17:0];
    btf2_re = Radix22ButterflyG2_btf2_re_reg[17:0];
    btf2_im = Radix22ButterflyG2_btf2_im_reg[17:0];
    btfout_vld = Radix22ButterflyG2_procEnb_dly2;
  end



  Subsystem_ip2_src_SDFCommuta_block4 SDFCOMMUTATOR_6_1 (.clk(clk),
                                                         .reset(reset),
                                                         .enb(enb),
                                                         .dout_5_1_vld(dout_5_1_vld),
                                                         .xf_re(xf_re),  // sfix18_En11
                                                         .xf_im(xf_im),  // sfix18_En11
                                                         .xf_vld(xf_vld),
                                                         .dinf_re(dinf_re),  // sfix18_En11
                                                         .dinf_im(dinf_im),  // sfix18_En11
                                                         .dinf_vld(dinf_vld),
                                                         .btf1_re(btf1_re),  // sfix18_En11
                                                         .btf1_im(btf1_im),  // sfix18_En11
                                                         .btf2_re(btf2_re),  // sfix18_En11
                                                         .btf2_im(btf2_im),  // sfix18_En11
                                                         .btfout_vld(btfout_vld),
                                                         .syncReset(syncReset),
                                                         .wrData_re(wrData_re),  // sfix18_En11
                                                         .wrData_im(wrData_im),  // sfix18_En11
                                                         .wrAddr(wrAddr),  // ufix5
                                                         .wrEnb(wrEnb),
                                                         .dout_6_1_re(dout_6_1_re),  // sfix18_En11
                                                         .dout_6_1_im(dout_6_1_im),  // sfix18_En11
                                                         .dout_6_1_vld(dout_6_1_vld)
                                                         );

  assign dinXTwdl_6_1_vld = btfin_vld;

endmodule  // Subsystem_ip2_src_RADIX22FFT_block9

