// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdl_model_fixed\Subsystem_ip2_src_Detect_Inc.v
// Created: 2024-12-21 14:39:09
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_ip2_src_Detect_Inc
// Source Path: hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/Detect Increase
// Hierarchy Level: 2
// Model version: 1.110
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_ip2_src_Detect_Inc
          (clk,
           reset,
           enb,
           U_U,
           Y_Y);


  input   clk;
  input   reset;
  input   enb;
  input   U_U;
  output  Y_Y;


  reg  U_k_1;
  wire FixPt_Relational_Operator_out1;

  // Edge
  // U(k)


  // 
  // Store in Global RAM
  always @(posedge clk)
    begin : Delay_Input1_process
      if (reset == 1'b1) begin
        U_k_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          U_k_1 <= U_U;
        end
      end
    end



  assign FixPt_Relational_Operator_out1 = U_U > U_k_1;



  assign Y_Y = FixPt_Relational_Operator_out1;

endmodule  // Subsystem_ip2_src_Detect_Inc

