// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdl_model_fixed\Subsystem_ip2_src_RADIX22FFT_block17.v
// Created: 2024-12-21 14:39:09
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_ip2_src_RADIX22FFT_block17
// Source Path: hdl_model_fixed/Subsystem1/Subsystem/FFT/RADIX22FFT_SDF2_10
// Hierarchy Level: 3
// Model version: 1.110
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_ip2_src_RADIX22FFT_block17
          (clk,
           reset,
           enb,
           dout_9_1_re,
           dout_9_1_im,
           dout_9_1_vld,
           rd_10_Addr,
           rd_10_Enb,
           proc_10_enb,
           multiply_10_J,
           syncReset,
           dout_10_1_re,
           dout_10_1_im,
           dout_10_1_vld,
           dinXTwdl_10_1_vld);


  input   clk;
  input   reset;
  input   enb;
  input   signed [20:0] dout_9_1_re;  // sfix21_En11
  input   signed [20:0] dout_9_1_im;  // sfix21_En11
  input   dout_9_1_vld;
  input   rd_10_Addr;  // ufix1
  input   rd_10_Enb;
  input   proc_10_enb;
  input   multiply_10_J;
  input   syncReset;
  output  signed [21:0] dout_10_1_re;  // sfix22_En11
  output  signed [21:0] dout_10_1_im;  // sfix22_En11
  output  dout_10_1_vld;
  output  dinXTwdl_10_1_vld;


  wire signed [21:0] din_re;  // sfix22_En11
  wire signed [21:0] din_im;  // sfix22_En11
  wire saveEnb;
  wire dinVld;
  reg signed [21:0] din_re_dly1;  // sfix22_En11
  reg signed [21:0] btfin_re;  // sfix22_En11
  reg signed [21:0] din_im_dly1;  // sfix22_En11
  reg signed [21:0] btfin_im;  // sfix22_En11
  wire mulIn_vld;
  reg  procEnb_dly1;
  reg  btfin_vld;
  reg  x_vld;
  reg  x_vld_dly;
  reg signed [21:0] x_im;  // sfix22_En11
  reg signed [21:0] x_im_dly;  // sfix22_En11
  wire signed [21:0] wrData_re;  // sfix22_En11
  wire signed [21:0] wrData_im;  // sfix22_En11
  wire wrAddr;  // ufix1
  wire wrEnb;
  reg signed [21:0] twoLocationReg_0_MEM_re_0;  // sfix22
  reg signed [21:0] twoLocationReg_0_MEM_im_0;  // sfix22
  reg signed [21:0] twoLocationReg_0_MEM_re_1;  // sfix22
  reg signed [21:0] twoLocationReg_0_MEM_im_1;  // sfix22
  reg signed [21:0] twoLocationReg_0_dout_re_reg;  // sfix22
  reg signed [21:0] twoLocationReg_0_dout_im_reg;  // sfix22
  reg signed [21:0] twoLocationReg_0_MEM_re_0_next;  // sfix22_En11
  reg signed [21:0] twoLocationReg_0_MEM_im_0_next;  // sfix22_En11
  reg signed [21:0] twoLocationReg_0_MEM_re_1_next;  // sfix22_En11
  reg signed [21:0] twoLocationReg_0_MEM_im_1_next;  // sfix22_En11
  reg signed [21:0] twoLocationReg_0_dout_re_reg_next;  // sfix22_En11
  reg signed [21:0] twoLocationReg_0_dout_im_reg_next;  // sfix22_En11
  reg signed [21:0] x_re;  // sfix22_En11
  reg signed [21:0] x_re_dly;  // sfix22_En11
  reg  Radix22ButterflyG2_procEnb_dly;
  reg  Radix22ButterflyG2_procEnb_dly1;
  reg  Radix22ButterflyG2_procEnb_dly2;
  reg signed [22:0] Radix22ButterflyG2_btf1_re_reg;  // sfix23
  reg signed [22:0] Radix22ButterflyG2_btf1_im_reg;  // sfix23
  reg signed [22:0] Radix22ButterflyG2_btf2_re_reg;  // sfix23
  reg signed [22:0] Radix22ButterflyG2_btf2_im_reg;  // sfix23
  reg signed [21:0] Radix22ButterflyG2_din_re_dly;  // sfix22
  reg signed [21:0] Radix22ButterflyG2_din_im_dly;  // sfix22
  reg  Radix22ButterflyG2_din_vld_dly;
  reg signed [21:0] Radix22ButterflyG2_x_re_dly;  // sfix22
  reg signed [21:0] Radix22ButterflyG2_x_im_dly;  // sfix22
  reg  Radix22ButterflyG2_x_vld_dly;
  reg signed [21:0] Radix22ButterflyG2_dinXTwdl_re_dly1;  // sfix22
  reg signed [21:0] Radix22ButterflyG2_dinXTwdl_im_dly1;  // sfix22
  reg signed [21:0] Radix22ButterflyG2_dinXTwdl_re_dly2;  // sfix22
  reg signed [21:0] Radix22ButterflyG2_dinXTwdl_im_dly2;  // sfix22
  reg  Radix22ButterflyG2_multiply_J_dly1;
  reg  Radix22ButterflyG2_procEnb_dly_next;
  reg  Radix22ButterflyG2_procEnb_dly1_next;
  reg  Radix22ButterflyG2_procEnb_dly2_next;
  reg signed [22:0] Radix22ButterflyG2_btf1_re_reg_next;  // sfix23_En11
  reg signed [22:0] Radix22ButterflyG2_btf1_im_reg_next;  // sfix23_En11
  reg signed [22:0] Radix22ButterflyG2_btf2_re_reg_next;  // sfix23_En11
  reg signed [22:0] Radix22ButterflyG2_btf2_im_reg_next;  // sfix23_En11
  reg signed [21:0] Radix22ButterflyG2_din_re_dly_next;  // sfix22_En11
  reg signed [21:0] Radix22ButterflyG2_din_im_dly_next;  // sfix22_En11
  reg  Radix22ButterflyG2_din_vld_dly_next;
  reg signed [21:0] Radix22ButterflyG2_x_re_dly_next;  // sfix22_En11
  reg signed [21:0] Radix22ButterflyG2_x_im_dly_next;  // sfix22_En11
  reg  Radix22ButterflyG2_x_vld_dly_next;
  reg signed [21:0] Radix22ButterflyG2_dinXTwdl_re_dly1_1;  // sfix22_En11
  reg signed [21:0] Radix22ButterflyG2_dinXTwdl_im_dly1_1;  // sfix22_En11
  reg signed [21:0] Radix22ButterflyG2_dinXTwdl_re_dly2_1;  // sfix22_En11
  reg signed [21:0] Radix22ButterflyG2_dinXTwdl_im_dly2_1;  // sfix22_En11
  reg  Radix22ButterflyG2_multiply_J_dly1_n;
  reg signed [21:0] xf_re;  // sfix22_En11
  reg signed [21:0] xf_im;  // sfix22_En11
  reg  xf_vld;
  reg signed [21:0] dinf_re;  // sfix22_En11
  reg signed [21:0] dinf_im;  // sfix22_En11
  reg  dinf_vld;
  reg signed [21:0] btf1_re;  // sfix22_En11
  reg signed [21:0] btf1_im;  // sfix22_En11
  reg signed [21:0] btf2_re;  // sfix22_En11
  reg signed [21:0] btf2_im;  // sfix22_En11
  reg  btfout_vld;
  reg signed [22:0] Radix22ButterflyG2_add_cast;  // sfix23_En11
  reg signed [22:0] Radix22ButterflyG2_add_cast_0;  // sfix23_En11
  reg signed [22:0] Radix22ButterflyG2_add_cast_1;  // sfix23_En11
  reg signed [22:0] Radix22ButterflyG2_add_cast_2;  // sfix23_En11
  reg signed [22:0] Radix22ButterflyG2_sub_cast;  // sfix23_En11
  reg signed [22:0] Radix22ButterflyG2_sub_cast_0;  // sfix23_En11
  reg signed [22:0] Radix22ButterflyG2_sub_cast_1;  // sfix23_En11
  reg signed [22:0] Radix22ButterflyG2_sub_cast_2;  // sfix23_En11
  reg signed [22:0] Radix22ButterflyG2_add_cast_3;  // sfix23_En11
  reg signed [22:0] Radix22ButterflyG2_add_cast_4;  // sfix23_En11
  reg signed [22:0] Radix22ButterflyG2_add_cast_5;  // sfix23_En11
  reg signed [22:0] Radix22ButterflyG2_add_cast_6;  // sfix23_En11
  reg signed [22:0] Radix22ButterflyG2_sub_cast_3;  // sfix23_En11
  reg signed [22:0] Radix22ButterflyG2_sub_cast_4;  // sfix23_En11
  reg signed [22:0] Radix22ButterflyG2_sub_cast_5;  // sfix23_En11
  reg signed [22:0] Radix22ButterflyG2_sub_cast_6;  // sfix23_En11


  assign din_re = {dout_9_1_re[20], dout_9_1_re};



  assign din_im = {dout_9_1_im[20], dout_9_1_im};



  assign saveEnb =  ~ proc_10_enb;



  assign dinVld = dout_9_1_vld & saveEnb;



  always @(posedge clk)
    begin : intdelay_process
      if (reset == 1'b1) begin
        din_re_dly1 <= 22'sb0000000000000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            din_re_dly1 <= 22'sb0000000000000000000000;
          end
          else begin
            din_re_dly1 <= din_re;
          end
        end
      end
    end



  always @(posedge clk)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        btfin_re <= 22'sb0000000000000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            btfin_re <= 22'sb0000000000000000000000;
          end
          else begin
            btfin_re <= din_re_dly1;
          end
        end
      end
    end



  always @(posedge clk)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        din_im_dly1 <= 22'sb0000000000000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            din_im_dly1 <= 22'sb0000000000000000000000;
          end
          else begin
            din_im_dly1 <= din_im;
          end
        end
      end
    end



  always @(posedge clk)
    begin : intdelay_3_process
      if (reset == 1'b1) begin
        btfin_im <= 22'sb0000000000000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            btfin_im <= 22'sb0000000000000000000000;
          end
          else begin
            btfin_im <= din_im_dly1;
          end
        end
      end
    end



  assign mulIn_vld = dout_9_1_vld & proc_10_enb;



  always @(posedge clk)
    begin : intdelay_4_process
      if (reset == 1'b1) begin
        procEnb_dly1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            procEnb_dly1 <= 1'b0;
          end
          else begin
            procEnb_dly1 <= mulIn_vld;
          end
        end
      end
    end



  always @(posedge clk)
    begin : intdelay_5_process
      if (reset == 1'b1) begin
        btfin_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            btfin_vld <= 1'b0;
          end
          else begin
            btfin_vld <= procEnb_dly1;
          end
        end
      end
    end



  always @(posedge clk)
    begin : intdelay_6_process
      if (reset == 1'b1) begin
        x_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            x_vld <= 1'b0;
          end
          else begin
            x_vld <= rd_10_Enb;
          end
        end
      end
    end



  always @(posedge clk)
    begin : intdelay_7_process
      if (reset == 1'b1) begin
        x_vld_dly <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            x_vld_dly <= 1'b0;
          end
          else begin
            x_vld_dly <= x_vld;
          end
        end
      end
    end



  always @(posedge clk)
    begin : intdelay_8_process
      if (reset == 1'b1) begin
        x_im_dly <= 22'sb0000000000000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            x_im_dly <= 22'sb0000000000000000000000;
          end
          else begin
            x_im_dly <= x_im;
          end
        end
      end
    end



  // twoLocationReg_0
  always @(posedge clk)
    begin : twoLocationReg_0_process
      if (reset == 1'b1) begin
        twoLocationReg_0_MEM_re_0 <= 22'sb0000000000000000000000;
        twoLocationReg_0_MEM_im_0 <= 22'sb0000000000000000000000;
        twoLocationReg_0_MEM_re_1 <= 22'sb0000000000000000000000;
        twoLocationReg_0_MEM_im_1 <= 22'sb0000000000000000000000;
        twoLocationReg_0_dout_re_reg <= 22'sb0000000000000000000000;
        twoLocationReg_0_dout_im_reg <= 22'sb0000000000000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            twoLocationReg_0_MEM_re_0 <= 22'sb0000000000000000000000;
            twoLocationReg_0_MEM_im_0 <= 22'sb0000000000000000000000;
            twoLocationReg_0_MEM_re_1 <= 22'sb0000000000000000000000;
            twoLocationReg_0_MEM_im_1 <= 22'sb0000000000000000000000;
            twoLocationReg_0_dout_re_reg <= 22'sb0000000000000000000000;
            twoLocationReg_0_dout_im_reg <= 22'sb0000000000000000000000;
          end
          else begin
            twoLocationReg_0_MEM_re_0 <= twoLocationReg_0_MEM_re_0_next;
            twoLocationReg_0_MEM_im_0 <= twoLocationReg_0_MEM_im_0_next;
            twoLocationReg_0_MEM_re_1 <= twoLocationReg_0_MEM_re_1_next;
            twoLocationReg_0_MEM_im_1 <= twoLocationReg_0_MEM_im_1_next;
            twoLocationReg_0_dout_re_reg <= twoLocationReg_0_dout_re_reg_next;
            twoLocationReg_0_dout_im_reg <= twoLocationReg_0_dout_im_reg_next;
          end
        end
      end
    end

  always @(rd_10_Addr, twoLocationReg_0_MEM_im_0, twoLocationReg_0_MEM_im_1,
       twoLocationReg_0_MEM_re_0, twoLocationReg_0_MEM_re_1,
       twoLocationReg_0_dout_im_reg, twoLocationReg_0_dout_re_reg, wrAddr,
       wrData_im, wrData_re, wrEnb) begin
    twoLocationReg_0_MEM_re_0_next = twoLocationReg_0_MEM_re_0;
    twoLocationReg_0_MEM_im_0_next = twoLocationReg_0_MEM_im_0;
    twoLocationReg_0_MEM_re_1_next = twoLocationReg_0_MEM_re_1;
    twoLocationReg_0_MEM_im_1_next = twoLocationReg_0_MEM_im_1;
    if (rd_10_Addr == 1'b1) begin
      twoLocationReg_0_dout_re_reg_next = twoLocationReg_0_MEM_re_1;
      twoLocationReg_0_dout_im_reg_next = twoLocationReg_0_MEM_im_1;
    end
    else begin
      twoLocationReg_0_dout_re_reg_next = twoLocationReg_0_MEM_re_0;
      twoLocationReg_0_dout_im_reg_next = twoLocationReg_0_MEM_im_0;
    end
    if (wrEnb) begin
      if (wrAddr == 1'b1) begin
        twoLocationReg_0_MEM_re_1_next = wrData_re;
        twoLocationReg_0_MEM_im_1_next = wrData_im;
      end
      else begin
        twoLocationReg_0_MEM_re_0_next = wrData_re;
        twoLocationReg_0_MEM_im_0_next = wrData_im;
      end
    end
    x_re = twoLocationReg_0_dout_re_reg;
    x_im = twoLocationReg_0_dout_im_reg;
  end



  always @(posedge clk)
    begin : intdelay_9_process
      if (reset == 1'b1) begin
        x_re_dly <= 22'sb0000000000000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            x_re_dly <= 22'sb0000000000000000000000;
          end
          else begin
            x_re_dly <= x_re;
          end
        end
      end
    end



  // Radix22ButterflyG2
  always @(posedge clk)
    begin : Radix22ButterflyG2_process
      if (reset == 1'b1) begin
        Radix22ButterflyG2_procEnb_dly <= 1'b0;
        Radix22ButterflyG2_procEnb_dly1 <= 1'b0;
        Radix22ButterflyG2_procEnb_dly2 <= 1'b0;
        Radix22ButterflyG2_btf1_re_reg <= 23'sb00000000000000000000000;
        Radix22ButterflyG2_btf1_im_reg <= 23'sb00000000000000000000000;
        Radix22ButterflyG2_btf2_re_reg <= 23'sb00000000000000000000000;
        Radix22ButterflyG2_btf2_im_reg <= 23'sb00000000000000000000000;
        Radix22ButterflyG2_din_re_dly <= 22'sb0000000000000000000000;
        Radix22ButterflyG2_din_im_dly <= 22'sb0000000000000000000000;
        Radix22ButterflyG2_din_vld_dly <= 1'b0;
        Radix22ButterflyG2_x_re_dly <= 22'sb0000000000000000000000;
        Radix22ButterflyG2_x_im_dly <= 22'sb0000000000000000000000;
        Radix22ButterflyG2_x_vld_dly <= 1'b0;
        Radix22ButterflyG2_dinXTwdl_re_dly1 <= 22'sb0000000000000000000000;
        Radix22ButterflyG2_dinXTwdl_im_dly1 <= 22'sb0000000000000000000000;
        Radix22ButterflyG2_dinXTwdl_re_dly2 <= 22'sb0000000000000000000000;
        Radix22ButterflyG2_dinXTwdl_im_dly2 <= 22'sb0000000000000000000000;
        Radix22ButterflyG2_multiply_J_dly1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            Radix22ButterflyG2_procEnb_dly <= 1'b0;
            Radix22ButterflyG2_procEnb_dly1 <= 1'b0;
            Radix22ButterflyG2_procEnb_dly2 <= 1'b0;
            Radix22ButterflyG2_btf1_re_reg <= 23'sb00000000000000000000000;
            Radix22ButterflyG2_btf1_im_reg <= 23'sb00000000000000000000000;
            Radix22ButterflyG2_btf2_re_reg <= 23'sb00000000000000000000000;
            Radix22ButterflyG2_btf2_im_reg <= 23'sb00000000000000000000000;
            Radix22ButterflyG2_din_re_dly <= 22'sb0000000000000000000000;
            Radix22ButterflyG2_din_im_dly <= 22'sb0000000000000000000000;
            Radix22ButterflyG2_din_vld_dly <= 1'b0;
            Radix22ButterflyG2_x_re_dly <= 22'sb0000000000000000000000;
            Radix22ButterflyG2_x_im_dly <= 22'sb0000000000000000000000;
            Radix22ButterflyG2_x_vld_dly <= 1'b0;
            Radix22ButterflyG2_dinXTwdl_re_dly1 <= 22'sb0000000000000000000000;
            Radix22ButterflyG2_dinXTwdl_im_dly1 <= 22'sb0000000000000000000000;
            Radix22ButterflyG2_dinXTwdl_re_dly2 <= 22'sb0000000000000000000000;
            Radix22ButterflyG2_dinXTwdl_im_dly2 <= 22'sb0000000000000000000000;
            Radix22ButterflyG2_multiply_J_dly1 <= 1'b0;
          end
          else begin
            Radix22ButterflyG2_procEnb_dly <= Radix22ButterflyG2_procEnb_dly_next;
            Radix22ButterflyG2_procEnb_dly1 <= Radix22ButterflyG2_procEnb_dly1_next;
            Radix22ButterflyG2_procEnb_dly2 <= Radix22ButterflyG2_procEnb_dly2_next;
            Radix22ButterflyG2_btf1_re_reg <= Radix22ButterflyG2_btf1_re_reg_next;
            Radix22ButterflyG2_btf1_im_reg <= Radix22ButterflyG2_btf1_im_reg_next;
            Radix22ButterflyG2_btf2_re_reg <= Radix22ButterflyG2_btf2_re_reg_next;
            Radix22ButterflyG2_btf2_im_reg <= Radix22ButterflyG2_btf2_im_reg_next;
            Radix22ButterflyG2_din_re_dly <= Radix22ButterflyG2_din_re_dly_next;
            Radix22ButterflyG2_din_im_dly <= Radix22ButterflyG2_din_im_dly_next;
            Radix22ButterflyG2_din_vld_dly <= Radix22ButterflyG2_din_vld_dly_next;
            Radix22ButterflyG2_x_re_dly <= Radix22ButterflyG2_x_re_dly_next;
            Radix22ButterflyG2_x_im_dly <= Radix22ButterflyG2_x_im_dly_next;
            Radix22ButterflyG2_x_vld_dly <= Radix22ButterflyG2_x_vld_dly_next;
            Radix22ButterflyG2_dinXTwdl_re_dly1 <= Radix22ButterflyG2_dinXTwdl_re_dly1_1;
            Radix22ButterflyG2_dinXTwdl_im_dly1 <= Radix22ButterflyG2_dinXTwdl_im_dly1_1;
            Radix22ButterflyG2_dinXTwdl_re_dly2 <= Radix22ButterflyG2_dinXTwdl_re_dly2_1;
            Radix22ButterflyG2_dinXTwdl_im_dly2 <= Radix22ButterflyG2_dinXTwdl_im_dly2_1;
            Radix22ButterflyG2_multiply_J_dly1 <= Radix22ButterflyG2_multiply_J_dly1_n;
          end
        end
      end
    end

  always @(Radix22ButterflyG2_btf1_im_reg, Radix22ButterflyG2_btf1_re_reg,
       Radix22ButterflyG2_btf2_im_reg, Radix22ButterflyG2_btf2_re_reg,
       Radix22ButterflyG2_dinXTwdl_im_dly1, Radix22ButterflyG2_dinXTwdl_im_dly2,
       Radix22ButterflyG2_dinXTwdl_re_dly1, Radix22ButterflyG2_dinXTwdl_re_dly2,
       Radix22ButterflyG2_din_im_dly, Radix22ButterflyG2_din_re_dly,
       Radix22ButterflyG2_din_vld_dly, Radix22ButterflyG2_multiply_J_dly1,
       Radix22ButterflyG2_procEnb_dly, Radix22ButterflyG2_procEnb_dly1,
       Radix22ButterflyG2_procEnb_dly2, Radix22ButterflyG2_x_im_dly,
       Radix22ButterflyG2_x_re_dly, Radix22ButterflyG2_x_vld_dly, btfin_im,
       btfin_re, btfin_vld, dinVld, din_im, din_re, multiply_10_J, x_im_dly,
       x_re_dly, x_vld_dly) begin
    Radix22ButterflyG2_add_cast_1 = 23'sb00000000000000000000000;
    Radix22ButterflyG2_add_cast_2 = 23'sb00000000000000000000000;
    Radix22ButterflyG2_sub_cast_1 = 23'sb00000000000000000000000;
    Radix22ButterflyG2_sub_cast_2 = 23'sb00000000000000000000000;
    Radix22ButterflyG2_add_cast_5 = 23'sb00000000000000000000000;
    Radix22ButterflyG2_add_cast_6 = 23'sb00000000000000000000000;
    Radix22ButterflyG2_sub_cast_5 = 23'sb00000000000000000000000;
    Radix22ButterflyG2_sub_cast_6 = 23'sb00000000000000000000000;
    Radix22ButterflyG2_add_cast = 23'sb00000000000000000000000;
    Radix22ButterflyG2_add_cast_0 = 23'sb00000000000000000000000;
    Radix22ButterflyG2_sub_cast = 23'sb00000000000000000000000;
    Radix22ButterflyG2_sub_cast_0 = 23'sb00000000000000000000000;
    Radix22ButterflyG2_add_cast_3 = 23'sb00000000000000000000000;
    Radix22ButterflyG2_add_cast_4 = 23'sb00000000000000000000000;
    Radix22ButterflyG2_sub_cast_3 = 23'sb00000000000000000000000;
    Radix22ButterflyG2_sub_cast_4 = 23'sb00000000000000000000000;
    Radix22ButterflyG2_x_re_dly_next = x_re_dly;
    Radix22ButterflyG2_x_im_dly_next = x_im_dly;
    Radix22ButterflyG2_x_vld_dly_next = x_vld_dly;
    Radix22ButterflyG2_din_re_dly_next = din_re;
    Radix22ButterflyG2_din_im_dly_next = din_im;
    Radix22ButterflyG2_din_vld_dly_next = dinVld;
    Radix22ButterflyG2_procEnb_dly2_next = Radix22ButterflyG2_procEnb_dly1;
    Radix22ButterflyG2_procEnb_dly1_next = Radix22ButterflyG2_procEnb_dly;
    Radix22ButterflyG2_procEnb_dly_next = btfin_vld;
    if (Radix22ButterflyG2_multiply_J_dly1) begin
      Radix22ButterflyG2_add_cast_1 = {x_re_dly[21], x_re_dly};
      Radix22ButterflyG2_add_cast_2 = {Radix22ButterflyG2_dinXTwdl_im_dly2[21], 
        Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf1_re_reg_next = Radix22ButterflyG2_add_cast_1 + Radix22ButterflyG2_add_cast_2;
      Radix22ButterflyG2_sub_cast_1 = {x_re_dly[21], x_re_dly};
      Radix22ButterflyG2_sub_cast_2 = {Radix22ButterflyG2_dinXTwdl_im_dly2[21], 
        Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf2_re_reg_next = Radix22ButterflyG2_sub_cast_1 - Radix22ButterflyG2_sub_cast_2;
      Radix22ButterflyG2_add_cast_5 = {x_im_dly[21], x_im_dly};
      Radix22ButterflyG2_add_cast_6 = {Radix22ButterflyG2_dinXTwdl_re_dly2[21], 
        Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf2_im_reg_next = Radix22ButterflyG2_add_cast_5 + Radix22ButterflyG2_add_cast_6;
      Radix22ButterflyG2_sub_cast_5 = {x_im_dly[21], x_im_dly};
      Radix22ButterflyG2_sub_cast_6 = {Radix22ButterflyG2_dinXTwdl_re_dly2[21], 
        Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf1_im_reg_next = Radix22ButterflyG2_sub_cast_5 - Radix22ButterflyG2_sub_cast_6;
    end
    else begin
      Radix22ButterflyG2_add_cast = {x_re_dly[21], x_re_dly};
      Radix22ButterflyG2_add_cast_0 = {Radix22ButterflyG2_dinXTwdl_re_dly2[21], 
        Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf1_re_reg_next = Radix22ButterflyG2_add_cast + Radix22ButterflyG2_add_cast_0;
      Radix22ButterflyG2_sub_cast = {x_re_dly[21], x_re_dly};
      Radix22ButterflyG2_sub_cast_0 = {Radix22ButterflyG2_dinXTwdl_re_dly2[21], 
        Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf2_re_reg_next = Radix22ButterflyG2_sub_cast - Radix22ButterflyG2_sub_cast_0;
      Radix22ButterflyG2_add_cast_3 = {x_im_dly[21], x_im_dly};
      Radix22ButterflyG2_add_cast_4 = {Radix22ButterflyG2_dinXTwdl_im_dly2[21], 
        Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf1_im_reg_next = Radix22ButterflyG2_add_cast_3 + Radix22ButterflyG2_add_cast_4;
      Radix22ButterflyG2_sub_cast_3 = {x_im_dly[21], x_im_dly};
      Radix22ButterflyG2_sub_cast_4 = {Radix22ButterflyG2_dinXTwdl_im_dly2[21], 
        Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf2_im_reg_next = Radix22ButterflyG2_sub_cast_3 - Radix22ButterflyG2_sub_cast_4;
    end
    Radix22ButterflyG2_dinXTwdl_re_dly2_1 = Radix22ButterflyG2_dinXTwdl_re_dly1;
    Radix22ButterflyG2_dinXTwdl_im_dly2_1 = Radix22ButterflyG2_dinXTwdl_im_dly1;
    Radix22ButterflyG2_dinXTwdl_re_dly1_1 = btfin_re;
    Radix22ButterflyG2_dinXTwdl_im_dly1_1 = btfin_im;
    Radix22ButterflyG2_multiply_J_dly1_n = multiply_10_J;
    xf_re = Radix22ButterflyG2_x_re_dly;
    xf_im = Radix22ButterflyG2_x_im_dly;
    xf_vld = Radix22ButterflyG2_x_vld_dly;
    dinf_re = Radix22ButterflyG2_din_re_dly;
    dinf_im = Radix22ButterflyG2_din_im_dly;
    dinf_vld = Radix22ButterflyG2_din_vld_dly;
    btf1_re = Radix22ButterflyG2_btf1_re_reg[21:0];
    btf1_im = Radix22ButterflyG2_btf1_im_reg[21:0];
    btf2_re = Radix22ButterflyG2_btf2_re_reg[21:0];
    btf2_im = Radix22ButterflyG2_btf2_im_reg[21:0];
    btfout_vld = Radix22ButterflyG2_procEnb_dly2;
  end



  Subsystem_ip2_src_SDFCommuta_block8 SDFCOMMUTATOR_10_1 (.clk(clk),
                                                          .reset(reset),
                                                          .enb(enb),
                                                          .dout_9_1_vld(dout_9_1_vld),
                                                          .xf_re(xf_re),  // sfix22_En11
                                                          .xf_im(xf_im),  // sfix22_En11
                                                          .xf_vld(xf_vld),
                                                          .dinf_re(dinf_re),  // sfix22_En11
                                                          .dinf_im(dinf_im),  // sfix22_En11
                                                          .dinf_vld(dinf_vld),
                                                          .btf1_re(btf1_re),  // sfix22_En11
                                                          .btf1_im(btf1_im),  // sfix22_En11
                                                          .btf2_re(btf2_re),  // sfix22_En11
                                                          .btf2_im(btf2_im),  // sfix22_En11
                                                          .btfout_vld(btfout_vld),
                                                          .syncReset(syncReset),
                                                          .wrData_re(wrData_re),  // sfix22_En11
                                                          .wrData_im(wrData_im),  // sfix22_En11
                                                          .wrAddr(wrAddr),  // ufix1
                                                          .wrEnb(wrEnb),
                                                          .dout_10_1_re(dout_10_1_re),  // sfix22_En11
                                                          .dout_10_1_im(dout_10_1_im),  // sfix22_En11
                                                          .dout_10_1_vld(dout_10_1_vld)
                                                          );

  assign dinXTwdl_10_1_vld = btfin_vld;

endmodule  // Subsystem_ip2_src_RADIX22FFT_block17

