// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdl_model_fixed\Subsystem_ip2_src_Sample_and_block.v
// Created: 2024-12-20 15:38:10
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_ip2_src_Sample_and_block
// Source Path: hdl_model_fixed/Subsystem1/Subsystem Reference/Sample and Hold
// Hierarchy Level: 2
// Model version: 1.105
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_ip2_src_Sample_and_block
          (clk,
           reset,
           enb,
           In_rsvd,
           Trigger_rsvd,
           alpha);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] In_rsvd;  // sfix16_En14
  input   Trigger_rsvd;
  output  signed [15:0] alpha;  // sfix16_En14


  wire enb_gated;
  reg  Trigger_delayed;
  wire Trigger_emulated;
  wire signed [15:0] In_bypass;  // sfix16_En14
  reg signed [15:0] In_last_value;  // sfix16_En14


  always @(posedge clk)
    begin : Trigger_delay
      if (reset) begin
        Trigger_delayed <= 1'b1;
      end
      else begin
        if (enb) begin
          Trigger_delayed <= Trigger_rsvd;
        end
      end
    end

  assign Trigger_emulated = !Trigger_delayed && Trigger_rsvd;

  assign enb_gated = Trigger_emulated && enb;

  always @(posedge clk)
    begin : alpha_bypass_process
      if (reset == 1'b1) begin
        In_last_value <= 16'sb0000000000000000;
      end
      else begin
        if (enb_gated) begin
          In_last_value <= In_bypass;
        end
      end
    end



  assign In_bypass = (Trigger_emulated == 1'b0 ? In_last_value :
              In_rsvd);



  assign alpha = In_bypass;

endmodule  // Subsystem_ip2_src_Sample_and_block

