-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\hdl_model_fixed\Cast_to_Union_of_Types_block.vhd
-- Created: 2024-12-15 20:50:14
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Cast_to_Union_of_Types_block
-- Source Path: hdl_model_fixed/Subsystem1/Subsystem Reference/CORDIC Square Root HDL Optimized/Cast to Union of 
-- Type
-- Hierarchy Level: 3
-- Model version: 1.30
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Cast_to_Union_of_Types_block IS
  PORT( Xref                              :   IN    std_logic_vector(21 DOWNTO 0);  -- sfix22_En20
        Cin                               :   IN    std_logic_vector(21 DOWNTO 0);  -- sfix22_En20
        Cout                              :   OUT   std_logic_vector(21 DOWNTO 0)  -- sfix22_En20
        );
END Cast_to_Union_of_Types_block;


ARCHITECTURE rtl OF Cast_to_Union_of_Types_block IS

  -- Signals
  SIGNAL Xref_signed                      : signed(21 DOWNTO 0);  -- sfix22_En20
  SIGNAL Cin_signed                       : signed(21 DOWNTO 0);  -- sfix22_En20
  SIGNAL Cout_tmp                         : signed(21 DOWNTO 0);  -- sfix22_En20

BEGIN
  Xref_signed <= signed(Xref);

  Cin_signed <= signed(Cin);

  --castToUnionType Cast second input to union of the two types
  Cout_tmp <= Cin_signed;

  Cout <= std_logic_vector(Cout_tmp);

END rtl;

