SLStudio.Utils.RemoveHighlighting(get_param('hdl_model_fixed', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_hdl_model_fixed', 'handle'));
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference', 1, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference', 1, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Serializer1D', 1, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Serializer1D', 1, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/Delay', 1, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/Delay', 1, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/Deserializer1D', 1, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/Deserializer1D', 1, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/CORDIC Square Root HDL Optimized', 1, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/CORDIC Square Root HDL Optimized', 1, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Multiply-Accumulate', 1, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Multiply-Accumulate', 1, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Multiply-Accumulate', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Multiply-Accumulate', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex/CORDIC Square Root HDL Optimized1', 1, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex/CORDIC Square Root HDL Optimized1', 1, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/myRMS/CORDIC Square Root HDL Optimized', 1, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/myRMS/CORDIC Square Root HDL Optimized', 1, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/myRMS/Multiply-Accumulate', 1, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/myRMS/Multiply-Accumulate', 1, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/myRMS/Multiply-Accumulate', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/myRMS/Multiply-Accumulate', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex/CORDIC Square Root HDL Optimized1/Synchronous Subsystem/cordicSquareRootHDL/embmathops_c2_srwrzER3uCGRdPfDbow0ID_cordicSquareRootHDL_controlled/embmathops_c2_srwrzER3uCGRdPfDbow0ID_cordicSquareRootHDL', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex/CORDIC Square Root HDL Optimized1/Synchronous Subsystem/cordicSquareRootHDL', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/CORDIC Square Root HDL Optimized/Synchronous Subsystem/cordicSquareRootHDL/embmathops_c2_skVmLPFzLIK224pVNfQB1qF_cordicSquareRootHDL_controlled/embmathops_c2_skVmLPFzLIK224pVNfQB1qF_cordicSquareRootHDL', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/CORDIC Square Root HDL Optimized/Synchronous Subsystem/cordicSquareRootHDL', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1/Normalize numerator/positiveRealNormalizer/embreciprocals_c3_positiveRealNormalizer_controlled/embreciprocals_c3_positiveRealNormalizer', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Normalize numerator/positiveRealNormalizer', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1/Normalize denominator/positiveRealNormalizer/embreciprocals_c3_positiveRealNormalizer_controlled/embreciprocals_c3_positiveRealNormalizer', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Normalize denominator/positiveRealNormalizer', 0, 1, '');
