SLStudio.Utils.RemoveHighlighting(get_param('hdl_model_fixed', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_hdl_model_fixed', 'handle'));
annotate_port('gm_hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/myRMS', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/myRMS', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/S-R Flip-Flop', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/S-R Flip-Flop', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/S-R Flip-Flop', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/Sample and Hold1', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/Sample and Hold1', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/Sample and Hold2', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/Sample and Hold2', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/MATLAB Function', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/MATLAB Function', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/MATLAB Function1', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/MATLAB Function1', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/NOT', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/NOT', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/S-R Flip-Flop', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/S-R Flip-Flop', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/S-R Flip-Flop', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem/FFT', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem/FFT', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem/FFT', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem/FFT', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/CORDIC Square Root HDL Optimized', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/CORDIC Square Root HDL Optimized', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Sample and Hold', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Sample and Hold', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Sample and Hold1', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Sample and Hold1', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Sample and Hold2', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Sample and Hold2', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Select_Freq', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Select_Freq', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Multiply-Accumulate', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Multiply-Accumulate', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/S-R Flip-Flop', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/S-R Flip-Flop', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/S-R Flip-Flop', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex/CORDIC Square Root HDL Optimized1', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex/CORDIC Square Root HDL Optimized1', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex/CORDIC Square Root HDL Optimized1/Synchronous Subsystem', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex/CORDIC Square Root HDL Optimized1/Synchronous Subsystem', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex/CORDIC Square Root HDL Optimized1/Synchronous Subsystem/cordicSquareRootHDL', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex/CORDIC Square Root HDL Optimized1/Synchronous Subsystem/cordicSquareRootHDL', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/CORDIC Square Root HDL Optimized/Synchronous Subsystem', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/CORDIC Square Root HDL Optimized/Synchronous Subsystem', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/CORDIC Square Root HDL Optimized/Synchronous Subsystem/cordicSquareRootHDL', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/CORDIC Square Root HDL Optimized/Synchronous Subsystem/cordicSquareRootHDL', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/Verify divide sizes', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/Verify divide sizes', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1/Normalize numerator', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Normalize numerator', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1/Normalize denominator', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Normalize denominator', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1/Divide real numerator by denominator', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Divide real numerator by denominator', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1/Divide by zero handler', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Divide by zero handler', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1/Upcast Wordlength', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Upcast Wordlength', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1/MATLAB Function', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/MATLAB Function', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1/Normalize numerator/positiveRealNormalizer', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Normalize numerator/positiveRealNormalizer', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1/Normalize denominator/positiveRealNormalizer', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Normalize denominator/positiveRealNormalizer', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1/Divide real numerator by denominator/normalizedCORDICDivide', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Divide real numerator by denominator/normalizedCORDICDivide', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1/Divide by zero handler/Compare To Zero', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Divide by zero handler/Compare To Zero', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1/Divide by zero handler/Compare To Zero/Compare', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Divide by zero handler/Compare To Zero/Compare', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Select_Freq/NOT', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Select_Freq/NOT', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/myRMS/CORDIC Square Root HDL Optimized', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/myRMS/CORDIC Square Root HDL Optimized', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/myRMS/Sample and Hold', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/myRMS/Sample and Hold', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/myRMS/Multiply-Accumulate', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/myRMS/Multiply-Accumulate', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/myRMS/Multiply-Accumulate', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/myRMS/Multiply-Accumulate', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/myRMS/S-R Flip-Flop', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/myRMS/S-R Flip-Flop', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/myRMS/S-R Flip-Flop', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/myRMS/CORDIC Square Root HDL Optimized/Synchronous Subsystem', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/myRMS/CORDIC Square Root HDL Optimized/Synchronous Subsystem', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/myRMS/CORDIC Square Root HDL Optimized/Synchronous Subsystem/cordicSquareRootHDL', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/myRMS/CORDIC Square Root HDL Optimized/Synchronous Subsystem/cordicSquareRootHDL', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex/CORDIC Square Root HDL Optimized1/Synchronous Subsystem/cordicSquareRootHDL/embmathops_c2_srwrzER3uCGRdPfDbow0ID_cordicSquareRootHDL_controlled/embmathops_c2_srwrzER3uCGRdPfDbow0ID_cordicSquareRootHDL', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex/CORDIC Square Root HDL Optimized1/Synchronous Subsystem/cordicSquareRootHDL', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/CORDIC Square Root HDL Optimized/Synchronous Subsystem/cordicSquareRootHDL/embmathops_c2_skVmLPFzLIK224pVNfQB1qF_cordicSquareRootHDL_controlled/embmathops_c2_skVmLPFzLIK224pVNfQB1qF_cordicSquareRootHDL', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/CORDIC Square Root HDL Optimized/Synchronous Subsystem/cordicSquareRootHDL', 0, 1, '');
annotate_port('gm_hdl_model_fixed/Subsystem1/myRMS/CORDIC Square Root HDL Optimized/Synchronous Subsystem/cordicSquareRootHDL/embmathops_c2_svA684MOYugZkgHyA2vefIH_cordicSquareRootHDL_controlled/embmathops_c2_svA684MOYugZkgHyA2vefIH_cordicSquareRootHDL', 0, 1, '');
annotate_port('hdl_model_fixed/Subsystem1/myRMS/CORDIC Square Root HDL Optimized/Synchronous Subsystem/cordicSquareRootHDL', 0, 1, '');
