-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\hdl_model_fixed\Compare_To_Zero.vhd
-- Created: 2024-12-15 20:50:14
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Compare_To_Zero
-- Source Path: hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Divide 
-- by zero handler/Compare To Zer
-- Hierarchy Level: 5
-- Model version: 1.30
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Compare_To_Zero IS
  PORT( u                                 :   IN    std_logic_vector(21 DOWNTO 0);  -- sfix22_En20
        y                                 :   OUT   std_logic
        );
END Compare_To_Zero;


ARCHITECTURE rtl OF Compare_To_Zero IS

  -- Signals
  SIGNAL u_signed                         : signed(21 DOWNTO 0);  -- sfix22_En20
  SIGNAL Constant_out1                    : signed(21 DOWNTO 0);  -- sfix22_En20
  SIGNAL Compare_out1                     : std_logic;

BEGIN
  u_signed <= signed(u);

  Constant_out1 <= to_signed(16#000000#, 22);

  
  Compare_out1 <= '1' WHEN u_signed >= Constant_out1 ELSE
      '0';

  y <= Compare_out1;

END rtl;

