// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdl_model_fixed\CORDIC_Square_Root_HDL_Optim_block1.v
// Created: 2024-12-20 21:02:03
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: CORDIC_Square_Root_HDL_Optim_block1
// Source Path: hdl_model_fixed/Subsystem1/myRMS/CORDIC Square Root HDL Optimized
// Hierarchy Level: 2
// Model version: 1.105
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module CORDIC_Square_Root_HDL_Optim_block1
          (clk,
           reset,
           enb,
           u_u,
           validIn,
           restart,
           y_y,
           validOut);


  input   clk;
  input   reset;
  input   enb;
  input   [15:0] u_u;  // ufix16_En7
  input   validIn;
  input   restart;
  output  [15:0] y_y;  // ufix16_En7
  output  validOut;


  wire signed [15:0] Synchronous_Subsystem_out1;  // sfix16_En14
  wire signed [31:0] Synchronous_Subsystem_out2;  // int32
  wire Synchronous_Subsystem_out3;
  wire Synchronous_Subsystem_out4;
  wire signed [23:0] Cout;  // sfix24_En14
  wire signed [23:0] y_y_1;  // sfix24_En14
  wire [15:0] Data_Type_Conversion_out1;  // ufix16_En7


  Synchronous_Subsystem_block1 Synchronous_Subsystem_2 (.clk(clk),
                                                        .reset(reset),
                                                        .enb(enb),
                                                        .u_u(u_u),  // ufix16_En7
                                                        .validIn(validIn),
                                                        .restart(restart),
                                                        .dataOut(Synchronous_Subsystem_out1),  // sfix16_En14
                                                        .eOut(Synchronous_Subsystem_out2),  // int32
                                                        .isZero(Synchronous_Subsystem_out3),
                                                        .validOut(Synchronous_Subsystem_out4)
                                                        );

  Cast_to_Union_of_Types_block2 Cast_to_Union_of_Types_3 (.Xref(u_u),  // ufix16_En7
                                                          .Cin(Synchronous_Subsystem_out1),  // sfix16_En14
                                                          .Cout(Cout)  // sfix24_En14
                                                          );

  Bit_Shift_Arithmetic_block1 Bit_Shift_Arithmetic_2 (.u_u(Cout),  // sfix24_En14
                                                      .e_e(Synchronous_Subsystem_out2),  // int32
                                                      .isZero(Synchronous_Subsystem_out3),
                                                      .y_y(y_y_1)  // sfix24_En14
                                                      );

  assign Data_Type_Conversion_out1 = y_y_1[22:7] + y_y_1[6];



  assign y_y = Data_Type_Conversion_out1;

  assign validOut = Synchronous_Subsystem_out4;

endmodule  // CORDIC_Square_Root_HDL_Optim_block1

