-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\hdl_model_fixed\CORDIC_Square_Root_HDL_Optimized.vhd
-- Created: 2024-12-15 20:50:14
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: CORDIC_Square_Root_HDL_Optimized
-- Source Path: hdl_model_fixed/Subsystem1/Subsystem Reference/CORDIC Square Root HDL Optimized
-- Hierarchy Level: 2
-- Model version: 1.30
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY CORDIC_Square_Root_HDL_Optimized IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_25_0                        :   IN    std_logic;
        u                                 :   IN    std_logic_vector(21 DOWNTO 0);  -- sfix22_En20
        validIn                           :   IN    std_logic;
        restart                           :   IN    std_logic;
        y                                 :   OUT   std_logic_vector(21 DOWNTO 0);  -- sfix22_En20
        validOut                          :   OUT   std_logic
        );
END CORDIC_Square_Root_HDL_Optimized;


ARCHITECTURE rtl OF CORDIC_Square_Root_HDL_Optimized IS

  -- Component Declarations
  COMPONENT Synchronous_Subsystem_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_25_0                      :   IN    std_logic;
          u                               :   IN    std_logic_vector(21 DOWNTO 0);  -- sfix22_En20
          validIn                         :   IN    std_logic;
          restart                         :   IN    std_logic;
          dataOut                         :   OUT   std_logic_vector(21 DOWNTO 0);  -- sfix22_En20
          eOut                            :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
          isZero                          :   OUT   std_logic;
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT Cast_to_Union_of_Types_block
    PORT( Xref                            :   IN    std_logic_vector(21 DOWNTO 0);  -- sfix22_En20
          Cin                             :   IN    std_logic_vector(21 DOWNTO 0);  -- sfix22_En20
          Cout                            :   OUT   std_logic_vector(21 DOWNTO 0)  -- sfix22_En20
          );
  END COMPONENT;

  COMPONENT Bit_Shift_Arithmetic_block
    PORT( u                               :   IN    std_logic_vector(21 DOWNTO 0);  -- sfix22_En20
          e                               :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          isZero                          :   IN    std_logic;
          y                               :   OUT   std_logic_vector(21 DOWNTO 0)  -- sfix22_En20
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Synchronous_Subsystem_block
    USE ENTITY work.Synchronous_Subsystem_block(rtl);

  FOR ALL : Cast_to_Union_of_Types_block
    USE ENTITY work.Cast_to_Union_of_Types_block(rtl);

  FOR ALL : Bit_Shift_Arithmetic_block
    USE ENTITY work.Bit_Shift_Arithmetic_block(rtl);

  -- Signals
  SIGNAL Synchronous_Subsystem_out1       : std_logic_vector(21 DOWNTO 0);  -- ufix22
  SIGNAL Synchronous_Subsystem_out2       : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Synchronous_Subsystem_out3       : std_logic;
  SIGNAL Synchronous_Subsystem_out4       : std_logic;
  SIGNAL Cout                             : std_logic_vector(21 DOWNTO 0);  -- ufix22

BEGIN
  u_Synchronous_Subsystem : Synchronous_Subsystem_block
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_25_0 => enb_1_25_0,
              u => u,  -- sfix22_En20
              validIn => validIn,
              restart => restart,
              dataOut => Synchronous_Subsystem_out1,  -- sfix22_En20
              eOut => Synchronous_Subsystem_out2,  -- int32
              isZero => Synchronous_Subsystem_out3,
              validOut => Synchronous_Subsystem_out4
              );

  u_Cast_to_Union_of_Types : Cast_to_Union_of_Types_block
    PORT MAP( Xref => u,  -- sfix22_En20
              Cin => Synchronous_Subsystem_out1,  -- sfix22_En20
              Cout => Cout  -- sfix22_En20
              );

  u_Bit_Shift_Arithmetic : Bit_Shift_Arithmetic_block
    PORT MAP( u => Cout,  -- sfix22_En20
              e => Synchronous_Subsystem_out2,  -- int32
              isZero => Synchronous_Subsystem_out3,
              y => y  -- sfix22_En20
              );

  validOut <= Synchronous_Subsystem_out4;

END rtl;

