// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdl_model_fixed\fft_ip2_src_MINRESRX2FFT_BTF.v
// Created: 2024-12-19 16:24:48
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: fft_ip2_src_MINRESRX2FFT_BTF
// Source Path: hdl_model_fixed/Subsystem1/my_FFT/FFT/MINRESRX2FFT_BTFSEL
// Hierarchy Level: 2
// Model version: 1.95
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module fft_ip2_src_MINRESRX2FFT_BTF
          (clk,
           reset,
           enb_1_2_0,
           din_1_re,
           din_1_im,
           validIn,
           rdy,
           dMemOut1_re,
           dMemOut1_im,
           dMemOut2_re,
           dMemOut2_im,
           dMemOut_vld,
           stage,
           initIC,
           syncReset,
           btfIn1_re,
           btfIn1_im,
           btfIn2_re,
           btfIn2_im,
           btfIn_vld);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   signed [22:0] din_1_re;  // sfix23_En11
  input   signed [22:0] din_1_im;  // sfix23_En11
  input   validIn;
  input   rdy;
  input   signed [22:0] dMemOut1_re;  // sfix23_En11
  input   signed [22:0] dMemOut1_im;  // sfix23_En11
  input   signed [22:0] dMemOut2_re;  // sfix23_En11
  input   signed [22:0] dMemOut2_im;  // sfix23_En11
  input   dMemOut_vld;
  input   [3:0] stage;  // ufix4
  input   initIC;
  input   syncReset;
  output  signed [22:0] btfIn1_re;  // sfix23_En11
  output  signed [22:0] btfIn1_im;  // sfix23_En11
  output  signed [22:0] btfIn2_re;  // sfix23_En11
  output  signed [22:0] btfIn2_im;  // sfix23_En11
  output  btfIn_vld;


  reg signed [22:0] minResRX2FFTBTFSEL_btfIn1Reg_re;  // sfix23
  reg signed [22:0] minResRX2FFTBTFSEL_btfIn1Reg_im;  // sfix23
  reg signed [22:0] minResRX2FFTBTFSEL_btfIn2Reg_re;  // sfix23
  reg signed [22:0] minResRX2FFTBTFSEL_btfIn2Reg_im;  // sfix23
  reg  minResRX2FFTBTFSEL_btfInReg_vld;
  reg [9:0] minResRX2FFTBTFSEL_cnt;  // ufix10
  reg [9:0] minResRX2FFTBTFSEL_cntMax;  // ufix10
  reg  minResRX2FFTBTFSEL_muxSel;
  reg signed [22:0] minResRX2FFTBTFSEL_dinReg1_re;  // sfix23
  reg signed [22:0] minResRX2FFTBTFSEL_dinReg1_im;  // sfix23
  reg signed [22:0] minResRX2FFTBTFSEL_dinReg2_re;  // sfix23
  reg signed [22:0] minResRX2FFTBTFSEL_dinReg2_im;  // sfix23
  reg signed [22:0] minResRX2FFTBTFSEL_dinReg3_re;  // sfix23
  reg signed [22:0] minResRX2FFTBTFSEL_dinReg3_im;  // sfix23
  reg signed [22:0] minResRX2FFTBTFSEL_dMemOut1Reg_re;  // sfix23
  reg signed [22:0] minResRX2FFTBTFSEL_dMemOut1Reg_im;  // sfix23
  reg signed [22:0] minResRX2FFTBTFSEL_dMemOut2Reg_re;  // sfix23
  reg signed [22:0] minResRX2FFTBTFSEL_dMemOut2Reg_im;  // sfix23
  reg  minResRX2FFTBTFSEL_dMemOutReg_vld;
  reg signed [22:0] minResRX2FFTBTFSEL_btfIn1Reg_re_next;  // sfix23_En11
  reg signed [22:0] minResRX2FFTBTFSEL_btfIn1Reg_im_next;  // sfix23_En11
  reg signed [22:0] minResRX2FFTBTFSEL_btfIn2Reg_re_next;  // sfix23_En11
  reg signed [22:0] minResRX2FFTBTFSEL_btfIn2Reg_im_next;  // sfix23_En11
  reg  minResRX2FFTBTFSEL_btfInReg_vld_next;
  reg [9:0] minResRX2FFTBTFSEL_cnt_next;  // ufix10
  reg [9:0] minResRX2FFTBTFSEL_cntMax_next;  // ufix10
  reg  minResRX2FFTBTFSEL_muxSel_next;
  reg signed [22:0] minResRX2FFTBTFSEL_dinReg1_re_next;  // sfix23_En11
  reg signed [22:0] minResRX2FFTBTFSEL_dinReg1_im_next;  // sfix23_En11
  reg signed [22:0] minResRX2FFTBTFSEL_dinReg2_re_next;  // sfix23_En11
  reg signed [22:0] minResRX2FFTBTFSEL_dinReg2_im_next;  // sfix23_En11
  reg signed [22:0] minResRX2FFTBTFSEL_dinReg3_re_next;  // sfix23_En11
  reg signed [22:0] minResRX2FFTBTFSEL_dinReg3_im_next;  // sfix23_En11
  reg signed [22:0] minResRX2FFTBTFSEL_dMemOut1Reg_re_ne;  // sfix23_En11
  reg signed [22:0] minResRX2FFTBTFSEL_dMemOut1Reg_im_ne;  // sfix23_En11
  reg signed [22:0] minResRX2FFTBTFSEL_dMemOut2Reg_re_ne;  // sfix23_En11
  reg signed [22:0] minResRX2FFTBTFSEL_dMemOut2Reg_im_ne;  // sfix23_En11
  reg  minResRX2FFTBTFSEL_dMemOutReg_vld_ne;
  reg signed [22:0] btfIn1_re_1;  // sfix23_En11
  reg signed [22:0] btfIn1_im_1;  // sfix23_En11
  reg signed [22:0] btfIn2_re_1;  // sfix23_En11
  reg signed [22:0] btfIn2_im_1;  // sfix23_En11
  reg  btfIn_vld_1;


  // minResRX2FFTBTFSEL
  always @(posedge clk)
    begin : minResRX2FFTBTFSEL_process
      if (reset == 1'b1) begin
        minResRX2FFTBTFSEL_btfIn1Reg_re <= 23'sb00000000000000000000000;
        minResRX2FFTBTFSEL_btfIn1Reg_im <= 23'sb00000000000000000000000;
        minResRX2FFTBTFSEL_btfIn2Reg_re <= 23'sb00000000000000000000000;
        minResRX2FFTBTFSEL_btfIn2Reg_im <= 23'sb00000000000000000000000;
        minResRX2FFTBTFSEL_dinReg1_re <= 23'sb00000000000000000000000;
        minResRX2FFTBTFSEL_dinReg1_im <= 23'sb00000000000000000000000;
        minResRX2FFTBTFSEL_dinReg2_re <= 23'sb00000000000000000000000;
        minResRX2FFTBTFSEL_dinReg2_im <= 23'sb00000000000000000000000;
        minResRX2FFTBTFSEL_dinReg3_re <= 23'sb00000000000000000000000;
        minResRX2FFTBTFSEL_dinReg3_im <= 23'sb00000000000000000000000;
        minResRX2FFTBTFSEL_dMemOut1Reg_re <= 23'sb00000000000000000000000;
        minResRX2FFTBTFSEL_dMemOut1Reg_im <= 23'sb00000000000000000000000;
        minResRX2FFTBTFSEL_dMemOut2Reg_re <= 23'sb00000000000000000000000;
        minResRX2FFTBTFSEL_dMemOut2Reg_im <= 23'sb00000000000000000000000;
        minResRX2FFTBTFSEL_cnt <= 10'b0000000000;
        minResRX2FFTBTFSEL_cntMax <= 10'b0000000000;
        minResRX2FFTBTFSEL_muxSel <= 1'b0;
        minResRX2FFTBTFSEL_btfInReg_vld <= 1'b0;
        minResRX2FFTBTFSEL_dMemOutReg_vld <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          if (syncReset == 1'b1) begin
            minResRX2FFTBTFSEL_btfIn1Reg_re <= 23'sb00000000000000000000000;
            minResRX2FFTBTFSEL_btfIn1Reg_im <= 23'sb00000000000000000000000;
            minResRX2FFTBTFSEL_btfIn2Reg_re <= 23'sb00000000000000000000000;
            minResRX2FFTBTFSEL_btfIn2Reg_im <= 23'sb00000000000000000000000;
            minResRX2FFTBTFSEL_dinReg1_re <= 23'sb00000000000000000000000;
            minResRX2FFTBTFSEL_dinReg1_im <= 23'sb00000000000000000000000;
            minResRX2FFTBTFSEL_dinReg2_re <= 23'sb00000000000000000000000;
            minResRX2FFTBTFSEL_dinReg2_im <= 23'sb00000000000000000000000;
            minResRX2FFTBTFSEL_dinReg3_re <= 23'sb00000000000000000000000;
            minResRX2FFTBTFSEL_dinReg3_im <= 23'sb00000000000000000000000;
            minResRX2FFTBTFSEL_dMemOut1Reg_re <= 23'sb00000000000000000000000;
            minResRX2FFTBTFSEL_dMemOut1Reg_im <= 23'sb00000000000000000000000;
            minResRX2FFTBTFSEL_dMemOut2Reg_re <= 23'sb00000000000000000000000;
            minResRX2FFTBTFSEL_dMemOut2Reg_im <= 23'sb00000000000000000000000;
            minResRX2FFTBTFSEL_cnt <= 10'b0000000000;
            minResRX2FFTBTFSEL_cntMax <= 10'b0000000000;
            minResRX2FFTBTFSEL_muxSel <= 1'b0;
            minResRX2FFTBTFSEL_btfInReg_vld <= 1'b0;
            minResRX2FFTBTFSEL_dMemOutReg_vld <= 1'b0;
          end
          else begin
            minResRX2FFTBTFSEL_btfIn1Reg_re <= minResRX2FFTBTFSEL_btfIn1Reg_re_next;
            minResRX2FFTBTFSEL_btfIn1Reg_im <= minResRX2FFTBTFSEL_btfIn1Reg_im_next;
            minResRX2FFTBTFSEL_btfIn2Reg_re <= minResRX2FFTBTFSEL_btfIn2Reg_re_next;
            minResRX2FFTBTFSEL_btfIn2Reg_im <= minResRX2FFTBTFSEL_btfIn2Reg_im_next;
            minResRX2FFTBTFSEL_btfInReg_vld <= minResRX2FFTBTFSEL_btfInReg_vld_next;
            minResRX2FFTBTFSEL_cnt <= minResRX2FFTBTFSEL_cnt_next;
            minResRX2FFTBTFSEL_cntMax <= minResRX2FFTBTFSEL_cntMax_next;
            minResRX2FFTBTFSEL_muxSel <= minResRX2FFTBTFSEL_muxSel_next;
            minResRX2FFTBTFSEL_dinReg1_re <= minResRX2FFTBTFSEL_dinReg1_re_next;
            minResRX2FFTBTFSEL_dinReg1_im <= minResRX2FFTBTFSEL_dinReg1_im_next;
            minResRX2FFTBTFSEL_dinReg2_re <= minResRX2FFTBTFSEL_dinReg2_re_next;
            minResRX2FFTBTFSEL_dinReg2_im <= minResRX2FFTBTFSEL_dinReg2_im_next;
            minResRX2FFTBTFSEL_dinReg3_re <= minResRX2FFTBTFSEL_dinReg3_re_next;
            minResRX2FFTBTFSEL_dinReg3_im <= minResRX2FFTBTFSEL_dinReg3_im_next;
            minResRX2FFTBTFSEL_dMemOut1Reg_re <= minResRX2FFTBTFSEL_dMemOut1Reg_re_ne;
            minResRX2FFTBTFSEL_dMemOut1Reg_im <= minResRX2FFTBTFSEL_dMemOut1Reg_im_ne;
            minResRX2FFTBTFSEL_dMemOut2Reg_re <= minResRX2FFTBTFSEL_dMemOut2Reg_re_ne;
            minResRX2FFTBTFSEL_dMemOut2Reg_im <= minResRX2FFTBTFSEL_dMemOut2Reg_im_ne;
            minResRX2FFTBTFSEL_dMemOutReg_vld <= minResRX2FFTBTFSEL_dMemOutReg_vld_ne;
          end
        end
      end
    end

  always @(dMemOut1_im, dMemOut1_re, dMemOut2_im, dMemOut2_re, dMemOut_vld, din_1_im,
       din_1_re, initIC, minResRX2FFTBTFSEL_btfIn1Reg_im,
       minResRX2FFTBTFSEL_btfIn1Reg_re, minResRX2FFTBTFSEL_btfIn2Reg_im,
       minResRX2FFTBTFSEL_btfIn2Reg_re, minResRX2FFTBTFSEL_btfInReg_vld,
       minResRX2FFTBTFSEL_cnt, minResRX2FFTBTFSEL_cntMax,
       minResRX2FFTBTFSEL_dMemOut1Reg_im, minResRX2FFTBTFSEL_dMemOut1Reg_re,
       minResRX2FFTBTFSEL_dMemOut2Reg_im, minResRX2FFTBTFSEL_dMemOut2Reg_re,
       minResRX2FFTBTFSEL_dMemOutReg_vld, minResRX2FFTBTFSEL_dinReg1_im,
       minResRX2FFTBTFSEL_dinReg1_re, minResRX2FFTBTFSEL_dinReg2_im,
       minResRX2FFTBTFSEL_dinReg2_re, minResRX2FFTBTFSEL_dinReg3_im,
       minResRX2FFTBTFSEL_dinReg3_re, minResRX2FFTBTFSEL_muxSel, stage) begin
    minResRX2FFTBTFSEL_cnt_next = minResRX2FFTBTFSEL_cnt;
    minResRX2FFTBTFSEL_cntMax_next = minResRX2FFTBTFSEL_cntMax;
    minResRX2FFTBTFSEL_muxSel_next = minResRX2FFTBTFSEL_muxSel;
    case ( stage)
      4'b0000 :
        begin
          minResRX2FFTBTFSEL_btfIn1Reg_re_next = minResRX2FFTBTFSEL_dMemOut1Reg_re;
          minResRX2FFTBTFSEL_btfIn1Reg_im_next = minResRX2FFTBTFSEL_dMemOut1Reg_im;
          minResRX2FFTBTFSEL_btfIn2Reg_re_next = minResRX2FFTBTFSEL_dinReg3_re;
          minResRX2FFTBTFSEL_btfIn2Reg_im_next = minResRX2FFTBTFSEL_dinReg3_im;
        end
      default :
        begin
          if (minResRX2FFTBTFSEL_muxSel) begin
            minResRX2FFTBTFSEL_btfIn1Reg_re_next = minResRX2FFTBTFSEL_dMemOut2Reg_re;
            minResRX2FFTBTFSEL_btfIn1Reg_im_next = minResRX2FFTBTFSEL_dMemOut2Reg_im;
            minResRX2FFTBTFSEL_btfIn2Reg_re_next = minResRX2FFTBTFSEL_dMemOut1Reg_re;
            minResRX2FFTBTFSEL_btfIn2Reg_im_next = minResRX2FFTBTFSEL_dMemOut1Reg_im;
          end
          else begin
            minResRX2FFTBTFSEL_btfIn1Reg_re_next = minResRX2FFTBTFSEL_dMemOut1Reg_re;
            minResRX2FFTBTFSEL_btfIn1Reg_im_next = minResRX2FFTBTFSEL_dMemOut1Reg_im;
            minResRX2FFTBTFSEL_btfIn2Reg_re_next = minResRX2FFTBTFSEL_dMemOut2Reg_re;
            minResRX2FFTBTFSEL_btfIn2Reg_im_next = minResRX2FFTBTFSEL_dMemOut2Reg_im;
          end
        end
    endcase
    minResRX2FFTBTFSEL_dinReg3_re_next = minResRX2FFTBTFSEL_dinReg2_re;
    minResRX2FFTBTFSEL_dinReg2_re_next = minResRX2FFTBTFSEL_dinReg1_re;
    minResRX2FFTBTFSEL_dinReg1_re_next = din_1_re;
    minResRX2FFTBTFSEL_dinReg3_im_next = minResRX2FFTBTFSEL_dinReg2_im;
    minResRX2FFTBTFSEL_dinReg2_im_next = minResRX2FFTBTFSEL_dinReg1_im;
    minResRX2FFTBTFSEL_dinReg1_im_next = din_1_im;
    if (initIC) begin
      minResRX2FFTBTFSEL_cnt_next = 10'b0000000000;
      minResRX2FFTBTFSEL_muxSel_next = 1'b0;
      case ( stage)
        4'b0000 :
          begin
            minResRX2FFTBTFSEL_cntMax_next = 10'b1111111111;
          end
        default :
          begin
            minResRX2FFTBTFSEL_cntMax_next = minResRX2FFTBTFSEL_cntMax >> 8'd1;
          end
      endcase
    end
    else if (minResRX2FFTBTFSEL_dMemOutReg_vld) begin
      if (minResRX2FFTBTFSEL_cnt == minResRX2FFTBTFSEL_cntMax) begin
        minResRX2FFTBTFSEL_cnt_next = 10'b0000000000;
        minResRX2FFTBTFSEL_muxSel_next =  ! minResRX2FFTBTFSEL_muxSel;
      end
      else begin
        minResRX2FFTBTFSEL_cnt_next = minResRX2FFTBTFSEL_cnt + 10'b0000000001;
      end
    end
    minResRX2FFTBTFSEL_btfInReg_vld_next = minResRX2FFTBTFSEL_dMemOutReg_vld;
    minResRX2FFTBTFSEL_dMemOutReg_vld_ne = dMemOut_vld;
    minResRX2FFTBTFSEL_dMemOut1Reg_re_ne = dMemOut1_re;
    minResRX2FFTBTFSEL_dMemOut1Reg_im_ne = dMemOut1_im;
    minResRX2FFTBTFSEL_dMemOut2Reg_re_ne = dMemOut2_re;
    minResRX2FFTBTFSEL_dMemOut2Reg_im_ne = dMemOut2_im;
    btfIn1_re_1 = minResRX2FFTBTFSEL_btfIn1Reg_re;
    btfIn1_im_1 = minResRX2FFTBTFSEL_btfIn1Reg_im;
    btfIn2_re_1 = minResRX2FFTBTFSEL_btfIn2Reg_re;
    btfIn2_im_1 = minResRX2FFTBTFSEL_btfIn2Reg_im;
    btfIn_vld_1 = minResRX2FFTBTFSEL_btfInReg_vld;
  end



  assign btfIn1_re = btfIn1_re_1;

  assign btfIn1_im = btfIn1_im_1;

  assign btfIn2_re = btfIn2_re_1;

  assign btfIn2_im = btfIn2_im_1;

  assign btfIn_vld = btfIn_vld_1;

endmodule  // fft_ip2_src_MINRESRX2FFT_BTF

