// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdl_model_fixed\fft_ip2_src_MINRESRX2_BUTTER.v
// Created: 2024-12-19 16:24:48
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: fft_ip2_src_MINRESRX2_BUTTER
// Source Path: hdl_model_fixed/Subsystem1/my_FFT/FFT/MINRESRX2_BUTTERFLY
// Hierarchy Level: 2
// Model version: 1.95
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module fft_ip2_src_MINRESRX2_BUTTER
          (clk,
           reset,
           enb_1_2_0,
           btfIn1_re,
           btfIn1_im,
           btfIn2_re,
           btfIn2_im,
           btfIn_vld,
           twdl_re,
           twdl_im,
           syncReset,
           btfOut1_re,
           btfOut1_im,
           btfOut2_re,
           btfOut2_im,
           btfOut_vld);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   signed [22:0] btfIn1_re;  // sfix23_En11
  input   signed [22:0] btfIn1_im;  // sfix23_En11
  input   signed [22:0] btfIn2_re;  // sfix23_En11
  input   signed [22:0] btfIn2_im;  // sfix23_En11
  input   btfIn_vld;
  input   signed [22:0] twdl_re;  // sfix23_En21
  input   signed [22:0] twdl_im;  // sfix23_En21
  input   syncReset;
  output  signed [22:0] btfOut1_re;  // sfix23_En11
  output  signed [22:0] btfOut1_im;  // sfix23_En11
  output  signed [22:0] btfOut2_re;  // sfix23_En11
  output  signed [22:0] btfOut2_im;  // sfix23_En11
  output  btfOut_vld;


  reg signed [22:0] intdelay_reg [0:1];  // sfix23 [2]
  wire signed [22:0] intdelay_reg_next [0:1];  // sfix23_En11 [2]
  wire signed [22:0] din2Dly_re;  // sfix23_En11
  reg signed [22:0] intdelay_reg_1 [0:1];  // sfix23 [2]
  wire signed [22:0] intdelay_reg_next_1 [0:1];  // sfix23_En11 [2]
  wire signed [22:0] din2Dly_im;  // sfix23_En11
  wire signed [46:0] dinXTwdl_re;  // sfix47_En32
  wire signed [46:0] dinXTwdl_im;  // sfix47_En32
  wire dinXTwdl_vld;
  reg signed [22:0] intdelay_reg_2 [0:7];  // sfix23 [8]
  reg signed [22:0] intdelay_reg_next_2 [0:7];  // sfix23_En11 [8]
  reg signed [22:0] din1Dly_re;  // sfix23_En11
  reg signed [22:0] intdelay_reg_3 [0:7];  // sfix23 [8]
  reg signed [22:0] intdelay_reg_next_3 [0:7];  // sfix23_En11 [8]
  reg signed [22:0] din1Dly_im;  // sfix23_En11
  reg  [7:0] intdelay_reg_4;  // ufix1 [8]
  wire din1Dly_vld;
  reg signed [47:0] minResRX2FFTButterfly_add1_re;  // sfix48
  reg signed [47:0] minResRX2FFTButterfly_add1_im;  // sfix48
  reg signed [47:0] minResRX2FFTButterfly_sub1_re;  // sfix48
  reg signed [47:0] minResRX2FFTButterfly_sub1_im;  // sfix48
  reg  minResRX2FFTButterfly_vld_reg;
  reg signed [47:0] minResRX2FFTButterfly_add1_cast_re;  // sfix48
  reg signed [47:0] minResRX2FFTButterfly_add1_cast_im;  // sfix48
  reg signed [47:0] minResRX2FFTButterfly_sub1_cast_re;  // sfix48
  reg signed [47:0] minResRX2FFTButterfly_sub1_cast_im;  // sfix48
  wire signed [47:0] minResRX2FFTButterfly_add1_re_next;  // sfix48_En32
  wire signed [47:0] minResRX2FFTButterfly_add1_im_next;  // sfix48_En32
  wire signed [47:0] minResRX2FFTButterfly_sub1_re_next;  // sfix48_En32
  wire signed [47:0] minResRX2FFTButterfly_sub1_im_next;  // sfix48_En32
  wire signed [47:0] minResRX2FFTButterfly_add1_cast_re_n;  // sfix48_En32
  wire signed [47:0] minResRX2FFTButterfly_add1_cast_im_n;  // sfix48_En32
  wire signed [47:0] minResRX2FFTButterfly_sub1_cast_re_n;  // sfix48_En32
  wire signed [47:0] minResRX2FFTButterfly_sub1_cast_im_n;  // sfix48_En32
  wire signed [47:0] minResRX2FFTButterfly_add_cast;  // sfix48_En32
  wire signed [47:0] minResRX2FFTButterfly_add_cast_1;  // sfix48_En32
  wire signed [47:0] minResRX2FFTButterfly_add_cast_2;  // sfix48_En32
  wire signed [47:0] minResRX2FFTButterfly_add_cast_3;  // sfix48_En32
  wire signed [47:0] minResRX2FFTButterfly_sub_cast;  // sfix48_En32
  wire signed [47:0] minResRX2FFTButterfly_sub_cast_1;  // sfix48_En32
  wire signed [47:0] minResRX2FFTButterfly_sub_cast_2;  // sfix48_En32
  wire signed [47:0] minResRX2FFTButterfly_sub_cast_3;  // sfix48_En32
  wire signed [47:0] btfOut1FP_re;  // sfix48_En32
  wire signed [47:0] btfOut1FP_im;  // sfix48_En32
  wire signed [47:0] btfOut2FP_re;  // sfix48_En32
  wire signed [47:0] btfOut2FP_im;  // sfix48_En32
  reg  btfOut_vld_1;
  reg signed [31:0] intdelay_t_0_0;  // int32
  reg signed [31:0] intdelay_t_1;  // int32
  reg signed [31:0] intdelay_t_0_0_1;  // int32
  reg signed [31:0] intdelay_t_0_0_2;  // int32
  reg signed [31:0] intdelay_t_0_1;  // int32
  reg signed [31:0] intdelay_t_1_1;  // int32
  reg signed [31:0] intdelay_t_0_01;  // int32
  reg signed [31:0] intdelay_t_1_2;  // int32


  always @(posedge clk)
    begin : intdelay_process
      if (reset == 1'b1) begin
        for(intdelay_t_1 = 32'sd0; intdelay_t_1 <= 32'sd1; intdelay_t_1 = intdelay_t_1 + 32'sd1) begin
          intdelay_reg[intdelay_t_1] <= 23'sb00000000000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          if (syncReset == 1'b1) begin
            for(intdelay_t_1 = 32'sd0; intdelay_t_1 <= 32'sd1; intdelay_t_1 = intdelay_t_1 + 32'sd1) begin
              intdelay_reg[intdelay_t_1] <= 23'sb00000000000000000000000;
            end
          end
          else begin
            for(intdelay_t_0_0 = 32'sd0; intdelay_t_0_0 <= 32'sd1; intdelay_t_0_0 = intdelay_t_0_0 + 32'sd1) 
              begin
              intdelay_reg[intdelay_t_0_0] <= intdelay_reg_next[intdelay_t_0_0];
            end
          end
        end
      end
    end

  assign din2Dly_re = intdelay_reg[1];
  assign intdelay_reg_next[0] = btfIn2_re;
  assign intdelay_reg_next[1] = intdelay_reg[0];



  always @(posedge clk)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        for(intdelay_t_1 = 32'sd0; intdelay_t_1 <= 32'sd1; intdelay_t_1 = intdelay_t_1 + 32'sd1) begin
          intdelay_reg_1[intdelay_t_1] <= 23'sb00000000000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          if (syncReset == 1'b1) begin
            for(intdelay_t_1 = 32'sd0; intdelay_t_1 <= 32'sd1; intdelay_t_1 = intdelay_t_1 + 32'sd1) begin
              intdelay_reg_1[intdelay_t_1] <= 23'sb00000000000000000000000;
            end
          end
          else begin
            for(intdelay_t_0_0_1 = 32'sd0; intdelay_t_0_0_1 <= 32'sd1; intdelay_t_0_0_1 = intdelay_t_0_0_1 + 
              32'sd1) begin
              intdelay_reg_1[intdelay_t_0_0_1] <= intdelay_reg_next_1[intdelay_t_0_0_1];
            end
          end
        end
      end
    end

  assign din2Dly_im = intdelay_reg_1[1];
  assign intdelay_reg_next_1[0] = btfIn2_im;
  assign intdelay_reg_next_1[1] = intdelay_reg_1[0];



  fft_ip2_src_Complex4Multiply MUL4_1 (.clk(clk),
                                       .reset(reset),
                                       .enb_1_2_0(enb_1_2_0),
                                       .btfIn2_re(din2Dly_re),  // sfix23_En11
                                       .btfIn2_im(din2Dly_im),  // sfix23_En11
                                       .din2Dly_vld(btfIn_vld),
                                       .twdl_re(twdl_re),  // sfix23_En21
                                       .twdl_im(twdl_im),  // sfix23_En21
                                       .syncReset(syncReset),
                                       .dinXTwdl_re(dinXTwdl_re),  // sfix47_En32
                                       .dinXTwdl_im(dinXTwdl_im),  // sfix47_En32
                                       .dinXTwdl_vld(dinXTwdl_vld)
                                       );

  always @(posedge clk)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        for(intdelay_t_1_1 = 32'sd0; intdelay_t_1_1 <= 32'sd7; intdelay_t_1_1 = intdelay_t_1_1 + 32'sd1) begin
          intdelay_reg_2[intdelay_t_1_1] <= 23'sb00000000000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          if (syncReset == 1'b1) begin
            for(intdelay_t_1_1 = 32'sd0; intdelay_t_1_1 <= 32'sd7; intdelay_t_1_1 = intdelay_t_1_1 + 32'sd1) 
              begin
              intdelay_reg_2[intdelay_t_1_1] <= 23'sb00000000000000000000000;
            end
          end
          else begin
            for(intdelay_t_0_1 = 32'sd0; intdelay_t_0_1 <= 32'sd7; intdelay_t_0_1 = intdelay_t_0_1 + 32'sd1) 
              begin
              intdelay_reg_2[intdelay_t_0_1] <= intdelay_reg_next_2[intdelay_t_0_1];
            end
          end
        end
      end
    end

  always @* begin
    din1Dly_re = intdelay_reg_2[7];
    intdelay_reg_next_2[0] = btfIn1_re;

    for(intdelay_t_0_0_2 = 32'sd0; intdelay_t_0_0_2 <= 32'sd6; intdelay_t_0_0_2 = intdelay_t_0_0_2 + 32'sd1) 
      begin
      intdelay_reg_next_2[intdelay_t_0_0_2 + 32'sd1] = intdelay_reg_2[intdelay_t_0_0_2];
    end

  end



  always @(posedge clk)
    begin : intdelay_3_process
      if (reset == 1'b1) begin
        for(intdelay_t_1_2 = 32'sd0; intdelay_t_1_2 <= 32'sd7; intdelay_t_1_2 = intdelay_t_1_2 + 32'sd1) begin
          intdelay_reg_3[intdelay_t_1_2] <= 23'sb00000000000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          if (syncReset == 1'b1) begin
            for(intdelay_t_1_2 = 32'sd0; intdelay_t_1_2 <= 32'sd7; intdelay_t_1_2 = intdelay_t_1_2 + 32'sd1) 
              begin
              intdelay_reg_3[intdelay_t_1_2] <= 23'sb00000000000000000000000;
            end
          end
          else begin
            for(intdelay_t_0_1 = 32'sd0; intdelay_t_0_1 <= 32'sd7; intdelay_t_0_1 = intdelay_t_0_1 + 32'sd1) 
              begin
              intdelay_reg_3[intdelay_t_0_1] <= intdelay_reg_next_3[intdelay_t_0_1];
            end
          end
        end
      end
    end

  always @* begin
    din1Dly_im = intdelay_reg_3[7];
    intdelay_reg_next_3[0] = btfIn1_im;

    for(intdelay_t_0_01 = 32'sd0; intdelay_t_0_01 <= 32'sd6; intdelay_t_0_01 = intdelay_t_0_01 + 32'sd1) begin
      intdelay_reg_next_3[intdelay_t_0_01 + 32'sd1] = intdelay_reg_3[intdelay_t_0_01];
    end

  end



  always @(posedge clk)
    begin : intdelay_4_process
      if (reset == 1'b1) begin
        intdelay_reg_4 <= {8{1'b0}};
      end
      else begin
        if (enb_1_2_0) begin
          if (syncReset == 1'b1) begin
            intdelay_reg_4 <= {8{1'b0}};
          end
          else begin
            intdelay_reg_4[0] <= btfIn_vld;
            intdelay_reg_4[32'sd7:32'sd1] <= intdelay_reg_4[32'sd6:32'sd0];
          end
        end
      end
    end

  assign din1Dly_vld = intdelay_reg_4[7];



  // minResRX2FFTButterfly
  always @(posedge clk)
    begin : minResRX2FFTButterfly_process
      if (reset == 1'b1) begin
        minResRX2FFTButterfly_add1_re <= 48'sh000000000000;
        minResRX2FFTButterfly_add1_im <= 48'sh000000000000;
        minResRX2FFTButterfly_sub1_re <= 48'sh000000000000;
        minResRX2FFTButterfly_sub1_im <= 48'sh000000000000;
        minResRX2FFTButterfly_add1_cast_re <= 48'sh000000000000;
        minResRX2FFTButterfly_add1_cast_im <= 48'sh000000000000;
        minResRX2FFTButterfly_sub1_cast_re <= 48'sh000000000000;
        minResRX2FFTButterfly_sub1_cast_im <= 48'sh000000000000;
        minResRX2FFTButterfly_vld_reg <= 1'b0;
        btfOut_vld_1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          if (syncReset == 1'b1) begin
            minResRX2FFTButterfly_add1_re <= 48'sh000000000000;
            minResRX2FFTButterfly_add1_im <= 48'sh000000000000;
            minResRX2FFTButterfly_sub1_re <= 48'sh000000000000;
            minResRX2FFTButterfly_sub1_im <= 48'sh000000000000;
            minResRX2FFTButterfly_add1_cast_re <= 48'sh000000000000;
            minResRX2FFTButterfly_add1_cast_im <= 48'sh000000000000;
            minResRX2FFTButterfly_sub1_cast_re <= 48'sh000000000000;
            minResRX2FFTButterfly_sub1_cast_im <= 48'sh000000000000;
            minResRX2FFTButterfly_vld_reg <= 1'b0;
            btfOut_vld_1 <= 1'b0;
          end
          else begin
            minResRX2FFTButterfly_add1_re <= minResRX2FFTButterfly_add1_re_next;
            minResRX2FFTButterfly_add1_im <= minResRX2FFTButterfly_add1_im_next;
            minResRX2FFTButterfly_sub1_re <= minResRX2FFTButterfly_sub1_re_next;
            minResRX2FFTButterfly_sub1_im <= minResRX2FFTButterfly_sub1_im_next;
            minResRX2FFTButterfly_add1_cast_re <= minResRX2FFTButterfly_add1_cast_re_n;
            minResRX2FFTButterfly_add1_cast_im <= minResRX2FFTButterfly_add1_cast_im_n;
            minResRX2FFTButterfly_sub1_cast_re <= minResRX2FFTButterfly_sub1_cast_re_n;
            minResRX2FFTButterfly_sub1_cast_im <= minResRX2FFTButterfly_sub1_cast_im_n;
            btfOut_vld_1 <= minResRX2FFTButterfly_vld_reg;
            minResRX2FFTButterfly_vld_reg <= din1Dly_vld;
          end
        end
      end
    end

  assign minResRX2FFTButterfly_add1_cast_re_n = minResRX2FFTButterfly_add1_re;
  assign minResRX2FFTButterfly_add1_cast_im_n = minResRX2FFTButterfly_add1_im;
  assign minResRX2FFTButterfly_sub1_cast_re_n = minResRX2FFTButterfly_sub1_re;
  assign minResRX2FFTButterfly_sub1_cast_im_n = minResRX2FFTButterfly_sub1_im;
  assign minResRX2FFTButterfly_add_cast = {{4{din1Dly_re[22]}}, {din1Dly_re, 21'b000000000000000000000}};
  assign minResRX2FFTButterfly_add_cast_1 = {dinXTwdl_re[46], dinXTwdl_re};
  assign minResRX2FFTButterfly_add1_re_next = minResRX2FFTButterfly_add_cast + 
    minResRX2FFTButterfly_add_cast_1;
  assign minResRX2FFTButterfly_add_cast_2 = {{4{din1Dly_im[22]}}, {din1Dly_im, 21'b000000000000000000000}};
  assign minResRX2FFTButterfly_add_cast_3 = {dinXTwdl_im[46], dinXTwdl_im};
  assign minResRX2FFTButterfly_add1_im_next = minResRX2FFTButterfly_add_cast_2 + 
    minResRX2FFTButterfly_add_cast_3;
  assign minResRX2FFTButterfly_sub_cast = {{4{din1Dly_re[22]}}, {din1Dly_re, 21'b000000000000000000000}};
  assign minResRX2FFTButterfly_sub_cast_1 = {dinXTwdl_re[46], dinXTwdl_re};
  assign minResRX2FFTButterfly_sub1_re_next = minResRX2FFTButterfly_sub_cast - 
    minResRX2FFTButterfly_sub_cast_1;
  assign minResRX2FFTButterfly_sub_cast_2 = {{4{din1Dly_im[22]}}, {din1Dly_im, 21'b000000000000000000000}};
  assign minResRX2FFTButterfly_sub_cast_3 = {dinXTwdl_im[46], dinXTwdl_im};
  assign minResRX2FFTButterfly_sub1_im_next = minResRX2FFTButterfly_sub_cast_2 - 
    minResRX2FFTButterfly_sub_cast_3;
  assign btfOut1FP_re = minResRX2FFTButterfly_add1_cast_re;
  assign btfOut1FP_im = minResRX2FFTButterfly_add1_cast_im;
  assign btfOut2FP_re = minResRX2FFTButterfly_sub1_cast_re;
  assign btfOut2FP_im = minResRX2FFTButterfly_sub1_cast_im;



  assign btfOut1_re = btfOut1FP_re[43:21];



  assign btfOut1_im = btfOut1FP_im[43:21];



  assign btfOut2_re = btfOut2FP_re[43:21];



  assign btfOut2_im = btfOut2FP_im[43:21];



  assign btfOut_vld = btfOut_vld_1;

endmodule  // fft_ip2_src_MINRESRX2_BUTTER

