open_system('hdl_model_fixed');
open_system('gm_hdl_model_fixed');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem Reference', 'user2');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem Reference', 'user2');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Serializer1D', 'user2');
annotate_port('gm_hdl_model_fixed/Subsystem1/Serializer1D', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('hdl_model_fixed/Subsystem1/Serializer1D', 'user2');
annotate_port('hdl_model_fixed/Subsystem1/Serializer1D', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/Delay', 'user2');
annotate_port('gm_hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/Delay', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/Delay', 'user2');
annotate_port('hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/Delay', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/Deserializer1D', 'user2');
annotate_port('gm_hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/Deserializer1D', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/Deserializer1D', 'user2');
annotate_port('hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/Deserializer1D', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/CORDIC Square Root HDL Optimized', 'user2');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/CORDIC Square Root HDL Optimized', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem Reference/CORDIC Square Root HDL Optimized', 'user2');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/CORDIC Square Root HDL Optimized', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Multiply-Accumulate', 'user2');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Multiply-Accumulate', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem Reference/Multiply-Accumulate', 'user2');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Multiply-Accumulate', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex/CORDIC Square Root HDL Optimized1', 'user2');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex/CORDIC Square Root HDL Optimized1', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex/CORDIC Square Root HDL Optimized1', 'user2');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex/CORDIC Square Root HDL Optimized1', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/myRMS/CORDIC Square Root HDL Optimized', 'user2');
annotate_port('gm_hdl_model_fixed/Subsystem1/myRMS/CORDIC Square Root HDL Optimized', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('hdl_model_fixed/Subsystem1/myRMS/CORDIC Square Root HDL Optimized', 'user2');
annotate_port('hdl_model_fixed/Subsystem1/myRMS/CORDIC Square Root HDL Optimized', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/myRMS/Multiply-Accumulate', 'user2');
annotate_port('gm_hdl_model_fixed/Subsystem1/myRMS/Multiply-Accumulate', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('hdl_model_fixed/Subsystem1/myRMS/Multiply-Accumulate', 'user2');
annotate_port('hdl_model_fixed/Subsystem1/myRMS/Multiply-Accumulate', 1, 1, 'Obstacle to clock-rate pipelining');
