open_system('hdl_model_fixed');
open_system('gm_hdl_model_fixed');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Multiply-Accumulate', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Multiply-Accumulate', 0, 1, 'Blocks delay absorption: 4 cycles');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem Reference/Multiply-Accumulate', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Multiply-Accumulate', 0, 1, 'Blocks delay absorption: 4 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/myRMS/Multiply-Accumulate', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/myRMS/Multiply-Accumulate', 0, 1, 'Blocks delay absorption: 2 cycles');
hilite_system('hdl_model_fixed/Subsystem1/myRMS/Multiply-Accumulate', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/myRMS/Multiply-Accumulate', 0, 1, 'Blocks delay absorption: 2 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex/CORDIC Square Root HDL Optimized1/Synchronous Subsystem/cordicSquareRootHDL/embmathops_c2_srwrzER3uCGRdPfDbow0ID_cordicSquareRootHDL_controlled/embmathops_c2_srwrzER3uCGRdPfDbow0ID_cordicSquareRootHDL', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex/CORDIC Square Root HDL Optimized1/Synchronous Subsystem/cordicSquareRootHDL/embmathops_c2_srwrzER3uCGRdPfDbow0ID_cordicSquareRootHDL_controlled/embmathops_c2_srwrzER3uCGRdPfDbow0ID_cordicSquareRootHDL', 0, 1, 'Blocks delay absorption: 2 cycles');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex/CORDIC Square Root HDL Optimized1/Synchronous Subsystem/cordicSquareRootHDL', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex/CORDIC Square Root HDL Optimized1/Synchronous Subsystem/cordicSquareRootHDL', 0, 1, 'Blocks delay absorption: 2 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/CORDIC Square Root HDL Optimized/Synchronous Subsystem/cordicSquareRootHDL/embmathops_c2_skVmLPFzLIK224pVNfQB1qF_cordicSquareRootHDL_controlled/embmathops_c2_skVmLPFzLIK224pVNfQB1qF_cordicSquareRootHDL', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/CORDIC Square Root HDL Optimized/Synchronous Subsystem/cordicSquareRootHDL/embmathops_c2_skVmLPFzLIK224pVNfQB1qF_cordicSquareRootHDL_controlled/embmathops_c2_skVmLPFzLIK224pVNfQB1qF_cordicSquareRootHDL', 0, 1, 'Blocks delay absorption: 4 cycles');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem Reference/CORDIC Square Root HDL Optimized/Synchronous Subsystem/cordicSquareRootHDL', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/CORDIC Square Root HDL Optimized/Synchronous Subsystem/cordicSquareRootHDL', 0, 1, 'Blocks delay absorption: 4 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1/Normalize numerator/positiveRealNormalizer/embreciprocals_c3_positiveRealNormalizer_controlled/embreciprocals_c3_positiveRealNormalizer', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1/Normalize numerator/positiveRealNormalizer/embreciprocals_c3_positiveRealNormalizer_controlled/embreciprocals_c3_positiveRealNormalizer', 0, 1, 'Blocks delay absorption: 5 cycles');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Normalize numerator/positiveRealNormalizer', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Normalize numerator/positiveRealNormalizer', 0, 1, 'Blocks delay absorption: 5 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1/Normalize denominator/positiveRealNormalizer/embreciprocals_c3_positiveRealNormalizer_controlled/embreciprocals_c3_positiveRealNormalizer', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1/Normalize denominator/positiveRealNormalizer/embreciprocals_c3_positiveRealNormalizer_controlled/embreciprocals_c3_positiveRealNormalizer', 0, 1, 'Blocks delay absorption: 5 cycles');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Normalize denominator/positiveRealNormalizer', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Normalize denominator/positiveRealNormalizer', 0, 1, 'Blocks delay absorption: 5 cycles');
