open_system('hdl_model_fixed');
open_system('gm_hdl_model_fixed');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/myRMS/Multiply-Accumulate', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/myRMS/Multiply-Accumulate', 0, 1, 'Blocks delay absorption: 3 cycles');
hilite_system('hdl_model_fixed/Subsystem1/myRMS/Multiply-Accumulate', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/myRMS/Multiply-Accumulate', 0, 1, 'Blocks delay absorption: 3 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex/CORDIC Square Root HDL Optimized1/Synchronous Subsystem/cordicSquareRootHDL/embmathops_c2_srwrzER3uCGRdPfDbow0ID_cordicSquareRootHDL_controlled/embmathops_c2_srwrzER3uCGRdPfDbow0ID_cordicSquareRootHDL', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex/CORDIC Square Root HDL Optimized1/Synchronous Subsystem/cordicSquareRootHDL/embmathops_c2_srwrzER3uCGRdPfDbow0ID_cordicSquareRootHDL_controlled/embmathops_c2_srwrzER3uCGRdPfDbow0ID_cordicSquareRootHDL', 0, 1, 'Blocks delay absorption: 3 cycles');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex/CORDIC Square Root HDL Optimized1/Synchronous Subsystem/cordicSquareRootHDL', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex/CORDIC Square Root HDL Optimized1/Synchronous Subsystem/cordicSquareRootHDL', 0, 1, 'Blocks delay absorption: 3 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/CORDIC Square Root HDL Optimized/Synchronous Subsystem/cordicSquareRootHDL/embmathops_c2_skVmLPFzLIK224pVNfQB1qF_cordicSquareRootHDL_controlled/embmathops_c2_skVmLPFzLIK224pVNfQB1qF_cordicSquareRootHDL', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/CORDIC Square Root HDL Optimized/Synchronous Subsystem/cordicSquareRootHDL/embmathops_c2_skVmLPFzLIK224pVNfQB1qF_cordicSquareRootHDL_controlled/embmathops_c2_skVmLPFzLIK224pVNfQB1qF_cordicSquareRootHDL', 0, 1, 'Blocks delay absorption: 2 cycles');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem Reference/CORDIC Square Root HDL Optimized/Synchronous Subsystem/cordicSquareRootHDL', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/CORDIC Square Root HDL Optimized/Synchronous Subsystem/cordicSquareRootHDL', 0, 1, 'Blocks delay absorption: 2 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/myRMS/CORDIC Square Root HDL Optimized/Synchronous Subsystem/cordicSquareRootHDL/embmathops_c2_svA684MOYugZkgHyA2vefIH_cordicSquareRootHDL_controlled/embmathops_c2_svA684MOYugZkgHyA2vefIH_cordicSquareRootHDL', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/myRMS/CORDIC Square Root HDL Optimized/Synchronous Subsystem/cordicSquareRootHDL/embmathops_c2_svA684MOYugZkgHyA2vefIH_cordicSquareRootHDL_controlled/embmathops_c2_svA684MOYugZkgHyA2vefIH_cordicSquareRootHDL', 0, 1, 'Blocks delay absorption: 2 cycles');
hilite_system('hdl_model_fixed/Subsystem1/myRMS/CORDIC Square Root HDL Optimized/Synchronous Subsystem/cordicSquareRootHDL', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/myRMS/CORDIC Square Root HDL Optimized/Synchronous Subsystem/cordicSquareRootHDL', 0, 1, 'Blocks delay absorption: 2 cycles');
