// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdl_model_fixed\RADIX22FFT_SDF1_7.v
// Created: 2024-12-20 21:02:02
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: RADIX22FFT_SDF1_7
// Source Path: hdl_model_fixed/Subsystem1/Subsystem/FFT/RADIX22FFT_SDF1_7
// Hierarchy Level: 3
// Model version: 1.105
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module RADIX22FFT_SDF1_7
          (clk,
           reset,
           enb,
           din_7_1_re_dly,
           din_7_1_im_dly,
           din_7_vld_dly,
           rd_7_Addr,
           rd_7_Enb,
           twdl_7_1_re,
           twdl_7_1_im,
           proc_7_enb,
           syncReset,
           dout_7_1_re,
           dout_7_1_im,
           dout_7_1_vld,
           dinXTwdl_7_1_vld);


  input   clk;
  input   reset;
  input   enb;
  input   signed [17:0] din_7_1_re_dly;  // sfix18_En11
  input   signed [17:0] din_7_1_im_dly;  // sfix18_En11
  input   din_7_vld_dly;
  input   [3:0] rd_7_Addr;  // ufix4
  input   rd_7_Enb;
  input   signed [11:0] twdl_7_1_re;  // sfix12_En10
  input   signed [11:0] twdl_7_1_im;  // sfix12_En10
  input   proc_7_enb;
  input   syncReset;
  output  signed [18:0] dout_7_1_re;  // sfix19_En11
  output  signed [18:0] dout_7_1_im;  // sfix19_En11
  output  dout_7_1_vld;
  output  dinXTwdl_7_1_vld;


  wire signed [18:0] din_re;  // sfix19_En11
  wire signed [18:0] din_im;  // sfix19_En11
  wire signed [18:0] dinXTwdl_re;  // sfix19_En11
  wire signed [18:0] dinXTwdl_im;  // sfix19_En11
  reg  x_vld;
  wire signed [18:0] wrData_im;  // sfix19_En11
  wire [3:0] wrAddr;  // ufix4
  wire wrEnb;
  wire signed [18:0] x_im;  // sfix19_En11
  wire signed [18:0] wrData_re;  // sfix19_En11
  wire signed [18:0] x_re;  // sfix19_En11
  reg signed [19:0] Radix22ButterflyG1_btf1_re_reg;  // sfix20
  reg signed [19:0] Radix22ButterflyG1_btf1_im_reg;  // sfix20
  reg signed [19:0] Radix22ButterflyG1_btf2_re_reg;  // sfix20
  reg signed [19:0] Radix22ButterflyG1_btf2_im_reg;  // sfix20
  reg signed [18:0] Radix22ButterflyG1_x_re_dly1;  // sfix19
  reg signed [18:0] Radix22ButterflyG1_x_im_dly1;  // sfix19
  reg  Radix22ButterflyG1_x_vld_dly1;
  reg signed [18:0] Radix22ButterflyG1_dinXtwdl_re_dly1;  // sfix19
  reg signed [18:0] Radix22ButterflyG1_dinXtwdl_im_dly1;  // sfix19
  reg signed [18:0] Radix22ButterflyG1_dinXtwdl_re_dly2;  // sfix19
  reg signed [18:0] Radix22ButterflyG1_dinXtwdl_im_dly2;  // sfix19
  reg  Radix22ButterflyG1_dinXtwdl_vld_dly1;
  reg  Radix22ButterflyG1_dinXtwdl_vld_dly2;
  wire signed [19:0] Radix22ButterflyG1_btf1_re_reg_next;  // sfix20_En11
  wire signed [19:0] Radix22ButterflyG1_btf1_im_reg_next;  // sfix20_En11
  wire signed [19:0] Radix22ButterflyG1_btf2_re_reg_next;  // sfix20_En11
  wire signed [19:0] Radix22ButterflyG1_btf2_im_reg_next;  // sfix20_En11
  wire signed [19:0] Radix22ButterflyG1_add_cast;  // sfix20_En11
  wire signed [19:0] Radix22ButterflyG1_add_cast_1;  // sfix20_En11
  wire signed [19:0] Radix22ButterflyG1_sub_cast;  // sfix20_En11
  wire signed [19:0] Radix22ButterflyG1_sub_cast_1;  // sfix20_En11
  wire signed [19:0] Radix22ButterflyG1_add_cast_2;  // sfix20_En11
  wire signed [19:0] Radix22ButterflyG1_add_cast_3;  // sfix20_En11
  wire signed [19:0] Radix22ButterflyG1_sub_cast_2;  // sfix20_En11
  wire signed [19:0] Radix22ButterflyG1_sub_cast_3;  // sfix20_En11
  reg signed [18:0] xf_re;  // sfix19_En11
  reg signed [18:0] xf_im;  // sfix19_En11
  reg  xf_vld;
  wire signed [18:0] dinXTwdlf_re;  // sfix19_En11
  wire signed [18:0] dinXTwdlf_im;  // sfix19_En11
  wire dinxTwdlf_vld;
  wire signed [18:0] btf1_re;  // sfix19_En11
  wire signed [18:0] btf1_im;  // sfix19_En11
  wire signed [18:0] btf2_re;  // sfix19_En11
  wire signed [18:0] btf2_im;  // sfix19_En11
  reg  btf_vld;


  assign din_re = {din_7_1_re_dly[17], din_7_1_re_dly};



  assign din_im = {din_7_1_im_dly[17], din_7_1_im_dly};



  Complex4Multiply_block1 MUL4_2 (.clk(clk),
                                  .reset(reset),
                                  .enb(enb),
                                  .din_re(din_re),  // sfix19_En11
                                  .din_im(din_im),  // sfix19_En11
                                  .din_7_vld_dly(din_7_vld_dly),
                                  .twdl_7_1_re(twdl_7_1_re),  // sfix12_En10
                                  .twdl_7_1_im(twdl_7_1_im),  // sfix12_En10
                                  .syncReset(syncReset),
                                  .dinXTwdl_re(dinXTwdl_re),  // sfix19_En11
                                  .dinXTwdl_im(dinXTwdl_im),  // sfix19_En11
                                  .dinXTwdl_7_1_vld(dinXTwdl_7_1_vld)
                                  );

  always @(posedge clk)
    begin : intdelay_process
      if (reset == 1'b1) begin
        x_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            x_vld <= 1'b0;
          end
          else begin
            x_vld <= rd_7_Enb;
          end
        end
      end
    end



  SimpleDualPortRAM_generic #(.AddrWidth(4),
                              .DataWidth(19)
                              )
                            dataMEM_im_0_7_1 (.clk(clk),
                                              .enb(enb),
                                              .wr_din(wrData_im),
                                              .wr_addr(wrAddr),
                                              .wr_en(wrEnb),
                                              .rd_addr(rd_7_Addr),
                                              .dout(x_im)
                                              );

  SimpleDualPortRAM_generic #(.AddrWidth(4),
                              .DataWidth(19)
                              )
                            dataMEM_re_0_7_1 (.clk(clk),
                                              .enb(enb),
                                              .wr_din(wrData_re),
                                              .wr_addr(wrAddr),
                                              .wr_en(wrEnb),
                                              .rd_addr(rd_7_Addr),
                                              .dout(x_re)
                                              );

  // Radix22ButterflyG1
  always @(posedge clk)
    begin : Radix22ButterflyG1_process
      if (reset == 1'b1) begin
        Radix22ButterflyG1_btf1_re_reg <= 20'sb00000000000000000000;
        Radix22ButterflyG1_btf1_im_reg <= 20'sb00000000000000000000;
        Radix22ButterflyG1_btf2_re_reg <= 20'sb00000000000000000000;
        Radix22ButterflyG1_btf2_im_reg <= 20'sb00000000000000000000;
        Radix22ButterflyG1_x_re_dly1 <= 19'sb0000000000000000000;
        Radix22ButterflyG1_x_im_dly1 <= 19'sb0000000000000000000;
        Radix22ButterflyG1_x_vld_dly1 <= 1'b0;
        xf_re <= 19'sb0000000000000000000;
        xf_im <= 19'sb0000000000000000000;
        xf_vld <= 1'b0;
        Radix22ButterflyG1_dinXtwdl_re_dly1 <= 19'sb0000000000000000000;
        Radix22ButterflyG1_dinXtwdl_im_dly1 <= 19'sb0000000000000000000;
        Radix22ButterflyG1_dinXtwdl_re_dly2 <= 19'sb0000000000000000000;
        Radix22ButterflyG1_dinXtwdl_im_dly2 <= 19'sb0000000000000000000;
        Radix22ButterflyG1_dinXtwdl_vld_dly1 <= 1'b0;
        Radix22ButterflyG1_dinXtwdl_vld_dly2 <= 1'b0;
        btf_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            Radix22ButterflyG1_btf1_re_reg <= 20'sb00000000000000000000;
            Radix22ButterflyG1_btf1_im_reg <= 20'sb00000000000000000000;
            Radix22ButterflyG1_btf2_re_reg <= 20'sb00000000000000000000;
            Radix22ButterflyG1_btf2_im_reg <= 20'sb00000000000000000000;
            Radix22ButterflyG1_x_re_dly1 <= 19'sb0000000000000000000;
            Radix22ButterflyG1_x_im_dly1 <= 19'sb0000000000000000000;
            Radix22ButterflyG1_x_vld_dly1 <= 1'b0;
            xf_re <= 19'sb0000000000000000000;
            xf_im <= 19'sb0000000000000000000;
            xf_vld <= 1'b0;
            Radix22ButterflyG1_dinXtwdl_re_dly1 <= 19'sb0000000000000000000;
            Radix22ButterflyG1_dinXtwdl_im_dly1 <= 19'sb0000000000000000000;
            Radix22ButterflyG1_dinXtwdl_re_dly2 <= 19'sb0000000000000000000;
            Radix22ButterflyG1_dinXtwdl_im_dly2 <= 19'sb0000000000000000000;
            Radix22ButterflyG1_dinXtwdl_vld_dly1 <= 1'b0;
            Radix22ButterflyG1_dinXtwdl_vld_dly2 <= 1'b0;
            btf_vld <= 1'b0;
          end
          else begin
            Radix22ButterflyG1_btf1_re_reg <= Radix22ButterflyG1_btf1_re_reg_next;
            Radix22ButterflyG1_btf1_im_reg <= Radix22ButterflyG1_btf1_im_reg_next;
            Radix22ButterflyG1_btf2_re_reg <= Radix22ButterflyG1_btf2_re_reg_next;
            Radix22ButterflyG1_btf2_im_reg <= Radix22ButterflyG1_btf2_im_reg_next;
            xf_re <= Radix22ButterflyG1_x_re_dly1;
            xf_im <= Radix22ButterflyG1_x_im_dly1;
            xf_vld <= Radix22ButterflyG1_x_vld_dly1;
            btf_vld <= Radix22ButterflyG1_dinXtwdl_vld_dly2;
            Radix22ButterflyG1_dinXtwdl_vld_dly2 <= Radix22ButterflyG1_dinXtwdl_vld_dly1;
            Radix22ButterflyG1_dinXtwdl_re_dly2 <= Radix22ButterflyG1_dinXtwdl_re_dly1;
            Radix22ButterflyG1_dinXtwdl_im_dly2 <= Radix22ButterflyG1_dinXtwdl_im_dly1;
            Radix22ButterflyG1_dinXtwdl_re_dly1 <= dinXTwdl_re;
            Radix22ButterflyG1_dinXtwdl_im_dly1 <= dinXTwdl_im;
            Radix22ButterflyG1_x_re_dly1 <= x_re;
            Radix22ButterflyG1_x_im_dly1 <= x_im;
            Radix22ButterflyG1_x_vld_dly1 <= x_vld;
            Radix22ButterflyG1_dinXtwdl_vld_dly1 <= proc_7_enb && dinXTwdl_7_1_vld;
          end
        end
      end
    end

  assign dinxTwdlf_vld = ( ! proc_7_enb) && dinXTwdl_7_1_vld;
  assign Radix22ButterflyG1_add_cast = {Radix22ButterflyG1_x_re_dly1[18], Radix22ButterflyG1_x_re_dly1};
  assign Radix22ButterflyG1_add_cast_1 = {Radix22ButterflyG1_dinXtwdl_re_dly2[18], 
    Radix22ButterflyG1_dinXtwdl_re_dly2};
  assign Radix22ButterflyG1_btf1_re_reg_next = Radix22ButterflyG1_add_cast + Radix22ButterflyG1_add_cast_1;
  assign Radix22ButterflyG1_sub_cast = {Radix22ButterflyG1_x_re_dly1[18], Radix22ButterflyG1_x_re_dly1};
  assign Radix22ButterflyG1_sub_cast_1 = {Radix22ButterflyG1_dinXtwdl_re_dly2[18], 
    Radix22ButterflyG1_dinXtwdl_re_dly2};
  assign Radix22ButterflyG1_btf2_re_reg_next = Radix22ButterflyG1_sub_cast - Radix22ButterflyG1_sub_cast_1;
  assign Radix22ButterflyG1_add_cast_2 = {Radix22ButterflyG1_x_im_dly1[18], Radix22ButterflyG1_x_im_dly1};
  assign Radix22ButterflyG1_add_cast_3 = {Radix22ButterflyG1_dinXtwdl_im_dly2[18], 
    Radix22ButterflyG1_dinXtwdl_im_dly2};
  assign Radix22ButterflyG1_btf1_im_reg_next = Radix22ButterflyG1_add_cast_2 + Radix22ButterflyG1_add_cast_3;
  assign Radix22ButterflyG1_sub_cast_2 = {Radix22ButterflyG1_x_im_dly1[18], Radix22ButterflyG1_x_im_dly1};
  assign Radix22ButterflyG1_sub_cast_3 = {Radix22ButterflyG1_dinXtwdl_im_dly2[18], 
    Radix22ButterflyG1_dinXtwdl_im_dly2};
  assign Radix22ButterflyG1_btf2_im_reg_next = Radix22ButterflyG1_sub_cast_2 - Radix22ButterflyG1_sub_cast_3;
  assign dinXTwdlf_re = dinXTwdl_re;
  assign dinXTwdlf_im = dinXTwdl_im;
  assign btf1_re = Radix22ButterflyG1_btf1_re_reg[18:0];
  assign btf1_im = Radix22ButterflyG1_btf1_im_reg[18:0];
  assign btf2_re = Radix22ButterflyG1_btf2_re_reg[18:0];
  assign btf2_im = Radix22ButterflyG1_btf2_im_reg[18:0];



  SDFCommutator7 SDFCOMMUTATOR_7_1 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .din_7_vld_dly(din_7_vld_dly),
                                    .xf_re(xf_re),  // sfix19_En11
                                    .xf_im(xf_im),  // sfix19_En11
                                    .xf_vld(xf_vld),
                                    .dinXTwdlf_re(dinXTwdlf_re),  // sfix19_En11
                                    .dinXTwdlf_im(dinXTwdlf_im),  // sfix19_En11
                                    .dinxTwdlf_vld(dinxTwdlf_vld),
                                    .btf1_re(btf1_re),  // sfix19_En11
                                    .btf1_im(btf1_im),  // sfix19_En11
                                    .btf2_re(btf2_re),  // sfix19_En11
                                    .btf2_im(btf2_im),  // sfix19_En11
                                    .btf_vld(btf_vld),
                                    .syncReset(syncReset),
                                    .wrData_re(wrData_re),  // sfix19_En11
                                    .wrData_im(wrData_im),  // sfix19_En11
                                    .wrAddr(wrAddr),  // ufix4
                                    .wrEnb(wrEnb),
                                    .dout_7_1_re(dout_7_1_re),  // sfix19_En11
                                    .dout_7_1_im(dout_7_1_im),  // sfix19_En11
                                    .dout_7_1_vld(dout_7_1_vld)
                                    );

endmodule  // RADIX22FFT_SDF1_7

