// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdl_model_fixed\Real_Divide_HDL_Optimized.v
// Created: 2024-12-20 21:02:03
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Real_Divide_HDL_Optimized
// Source Path: hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized
// Hierarchy Level: 2
// Model version: 1.105
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Real_Divide_HDL_Optimized
          (clk,
           reset,
           enb,
           num,
           den,
           validIn,
           y_y,
           validOut);


  input   clk;
  input   reset;
  input   enb;
  input   signed [16:0] num;  // sfix17_En14
  input   signed [16:0] den;  // sfix17_En14
  input   validIn;
  output  signed [17:0] y_y;  // sfix18_En10
  output  validOut;


  wire signed [16:0] den_1;  // sfix17_En14
  wire signed [16:0] num_1;  // sfix17_En14
  wire signed [17:0] ForEach_Real_Divide_out1;  // sfix18_En10
  wire ForEach_Real_Divide_out2;
  wire signed [17:0] z_z;  // sfix18_En10
  reg  [3:0] rd_0_reg;  // ufix1 [4]
  wire ForEach_Real_Divide_out2_1;
  wire y_y_1;


  Verify_divide_sizes Verify_divide_sizes_1_1 (.clk(clk),
                                               .reset(reset),
                                               .enb(enb),
                                               .denominator(den),  // sfix17_En14
                                               .numerator(num),  // sfix17_En14
                                               .den(den_1),  // sfix17_En14
                                               .num(num_1)  // sfix17_En14
                                               );

  ForEach_Real_Divide ForEach_Real_Divide_instance (.clk(clk),
                                                    .reset(reset),
                                                    .enb(enb),
                                                    .den(den_1),  // sfix17_En14
                                                    .num(num_1),  // sfix17_En14
                                                    .validIn(validIn),
                                                    .y_y(ForEach_Real_Divide_out1),  // sfix18_En10
                                                    .validOut(ForEach_Real_Divide_out2)
                                                    );

  Reshape_to_original_size Reshape_to_original_size_1_1 (.y_y(ForEach_Real_Divide_out1),  // sfix18_En10
                                                         .u_u(num),  // sfix17_En14
                                                         .z_z(z_z)  // sfix18_En10
                                                         );

  assign y_y = z_z;

  always @(posedge clk)
    begin : rd_0_process
      if (reset == 1'b1) begin
        rd_0_reg <= {4{1'b0}};
      end
      else begin
        if (enb) begin
          rd_0_reg[0] <= ForEach_Real_Divide_out2;
          rd_0_reg[32'sd3:32'sd1] <= rd_0_reg[32'sd2:32'sd0];
        end
      end
    end

  assign ForEach_Real_Divide_out2_1 = rd_0_reg[3];



  y_u_1 y_u_1_1_1 (.u_u(ForEach_Real_Divide_out2_1),
                   .y_y(y_y_1)
                   );

  assign validOut = y_y_1;

endmodule  // Real_Divide_HDL_Optimized

