// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdl_model_fixed\Reshape_to_original_size.v
// Created: 2024-12-20 21:02:03
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Reshape_to_original_size

// Source Path: hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/Reshape to original size
// Hierarchy Level: 3
// Model version: 1.105
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Reshape_to_original_size
          (y_y,
           u_u,
           z_z);


  input   signed [17:0] y_y;  // sfix18_En10
  input   signed [16:0] u_u;  // sfix17_En14
  output  signed [17:0] z_z;  // sfix18_En10




  assign z_z = y_y;



endmodule  // Reshape_to_original_size

