-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\hdl_model_fixed\Reshape_to_original_size.vhd
-- Created: 2024-12-15 20:50:14
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Reshape_to_original_size
-- Source Path: hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/Reshape to original size
-- Hierarchy Level: 3
-- Model version: 1.30
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Reshape_to_original_size IS
  PORT( y                                 :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        u                                 :   IN    std_logic_vector(21 DOWNTO 0);  -- sfix22_En20
        z                                 :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En15
        );
END Reshape_to_original_size;


ARCHITECTURE rtl OF Reshape_to_original_size IS

  -- Signals
  SIGNAL y_signed                         : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL u_signed                         : signed(21 DOWNTO 0);  -- sfix22_En20
  SIGNAL z_tmp                            : signed(15 DOWNTO 0);  -- sfix16_En15

BEGIN
  y_signed <= signed(y);

  u_signed <= signed(u);

  z_tmp <= y_signed;

  z <= std_logic_vector(z_tmp);

END rtl;

