-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\hdl_model_fixed\Select_Freq.vhd
-- Created: 2024-12-15 20:50:14
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Select_Freq
-- Source Path: hdl_model_fixed/Subsystem1/Subsystem Reference/Select_Freq
-- Hierarchy Level: 2
-- Model version: 1.30
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Select_Freq IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_25_0                        :   IN    std_logic;
        enb                               :   IN    std_logic;
        Out1                              :   OUT   std_logic
        );
END Select_Freq;


ARCHITECTURE rtl OF Select_Freq IS

  -- Signals
  SIGNAL NOT_out1                         : std_logic;
  SIGNAL count_step                       : unsigned(11 DOWNTO 0);  -- ufix12
  SIGNAL count_from                       : unsigned(11 DOWNTO 0);  -- ufix12
  SIGNAL count_reset                      : unsigned(11 DOWNTO 0);  -- ufix12
  SIGNAL HDL_Counter_out1                 : unsigned(11 DOWNTO 0);  -- ufix12
  SIGNAL count                            : unsigned(11 DOWNTO 0);  -- ufix12
  SIGNAL need_to_wrap                     : std_logic;
  SIGNAL count_value                      : unsigned(11 DOWNTO 0);  -- ufix12
  SIGNAL count_1                          : unsigned(11 DOWNTO 0);  -- ufix12
  SIGNAL count_2                          : unsigned(11 DOWNTO 0);  -- ufix12
  SIGNAL switch_compare_1                 : std_logic;
  SIGNAL Constant_out1                    : std_logic;
  SIGNAL Constant1_out1                   : std_logic;
  SIGNAL Switch_out1                      : std_logic;
  SIGNAL switch_compare_1_1               : std_logic;
  SIGNAL Switch1_out1                     : std_logic;
  SIGNAL AND_out1                         : std_logic;

BEGIN
  NOT_out1 <=  NOT enb;

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 2048
  count_step <= to_unsigned(16#001#, 12);

  count_from <= to_unsigned(16#000#, 12);

  count_reset <= to_unsigned(16#000#, 12);

  count <= HDL_Counter_out1 + count_step;

  
  need_to_wrap <= '1' WHEN HDL_Counter_out1 = to_unsigned(16#800#, 12) ELSE
      '0';

  
  count_value <= count WHEN need_to_wrap = '0' ELSE
      count_from;

  
  count_1 <= HDL_Counter_out1 WHEN enb = '0' ELSE
      count_value;

  
  count_2 <= count_1 WHEN NOT_out1 = '0' ELSE
      count_reset;

  HDL_Counter_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      HDL_Counter_out1 <= to_unsigned(16#000#, 12);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_25_0 = '1' THEN
        HDL_Counter_out1 <= count_2;
      END IF;
    END IF;
  END PROCESS HDL_Counter_process;


  
  switch_compare_1 <= '1' WHEN HDL_Counter_out1 > to_unsigned(16#009#, 12) ELSE
      '0';

  Constant_out1 <= '0';

  Constant1_out1 <= '1';

  
  Switch_out1 <= Constant_out1 WHEN switch_compare_1 = '0' ELSE
      Constant1_out1;

  
  switch_compare_1_1 <= '1' WHEN HDL_Counter_out1 > to_unsigned(16#400#, 12) ELSE
      '0';

  
  Switch1_out1 <= Constant1_out1 WHEN switch_compare_1_1 = '0' ELSE
      Constant_out1;

  AND_out1 <= Switch_out1 AND Switch1_out1;

  Out1 <= AND_out1;

END rtl;

