// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdl_model_fixed\Subsystem_ip2_src_Bit_Shift.v
// Created: 2024-12-21 15:37:35
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_ip2_src_Bit_Shift

// Source Path: hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex/CORDIC Square Root HDL Optimized1/Bit 
// Shift Arithmeti
// Hierarchy Level: 4
// Model version: 1.113
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_ip2_src_Bit_Shift
          (u_u,
           e_e,
           isZero,
           y_y);


  input   signed [23:0] u_u;  // sfix24_En22
  input   signed [31:0] e_e;  // int32
  input   isZero;
  output  signed [23:0] y_y;  // sfix24_En22


  reg signed [23:0] y_y_1;  // sfix24_En22
  reg signed [31:0] yfi;  // sfix32
  reg signed [32:0] t_0;  // sfix33
  reg signed [32:0] t_1;  // sfix33


  always @(e_e, isZero, u_u) begin
    t_0 = 33'sh000000000;
    t_1 = 33'sh000000000;
    yfi = 32'sb00000000000000000000000000000000;
    if (isZero) begin
      y_y_1 = 24'sb000000000000000000000000;
    end
    else if (e_e < 32'sb00000000000000000000000000000000) begin
      t_1 = {e_e[31], e_e};
      t_0 =  - (t_1);
      yfi = t_0[31:0];
      y_y_1 = u_u <<< yfi;
    end
    else begin
      y_y_1 = u_u >>> e_e;
    end
  end



  assign y_y = y_y_1;

endmodule  // Subsystem_ip2_src_Bit_Shift

