-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\hdl_model_fixed\Subsystem_ip_src_Synchronous_Subsystem.vhd
-- Created: 2024-12-15 16:17:57
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Subsystem_ip_src_Synchronous_Subsystem
-- Source Path: hdl_model_fixed/Subsystem1/Subsystem Reference/CORDIC Square Root HDL Optimized/Synchronous Subsystem
-- Hierarchy Level: 3
-- Model version: 1.22
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Subsystem_ip_src_Synchronous_Subsystem IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_25_0                        :   IN    std_logic;
        u                                 :   IN    std_logic_vector(21 DOWNTO 0);  -- sfix22_En11
        validIn                           :   IN    std_logic;
        restart                           :   IN    std_logic;
        dataOut                           :   OUT   std_logic_vector(21 DOWNTO 0);  -- sfix22_En20
        eOut                              :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
        isZero                            :   OUT   std_logic;
        validOut                          :   OUT   std_logic
        );
END Subsystem_ip_src_Synchronous_Subsystem;


ARCHITECTURE rtl OF Subsystem_ip_src_Synchronous_Subsystem IS

  -- Component Declarations
  COMPONENT Subsystem_ip_src_cordicSquareRootHDL
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_25_0                      :   IN    std_logic;
          u                               :   IN    std_logic_vector(21 DOWNTO 0);  -- sfix22_En11
          validIn                         :   IN    std_logic;
          restart                         :   IN    std_logic;
          dataOut                         :   OUT   std_logic_vector(21 DOWNTO 0);  -- sfix22_En20
          eOut                            :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
          isZero                          :   OUT   std_logic;
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Subsystem_ip_src_cordicSquareRootHDL
    USE ENTITY work.Subsystem_ip_src_cordicSquareRootHDL(rtl);

  -- Signals
  SIGNAL dataOut_tmp                      : std_logic_vector(21 DOWNTO 0);  -- ufix22
  SIGNAL eOut_tmp                         : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_cordicSquareRootHDL : Subsystem_ip_src_cordicSquareRootHDL
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_25_0 => enb_1_25_0,
              u => u,  -- sfix22_En11
              validIn => validIn,
              restart => restart,
              dataOut => dataOut_tmp,  -- sfix22_En20
              eOut => eOut_tmp,  -- int32
              isZero => isZero,
              validOut => validOut
              );

  dataOut <= dataOut_tmp;

  eOut <= eOut_tmp;

END rtl;

