// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdl_model_fixed\Subsystem_ip2_src_Synchronous_Subsystem.v
// Created: 2024-12-16 17:45:39
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_ip2_src_Synchronous_Subsystem
// Source Path: hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex/CORDIC Square Root HDL Optimized1/Synchronous 
// Subsyste
// Hierarchy Level: 4
// Model version: 1.56
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_ip2_src_Synchronous_Subsystem
          (clk,
           reset,
           enb,
           enb_1_2_0,
           enb_1_2_1,
           u,
           validIn,
           restart,
           dataOut,
           eOut,
           isZero,
           validOut);


  input   clk;
  input   reset;
  input   enb;
  input   enb_1_2_0;
  input   enb_1_2_1;
  input   signed [23:0] u;  // sfix24_En22
  input   validIn;
  input   restart;
  output  signed [23:0] dataOut;  // sfix24_En22
  output  signed [31:0] eOut;  // int32
  output  isZero;
  output  validOut;




  Subsystem_ip2_src_cordicSquareRootHDL u_cordicSquareRootHDL (.clk(clk),
                                                               .reset(reset),
                                                               .enb(enb),
                                                               .enb_1_2_0(enb_1_2_0),
                                                               .enb_1_2_1(enb_1_2_1),
                                                               .u(u),  // sfix24_En22
                                                               .validIn(validIn),
                                                               .restart(restart),
                                                               .dataOut(dataOut),  // sfix24_En22
                                                               .eOut(eOut),  // int32
                                                               .isZero(isZero),
                                                               .validOut(validOut)
                                                               );

endmodule  // Subsystem_ip2_src_Synchronous_Subsystem

