-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\hdl_model_fixed\Subsystem_Reference.vhd
-- Created: 2024-12-15 20:50:14
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Subsystem_Reference
-- Source Path: hdl_model_fixed/Subsystem1/Subsystem Reference
-- Hierarchy Level: 1
-- Model version: 1.30
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Subsystem_Reference IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_25_0                        :   IN    std_logic;
        FFT_In_re                         :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12_En11
        FFT_In_im                         :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12_En11
        Valid_In                          :   IN    std_logic;
        reset_1                           :   IN    std_logic;
        THD                               :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        valid_out                         :   OUT   std_logic
        );
END Subsystem_Reference;


ARCHITECTURE rtl OF Subsystem_Reference IS

  -- Component Declarations
  COMPONENT Absolute_of_Complex
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_25_0                      :   IN    std_logic;
          In1_re                          :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12_En11
          In1_im                          :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12_En11
          validIn                         :   IN    std_logic;
          restart                         :   IN    std_logic;
          y                               :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT Select_Freq
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_25_0                      :   IN    std_logic;
          enb                             :   IN    std_logic;
          Out1                            :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT Sample_and_Hold2_block1
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_25_0                      :   IN    std_logic;
          In_rsvd                         :   IN    std_logic_vector(21 DOWNTO 0);  -- sfix22_En20
          Trigger                         :   IN    std_logic;
          alpha                           :   OUT   std_logic_vector(21 DOWNTO 0)  -- sfix22_En20
          );
  END COMPONENT;

  COMPONENT CORDIC_Square_Root_HDL_Optimized
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_25_0                      :   IN    std_logic;
          u                               :   IN    std_logic_vector(21 DOWNTO 0);  -- sfix22_En20
          validIn                         :   IN    std_logic;
          restart                         :   IN    std_logic;
          y                               :   OUT   std_logic_vector(21 DOWNTO 0);  -- sfix22_En20
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT Sample_and_Hold_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_25_0                      :   IN    std_logic;
          In_rsvd                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          Trigger                         :   IN    std_logic;
          alpha                           :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
          );
  END COMPONENT;

  COMPONENT Real_Divide_HDL_Optimized
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_25_0                      :   IN    std_logic;
          num                             :   IN    std_logic_vector(21 DOWNTO 0);  -- sfix22_En20
          den                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          validIn                         :   IN    std_logic;
          y                               :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT Sample_and_Hold2_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_25_0                      :   IN    std_logic;
          In_rsvd                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          Trigger                         :   IN    std_logic;
          alpha                           :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En15
          );
  END COMPONENT;

  COMPONENT S_R_Flip_Flop_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_25_0                      :   IN    std_logic;
          in1                             :   IN    std_logic;
          in2                             :   IN    std_logic;
          out1                            :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Absolute_of_Complex
    USE ENTITY work.Absolute_of_Complex(rtl);

  FOR ALL : Select_Freq
    USE ENTITY work.Select_Freq(rtl);

  FOR ALL : Sample_and_Hold2_block1
    USE ENTITY work.Sample_and_Hold2_block1(rtl);

  FOR ALL : CORDIC_Square_Root_HDL_Optimized
    USE ENTITY work.CORDIC_Square_Root_HDL_Optimized(rtl);

  FOR ALL : Sample_and_Hold_block
    USE ENTITY work.Sample_and_Hold_block(rtl);

  FOR ALL : Real_Divide_HDL_Optimized
    USE ENTITY work.Real_Divide_HDL_Optimized(rtl);

  FOR ALL : Sample_and_Hold2_block
    USE ENTITY work.Sample_and_Hold2_block(rtl);

  FOR ALL : S_R_Flip_Flop_block
    USE ENTITY work.S_R_Flip_Flop_block(rtl);

  -- Signals
  SIGNAL Absolute_of_Complex_out1         : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL validOut                         : std_logic;
  SIGNAL Select_Freq_out1                 : std_logic;
  SIGNAL Multiply_Accumulate_counter_out  : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL s                                : std_logic;
  SIGNAL Multiply_Accumulate_and1_out     : std_logic;
  SIGNAL switch_compare_1                 : std_logic;
  SIGNAL s_1                              : signed(21 DOWNTO 0);  -- sfix22_En20
  SIGNAL Multiply_Accumulate_not1_out     : std_logic;
  SIGNAL switch_compare_1_1               : std_logic;
  SIGNAL Absolute_of_Complex_out1_signed  : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL s_2                              : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Multiply_Accumulate_input_mux_out : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Multiply_Accumulate_multiply_out : signed(31 DOWNTO 0);  -- sfix32_En28
  SIGNAL Multiply_Accumulate_out1         : signed(21 DOWNTO 0);  -- sfix22_En20
  SIGNAL Multiply_Accumulate_add_fb_in    : signed(21 DOWNTO 0);  -- sfix22_En20
  SIGNAL Multiply_Accumulate_add_add_cast : signed(32 DOWNTO 0);  -- sfix33_En28
  SIGNAL Multiply_Accumulate_add_add_cast_1 : signed(32 DOWNTO 0);  -- sfix33_En28
  SIGNAL Multiply_Accumulate_add_add_temp : signed(32 DOWNTO 0);  -- sfix33_En28
  SIGNAL Multiply_Accumulate_multiplyAdd_out : signed(21 DOWNTO 0);  -- sfix22_En20
  SIGNAL s_3                              : std_logic;
  SIGNAL Multiply_Accumulate_and2_out     : std_logic;
  SIGNAL Multiply_Accumulate_out2         : std_logic;
  SIGNAL Multiply_Accumulate_out3         : std_logic;
  SIGNAL AND_out1                         : std_logic;
  SIGNAL Sample_and_Hold2_out1            : std_logic_vector(21 DOWNTO 0);  -- ufix22
  SIGNAL CORDIC_Square_Root_HDL_Optimized_out1 : std_logic_vector(21 DOWNTO 0);  -- ufix22
  SIGNAL validOut_1                       : std_logic;
  SIGNAL Delay_reg                        : std_logic_vector(7 DOWNTO 0);  -- ufix1 [8]
  SIGNAL Delay_out1                       : std_logic;
  SIGNAL Sample_and_Hold_out1             : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Real_Divide_HDL_Optimized_out1   : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Real_Divide_HDL_Optimized_out2   : std_logic;
  SIGNAL Sample_and_Hold1_out1            : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL S_R_Flip_Flop_out1               : std_logic;

  ATTRIBUTE use_dsp : string;

  ATTRIBUTE use_dsp OF Multiply_Accumulate_multiply_out : SIGNAL IS "yes";

BEGIN
  u_Absolute_of_Complex : Absolute_of_Complex
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_25_0 => enb_1_25_0,
              In1_re => FFT_In_re,  -- sfix12_En11
              In1_im => FFT_In_im,  -- sfix12_En11
              validIn => Valid_In,
              restart => reset_1,
              y => Absolute_of_Complex_out1,  -- sfix16_En14
              validOut => validOut
              );

  u_Select_Freq : Select_Freq
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_25_0 => enb_1_25_0,
              enb => validOut,
              Out1 => Select_Freq_out1
              );

  u_Sample_and_Hold2 : Sample_and_Hold2_block1
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_25_0 => enb_1_25_0,
              In_rsvd => std_logic_vector(Multiply_Accumulate_out1),  -- sfix22_En20
              Trigger => AND_out1,
              alpha => Sample_and_Hold2_out1  -- sfix22_En20
              );

  u_CORDIC_Square_Root_HDL_Optimized : CORDIC_Square_Root_HDL_Optimized
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_25_0 => enb_1_25_0,
              u => Sample_and_Hold2_out1,  -- sfix22_En20
              validIn => AND_out1,
              restart => reset_1,
              y => CORDIC_Square_Root_HDL_Optimized_out1,  -- sfix22_En20
              validOut => validOut_1
              );

  u_Sample_and_Hold : Sample_and_Hold_block
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_25_0 => enb_1_25_0,
              In_rsvd => Absolute_of_Complex_out1,  -- sfix16_En14
              Trigger => Delay_out1,
              alpha => Sample_and_Hold_out1  -- sfix16_En14
              );

  u_Real_Divide_HDL_Optimized : Real_Divide_HDL_Optimized
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_25_0 => enb_1_25_0,
              num => CORDIC_Square_Root_HDL_Optimized_out1,  -- sfix22_En20
              den => Sample_and_Hold_out1,  -- sfix16_En14
              validIn => validOut_1,
              y => Real_Divide_HDL_Optimized_out1,  -- sfix16_En15
              validOut => Real_Divide_HDL_Optimized_out2
              );

  u_Sample_and_Hold1 : Sample_and_Hold2_block
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_25_0 => enb_1_25_0,
              In_rsvd => Real_Divide_HDL_Optimized_out1,  -- sfix16_En15
              Trigger => Real_Divide_HDL_Optimized_out2,
              alpha => Sample_and_Hold1_out1  -- sfix16_En15
              );

  u_S_R_Flip_Flop_inst : S_R_Flip_Flop_block
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_25_0 => enb_1_25_0,
              in1 => Real_Divide_HDL_Optimized_out2,
              in2 => reset_1,
              out1 => S_R_Flip_Flop_out1
              );

  -- Count limited, Unsigned Counter
  --  initial value   = 1
  --  step value      = 1
  --  count to value  = 1015
  Multiply_Accumulate_counter_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Multiply_Accumulate_counter_out <= to_unsigned(16#001#, 10);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_25_0 = '1' THEN
        IF Select_Freq_out1 = '1' THEN 
          IF Multiply_Accumulate_counter_out >= to_unsigned(16#3F7#, 10) THEN 
            Multiply_Accumulate_counter_out <= to_unsigned(16#001#, 10);
          ELSE 
            Multiply_Accumulate_counter_out <= Multiply_Accumulate_counter_out + to_unsigned(16#001#, 10);
          END IF;
        END IF;
      END IF;
    END IF;
  END PROCESS Multiply_Accumulate_counter_process;


  
  s <= '1' WHEN Multiply_Accumulate_counter_out = to_unsigned(16#001#, 10) ELSE
      '0';

  Multiply_Accumulate_and1_out <= Select_Freq_out1 AND s;

  
  switch_compare_1 <= '1' WHEN Multiply_Accumulate_and1_out > '0' ELSE
      '0';

  s_1 <= to_signed(16#000000#, 22);

  Multiply_Accumulate_not1_out <=  NOT Select_Freq_out1;

  
  switch_compare_1_1 <= '1' WHEN Multiply_Accumulate_not1_out > '0' ELSE
      '0';

  Absolute_of_Complex_out1_signed <= signed(Absolute_of_Complex_out1);

  s_2 <= to_signed(16#0000#, 16);

  
  Multiply_Accumulate_input_mux_out <= Absolute_of_Complex_out1_signed WHEN switch_compare_1_1 = '0' ELSE
      s_2;

  Multiply_Accumulate_multiply_out <= Multiply_Accumulate_input_mux_out * Absolute_of_Complex_out1_signed;

  
  Multiply_Accumulate_add_fb_in <= Multiply_Accumulate_out1 WHEN switch_compare_1 = '0' ELSE
      s_1;

  Multiply_Accumulate_add_add_cast <= resize(Multiply_Accumulate_add_fb_in & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 33);
  Multiply_Accumulate_add_add_cast_1 <= resize(Multiply_Accumulate_multiply_out, 33);
  Multiply_Accumulate_add_add_temp <= Multiply_Accumulate_add_add_cast + Multiply_Accumulate_add_add_cast_1;
  Multiply_Accumulate_multiplyAdd_out <= Multiply_Accumulate_add_add_temp(29 DOWNTO 8);

  Multiply_Accumulate_delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Multiply_Accumulate_out1 <= to_signed(16#000000#, 22);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_25_0 = '1' THEN
        Multiply_Accumulate_out1 <= Multiply_Accumulate_multiplyAdd_out;
      END IF;
    END IF;
  END PROCESS Multiply_Accumulate_delay_process;


  
  s_3 <= '1' WHEN Multiply_Accumulate_counter_out = to_unsigned(16#3F7#, 10) ELSE
      '0';

  Multiply_Accumulate_and2_out <= Select_Freq_out1 AND s_3;

  Multiply_Accumulate_delay_endout_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Multiply_Accumulate_out2 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_25_0 = '1' THEN
        Multiply_Accumulate_out2 <= Multiply_Accumulate_and2_out;
      END IF;
    END IF;
  END PROCESS Multiply_Accumulate_delay_endout_process;


  Multiply_Accumulate_delay_validout_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Multiply_Accumulate_out3 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_25_0 = '1' THEN
        Multiply_Accumulate_out3 <= Select_Freq_out1;
      END IF;
    END IF;
  END PROCESS Multiply_Accumulate_delay_validout_process;


  AND_out1 <= Multiply_Accumulate_out2 AND Multiply_Accumulate_out3;

  Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_25_0 = '1' THEN
        Delay_reg(0) <= validOut;
        Delay_reg(7 DOWNTO 1) <= Delay_reg(6 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS Delay_process;

  Delay_out1 <= Delay_reg(7);

  THD <= Sample_and_Hold1_out1;

  valid_out <= S_R_Flip_Flop_out1;

END rtl;

