// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdl_model_fixed\Subsystem_ip2_src_BUF_MIN_MA.v
// Created: 2024-12-21 15:37:35
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_ip2_src_BUF_MIN_MA
// Source Path: hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG
// Hierarchy Level: 1
// Model version: 1.113
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_ip2_src_BUF_MIN_MA
          (clk,
           reset,
           enb,
           data,
           validIn,
           Max_rsvd,
           Min_rsvd,
           ValidOut);


  input   clk;
  input   reset;
  input   enb;
  input   signed [11:0] data;  // sfix12_En11
  input   validIn;
  output  signed [11:0] Max_rsvd;  // sfix12_En11
  output  signed [11:0] Min_rsvd;  // sfix12_En11
  output  ValidOut;


  wire NOT_out1;
  wire signed [11:0] max_out;  // sfix12_En11
  reg signed [11:0] Delay_out1;  // sfix12_En11
  wire signed [11:0] Sample_and_Hold1_out1;  // sfix12_En11
  wire signed [11:0] max_rsvd_1;  // sfix12_En11
  wire signed [11:0] min_out;  // sfix12_En11
  reg signed [11:0] Delay1_out1;  // sfix12_En11
  wire signed [11:0] Sample_and_Hold2_out1;  // sfix12_En11
  wire Detect_Decrease1_out1;
  wire Detect_Increase_out1;
  wire S_R_Flip_Flop_out1;


  assign NOT_out1 =  ~ validIn;



  Subsystem_ip2_src_MATLAB_Fun_block MATLAB_Function1_1 (.clk(clk),
                                                         .reset(reset),
                                                         .enb(enb),
                                                         .input_data(data),  // sfix12_En11
                                                         .reset_1(NOT_out1),
                                                         .max_out(max_out)  // sfix12_En11
                                                         );

  always @(posedge clk)
    begin : Delay_rsvd_process
      if (reset == 1'b1) begin
        Delay_out1 <= 12'sb000000000000;
      end
      else begin
        if (enb) begin
          Delay_out1 <= max_out;
        end
      end
    end



  Subsystem_ip2_src_Sample_and Sample_and_Hold1_1 (.clk(clk),
                                                   .reset(reset),
                                                   .enb(enb),
                                                   .In_rsvd(Delay_out1),  // sfix12_En11
                                                   .Trigger_rsvd(validIn),
                                                   .alpha(Sample_and_Hold1_out1)  // sfix12_En11
                                                   );

  assign Max_rsvd = Sample_and_Hold1_out1;

  assign max_rsvd_1 = data;

  Subsystem_ip2_src_MATLAB_Fun MATLAB_Function_1 (.clk(clk),
                                                  .reset(reset),
                                                  .enb(enb),
                                                  .input_data(max_rsvd_1),  // sfix12_En11
                                                  .reset_1(NOT_out1),
                                                  .min_out(min_out)  // sfix12_En11
                                                  );

  always @(posedge clk)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1 <= 12'sb000000000000;
      end
      else begin
        if (enb) begin
          Delay1_out1 <= min_out;
        end
      end
    end



  Subsystem_ip2_src_Sample_and Sample_and_Hold2_1 (.clk(clk),
                                                   .reset(reset),
                                                   .enb(enb),
                                                   .In_rsvd(Delay1_out1),  // sfix12_En11
                                                   .Trigger_rsvd(validIn),
                                                   .alpha(Sample_and_Hold2_out1)  // sfix12_En11
                                                   );

  assign Min_rsvd = Sample_and_Hold2_out1;

  Subsystem_ip2_src_Detect_Dec Detect_Decrease1_1 (.clk(clk),
                                                   .reset(reset),
                                                   .enb(enb),
                                                   .U_U(validIn),
                                                   .Y_Y(Detect_Decrease1_out1)
                                                   );

  Subsystem_ip2_src_Detect_Inc Detect_Increase_1 (.clk(clk),
                                                  .reset(reset),
                                                  .enb(enb),
                                                  .U_U(validIn),
                                                  .Y_Y(Detect_Increase_out1)
                                                  );

  Subsystem_ip2_src_S_R_Flip_F S_R_Flip_Flop_inst_1 (.clk(clk),
                                                     .reset(reset),
                                                     .enb(enb),
                                                     .in1(Detect_Decrease1_out1),
                                                     .in2(Detect_Increase_out1),
                                                     .out1(S_R_Flip_Flop_out1)
                                                     );

  assign ValidOut = S_R_Flip_Flop_out1;

endmodule  // Subsystem_ip2_src_BUF_MIN_MA

