-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\hdl_model_fixed\Subsystem_ip_src_S_R_Flip_Flop_block1.vhd
-- Created: 2024-12-15 16:17:57
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Subsystem_ip_src_S_R_Flip_Flop_block1
-- Source Path: hdl_model_fixed/Subsystem1/myRMS/S-R Flip Flop
-- Hierarchy Level: 2
-- Model version: 1.22
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.Subsystem_ip_src_Subsystem1_pkg.ALL;

ENTITY Subsystem_ip_src_S_R_Flip_Flop_block1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_25_0                        :   IN    std_logic;
        in1                               :   IN    std_logic;
        in2                               :   IN    std_logic;
        out1                              :   OUT   std_logic
        );
END Subsystem_ip_src_S_R_Flip_Flop_block1;


ARCHITECTURE rtl OF Subsystem_ip_src_S_R_Flip_Flop_block1 IS

  -- Constants
  CONSTANT S_R_Flip_FlopDirect_Lookup_Table_data : vector_of_unsigned3(0 TO 7) := 
    (to_unsigned(16#1#, 3), to_unsigned(16#2#, 3), to_unsigned(16#1#, 3), to_unsigned(16#1#, 3),
     to_unsigned(16#2#, 3), to_unsigned(16#2#, 3), to_unsigned(16#0#, 3), to_unsigned(16#0#, 3));  -- ufix3 [8]

  -- Signals
  SIGNAL out1_1                           : std_logic;
  SIGNAL Previous_Q                       : std_logic;
  SIGNAL InpCombined                      : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL OutCombined                      : unsigned(2 DOWNTO 0);  -- ufix3

BEGIN
  S_R_Flip_Flop_memory_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Previous_Q <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_25_0 = '1' THEN
        Previous_Q <= out1_1;
      END IF;
    END IF;
  END PROCESS S_R_Flip_Flop_memory_process;


  InpCombined <= unsigned'(in1 & in2 & Previous_Q);

  OutCombined <= S_R_Flip_FlopDirect_Lookup_Table_data(to_integer(InpCombined));

  out1_1 <= OutCombined(1);

  out1 <= out1_1;

END rtl;

