-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\hdl_model_fixed\Subsystem_ip_src_Divide_by_zero_handler.vhd
-- Created: 2024-12-15 16:17:57
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Subsystem_ip_src_Divide_by_zero_handler
-- Source Path: hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Divide 
-- by zero handle
-- Hierarchy Level: 4
-- Model version: 1.22
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Subsystem_ip_src_Divide_by_zero_handler IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_25_0                        :   IN    std_logic;
        yIn                               :   IN    std_logic_vector(21 DOWNTO 0);  -- sfix22_En20
        yOut                              :   OUT   std_logic_vector(11 DOWNTO 0)  -- sfix12_En11
        );
END Subsystem_ip_src_Divide_by_zero_handler;


ARCHITECTURE rtl OF Subsystem_ip_src_Divide_by_zero_handler IS

  -- Component Declarations
  COMPONENT Subsystem_ip_src_Compare_To_Zero
    PORT( u                               :   IN    std_logic_vector(21 DOWNTO 0);  -- sfix22_En20
          y                               :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Subsystem_ip_src_Compare_To_Zero
    USE ENTITY work.Subsystem_ip_src_Compare_To_Zero(rtl);

  -- Signals
  SIGNAL Compare_To_Zero_out1             : std_logic;
  SIGNAL Delay13_out1                     : std_logic;
  SIGNAL switch_compare_1                 : std_logic;
  SIGNAL Constant3_out1                   : signed(11 DOWNTO 0);  -- sfix12_En11
  SIGNAL Constant4_out1                   : signed(11 DOWNTO 0);  -- sfix12_En11
  SIGNAL Switch_out1                      : signed(11 DOWNTO 0);  -- sfix12_En11
  SIGNAL Delay3_out1                      : signed(11 DOWNTO 0);  -- sfix12_En11

BEGIN
  u_Compare_To_Zero : Subsystem_ip_src_Compare_To_Zero
    PORT MAP( u => yIn,  -- sfix22_En20
              y => Compare_To_Zero_out1
              );

  Delay13_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay13_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_25_0 = '1' THEN
        Delay13_out1 <= Compare_To_Zero_out1;
      END IF;
    END IF;
  END PROCESS Delay13_process;


  
  switch_compare_1 <= '1' WHEN Delay13_out1 > '0' ELSE
      '0';

  Constant3_out1 <= to_signed(-16#800#, 12);

  Constant4_out1 <= to_signed(16#7FF#, 12);

  
  Switch_out1 <= Constant3_out1 WHEN switch_compare_1 = '0' ELSE
      Constant4_out1;

  Delay3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay3_out1 <= to_signed(16#000#, 12);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_25_0 = '1' THEN
        Delay3_out1 <= Switch_out1;
      END IF;
    END IF;
  END PROCESS Delay3_process;


  yOut <= std_logic_vector(Delay3_out1);

END rtl;

