// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdl_model_fixed\Subsystem_ip2_src_MINRESRX2F_block2.v
// Created: 2024-12-20 22:36:38
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_ip2_src_MINRESRX2F_block2
// Source Path: hdl_model_fixed/Subsystem1/Subsystem/FFT/MINRESRX2FFT_MEMSEL
// Hierarchy Level: 3
// Model version: 1.106
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_ip2_src_MINRESRX2F_block2
          (clk,
           reset,
           enb,
           btfOut1_re,
           btfOut1_im,
           btfOut2_re,
           btfOut2_im,
           btfOut_vld,
           stage,
           initIC,
           syncReset,
           stgOut1_re,
           stgOut1_im,
           stgOut2_re,
           stgOut2_im,
           stgOut_vld);


  input   clk;
  input   reset;
  input   enb;
  input   signed [22:0] btfOut1_re;  // sfix23_En11
  input   signed [22:0] btfOut1_im;  // sfix23_En11
  input   signed [22:0] btfOut2_re;  // sfix23_En11
  input   signed [22:0] btfOut2_im;  // sfix23_En11
  input   btfOut_vld;
  input   [3:0] stage;  // ufix4
  input   initIC;
  input   syncReset;
  output  signed [22:0] stgOut1_re;  // sfix23_En11
  output  signed [22:0] stgOut1_im;  // sfix23_En11
  output  signed [22:0] stgOut2_re;  // sfix23_En11
  output  signed [22:0] stgOut2_im;  // sfix23_En11
  output  stgOut_vld;


  reg signed [22:0] MINRESRX2FFTMEMSEL_stgOut1Reg_re;  // sfix23
  reg signed [22:0] MINRESRX2FFTMEMSEL_stgOut1Reg_im;  // sfix23
  reg signed [22:0] MINRESRX2FFTMEMSEL_stgOut2Reg_re;  // sfix23
  reg signed [22:0] MINRESRX2FFTMEMSEL_stgOut2Reg_im;  // sfix23
  reg  MINRESRX2FFTMEMSEL_stgOutReg_vld;
  reg [9:0] MINRESRX2FFTMEMSEL_cnt;  // ufix10
  reg [9:0] MINRESRX2FFTMEMSEL_cntMax;  // ufix10
  reg  MINRESRX2FFTMEMSEL_muxSel;
  reg signed [22:0] MINRESRX2FFTMEMSEL_stgOut1Reg_re_nex;  // sfix23_En11
  reg signed [22:0] MINRESRX2FFTMEMSEL_stgOut1Reg_im_nex;  // sfix23_En11
  reg signed [22:0] MINRESRX2FFTMEMSEL_stgOut2Reg_re_nex;  // sfix23_En11
  reg signed [22:0] MINRESRX2FFTMEMSEL_stgOut2Reg_im_nex;  // sfix23_En11
  reg  MINRESRX2FFTMEMSEL_stgOutReg_vld_nex;
  reg [9:0] MINRESRX2FFTMEMSEL_cnt_next;  // ufix10
  reg [9:0] MINRESRX2FFTMEMSEL_cntMax_next;  // ufix10
  reg  MINRESRX2FFTMEMSEL_muxSel_next;
  reg signed [22:0] stgOut1_re_1;  // sfix23_En11
  reg signed [22:0] stgOut1_im_1;  // sfix23_En11
  reg signed [22:0] stgOut2_re_1;  // sfix23_En11
  reg signed [22:0] stgOut2_im_1;  // sfix23_En11
  reg  stgOut_vld_1;


  // MINRESRX2FFTMEMSEL
  always @(posedge clk)
    begin : MINRESRX2FFTMEMSEL_process
      if (reset == 1'b1) begin
        MINRESRX2FFTMEMSEL_stgOut1Reg_re <= 23'sb00000000000000000000000;
        MINRESRX2FFTMEMSEL_stgOut1Reg_im <= 23'sb00000000000000000000000;
        MINRESRX2FFTMEMSEL_stgOut2Reg_re <= 23'sb00000000000000000000000;
        MINRESRX2FFTMEMSEL_stgOut2Reg_im <= 23'sb00000000000000000000000;
        MINRESRX2FFTMEMSEL_cnt <= 10'b0000000000;
        MINRESRX2FFTMEMSEL_cntMax <= 10'b0000000000;
        MINRESRX2FFTMEMSEL_muxSel <= 1'b0;
        MINRESRX2FFTMEMSEL_stgOutReg_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            MINRESRX2FFTMEMSEL_stgOut1Reg_re <= 23'sb00000000000000000000000;
            MINRESRX2FFTMEMSEL_stgOut1Reg_im <= 23'sb00000000000000000000000;
            MINRESRX2FFTMEMSEL_stgOut2Reg_re <= 23'sb00000000000000000000000;
            MINRESRX2FFTMEMSEL_stgOut2Reg_im <= 23'sb00000000000000000000000;
            MINRESRX2FFTMEMSEL_cnt <= 10'b0000000000;
            MINRESRX2FFTMEMSEL_cntMax <= 10'b0000000000;
            MINRESRX2FFTMEMSEL_muxSel <= 1'b0;
            MINRESRX2FFTMEMSEL_stgOutReg_vld <= 1'b0;
          end
          else begin
            MINRESRX2FFTMEMSEL_stgOut1Reg_re <= MINRESRX2FFTMEMSEL_stgOut1Reg_re_nex;
            MINRESRX2FFTMEMSEL_stgOut1Reg_im <= MINRESRX2FFTMEMSEL_stgOut1Reg_im_nex;
            MINRESRX2FFTMEMSEL_stgOut2Reg_re <= MINRESRX2FFTMEMSEL_stgOut2Reg_re_nex;
            MINRESRX2FFTMEMSEL_stgOut2Reg_im <= MINRESRX2FFTMEMSEL_stgOut2Reg_im_nex;
            MINRESRX2FFTMEMSEL_stgOutReg_vld <= MINRESRX2FFTMEMSEL_stgOutReg_vld_nex;
            MINRESRX2FFTMEMSEL_cnt <= MINRESRX2FFTMEMSEL_cnt_next;
            MINRESRX2FFTMEMSEL_cntMax <= MINRESRX2FFTMEMSEL_cntMax_next;
            MINRESRX2FFTMEMSEL_muxSel <= MINRESRX2FFTMEMSEL_muxSel_next;
          end
        end
      end
    end

  always @(MINRESRX2FFTMEMSEL_cnt, MINRESRX2FFTMEMSEL_cntMax, MINRESRX2FFTMEMSEL_muxSel,
       MINRESRX2FFTMEMSEL_stgOut1Reg_im, MINRESRX2FFTMEMSEL_stgOut1Reg_re,
       MINRESRX2FFTMEMSEL_stgOut2Reg_im, MINRESRX2FFTMEMSEL_stgOut2Reg_re,
       MINRESRX2FFTMEMSEL_stgOutReg_vld, btfOut1_im, btfOut1_re, btfOut2_im,
       btfOut2_re, btfOut_vld, initIC, stage) begin
    MINRESRX2FFTMEMSEL_cnt_next = MINRESRX2FFTMEMSEL_cnt;
    MINRESRX2FFTMEMSEL_cntMax_next = MINRESRX2FFTMEMSEL_cntMax;
    MINRESRX2FFTMEMSEL_muxSel_next = MINRESRX2FFTMEMSEL_muxSel;
    if (MINRESRX2FFTMEMSEL_muxSel) begin
      MINRESRX2FFTMEMSEL_stgOut1Reg_re_nex = btfOut2_re;
      MINRESRX2FFTMEMSEL_stgOut1Reg_im_nex = btfOut2_im;
      MINRESRX2FFTMEMSEL_stgOut2Reg_re_nex = btfOut1_re;
      MINRESRX2FFTMEMSEL_stgOut2Reg_im_nex = btfOut1_im;
    end
    else begin
      MINRESRX2FFTMEMSEL_stgOut1Reg_re_nex = btfOut1_re;
      MINRESRX2FFTMEMSEL_stgOut1Reg_im_nex = btfOut1_im;
      MINRESRX2FFTMEMSEL_stgOut2Reg_re_nex = btfOut2_re;
      MINRESRX2FFTMEMSEL_stgOut2Reg_im_nex = btfOut2_im;
    end
    if (initIC) begin
      MINRESRX2FFTMEMSEL_cnt_next = 10'b0000000000;
      MINRESRX2FFTMEMSEL_muxSel_next = 1'b0;
      case ( stage)
        4'b0000 :
          begin
            MINRESRX2FFTMEMSEL_cntMax_next = 10'b0111111111;
          end
        4'b1010 :
          begin
            MINRESRX2FFTMEMSEL_cntMax_next = 10'b1111111111;
          end
        default :
          begin
            MINRESRX2FFTMEMSEL_cntMax_next = MINRESRX2FFTMEMSEL_cntMax >> 8'd1;
          end
      endcase
    end
    else if (btfOut_vld) begin
      if (MINRESRX2FFTMEMSEL_cnt == MINRESRX2FFTMEMSEL_cntMax) begin
        MINRESRX2FFTMEMSEL_cnt_next = 10'b0000000000;
        MINRESRX2FFTMEMSEL_muxSel_next =  ! MINRESRX2FFTMEMSEL_muxSel;
      end
      else begin
        MINRESRX2FFTMEMSEL_cnt_next = MINRESRX2FFTMEMSEL_cnt + 10'b0000000001;
      end
    end
    MINRESRX2FFTMEMSEL_stgOutReg_vld_nex = btfOut_vld;
    stgOut1_re_1 = MINRESRX2FFTMEMSEL_stgOut1Reg_re;
    stgOut1_im_1 = MINRESRX2FFTMEMSEL_stgOut1Reg_im;
    stgOut2_re_1 = MINRESRX2FFTMEMSEL_stgOut2Reg_re;
    stgOut2_im_1 = MINRESRX2FFTMEMSEL_stgOut2Reg_im;
    stgOut_vld_1 = MINRESRX2FFTMEMSEL_stgOutReg_vld;
  end



  assign stgOut1_re = stgOut1_re_1;

  assign stgOut1_im = stgOut1_im_1;

  assign stgOut2_re = stgOut2_re_1;

  assign stgOut2_im = stgOut2_im_1;

  assign stgOut_vld = stgOut_vld_1;

endmodule  // Subsystem_ip2_src_MINRESRX2F_block2

