// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdl_model_fixed\Subsystem_ip2_src_Upcast_Wordlength.v
// Created: 2024-12-16 17:45:39
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_ip2_src_Upcast_Wordlength
// Source Path: hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Upcast 
// Wordlengt
// Hierarchy Level: 4
// Model version: 1.56
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_ip2_src_Upcast_Wordlength
          (x,
           y,
           u,
           v);


  input   signed [16:0] x;  // sfix17_En14
  input   signed [16:0] y;  // sfix17_En14
  output  signed [16:0] u;  // sfix17_En14
  output  signed [16:0] v;  // sfix17_En14




  // Copyright 2019 The MathWorks, Inc.
  assign u = x;
  assign v = y;



endmodule  // Subsystem_ip2_src_Upcast_Wordlength

