// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdl_model_fixed\Subsystem_ip2_src_RADIX22FFT_block3.v
// Created: 2024-12-21 15:37:35
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_ip2_src_RADIX22FFT_block3
// Source Path: hdl_model_fixed/Subsystem1/Subsystem/FFT/RADIX22FFT_SDF1_3
// Hierarchy Level: 3
// Model version: 1.113
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_ip2_src_RADIX22FFT_block3
          (clk,
           reset,
           enb,
           din_3_1_re_dly,
           din_3_1_im_dly,
           din_3_vld_dly,
           rd_3_Addr,
           rd_3_Enb,
           twdl_3_1_re,
           twdl_3_1_im,
           proc_3_enb,
           syncReset,
           dout_3_1_re,
           dout_3_1_im,
           dout_3_1_vld,
           dinXTwdl_3_1_vld);


  input   clk;
  input   reset;
  input   enb;
  input   signed [13:0] din_3_1_re_dly;  // sfix14_En11
  input   signed [13:0] din_3_1_im_dly;  // sfix14_En11
  input   din_3_vld_dly;
  input   [7:0] rd_3_Addr;  // ufix8
  input   rd_3_Enb;
  input   signed [11:0] twdl_3_1_re;  // sfix12_En10
  input   signed [11:0] twdl_3_1_im;  // sfix12_En10
  input   proc_3_enb;
  input   syncReset;
  output  signed [14:0] dout_3_1_re;  // sfix15_En11
  output  signed [14:0] dout_3_1_im;  // sfix15_En11
  output  dout_3_1_vld;
  output  dinXTwdl_3_1_vld;


  wire signed [14:0] din_re;  // sfix15_En11
  wire signed [14:0] din_im;  // sfix15_En11
  wire signed [14:0] dinXTwdl_re;  // sfix15_En11
  wire signed [14:0] dinXTwdl_im;  // sfix15_En11
  reg  x_vld;
  wire signed [14:0] wrData_im;  // sfix15_En11
  wire [7:0] wrAddr;  // ufix8
  wire wrEnb;
  wire signed [14:0] x_im;  // sfix15_En11
  wire signed [14:0] wrData_re;  // sfix15_En11
  wire signed [14:0] x_re;  // sfix15_En11
  reg signed [15:0] Radix22ButterflyG1_btf1_re_reg;  // sfix16
  reg signed [15:0] Radix22ButterflyG1_btf1_im_reg;  // sfix16
  reg signed [15:0] Radix22ButterflyG1_btf2_re_reg;  // sfix16
  reg signed [15:0] Radix22ButterflyG1_btf2_im_reg;  // sfix16
  reg signed [14:0] Radix22ButterflyG1_x_re_dly1;  // sfix15
  reg signed [14:0] Radix22ButterflyG1_x_im_dly1;  // sfix15
  reg  Radix22ButterflyG1_x_vld_dly1;
  reg signed [14:0] Radix22ButterflyG1_dinXtwdl_re_dly1;  // sfix15
  reg signed [14:0] Radix22ButterflyG1_dinXtwdl_im_dly1;  // sfix15
  reg signed [14:0] Radix22ButterflyG1_dinXtwdl_re_dly2;  // sfix15
  reg signed [14:0] Radix22ButterflyG1_dinXtwdl_im_dly2;  // sfix15
  reg  Radix22ButterflyG1_dinXtwdl_vld_dly1;
  reg  Radix22ButterflyG1_dinXtwdl_vld_dly2;
  wire signed [15:0] Radix22ButterflyG1_btf1_re_reg_next;  // sfix16_En11
  wire signed [15:0] Radix22ButterflyG1_btf1_im_reg_next;  // sfix16_En11
  wire signed [15:0] Radix22ButterflyG1_btf2_re_reg_next;  // sfix16_En11
  wire signed [15:0] Radix22ButterflyG1_btf2_im_reg_next;  // sfix16_En11
  wire signed [15:0] Radix22ButterflyG1_add_cast;  // sfix16_En11
  wire signed [15:0] Radix22ButterflyG1_add_cast_1;  // sfix16_En11
  wire signed [15:0] Radix22ButterflyG1_sub_cast;  // sfix16_En11
  wire signed [15:0] Radix22ButterflyG1_sub_cast_1;  // sfix16_En11
  wire signed [15:0] Radix22ButterflyG1_add_cast_2;  // sfix16_En11
  wire signed [15:0] Radix22ButterflyG1_add_cast_3;  // sfix16_En11
  wire signed [15:0] Radix22ButterflyG1_sub_cast_2;  // sfix16_En11
  wire signed [15:0] Radix22ButterflyG1_sub_cast_3;  // sfix16_En11
  reg signed [14:0] xf_re;  // sfix15_En11
  reg signed [14:0] xf_im;  // sfix15_En11
  reg  xf_vld;
  wire signed [14:0] dinXTwdlf_re;  // sfix15_En11
  wire signed [14:0] dinXTwdlf_im;  // sfix15_En11
  wire dinxTwdlf_vld;
  wire signed [14:0] btf1_re;  // sfix15_En11
  wire signed [14:0] btf1_im;  // sfix15_En11
  wire signed [14:0] btf2_re;  // sfix15_En11
  wire signed [14:0] btf2_im;  // sfix15_En11
  reg  btf_vld;


  assign din_re = {din_3_1_re_dly[13], din_3_1_re_dly};



  assign din_im = {din_3_1_im_dly[13], din_3_1_im_dly};



  Subsystem_ip2_src_Complex4Mu MUL4_1 (.clk(clk),
                                       .reset(reset),
                                       .enb(enb),
                                       .din_re(din_re),  // sfix15_En11
                                       .din_im(din_im),  // sfix15_En11
                                       .din_3_vld_dly(din_3_vld_dly),
                                       .twdl_3_1_re(twdl_3_1_re),  // sfix12_En10
                                       .twdl_3_1_im(twdl_3_1_im),  // sfix12_En10
                                       .syncReset(syncReset),
                                       .dinXTwdl_re(dinXTwdl_re),  // sfix15_En11
                                       .dinXTwdl_im(dinXTwdl_im),  // sfix15_En11
                                       .dinXTwdl_3_1_vld(dinXTwdl_3_1_vld)
                                       );

  always @(posedge clk)
    begin : intdelay_process
      if (reset == 1'b1) begin
        x_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            x_vld <= 1'b0;
          end
          else begin
            x_vld <= rd_3_Enb;
          end
        end
      end
    end



  Subsystem_ip2_src_SimpleDual #(.AddrWidth(8),
                                 .DataWidth(15)
                                 )
                               dataMEM_im_0_3_1 (.clk(clk),
                                                 .enb(enb),
                                                 .wr_din(wrData_im),
                                                 .wr_addr(wrAddr),
                                                 .wr_en(wrEnb),
                                                 .rd_addr(rd_3_Addr),
                                                 .dout(x_im)
                                                 );

  Subsystem_ip2_src_SimpleDual #(.AddrWidth(8),
                                 .DataWidth(15)
                                 )
                               dataMEM_re_0_3_1 (.clk(clk),
                                                 .enb(enb),
                                                 .wr_din(wrData_re),
                                                 .wr_addr(wrAddr),
                                                 .wr_en(wrEnb),
                                                 .rd_addr(rd_3_Addr),
                                                 .dout(x_re)
                                                 );

  // Radix22ButterflyG1
  always @(posedge clk)
    begin : Radix22ButterflyG1_process
      if (reset == 1'b1) begin
        Radix22ButterflyG1_btf1_re_reg <= 16'sb0000000000000000;
        Radix22ButterflyG1_btf1_im_reg <= 16'sb0000000000000000;
        Radix22ButterflyG1_btf2_re_reg <= 16'sb0000000000000000;
        Radix22ButterflyG1_btf2_im_reg <= 16'sb0000000000000000;
        Radix22ButterflyG1_x_re_dly1 <= 15'sb000000000000000;
        Radix22ButterflyG1_x_im_dly1 <= 15'sb000000000000000;
        Radix22ButterflyG1_x_vld_dly1 <= 1'b0;
        xf_re <= 15'sb000000000000000;
        xf_im <= 15'sb000000000000000;
        xf_vld <= 1'b0;
        Radix22ButterflyG1_dinXtwdl_re_dly1 <= 15'sb000000000000000;
        Radix22ButterflyG1_dinXtwdl_im_dly1 <= 15'sb000000000000000;
        Radix22ButterflyG1_dinXtwdl_re_dly2 <= 15'sb000000000000000;
        Radix22ButterflyG1_dinXtwdl_im_dly2 <= 15'sb000000000000000;
        Radix22ButterflyG1_dinXtwdl_vld_dly1 <= 1'b0;
        Radix22ButterflyG1_dinXtwdl_vld_dly2 <= 1'b0;
        btf_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            Radix22ButterflyG1_btf1_re_reg <= 16'sb0000000000000000;
            Radix22ButterflyG1_btf1_im_reg <= 16'sb0000000000000000;
            Radix22ButterflyG1_btf2_re_reg <= 16'sb0000000000000000;
            Radix22ButterflyG1_btf2_im_reg <= 16'sb0000000000000000;
            Radix22ButterflyG1_x_re_dly1 <= 15'sb000000000000000;
            Radix22ButterflyG1_x_im_dly1 <= 15'sb000000000000000;
            Radix22ButterflyG1_x_vld_dly1 <= 1'b0;
            xf_re <= 15'sb000000000000000;
            xf_im <= 15'sb000000000000000;
            xf_vld <= 1'b0;
            Radix22ButterflyG1_dinXtwdl_re_dly1 <= 15'sb000000000000000;
            Radix22ButterflyG1_dinXtwdl_im_dly1 <= 15'sb000000000000000;
            Radix22ButterflyG1_dinXtwdl_re_dly2 <= 15'sb000000000000000;
            Radix22ButterflyG1_dinXtwdl_im_dly2 <= 15'sb000000000000000;
            Radix22ButterflyG1_dinXtwdl_vld_dly1 <= 1'b0;
            Radix22ButterflyG1_dinXtwdl_vld_dly2 <= 1'b0;
            btf_vld <= 1'b0;
          end
          else begin
            Radix22ButterflyG1_btf1_re_reg <= Radix22ButterflyG1_btf1_re_reg_next;
            Radix22ButterflyG1_btf1_im_reg <= Radix22ButterflyG1_btf1_im_reg_next;
            Radix22ButterflyG1_btf2_re_reg <= Radix22ButterflyG1_btf2_re_reg_next;
            Radix22ButterflyG1_btf2_im_reg <= Radix22ButterflyG1_btf2_im_reg_next;
            xf_re <= Radix22ButterflyG1_x_re_dly1;
            xf_im <= Radix22ButterflyG1_x_im_dly1;
            xf_vld <= Radix22ButterflyG1_x_vld_dly1;
            btf_vld <= Radix22ButterflyG1_dinXtwdl_vld_dly2;
            Radix22ButterflyG1_dinXtwdl_vld_dly2 <= Radix22ButterflyG1_dinXtwdl_vld_dly1;
            Radix22ButterflyG1_dinXtwdl_re_dly2 <= Radix22ButterflyG1_dinXtwdl_re_dly1;
            Radix22ButterflyG1_dinXtwdl_im_dly2 <= Radix22ButterflyG1_dinXtwdl_im_dly1;
            Radix22ButterflyG1_dinXtwdl_re_dly1 <= dinXTwdl_re;
            Radix22ButterflyG1_dinXtwdl_im_dly1 <= dinXTwdl_im;
            Radix22ButterflyG1_x_re_dly1 <= x_re;
            Radix22ButterflyG1_x_im_dly1 <= x_im;
            Radix22ButterflyG1_x_vld_dly1 <= x_vld;
            Radix22ButterflyG1_dinXtwdl_vld_dly1 <= proc_3_enb && dinXTwdl_3_1_vld;
          end
        end
      end
    end

  assign dinxTwdlf_vld = ( ! proc_3_enb) && dinXTwdl_3_1_vld;
  assign Radix22ButterflyG1_add_cast = {Radix22ButterflyG1_x_re_dly1[14], Radix22ButterflyG1_x_re_dly1};
  assign Radix22ButterflyG1_add_cast_1 = {Radix22ButterflyG1_dinXtwdl_re_dly2[14], 
    Radix22ButterflyG1_dinXtwdl_re_dly2};
  assign Radix22ButterflyG1_btf1_re_reg_next = Radix22ButterflyG1_add_cast + Radix22ButterflyG1_add_cast_1;
  assign Radix22ButterflyG1_sub_cast = {Radix22ButterflyG1_x_re_dly1[14], Radix22ButterflyG1_x_re_dly1};
  assign Radix22ButterflyG1_sub_cast_1 = {Radix22ButterflyG1_dinXtwdl_re_dly2[14], 
    Radix22ButterflyG1_dinXtwdl_re_dly2};
  assign Radix22ButterflyG1_btf2_re_reg_next = Radix22ButterflyG1_sub_cast - Radix22ButterflyG1_sub_cast_1;
  assign Radix22ButterflyG1_add_cast_2 = {Radix22ButterflyG1_x_im_dly1[14], Radix22ButterflyG1_x_im_dly1};
  assign Radix22ButterflyG1_add_cast_3 = {Radix22ButterflyG1_dinXtwdl_im_dly2[14], 
    Radix22ButterflyG1_dinXtwdl_im_dly2};
  assign Radix22ButterflyG1_btf1_im_reg_next = Radix22ButterflyG1_add_cast_2 + Radix22ButterflyG1_add_cast_3;
  assign Radix22ButterflyG1_sub_cast_2 = {Radix22ButterflyG1_x_im_dly1[14], Radix22ButterflyG1_x_im_dly1};
  assign Radix22ButterflyG1_sub_cast_3 = {Radix22ButterflyG1_dinXtwdl_im_dly2[14], 
    Radix22ButterflyG1_dinXtwdl_im_dly2};
  assign Radix22ButterflyG1_btf2_im_reg_next = Radix22ButterflyG1_sub_cast_2 - Radix22ButterflyG1_sub_cast_3;
  assign dinXTwdlf_re = dinXTwdl_re;
  assign dinXTwdlf_im = dinXTwdl_im;
  assign btf1_re = Radix22ButterflyG1_btf1_re_reg[14:0];
  assign btf1_im = Radix22ButterflyG1_btf1_im_reg[14:0];
  assign btf2_re = Radix22ButterflyG1_btf2_re_reg[14:0];
  assign btf2_im = Radix22ButterflyG1_btf2_im_reg[14:0];



  Subsystem_ip2_src_SDFCommuta_block1 SDFCOMMUTATOR_3_1 (.clk(clk),
                                                         .reset(reset),
                                                         .enb(enb),
                                                         .din_3_vld_dly(din_3_vld_dly),
                                                         .xf_re(xf_re),  // sfix15_En11
                                                         .xf_im(xf_im),  // sfix15_En11
                                                         .xf_vld(xf_vld),
                                                         .dinXTwdlf_re(dinXTwdlf_re),  // sfix15_En11
                                                         .dinXTwdlf_im(dinXTwdlf_im),  // sfix15_En11
                                                         .dinxTwdlf_vld(dinxTwdlf_vld),
                                                         .btf1_re(btf1_re),  // sfix15_En11
                                                         .btf1_im(btf1_im),  // sfix15_En11
                                                         .btf2_re(btf2_re),  // sfix15_En11
                                                         .btf2_im(btf2_im),  // sfix15_En11
                                                         .btf_vld(btf_vld),
                                                         .syncReset(syncReset),
                                                         .wrData_re(wrData_re),  // sfix15_En11
                                                         .wrData_im(wrData_im),  // sfix15_En11
                                                         .wrAddr(wrAddr),  // ufix8
                                                         .wrEnb(wrEnb),
                                                         .dout_3_1_re(dout_3_1_re),  // sfix15_En11
                                                         .dout_3_1_im(dout_3_1_im),  // sfix15_En11
                                                         .dout_3_1_vld(dout_3_1_vld)
                                                         );

endmodule  // Subsystem_ip2_src_RADIX22FFT_block3

