-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\hdl_model_fixed\Subsystem_ip_src_myRMS.vhd
-- Created: 2024-12-15 16:17:57
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Subsystem_ip_src_myRMS
-- Source Path: hdl_model_fixed/Subsystem1/myRMS
-- Hierarchy Level: 1
-- Model version: 1.22
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.Subsystem_ip_src_Subsystem1_pkg.ALL;

ENTITY Subsystem_ip_src_myRMS IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_25_0                        :   IN    std_logic;
        data                              :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12_En11
        validIn                           :   IN    std_logic;
        reset_1                           :   IN    std_logic;
        y                                 :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16_En7
        validOut                          :   OUT   std_logic
        );
END Subsystem_ip_src_myRMS;


ARCHITECTURE rtl OF Subsystem_ip_src_myRMS IS

  -- Component Declarations
  COMPONENT Subsystem_ip_src_Sample_and_Hold_block1
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_25_0                      :   IN    std_logic;
          In_rsvd                         :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En7
          Trigger                         :   IN    std_logic;
          alpha                           :   OUT   std_logic_vector(15 DOWNTO 0)  -- ufix16_En7
          );
  END COMPONENT;

  COMPONENT Subsystem_ip_src_CORDIC_Square_Root_HDL_Optimized_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_25_0                      :   IN    std_logic;
          u                               :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En7
          validIn                         :   IN    std_logic;
          restart                         :   IN    std_logic;
          y                               :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16_En7
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT Subsystem_ip_src_S_R_Flip_Flop_block1
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_25_0                      :   IN    std_logic;
          in1                             :   IN    std_logic;
          in2                             :   IN    std_logic;
          out1                            :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Subsystem_ip_src_Sample_and_Hold_block1
    USE ENTITY work.Subsystem_ip_src_Sample_and_Hold_block1(rtl);

  FOR ALL : Subsystem_ip_src_CORDIC_Square_Root_HDL_Optimized_block
    USE ENTITY work.Subsystem_ip_src_CORDIC_Square_Root_HDL_Optimized_block(rtl);

  FOR ALL : Subsystem_ip_src_S_R_Flip_Flop_block1
    USE ENTITY work.Subsystem_ip_src_S_R_Flip_Flop_block1(rtl);

  -- Signals
  SIGNAL delayMatch_reg                   : std_logic_vector(2 DOWNTO 0);  -- ufix1 [3]
  SIGNAL Data_Type_Conversion_out1        : std_logic;
  SIGNAL Multiply_Accumulate_counter_out  : unsigned(11 DOWNTO 0);  -- ufix12
  SIGNAL s                                : std_logic;
  SIGNAL Multiply_Accumulate_and1_out     : std_logic;
  SIGNAL switch_compare_1                 : std_logic;
  SIGNAL s_1                              : unsigned(15 DOWNTO 0);  -- ufix16_En7
  SIGNAL Constant1_out1                   : signed(11 DOWNTO 0);  -- sfix12_En11
  SIGNAL HwModeRegister_reg               : vector_of_signed12(0 TO 1);  -- sfix12 [2]
  SIGNAL Constant1_out1_1                 : signed(11 DOWNTO 0);  -- sfix12_En11
  SIGNAL data_signed                      : signed(11 DOWNTO 0);  -- sfix12_En11
  SIGNAL data_1                           : signed(11 DOWNTO 0);  -- sfix12_En11
  SIGNAL mulOutput                        : signed(23 DOWNTO 0);  -- sfix24_En22
  SIGNAL mulOutput_1                      : signed(23 DOWNTO 0);  -- sfix24_En22
  SIGNAL Multiply_Add_add_add_cast        : signed(24 DOWNTO 0);  -- sfix25_En22
  SIGNAL Multiply_Add_add_add_cast_1      : signed(24 DOWNTO 0);  -- sfix25_En22
  SIGNAL Multiply_Add_out1                : signed(24 DOWNTO 0);  -- sfix25_En22
  SIGNAL Multiply_Accumulate_not1_out     : std_logic;
  SIGNAL switch_compare_1_1               : std_logic;
  SIGNAL Multiply_Add_out1_1              : signed(24 DOWNTO 0);  -- sfix25_En22
  SIGNAL Multiply_Add_out1_2              : unsigned(15 DOWNTO 0);  -- ufix16_En17
  SIGNAL s_2                              : unsigned(15 DOWNTO 0);  -- ufix16_En17
  SIGNAL Multiply_Accumulate_input_mux_out : unsigned(15 DOWNTO 0);  -- ufix16_En17
  SIGNAL Constant_out1                    : unsigned(15 DOWNTO 0);  -- ufix16_En15
  SIGNAL Multiply_Accumulate_multiply_out : unsigned(31 DOWNTO 0);  -- ufix32_En32
  SIGNAL Multiply_Accumulate_out1         : unsigned(15 DOWNTO 0);  -- ufix16_En7
  SIGNAL Multiply_Accumulate_add_fb_in    : unsigned(15 DOWNTO 0);  -- ufix16_En7
  SIGNAL Multiply_Accumulate_add_add_cast : unsigned(41 DOWNTO 0);  -- ufix42_En32
  SIGNAL Multiply_Accumulate_add_add_cast_1 : unsigned(41 DOWNTO 0);  -- ufix42_En32
  SIGNAL Multiply_Accumulate_add_add_temp : unsigned(41 DOWNTO 0);  -- ufix42_En32
  SIGNAL Multiply_Accumulate_multiplyAdd_out : unsigned(15 DOWNTO 0);  -- ufix16_En7
  SIGNAL s_3                              : std_logic;
  SIGNAL Multiply_Accumulate_and2_out     : std_logic;
  SIGNAL Multiply_Accumulate_out2         : std_logic;
  SIGNAL Multiply_Accumulate_out4         : std_logic;
  SIGNAL Delay1_reg                       : std_logic_vector(2048 DOWNTO 0);  -- ufix1 [2049]
  SIGNAL Delay1_out1                      : std_logic;
  SIGNAL Sample_and_Hold_out1             : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Sample_and_Hold_out1_unsigned    : unsigned(15 DOWNTO 0);  -- ufix16_En7
  SIGNAL Bit_Shift_out1                   : unsigned(15 DOWNTO 0);  -- ufix16_En7
  SIGNAL delayMatch1_reg                  : std_logic_vector(2 DOWNTO 0);  -- ufix1 [3]
  SIGNAL Delay1_out1_1                    : std_logic;
  SIGNAL AND_out1                         : std_logic;
  SIGNAL CORDIC_Square_Root_HDL_Optimized_out1 : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL validOut_1                       : std_logic;
  SIGNAL delayMatch2_reg                  : std_logic_vector(2 DOWNTO 0);  -- ufix1 [3]
  SIGNAL Data_Type_Conversion1_out1       : std_logic;
  SIGNAL S_R_Flip_Flop_out1               : std_logic;

  ATTRIBUTE use_dsp : string;

  ATTRIBUTE use_dsp OF mulOutput : SIGNAL IS "yes";
  ATTRIBUTE use_dsp OF Multiply_Accumulate_multiply_out : SIGNAL IS "yes";

BEGIN
  u_Sample_and_Hold : Subsystem_ip_src_Sample_and_Hold_block1
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_25_0 => enb_1_25_0,
              In_rsvd => std_logic_vector(Multiply_Accumulate_out1),  -- ufix16_En7
              Trigger => Multiply_Accumulate_out2,
              alpha => Sample_and_Hold_out1  -- ufix16_En7
              );

  u_CORDIC_Square_Root_HDL_Optimized : Subsystem_ip_src_CORDIC_Square_Root_HDL_Optimized_block
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_25_0 => enb_1_25_0,
              u => std_logic_vector(Bit_Shift_out1),  -- ufix16_En7
              validIn => AND_out1,
              restart => reset_1,
              y => CORDIC_Square_Root_HDL_Optimized_out1,  -- ufix16_En7
              validOut => validOut_1
              );

  u_S_R_Flip_Flop_inst : Subsystem_ip_src_S_R_Flip_Flop_block1
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_25_0 => enb_1_25_0,
              in1 => validOut_1,
              in2 => Data_Type_Conversion1_out1,
              out1 => S_R_Flip_Flop_out1
              );

  delayMatch_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_25_0 = '1' THEN
        delayMatch_reg(0) <= validIn;
        delayMatch_reg(2 DOWNTO 1) <= delayMatch_reg(1 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS delayMatch_process;

  Data_Type_Conversion_out1 <= delayMatch_reg(2);

  -- Count limited, Unsigned Counter
  --  initial value   = 1
  --  step value      = 1
  --  count to value  = 2048
  Multiply_Accumulate_counter_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Multiply_Accumulate_counter_out <= to_unsigned(16#001#, 12);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_25_0 = '1' THEN
        IF Data_Type_Conversion_out1 = '1' THEN 
          IF Multiply_Accumulate_counter_out >= to_unsigned(16#800#, 12) THEN 
            Multiply_Accumulate_counter_out <= to_unsigned(16#001#, 12);
          ELSE 
            Multiply_Accumulate_counter_out <= Multiply_Accumulate_counter_out + to_unsigned(16#001#, 12);
          END IF;
        END IF;
      END IF;
    END IF;
  END PROCESS Multiply_Accumulate_counter_process;


  
  s <= '1' WHEN Multiply_Accumulate_counter_out = to_unsigned(16#001#, 12) ELSE
      '0';

  Multiply_Accumulate_and1_out <= Data_Type_Conversion_out1 AND s;

  
  switch_compare_1 <= '1' WHEN Multiply_Accumulate_and1_out > '0' ELSE
      '0';

  s_1 <= to_unsigned(16#0000#, 16);

  Constant1_out1 <= to_signed(16#000#, 12);

  HwModeRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      HwModeRegister_reg <= (OTHERS => to_signed(16#000#, 12));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_25_0 = '1' THEN
        HwModeRegister_reg(0) <= Constant1_out1;
        HwModeRegister_reg(1) <= HwModeRegister_reg(0);
      END IF;
    END IF;
  END PROCESS HwModeRegister_process;

  Constant1_out1_1 <= HwModeRegister_reg(1);

  data_signed <= signed(data);

  reduced_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      data_1 <= to_signed(16#000#, 12);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_25_0 = '1' THEN
        data_1 <= data_signed;
      END IF;
    END IF;
  END PROCESS reduced_process;


  mulOutput <= data_1 * data_1;

  HwModeRegister_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      mulOutput_1 <= to_signed(16#000000#, 24);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_25_0 = '1' THEN
        mulOutput_1 <= mulOutput;
      END IF;
    END IF;
  END PROCESS HwModeRegister_1_process;


  Multiply_Add_add_add_cast <= resize(Constant1_out1_1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 25);
  Multiply_Add_add_add_cast_1 <= resize(mulOutput_1, 25);
  Multiply_Add_out1 <= Multiply_Add_add_add_cast + Multiply_Add_add_add_cast_1;

  Multiply_Accumulate_not1_out <=  NOT Data_Type_Conversion_out1;

  
  switch_compare_1_1 <= '1' WHEN Multiply_Accumulate_not1_out > '0' ELSE
      '0';

  HwModeRegister_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Multiply_Add_out1_1 <= to_signed(16#0000000#, 25);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_25_0 = '1' THEN
        Multiply_Add_out1_1 <= Multiply_Add_out1;
      END IF;
    END IF;
  END PROCESS HwModeRegister_2_process;


  Multiply_Add_out1_2 <= unsigned(Multiply_Add_out1_1(20 DOWNTO 5));

  s_2 <= to_unsigned(16#0000#, 16);

  
  Multiply_Accumulate_input_mux_out <= Multiply_Add_out1_2 WHEN switch_compare_1_1 = '0' ELSE
      s_2;

  Constant_out1 <= to_unsigned(16#8000#, 16);

  Multiply_Accumulate_multiply_out <= Multiply_Accumulate_input_mux_out * Constant_out1;

  
  Multiply_Accumulate_add_fb_in <= Multiply_Accumulate_out1 WHEN switch_compare_1 = '0' ELSE
      s_1;

  Multiply_Accumulate_add_add_cast <= resize(Multiply_Accumulate_add_fb_in & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 42);
  Multiply_Accumulate_add_add_cast_1 <= resize(Multiply_Accumulate_multiply_out, 42);
  Multiply_Accumulate_add_add_temp <= Multiply_Accumulate_add_add_cast + Multiply_Accumulate_add_add_cast_1;
  Multiply_Accumulate_multiplyAdd_out <= Multiply_Accumulate_add_add_temp(40 DOWNTO 25);

  Multiply_Accumulate_delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Multiply_Accumulate_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_25_0 = '1' THEN
        Multiply_Accumulate_out1 <= Multiply_Accumulate_multiplyAdd_out;
      END IF;
    END IF;
  END PROCESS Multiply_Accumulate_delay_process;


  
  s_3 <= '1' WHEN Multiply_Accumulate_counter_out = to_unsigned(16#800#, 12) ELSE
      '0';

  Multiply_Accumulate_and2_out <= Data_Type_Conversion_out1 AND s_3;

  Multiply_Accumulate_delay_endout_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Multiply_Accumulate_out2 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_25_0 = '1' THEN
        Multiply_Accumulate_out2 <= Multiply_Accumulate_and2_out;
      END IF;
    END IF;
  END PROCESS Multiply_Accumulate_delay_endout_process;


  Multiply_Accumulate_delay_validout_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Multiply_Accumulate_out4 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_25_0 = '1' THEN
        Multiply_Accumulate_out4 <= Data_Type_Conversion_out1;
      END IF;
    END IF;
  END PROCESS Multiply_Accumulate_delay_validout_process;


  Delay1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay1_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_25_0 = '1' THEN
        Delay1_reg(0) <= validIn;
        Delay1_reg(2048 DOWNTO 1) <= Delay1_reg(2047 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS Delay1_process;

  Delay1_out1 <= Delay1_reg(2048);

  Sample_and_Hold_out1_unsigned <= unsigned(Sample_and_Hold_out1);

  Bit_Shift_out1 <= SHIFT_RIGHT(Sample_and_Hold_out1_unsigned, 11);

  delayMatch1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch1_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_25_0 = '1' THEN
        delayMatch1_reg(0) <= Delay1_out1;
        delayMatch1_reg(2 DOWNTO 1) <= delayMatch1_reg(1 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS delayMatch1_process;

  Delay1_out1_1 <= delayMatch1_reg(2);

  AND_out1 <= Multiply_Accumulate_out4 AND Delay1_out1_1;

  delayMatch2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch2_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_25_0 = '1' THEN
        delayMatch2_reg(0) <= reset_1;
        delayMatch2_reg(2 DOWNTO 1) <= delayMatch2_reg(1 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS delayMatch2_process;

  Data_Type_Conversion1_out1 <= delayMatch2_reg(2);

  y <= CORDIC_Square_Root_HDL_Optimized_out1;

  validOut <= S_R_Flip_Flop_out1;

END rtl;

