// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdl_model_fixed\Subsystem_ip2_src_Select_Freq.v
// Created: 2024-12-16 17:45:39
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_ip2_src_Select_Freq
// Source Path: hdl_model_fixed/Subsystem1/Subsystem Reference/Select_Freq
// Hierarchy Level: 2
// Model version: 1.56
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_ip2_src_Select_Freq
          (clk,
           reset,
           enb_1_2_0,
           enb_1,
           Out1);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   enb_1;
  output  Out1;


  wire NOT_out1;
  wire [11:0] count_step;  // ufix12
  wire [11:0] count_from;  // ufix12
  wire [11:0] count_reset;  // ufix12
  wire stateControl_1;
  reg  [1:0] delayMatch_reg;  // ufix1 [2]
  wire stateControl_2;
  wire enb_1_2_0_gated;
  reg [11:0] HDL_Counter_out1;  // ufix12
  wire [11:0] count;  // ufix12
  wire need_to_wrap;
  wire [11:0] count_value;  // ufix12
  wire [11:0] count_1;  // ufix12
  wire [11:0] count_2;  // ufix12
  wire switch_compare_1;
  wire Constant_out1;
  wire Constant1_out1;
  wire Switch_out1;
  wire switch_compare_1_1;
  wire Switch1_out1;
  wire AND_out1;


  assign NOT_out1 =  ~ enb_1;



  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 2048
  assign count_step = 12'b000000000001;



  assign count_from = 12'b000000000000;



  assign count_reset = 12'b000000000000;



  assign stateControl_1 = 1'b1;



  always @(posedge clk)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        delayMatch_reg <= {2{1'b0}};
      end
      else begin
        if (enb_1_2_0) begin
          delayMatch_reg[0] <= stateControl_1;
          delayMatch_reg[1] <= delayMatch_reg[0];
        end
      end
    end

  assign stateControl_2 = delayMatch_reg[1];



  assign enb_1_2_0_gated = stateControl_2 && enb_1_2_0;

  assign count = HDL_Counter_out1 + count_step;



  assign need_to_wrap = HDL_Counter_out1 == 12'b100000000000;



  assign count_value = (need_to_wrap == 1'b0 ? count :
              count_from);



  assign count_1 = (enb_1 == 1'b0 ? HDL_Counter_out1 :
              count_value);



  assign count_2 = (NOT_out1 == 1'b0 ? count_1 :
              count_reset);



  always @(posedge clk)
    begin : HDL_Counter_process
      if (reset == 1'b1) begin
        HDL_Counter_out1 <= 12'b000000000000;
      end
      else begin
        if (enb_1_2_0_gated) begin
          HDL_Counter_out1 <= count_2;
        end
      end
    end



  assign switch_compare_1 = HDL_Counter_out1 > 12'b000000001001;



  assign Constant_out1 = 1'b0;



  assign Constant1_out1 = 1'b1;



  assign Switch_out1 = (switch_compare_1 == 1'b0 ? Constant_out1 :
              Constant1_out1);



  assign switch_compare_1_1 = HDL_Counter_out1 > 12'b010000000000;



  assign Switch1_out1 = (switch_compare_1_1 == 1'b0 ? Constant1_out1 :
              Constant_out1);



  assign AND_out1 = Switch_out1 & Switch1_out1;



  assign Out1 = AND_out1;

endmodule  // Subsystem_ip2_src_Select_Freq

