-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\hdl_model_fixed\Subsystem_ip_src_Sample_and_Hold2_block.vhd
-- Created: 2024-12-15 16:17:57
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Subsystem_ip_src_Sample_and_Hold2_block
-- Source Path: hdl_model_fixed/Subsystem1/Subsystem Reference/Sample and Hold2
-- Hierarchy Level: 2
-- Model version: 1.22
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Subsystem_ip_src_Sample_and_Hold2_block IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_25_0                        :   IN    std_logic;
        In_rsvd                           :   IN    std_logic_vector(21 DOWNTO 0);  -- sfix22_En11
        Trigger                           :   IN    std_logic;
        alpha                             :   OUT   std_logic_vector(21 DOWNTO 0)  -- sfix22_En11
        );
END Subsystem_ip_src_Sample_and_Hold2_block;


ARCHITECTURE rtl OF Subsystem_ip_src_Sample_and_Hold2_block IS

  -- Signals
  SIGNAL enb_1_25_0_gated                 : std_logic;
  SIGNAL Trigger_delayed                  : std_logic;
  SIGNAL Trigger_emulated                 : std_logic;
  SIGNAL In_signed                        : signed(21 DOWNTO 0);  -- sfix22_En11
  SIGNAL In_bypass                        : signed(21 DOWNTO 0);  -- sfix22_En11
  SIGNAL In_last_value                    : signed(21 DOWNTO 0);  -- sfix22_En11

BEGIN
  Trigger_delay_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Trigger_delayed <= '1';
    ELSIF clk'event AND clk = '1' THEN
      IF enb_1_25_0 = '1' THEN
        Trigger_delayed <= Trigger;
      END IF;
    END IF;
  END PROCESS Trigger_delay_process;

  Trigger_emulated <= NOT Trigger_delayed AND Trigger;

  enb_1_25_0_gated <= Trigger_emulated AND enb_1_25_0;

  In_signed <= signed(In_rsvd);

  alpha_bypass_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      In_last_value <= to_signed(16#000000#, 22);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_25_0_gated = '1' THEN
        In_last_value <= In_bypass;
      END IF;
    END IF;
  END PROCESS alpha_bypass_process;


  
  In_bypass <= In_last_value WHEN Trigger_emulated = '0' ELSE
      In_signed;

  alpha <= std_logic_vector(In_bypass);

END rtl;

