// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdl_model_fixed\Subsystem_ip2_src_Synchronous_Subsystem_block1.v
// Created: 2024-12-16 17:45:39
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_ip2_src_Synchronous_Subsystem_block1
// Source Path: hdl_model_fixed/Subsystem1/myRMS/CORDIC Square Root HDL Optimized/Synchronous Subsystem
// Hierarchy Level: 3
// Model version: 1.56
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_ip2_src_Synchronous_Subsystem_block1
          (clk,
           reset,
           enb_1_2_0,
           u,
           validIn,
           restart,
           dataOut,
           eOut,
           isZero,
           validOut);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   [15:0] u;  // ufix16_En7
  input   validIn;
  input   restart;
  output  signed [15:0] dataOut;  // sfix16_En14
  output  signed [31:0] eOut;  // int32
  output  isZero;
  output  validOut;




  Subsystem_ip2_src_cordicSquareRootHDL_block1 u_cordicSquareRootHDL (.clk(clk),
                                                                      .reset(reset),
                                                                      .enb_1_2_0(enb_1_2_0),
                                                                      .u(u),  // ufix16_En7
                                                                      .validIn(validIn),
                                                                      .restart(restart),
                                                                      .dataOut(dataOut),  // sfix16_En14
                                                                      .eOut(eOut),  // int32
                                                                      .isZero(isZero),
                                                                      .validOut(validOut)
                                                                      );

endmodule  // Subsystem_ip2_src_Synchronous_Subsystem_block1

