// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdl_model_fixed\Subsystem_ip2_src_RADIX22FFT_block1.v
// Created: 2024-12-21 15:37:35
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_ip2_src_RADIX22FFT_block1
// Source Path: hdl_model_fixed/Subsystem1/Subsystem/FFT/RADIX22FFT_SDF2_2
// Hierarchy Level: 3
// Model version: 1.113
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_ip2_src_RADIX22FFT_block1
          (clk,
           reset,
           enb,
           dout_1_1_re,
           dout_1_1_im,
           dout_1_1_vld,
           rd_2_Addr,
           rd_2_Enb,
           proc_2_enb,
           multiply_2_J,
           syncReset,
           dout_2_1_re,
           dout_2_1_im,
           dout_2_1_vld,
           dinXTwdl_2_1_vld);


  input   clk;
  input   reset;
  input   enb;
  input   signed [12:0] dout_1_1_re;  // sfix13_En11
  input   signed [12:0] dout_1_1_im;  // sfix13_En11
  input   dout_1_1_vld;
  input   [8:0] rd_2_Addr;  // ufix9
  input   rd_2_Enb;
  input   proc_2_enb;
  input   multiply_2_J;
  input   syncReset;
  output  signed [13:0] dout_2_1_re;  // sfix14_En11
  output  signed [13:0] dout_2_1_im;  // sfix14_En11
  output  dout_2_1_vld;
  output  dinXTwdl_2_1_vld;


  wire signed [13:0] din_re;  // sfix14_En11
  wire signed [13:0] din_im;  // sfix14_En11
  wire btfin_vld;
  wire saveEnb;
  wire dinVld;
  reg  x_vld;
  reg  x_vld_dly;
  wire signed [13:0] wrData_im;  // sfix14_En11
  wire [8:0] wrAddr;  // ufix9
  wire wrEnb;
  wire signed [13:0] x_im;  // sfix14_En11
  reg signed [13:0] x_im_dly;  // sfix14_En11
  wire signed [13:0] wrData_re;  // sfix14_En11
  wire signed [13:0] x_re;  // sfix14_En11
  reg signed [13:0] x_re_dly;  // sfix14_En11
  reg  Radix22ButterflyG2_procEnb_dly;
  reg  Radix22ButterflyG2_procEnb_dly1;
  reg  Radix22ButterflyG2_procEnb_dly2;
  reg signed [14:0] Radix22ButterflyG2_btf1_re_reg;  // sfix15
  reg signed [14:0] Radix22ButterflyG2_btf1_im_reg;  // sfix15
  reg signed [14:0] Radix22ButterflyG2_btf2_re_reg;  // sfix15
  reg signed [14:0] Radix22ButterflyG2_btf2_im_reg;  // sfix15
  reg signed [13:0] Radix22ButterflyG2_din_re_dly;  // sfix14
  reg signed [13:0] Radix22ButterflyG2_din_im_dly;  // sfix14
  reg  Radix22ButterflyG2_din_vld_dly;
  reg signed [13:0] Radix22ButterflyG2_x_re_dly;  // sfix14
  reg signed [13:0] Radix22ButterflyG2_x_im_dly;  // sfix14
  reg  Radix22ButterflyG2_x_vld_dly;
  reg signed [13:0] Radix22ButterflyG2_dinXTwdl_re_dly1;  // sfix14
  reg signed [13:0] Radix22ButterflyG2_dinXTwdl_im_dly1;  // sfix14
  reg signed [13:0] Radix22ButterflyG2_dinXTwdl_re_dly2;  // sfix14
  reg signed [13:0] Radix22ButterflyG2_dinXTwdl_im_dly2;  // sfix14
  reg  Radix22ButterflyG2_multiply_J_dly1;
  reg  Radix22ButterflyG2_procEnb_dly_next;
  reg  Radix22ButterflyG2_procEnb_dly1_next;
  reg  Radix22ButterflyG2_procEnb_dly2_next;
  reg signed [14:0] Radix22ButterflyG2_btf1_re_reg_next;  // sfix15_En11
  reg signed [14:0] Radix22ButterflyG2_btf1_im_reg_next;  // sfix15_En11
  reg signed [14:0] Radix22ButterflyG2_btf2_re_reg_next;  // sfix15_En11
  reg signed [14:0] Radix22ButterflyG2_btf2_im_reg_next;  // sfix15_En11
  reg signed [13:0] Radix22ButterflyG2_din_re_dly_next;  // sfix14_En11
  reg signed [13:0] Radix22ButterflyG2_din_im_dly_next;  // sfix14_En11
  reg  Radix22ButterflyG2_din_vld_dly_next;
  reg signed [13:0] Radix22ButterflyG2_x_re_dly_next;  // sfix14_En11
  reg signed [13:0] Radix22ButterflyG2_x_im_dly_next;  // sfix14_En11
  reg  Radix22ButterflyG2_x_vld_dly_next;
  reg signed [13:0] Radix22ButterflyG2_dinXTwdl_re_dly1_1;  // sfix14_En11
  reg signed [13:0] Radix22ButterflyG2_dinXTwdl_im_dly1_1;  // sfix14_En11
  reg signed [13:0] Radix22ButterflyG2_dinXTwdl_re_dly2_1;  // sfix14_En11
  reg signed [13:0] Radix22ButterflyG2_dinXTwdl_im_dly2_1;  // sfix14_En11
  reg  Radix22ButterflyG2_multiply_J_dly1_n;
  reg signed [13:0] xf_re;  // sfix14_En11
  reg signed [13:0] xf_im;  // sfix14_En11
  reg  xf_vld;
  reg signed [13:0] dinf_re;  // sfix14_En11
  reg signed [13:0] dinf_im;  // sfix14_En11
  reg  dinf_vld;
  reg signed [13:0] btf1_re;  // sfix14_En11
  reg signed [13:0] btf1_im;  // sfix14_En11
  reg signed [13:0] btf2_re;  // sfix14_En11
  reg signed [13:0] btf2_im;  // sfix14_En11
  reg  btfout_vld;
  reg signed [14:0] Radix22ButterflyG2_add_cast;  // sfix15_En11
  reg signed [14:0] Radix22ButterflyG2_add_cast_0;  // sfix15_En11
  reg signed [14:0] Radix22ButterflyG2_add_cast_1;  // sfix15_En11
  reg signed [14:0] Radix22ButterflyG2_add_cast_2;  // sfix15_En11
  reg signed [14:0] Radix22ButterflyG2_sub_cast;  // sfix15_En11
  reg signed [14:0] Radix22ButterflyG2_sub_cast_0;  // sfix15_En11
  reg signed [14:0] Radix22ButterflyG2_sub_cast_1;  // sfix15_En11
  reg signed [14:0] Radix22ButterflyG2_sub_cast_2;  // sfix15_En11
  reg signed [14:0] Radix22ButterflyG2_add_cast_3;  // sfix15_En11
  reg signed [14:0] Radix22ButterflyG2_add_cast_4;  // sfix15_En11
  reg signed [14:0] Radix22ButterflyG2_add_cast_5;  // sfix15_En11
  reg signed [14:0] Radix22ButterflyG2_add_cast_6;  // sfix15_En11
  reg signed [14:0] Radix22ButterflyG2_sub_cast_3;  // sfix15_En11
  reg signed [14:0] Radix22ButterflyG2_sub_cast_4;  // sfix15_En11
  reg signed [14:0] Radix22ButterflyG2_sub_cast_5;  // sfix15_En11
  reg signed [14:0] Radix22ButterflyG2_sub_cast_6;  // sfix15_En11


  assign din_re = {dout_1_1_re[12], dout_1_1_re};



  assign din_im = {dout_1_1_im[12], dout_1_1_im};



  assign btfin_vld = dout_1_1_vld & proc_2_enb;



  assign saveEnb =  ~ btfin_vld;



  assign dinVld = dout_1_1_vld & saveEnb;



  always @(posedge clk)
    begin : intdelay_process
      if (reset == 1'b1) begin
        x_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            x_vld <= 1'b0;
          end
          else begin
            x_vld <= rd_2_Enb;
          end
        end
      end
    end



  always @(posedge clk)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        x_vld_dly <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            x_vld_dly <= 1'b0;
          end
          else begin
            x_vld_dly <= x_vld;
          end
        end
      end
    end



  Subsystem_ip2_src_SimpleDual #(.AddrWidth(9),
                                 .DataWidth(14)
                                 )
                               dataMEM_im_0_2_1 (.clk(clk),
                                                 .enb(enb),
                                                 .wr_din(wrData_im),
                                                 .wr_addr(wrAddr),
                                                 .wr_en(wrEnb),
                                                 .rd_addr(rd_2_Addr),
                                                 .dout(x_im)
                                                 );

  always @(posedge clk)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        x_im_dly <= 14'sb00000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            x_im_dly <= 14'sb00000000000000;
          end
          else begin
            x_im_dly <= x_im;
          end
        end
      end
    end



  Subsystem_ip2_src_SimpleDual #(.AddrWidth(9),
                                 .DataWidth(14)
                                 )
                               dataMEM_re_0_2_1 (.clk(clk),
                                                 .enb(enb),
                                                 .wr_din(wrData_re),
                                                 .wr_addr(wrAddr),
                                                 .wr_en(wrEnb),
                                                 .rd_addr(rd_2_Addr),
                                                 .dout(x_re)
                                                 );

  always @(posedge clk)
    begin : intdelay_3_process
      if (reset == 1'b1) begin
        x_re_dly <= 14'sb00000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            x_re_dly <= 14'sb00000000000000;
          end
          else begin
            x_re_dly <= x_re;
          end
        end
      end
    end



  // Radix22ButterflyG2
  always @(posedge clk)
    begin : Radix22ButterflyG2_process
      if (reset == 1'b1) begin
        Radix22ButterflyG2_procEnb_dly <= 1'b0;
        Radix22ButterflyG2_procEnb_dly1 <= 1'b0;
        Radix22ButterflyG2_procEnb_dly2 <= 1'b0;
        Radix22ButterflyG2_btf1_re_reg <= 15'sb000000000000000;
        Radix22ButterflyG2_btf1_im_reg <= 15'sb000000000000000;
        Radix22ButterflyG2_btf2_re_reg <= 15'sb000000000000000;
        Radix22ButterflyG2_btf2_im_reg <= 15'sb000000000000000;
        Radix22ButterflyG2_din_re_dly <= 14'sb00000000000000;
        Radix22ButterflyG2_din_im_dly <= 14'sb00000000000000;
        Radix22ButterflyG2_din_vld_dly <= 1'b0;
        Radix22ButterflyG2_x_re_dly <= 14'sb00000000000000;
        Radix22ButterflyG2_x_im_dly <= 14'sb00000000000000;
        Radix22ButterflyG2_x_vld_dly <= 1'b0;
        Radix22ButterflyG2_dinXTwdl_re_dly1 <= 14'sb00000000000000;
        Radix22ButterflyG2_dinXTwdl_im_dly1 <= 14'sb00000000000000;
        Radix22ButterflyG2_dinXTwdl_re_dly2 <= 14'sb00000000000000;
        Radix22ButterflyG2_dinXTwdl_im_dly2 <= 14'sb00000000000000;
        Radix22ButterflyG2_multiply_J_dly1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            Radix22ButterflyG2_procEnb_dly <= 1'b0;
            Radix22ButterflyG2_procEnb_dly1 <= 1'b0;
            Radix22ButterflyG2_procEnb_dly2 <= 1'b0;
            Radix22ButterflyG2_btf1_re_reg <= 15'sb000000000000000;
            Radix22ButterflyG2_btf1_im_reg <= 15'sb000000000000000;
            Radix22ButterflyG2_btf2_re_reg <= 15'sb000000000000000;
            Radix22ButterflyG2_btf2_im_reg <= 15'sb000000000000000;
            Radix22ButterflyG2_din_re_dly <= 14'sb00000000000000;
            Radix22ButterflyG2_din_im_dly <= 14'sb00000000000000;
            Radix22ButterflyG2_din_vld_dly <= 1'b0;
            Radix22ButterflyG2_x_re_dly <= 14'sb00000000000000;
            Radix22ButterflyG2_x_im_dly <= 14'sb00000000000000;
            Radix22ButterflyG2_x_vld_dly <= 1'b0;
            Radix22ButterflyG2_dinXTwdl_re_dly1 <= 14'sb00000000000000;
            Radix22ButterflyG2_dinXTwdl_im_dly1 <= 14'sb00000000000000;
            Radix22ButterflyG2_dinXTwdl_re_dly2 <= 14'sb00000000000000;
            Radix22ButterflyG2_dinXTwdl_im_dly2 <= 14'sb00000000000000;
            Radix22ButterflyG2_multiply_J_dly1 <= 1'b0;
          end
          else begin
            Radix22ButterflyG2_procEnb_dly <= Radix22ButterflyG2_procEnb_dly_next;
            Radix22ButterflyG2_procEnb_dly1 <= Radix22ButterflyG2_procEnb_dly1_next;
            Radix22ButterflyG2_procEnb_dly2 <= Radix22ButterflyG2_procEnb_dly2_next;
            Radix22ButterflyG2_btf1_re_reg <= Radix22ButterflyG2_btf1_re_reg_next;
            Radix22ButterflyG2_btf1_im_reg <= Radix22ButterflyG2_btf1_im_reg_next;
            Radix22ButterflyG2_btf2_re_reg <= Radix22ButterflyG2_btf2_re_reg_next;
            Radix22ButterflyG2_btf2_im_reg <= Radix22ButterflyG2_btf2_im_reg_next;
            Radix22ButterflyG2_din_re_dly <= Radix22ButterflyG2_din_re_dly_next;
            Radix22ButterflyG2_din_im_dly <= Radix22ButterflyG2_din_im_dly_next;
            Radix22ButterflyG2_din_vld_dly <= Radix22ButterflyG2_din_vld_dly_next;
            Radix22ButterflyG2_x_re_dly <= Radix22ButterflyG2_x_re_dly_next;
            Radix22ButterflyG2_x_im_dly <= Radix22ButterflyG2_x_im_dly_next;
            Radix22ButterflyG2_x_vld_dly <= Radix22ButterflyG2_x_vld_dly_next;
            Radix22ButterflyG2_dinXTwdl_re_dly1 <= Radix22ButterflyG2_dinXTwdl_re_dly1_1;
            Radix22ButterflyG2_dinXTwdl_im_dly1 <= Radix22ButterflyG2_dinXTwdl_im_dly1_1;
            Radix22ButterflyG2_dinXTwdl_re_dly2 <= Radix22ButterflyG2_dinXTwdl_re_dly2_1;
            Radix22ButterflyG2_dinXTwdl_im_dly2 <= Radix22ButterflyG2_dinXTwdl_im_dly2_1;
            Radix22ButterflyG2_multiply_J_dly1 <= Radix22ButterflyG2_multiply_J_dly1_n;
          end
        end
      end
    end

  always @(Radix22ButterflyG2_btf1_im_reg, Radix22ButterflyG2_btf1_re_reg,
       Radix22ButterflyG2_btf2_im_reg, Radix22ButterflyG2_btf2_re_reg,
       Radix22ButterflyG2_dinXTwdl_im_dly1, Radix22ButterflyG2_dinXTwdl_im_dly2,
       Radix22ButterflyG2_dinXTwdl_re_dly1, Radix22ButterflyG2_dinXTwdl_re_dly2,
       Radix22ButterflyG2_din_im_dly, Radix22ButterflyG2_din_re_dly,
       Radix22ButterflyG2_din_vld_dly, Radix22ButterflyG2_multiply_J_dly1,
       Radix22ButterflyG2_procEnb_dly, Radix22ButterflyG2_procEnb_dly1,
       Radix22ButterflyG2_procEnb_dly2, Radix22ButterflyG2_x_im_dly,
       Radix22ButterflyG2_x_re_dly, Radix22ButterflyG2_x_vld_dly, btfin_vld,
       dinVld, din_im, din_re, multiply_2_J, x_im_dly, x_re_dly, x_vld_dly) begin
    Radix22ButterflyG2_add_cast_1 = 15'sb000000000000000;
    Radix22ButterflyG2_add_cast_2 = 15'sb000000000000000;
    Radix22ButterflyG2_sub_cast_1 = 15'sb000000000000000;
    Radix22ButterflyG2_sub_cast_2 = 15'sb000000000000000;
    Radix22ButterflyG2_add_cast_5 = 15'sb000000000000000;
    Radix22ButterflyG2_add_cast_6 = 15'sb000000000000000;
    Radix22ButterflyG2_sub_cast_5 = 15'sb000000000000000;
    Radix22ButterflyG2_sub_cast_6 = 15'sb000000000000000;
    Radix22ButterflyG2_add_cast = 15'sb000000000000000;
    Radix22ButterflyG2_add_cast_0 = 15'sb000000000000000;
    Radix22ButterflyG2_sub_cast = 15'sb000000000000000;
    Radix22ButterflyG2_sub_cast_0 = 15'sb000000000000000;
    Radix22ButterflyG2_add_cast_3 = 15'sb000000000000000;
    Radix22ButterflyG2_add_cast_4 = 15'sb000000000000000;
    Radix22ButterflyG2_sub_cast_3 = 15'sb000000000000000;
    Radix22ButterflyG2_sub_cast_4 = 15'sb000000000000000;
    Radix22ButterflyG2_x_re_dly_next = x_re_dly;
    Radix22ButterflyG2_x_im_dly_next = x_im_dly;
    Radix22ButterflyG2_x_vld_dly_next = x_vld_dly;
    Radix22ButterflyG2_din_re_dly_next = din_re;
    Radix22ButterflyG2_din_im_dly_next = din_im;
    Radix22ButterflyG2_din_vld_dly_next = dinVld;
    Radix22ButterflyG2_procEnb_dly2_next = Radix22ButterflyG2_procEnb_dly1;
    Radix22ButterflyG2_procEnb_dly1_next = Radix22ButterflyG2_procEnb_dly;
    Radix22ButterflyG2_procEnb_dly_next = btfin_vld;
    if (Radix22ButterflyG2_multiply_J_dly1) begin
      Radix22ButterflyG2_add_cast_1 = {x_re_dly[13], x_re_dly};
      Radix22ButterflyG2_add_cast_2 = {Radix22ButterflyG2_dinXTwdl_im_dly2[13], 
        Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf1_re_reg_next = Radix22ButterflyG2_add_cast_1 + Radix22ButterflyG2_add_cast_2;
      Radix22ButterflyG2_sub_cast_1 = {x_re_dly[13], x_re_dly};
      Radix22ButterflyG2_sub_cast_2 = {Radix22ButterflyG2_dinXTwdl_im_dly2[13], 
        Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf2_re_reg_next = Radix22ButterflyG2_sub_cast_1 - Radix22ButterflyG2_sub_cast_2;
      Radix22ButterflyG2_add_cast_5 = {x_im_dly[13], x_im_dly};
      Radix22ButterflyG2_add_cast_6 = {Radix22ButterflyG2_dinXTwdl_re_dly2[13], 
        Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf2_im_reg_next = Radix22ButterflyG2_add_cast_5 + Radix22ButterflyG2_add_cast_6;
      Radix22ButterflyG2_sub_cast_5 = {x_im_dly[13], x_im_dly};
      Radix22ButterflyG2_sub_cast_6 = {Radix22ButterflyG2_dinXTwdl_re_dly2[13], 
        Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf1_im_reg_next = Radix22ButterflyG2_sub_cast_5 - Radix22ButterflyG2_sub_cast_6;
    end
    else begin
      Radix22ButterflyG2_add_cast = {x_re_dly[13], x_re_dly};
      Radix22ButterflyG2_add_cast_0 = {Radix22ButterflyG2_dinXTwdl_re_dly2[13], 
        Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf1_re_reg_next = Radix22ButterflyG2_add_cast + Radix22ButterflyG2_add_cast_0;
      Radix22ButterflyG2_sub_cast = {x_re_dly[13], x_re_dly};
      Radix22ButterflyG2_sub_cast_0 = {Radix22ButterflyG2_dinXTwdl_re_dly2[13], 
        Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf2_re_reg_next = Radix22ButterflyG2_sub_cast - Radix22ButterflyG2_sub_cast_0;
      Radix22ButterflyG2_add_cast_3 = {x_im_dly[13], x_im_dly};
      Radix22ButterflyG2_add_cast_4 = {Radix22ButterflyG2_dinXTwdl_im_dly2[13], 
        Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf1_im_reg_next = Radix22ButterflyG2_add_cast_3 + Radix22ButterflyG2_add_cast_4;
      Radix22ButterflyG2_sub_cast_3 = {x_im_dly[13], x_im_dly};
      Radix22ButterflyG2_sub_cast_4 = {Radix22ButterflyG2_dinXTwdl_im_dly2[13], 
        Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf2_im_reg_next = Radix22ButterflyG2_sub_cast_3 - Radix22ButterflyG2_sub_cast_4;
    end
    Radix22ButterflyG2_dinXTwdl_re_dly2_1 = Radix22ButterflyG2_dinXTwdl_re_dly1;
    Radix22ButterflyG2_dinXTwdl_im_dly2_1 = Radix22ButterflyG2_dinXTwdl_im_dly1;
    Radix22ButterflyG2_dinXTwdl_re_dly1_1 = din_re;
    Radix22ButterflyG2_dinXTwdl_im_dly1_1 = din_im;
    Radix22ButterflyG2_multiply_J_dly1_n = multiply_2_J;
    xf_re = Radix22ButterflyG2_x_re_dly;
    xf_im = Radix22ButterflyG2_x_im_dly;
    xf_vld = Radix22ButterflyG2_x_vld_dly;
    dinf_re = Radix22ButterflyG2_din_re_dly;
    dinf_im = Radix22ButterflyG2_din_im_dly;
    dinf_vld = Radix22ButterflyG2_din_vld_dly;
    btf1_re = Radix22ButterflyG2_btf1_re_reg[13:0];
    btf1_im = Radix22ButterflyG2_btf1_im_reg[13:0];
    btf2_re = Radix22ButterflyG2_btf2_re_reg[13:0];
    btf2_im = Radix22ButterflyG2_btf2_im_reg[13:0];
    btfout_vld = Radix22ButterflyG2_procEnb_dly2;
  end



  Subsystem_ip2_src_SDFCommuta_block SDFCOMMUTATOR_2_1 (.clk(clk),
                                                        .reset(reset),
                                                        .enb(enb),
                                                        .dout_1_1_vld(dout_1_1_vld),
                                                        .xf_re(xf_re),  // sfix14_En11
                                                        .xf_im(xf_im),  // sfix14_En11
                                                        .xf_vld(xf_vld),
                                                        .dinf_re(dinf_re),  // sfix14_En11
                                                        .dinf_im(dinf_im),  // sfix14_En11
                                                        .dinf_vld(dinf_vld),
                                                        .btf1_re(btf1_re),  // sfix14_En11
                                                        .btf1_im(btf1_im),  // sfix14_En11
                                                        .btf2_re(btf2_re),  // sfix14_En11
                                                        .btf2_im(btf2_im),  // sfix14_En11
                                                        .btfout_vld(btfout_vld),
                                                        .syncReset(syncReset),
                                                        .wrData_re(wrData_re),  // sfix14_En11
                                                        .wrData_im(wrData_im),  // sfix14_En11
                                                        .wrAddr(wrAddr),  // ufix9
                                                        .wrEnb(wrEnb),
                                                        .dout_2_1_re(dout_2_1_re),  // sfix14_En11
                                                        .dout_2_1_im(dout_2_1_im),  // sfix14_En11
                                                        .dout_2_1_vld(dout_2_1_vld)
                                                        );

  assign dinXTwdl_2_1_vld = btfin_vld;

endmodule  // Subsystem_ip2_src_RADIX22FFT_block1

