-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\hdl_model_fixed\Subsystem_ip_src_Real_Divide_HDL_Optimized.vhd
-- Created: 2024-12-15 16:17:57
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Subsystem_ip_src_Real_Divide_HDL_Optimized
-- Source Path: hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized
-- Hierarchy Level: 2
-- Model version: 1.22
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Subsystem_ip_src_Real_Divide_HDL_Optimized IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_25_0                        :   IN    std_logic;
        num                               :   IN    std_logic_vector(21 DOWNTO 0);  -- sfix22_En11
        den                               :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12_En11
        validIn                           :   IN    std_logic;
        y                                 :   OUT   std_logic_vector(11 DOWNTO 0);  -- sfix12_En11
        validOut                          :   OUT   std_logic
        );
END Subsystem_ip_src_Real_Divide_HDL_Optimized;


ARCHITECTURE rtl OF Subsystem_ip_src_Real_Divide_HDL_Optimized IS

  -- Component Declarations
  COMPONENT Subsystem_ip_src_Verify_divide_sizes
    PORT( denominator                     :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12_En11
          numerator                       :   IN    std_logic_vector(21 DOWNTO 0);  -- sfix22_En11
          den                             :   OUT   std_logic_vector(11 DOWNTO 0);  -- sfix12_En11
          num                             :   OUT   std_logic_vector(21 DOWNTO 0)  -- sfix22_En11
          );
  END COMPONENT;

  COMPONENT Subsystem_ip_src_ForEach_Real_Divide
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_25_0                      :   IN    std_logic;
          den                             :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12_En11
          num                             :   IN    std_logic_vector(21 DOWNTO 0);  -- sfix22_En11
          validIn                         :   IN    std_logic;
          y                               :   OUT   std_logic_vector(11 DOWNTO 0);  -- sfix12_En11
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT Subsystem_ip_src_Reshape_to_original_size
    PORT( y                               :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12_En11
          u                               :   IN    std_logic_vector(21 DOWNTO 0);  -- sfix22_En11
          z                               :   OUT   std_logic_vector(11 DOWNTO 0)  -- sfix12_En11
          );
  END COMPONENT;

  COMPONENT Subsystem_ip_src_y_u_1
    PORT( u                               :   IN    std_logic;
          y                               :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Subsystem_ip_src_Verify_divide_sizes
    USE ENTITY work.Subsystem_ip_src_Verify_divide_sizes(rtl);

  FOR ALL : Subsystem_ip_src_ForEach_Real_Divide
    USE ENTITY work.Subsystem_ip_src_ForEach_Real_Divide(rtl);

  FOR ALL : Subsystem_ip_src_Reshape_to_original_size
    USE ENTITY work.Subsystem_ip_src_Reshape_to_original_size(rtl);

  FOR ALL : Subsystem_ip_src_y_u_1
    USE ENTITY work.Subsystem_ip_src_y_u_1(rtl);

  -- Signals
  SIGNAL den_1                            : std_logic_vector(11 DOWNTO 0);  -- ufix12
  SIGNAL num_1                            : std_logic_vector(21 DOWNTO 0);  -- ufix22
  SIGNAL ForEach_Real_Divide_out1         : std_logic_vector(11 DOWNTO 0);  -- ufix12
  SIGNAL ForEach_Real_Divide_out2         : std_logic;
  SIGNAL z                                : std_logic_vector(11 DOWNTO 0);  -- ufix12
  SIGNAL z_signed                         : signed(11 DOWNTO 0);  -- sfix12_En11
  SIGNAL Delay17_out1                     : signed(11 DOWNTO 0);  -- sfix12_En11
  SIGNAL y_1                              : std_logic;
  SIGNAL Delay1_out1                      : std_logic;

BEGIN
  u_Verify_divide_sizes : Subsystem_ip_src_Verify_divide_sizes
    PORT MAP( denominator => den,  -- sfix12_En11
              numerator => num,  -- sfix22_En11
              den => den_1,  -- sfix12_En11
              num => num_1  -- sfix22_En11
              );

  u_ForEach_Real_Divide_instance1 : Subsystem_ip_src_ForEach_Real_Divide
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_25_0 => enb_1_25_0,
              den => den_1,  -- sfix12_En11
              num => num_1,  -- sfix22_En11
              validIn => validIn,
              y => ForEach_Real_Divide_out1,  -- sfix12_En11
              validOut => ForEach_Real_Divide_out2
              );

  u_Reshape_to_original_size : Subsystem_ip_src_Reshape_to_original_size
    PORT MAP( y => ForEach_Real_Divide_out1,  -- sfix12_En11
              u => num,  -- sfix22_En11
              z => z  -- sfix12_En11
              );

  u_y_u_1 : Subsystem_ip_src_y_u_1
    PORT MAP( u => ForEach_Real_Divide_out2,
              y => y_1
              );

  z_signed <= signed(z);

  Delay17_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay17_out1 <= to_signed(16#000#, 12);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_25_0 = '1' THEN
        Delay17_out1 <= z_signed;
      END IF;
    END IF;
  END PROCESS Delay17_process;


  y <= std_logic_vector(Delay17_out1);

  Delay1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay1_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_25_0 = '1' THEN
        Delay1_out1 <= y_1;
      END IF;
    END IF;
  END PROCESS Delay1_process;


  validOut <= Delay1_out1;

END rtl;

