// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdl_model_fixed\Subsystem_ip2_src_Compare_To_Zero.v
// Created: 2024-12-16 16:15:42
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_ip2_src_Compare_To_Zero
// Source Path: hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Divide 
// by zero handler/Compare To Zer
// Hierarchy Level: 5
// Model version: 1.55
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_ip2_src_Compare_To_Zero
          (u,
           y);


  input   signed [16:0] u;  // sfix17_En15
  output  y;


  wire signed [16:0] Constant_out1;  // sfix17_En15
  wire Compare_out1;


  assign Constant_out1 = 17'sb00000000000000000;



  assign Compare_out1 = u >= Constant_out1;



  assign y = Compare_out1;

endmodule  // Subsystem_ip2_src_Compare_To_Zero

