-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\hdl_model_fixed\Subsystem_ip_src_Subsystem.vhd
-- Created: 2024-12-15 16:17:57
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Subsystem_ip_src_Subsystem
-- Source Path: hdl_model_fixed/Subsystem1/Subsystem Reference/Subsystem
-- Hierarchy Level: 2
-- Model version: 1.22
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Subsystem_ip_src_Subsystem IS
  PORT( In1                               :   IN    std_logic_vector(11 DOWNTO 0);  -- ufix12
        Out1                              :   OUT   std_logic
        );
END Subsystem_ip_src_Subsystem;


ARCHITECTURE rtl OF Subsystem_ip_src_Subsystem IS

  -- Signals
  SIGNAL In1_unsigned                     : unsigned(11 DOWNTO 0);  -- ufix12
  SIGNAL switch_compare_1                 : std_logic;
  SIGNAL Constant_out1                    : std_logic;
  SIGNAL Constant1_out1                   : std_logic;
  SIGNAL Switch_out1                      : std_logic;
  SIGNAL switch_compare_1_1               : std_logic;
  SIGNAL Switch1_out1                     : std_logic;
  SIGNAL AND_out1                         : std_logic;

BEGIN
  In1_unsigned <= unsigned(In1);

  
  switch_compare_1 <= '1' WHEN In1_unsigned > to_unsigned(16#009#, 12) ELSE
      '0';

  Constant_out1 <= '0';

  Constant1_out1 <= '1';

  
  Switch_out1 <= Constant_out1 WHEN switch_compare_1 = '0' ELSE
      Constant1_out1;

  
  switch_compare_1_1 <= '1' WHEN In1_unsigned > to_unsigned(16#400#, 12) ELSE
      '0';

  
  Switch1_out1 <= Constant1_out1 WHEN switch_compare_1_1 = '0' ELSE
      Constant_out1;

  AND_out1 <= Switch_out1 AND Switch1_out1;

  Out1 <= AND_out1;

END rtl;

