// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdl_model_fixed\Subsystem_ip2_src_CORDIC_Square_Root_HDL_Optimized1.v
// Created: 2024-12-16 16:15:42
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_ip2_src_CORDIC_Square_Root_HDL_Optimized1
// Source Path: hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex/CORDIC Square Root HDL Optimized1
// Hierarchy Level: 3
// Model version: 1.55
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_ip2_src_CORDIC_Square_Root_HDL_Optimized1
          (clk,
           reset,
           enb,
           enb_1_2_0,
           enb_1_2_1,
           u,
           validIn,
           restart,
           y,
           validOut);


  input   clk;
  input   reset;
  input   enb;
  input   enb_1_2_0;
  input   enb_1_2_1;
  input   signed [23:0] u;  // sfix24_En22
  input   validIn;
  input   restart;
  output  signed [23:0] y;  // sfix24_En22
  output  validOut;


  reg signed [23:0] delayMatch_reg [0:3];  // sfix24 [4]
  reg signed [23:0] delayMatch_reg_next [0:3];  // sfix24_En22 [4]
  reg signed [23:0] u_1;  // sfix24_En22
  wire signed [23:0] Synchronous_Subsystem_out1;  // sfix24_En22
  wire signed [31:0] Synchronous_Subsystem_out2;  // int32
  wire Synchronous_Subsystem_out3;
  wire Synchronous_Subsystem_out4;
  wire signed [23:0] Cout;  // sfix24_En22
  wire signed [23:0] y_1;  // sfix24_En22
  reg signed [31:0] delayMatch_t_0_0;  // int32
  reg signed [31:0] delayMatch_t_0_1;  // int32
  reg signed [31:0] delayMatch_t_1;  // int32


  always @(posedge clk)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        for(delayMatch_t_1 = 32'sd0; delayMatch_t_1 <= 32'sd3; delayMatch_t_1 = delayMatch_t_1 + 32'sd1) begin
          delayMatch_reg[delayMatch_t_1] <= 24'sb000000000000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch_t_0_1 = 32'sd0; delayMatch_t_0_1 <= 32'sd3; delayMatch_t_0_1 = delayMatch_t_0_1 + 32'sd1) begin
            delayMatch_reg[delayMatch_t_0_1] <= delayMatch_reg_next[delayMatch_t_0_1];
          end
        end
      end
    end

  always @* begin
    u_1 = delayMatch_reg[3];
    delayMatch_reg_next[0] = u;

    for(delayMatch_t_0_0 = 32'sd0; delayMatch_t_0_0 <= 32'sd2; delayMatch_t_0_0 = delayMatch_t_0_0 + 32'sd1) begin
      delayMatch_reg_next[delayMatch_t_0_0 + 32'sd1] = delayMatch_reg[delayMatch_t_0_0];
    end

  end



  Subsystem_ip2_src_Synchronous_Subsystem u_Synchronous_Subsystem (.clk(clk),
                                                                   .reset(reset),
                                                                   .enb(enb),
                                                                   .enb_1_2_0(enb_1_2_0),
                                                                   .enb_1_2_1(enb_1_2_1),
                                                                   .u(u),  // sfix24_En22
                                                                   .validIn(validIn),
                                                                   .restart(restart),
                                                                   .dataOut(Synchronous_Subsystem_out1),  // sfix24_En22
                                                                   .eOut(Synchronous_Subsystem_out2),  // int32
                                                                   .isZero(Synchronous_Subsystem_out3),
                                                                   .validOut(Synchronous_Subsystem_out4)
                                                                   );

  Subsystem_ip2_src_Cast_to_Union_of_Types u_Cast_to_Union_of_Types (.clk(clk),
                                                                     .reset(reset),
                                                                     .enb(enb),
                                                                     .Xref(u_1),  // sfix24_En22
                                                                     .Cin(Synchronous_Subsystem_out1),  // sfix24_En22
                                                                     .Cout(Cout)  // sfix24_En22
                                                                     );

  Subsystem_ip2_src_Bit_Shift_Arithmetic u_Bit_Shift_Arithmetic (.clk(clk),
                                                                 .reset(reset),
                                                                 .enb(enb),
                                                                 .u(Cout),  // sfix24_En22
                                                                 .e(Synchronous_Subsystem_out2),  // int32
                                                                 .isZero(Synchronous_Subsystem_out3),
                                                                 .y(y_1)  // sfix24_En22
                                                                 );

  assign y = y_1;

  assign validOut = Synchronous_Subsystem_out4;

endmodule  // Subsystem_ip2_src_CORDIC_Square_Root_HDL_Optimized1

