// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdl_model_fixed\Subsystem_ip2_src_y_u_1.v
// Created: 2024-12-16 16:15:42
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_ip2_src_y_u_1
// Source Path: hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/y = u(1)
// Hierarchy Level: 3
// Model version: 1.55
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_ip2_src_y_u_1
          (u,
           y);


  input   u;
  output  y;




  assign y = u;



endmodule  // Subsystem_ip2_src_y_u_1

