// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdl_model_fixed\Subsystem_ip2_src_Variable_Right_Shift.v
// Created: 2024-12-16 17:45:39
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_ip2_src_Variable_Right_Shift
// Source Path: hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Shift 
// and cast to output type/Variable Right Shif
// Hierarchy Level: 5
// Model version: 1.56
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_ip2_src_Variable_Right_Shift
          (clk,
           reset,
           enb_1_2_0,
           x,
           rightShift,
           y);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   signed [22:0] x;  // sfix23_En15
  input   signed [31:0] rightShift;  // int32
  output  signed [22:0] y;  // sfix23_En15


  wire Bit_Slice8_out1;  // ufix1
  reg  Delay4_out1;  // ufix1
  wire Bit_Slice7_out1;  // ufix1
  reg  Delay3_out1;  // ufix1
  wire Bit_Slice6_out1;  // ufix1
  reg  Delay2_out1;  // ufix1
  wire Bit_Slice5_out1;  // ufix1
  reg  Delay1_out1;  // ufix1
  wire Bit_Slice4_out1;  // ufix1
  wire Bit_Slice3_out1;  // ufix1
  wire Bit_Slice2_out1;  // ufix1
  wire Bit_Slice1_out1;  // ufix1
  wire signed [22:0] Bit_Shift_out1;  // sfix23_En15
  wire signed [22:0] Switch1_out1;  // sfix23_En15
  wire signed [22:0] Bit_Shift1_out1;  // sfix23_En15
  wire signed [22:0] Switch2_out1;  // sfix23_En15
  wire signed [22:0] Bit_Shift2_out1;  // sfix23_En15
  wire signed [22:0] Switch3_out1;  // sfix23_En15
  wire signed [22:0] Bit_Shift3_out1;  // sfix23_En15
  wire signed [22:0] Switch4_out1;  // sfix23_En15
  reg signed [22:0] Delay_out1;  // sfix23_En15
  wire signed [22:0] Bit_Shift4_out1;  // sfix23_En15
  wire signed [22:0] Switch5_out1;  // sfix23_En15
  wire signed [22:0] Bit_Shift5_out1;  // sfix23_En15
  wire signed [22:0] Switch6_out1;  // sfix23_En15
  wire signed [22:0] Bit_Shift6_out1;  // sfix23_En15
  wire signed [22:0] Switch7_out1;  // sfix23_En15
  wire signed [22:0] Bit_Shift7_out1;  // sfix23_En15
  wire signed [22:0] Switch8_out1;  // sfix23_En15


  assign Bit_Slice8_out1 = rightShift[7];



  always @(posedge clk)
    begin : Delay4_process
      if (reset == 1'b1) begin
        Delay4_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Delay4_out1 <= Bit_Slice8_out1;
        end
      end
    end



  assign Bit_Slice7_out1 = rightShift[6];



  always @(posedge clk)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Delay3_out1 <= Bit_Slice7_out1;
        end
      end
    end



  assign Bit_Slice6_out1 = rightShift[5];



  always @(posedge clk)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Delay2_out1 <= Bit_Slice6_out1;
        end
      end
    end



  assign Bit_Slice5_out1 = rightShift[4];



  always @(posedge clk)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Delay1_out1 <= Bit_Slice5_out1;
        end
      end
    end



  assign Bit_Slice4_out1 = rightShift[3];



  assign Bit_Slice3_out1 = rightShift[2];



  assign Bit_Slice2_out1 = rightShift[1];



  assign Bit_Slice1_out1 = rightShift[0];



  assign Bit_Shift_out1 = x >>> 8'd1;



  assign Switch1_out1 = (Bit_Slice1_out1 == 1'b0 ? x :
              Bit_Shift_out1);



  assign Bit_Shift1_out1 = Switch1_out1 >>> 8'd2;



  assign Switch2_out1 = (Bit_Slice2_out1 == 1'b0 ? Switch1_out1 :
              Bit_Shift1_out1);



  assign Bit_Shift2_out1 = Switch2_out1 >>> 8'd4;



  assign Switch3_out1 = (Bit_Slice3_out1 == 1'b0 ? Switch2_out1 :
              Bit_Shift2_out1);



  assign Bit_Shift3_out1 = Switch3_out1 >>> 8'd8;



  assign Switch4_out1 = (Bit_Slice4_out1 == 1'b0 ? Switch3_out1 :
              Bit_Shift3_out1);



  always @(posedge clk)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_out1 <= 23'sb00000000000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay_out1 <= Switch4_out1;
        end
      end
    end



  assign Bit_Shift4_out1 = Delay_out1 >>> 8'd16;



  assign Switch5_out1 = (Delay1_out1 == 1'b0 ? Delay_out1 :
              Bit_Shift4_out1);



  assign Bit_Shift5_out1 = Switch5_out1 >>> 8'd22;



  assign Switch6_out1 = (Delay2_out1 == 1'b0 ? Switch5_out1 :
              Bit_Shift5_out1);



  assign Bit_Shift6_out1 = Switch6_out1 >>> 8'd22;



  assign Switch7_out1 = (Delay3_out1 == 1'b0 ? Switch6_out1 :
              Bit_Shift6_out1);



  assign Bit_Shift7_out1 = Switch7_out1 >>> 8'd22;



  assign Switch8_out1 = (Delay4_out1 == 1'b0 ? Switch7_out1 :
              Bit_Shift7_out1);



  assign y = Switch8_out1;

endmodule  // Subsystem_ip2_src_Variable_Right_Shift

