// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdl_model_fixed\Subsystem_ip2_src_Cast_to_Union_of_Types_block2.v
// Created: 2024-12-16 17:45:39
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_ip2_src_Cast_to_Union_of_Types_block2
// Source Path: hdl_model_fixed/Subsystem1/myRMS/CORDIC Square Root HDL Optimized/Cast to Union of Types
// Hierarchy Level: 3
// Model version: 1.56
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_ip2_src_Cast_to_Union_of_Types_block2
          (Xref,
           Cin,
           Cout);


  input   [15:0] Xref;  // ufix16_En7
  input   signed [15:0] Cin;  // sfix16_En14
  output  signed [23:0] Cout;  // sfix24_En14




  //castToUnionType Cast second input to union of the two types
  assign Cout = {{8{Cin[15]}}, Cin};



endmodule  // Subsystem_ip2_src_Cast_to_Union_of_Types_block2

