-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\hdl_model_fixed\Subsystem_ip_src_Normalize_numerator.vhd
-- Created: 2024-12-15 16:17:57
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Subsystem_ip_src_Normalize_numerator
-- Source Path: hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Normalize 
-- numerato
-- Hierarchy Level: 4
-- Model version: 1.22
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Subsystem_ip_src_Normalize_numerator IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_25_0                        :   IN    std_logic;
        u                                 :   IN    std_logic_vector(21 DOWNTO 0);  -- sfix22_En11
        validIn                           :   IN    std_logic;
        x                                 :   OUT   std_logic_vector(21 DOWNTO 0);  -- sfix22_En20
        e                                 :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
        isNegative                        :   OUT   std_logic
        );
END Subsystem_ip_src_Normalize_numerator;


ARCHITECTURE rtl OF Subsystem_ip_src_Normalize_numerator IS

  -- Component Declarations
  COMPONENT Subsystem_ip_src_positiveRealNormalizer
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_25_0                      :   IN    std_logic;
          u                               :   IN    std_logic_vector(21 DOWNTO 0);  -- sfix22_En11
          validIn                         :   IN    std_logic;
          x                               :   OUT   std_logic_vector(21 DOWNTO 0);  -- sfix22_En20
          e                               :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
          isNegative                      :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Subsystem_ip_src_positiveRealNormalizer
    USE ENTITY work.Subsystem_ip_src_positiveRealNormalizer(rtl);

  -- Signals
  SIGNAL x_tmp                            : std_logic_vector(21 DOWNTO 0);  -- ufix22
  SIGNAL e_tmp                            : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_positiveRealNormalizer : Subsystem_ip_src_positiveRealNormalizer
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_25_0 => enb_1_25_0,
              u => u,  -- sfix22_En11
              validIn => validIn,
              x => x_tmp,  -- sfix22_En20
              e => e_tmp,  -- int32
              isNegative => isNegative
              );

  x <= x_tmp;

  e <= e_tmp;

END rtl;

