// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdl_model_fixed\Synchronous_Subsystem.v
// Created: 2024-12-20 21:02:03
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Synchronous_Subsystem

// Source Path: hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex/CORDIC Square Root HDL Optimized1/Synchronous 
// Subsyste
// Hierarchy Level: 4
// Model version: 1.105
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Synchronous_Subsystem
          (clk,
           reset,
           enb,
           u_u,
           validIn,
           restart,
           dataOut,
           eOut,
           isZero,
           validOut);


  input   clk;
  input   reset;
  input   enb;
  input   signed [23:0] u_u;  // sfix24_En22
  input   validIn;
  input   restart;
  output  signed [23:0] dataOut;  // sfix24_En22
  output  signed [31:0] eOut;  // int32
  output  isZero;
  output  validOut;




  cordicSquareRootHDL cordicSquareRootHDL_1_1 (.clk(clk),
                                               .reset(reset),
                                               .enb(enb),
                                               .u_u(u_u),  // sfix24_En22
                                               .validIn(validIn),
                                               .restart(restart),
                                               .dataOut(dataOut),  // sfix24_En22
                                               .eOut(eOut),  // int32
                                               .isZero(isZero),
                                               .validOut(validOut)
                                               );

endmodule  // Synchronous_Subsystem

