// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdl_model_fixed\Synchronous_Subsystem_block.v
// Created: 2024-12-20 21:02:03
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Synchronous_Subsystem_block

// Source Path: hdl_model_fixed/Subsystem1/Subsystem Reference/CORDIC Square Root HDL Optimized/Synchronous Subsystem
// Hierarchy Level: 3
// Model version: 1.105
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Synchronous_Subsystem_block
          (clk,
           reset,
           enb,
           u_u,
           validIn,
           restart,
           dataOut,
           eOut,
           isZero,
           validOut);


  input   clk;
  input   reset;
  input   enb;
  input   signed [21:0] u_u;  // sfix22_En20
  input   validIn;
  input   restart;
  output  signed [21:0] dataOut;  // sfix22_En20
  output  signed [31:0] eOut;  // int32
  output  isZero;
  output  validOut;




  cordicSquareRootHDL_block cordicSquareRootHDL_1 (.clk(clk),
                                                   .reset(reset),
                                                   .enb(enb),
                                                   .u_u(u_u),  // sfix22_En20
                                                   .validIn(validIn),
                                                   .restart(restart),
                                                   .dataOut(dataOut),  // sfix22_En20
                                                   .eOut(eOut),  // int32
                                                   .isZero(isZero),
                                                   .validOut(validOut)
                                                   );

endmodule  // Synchronous_Subsystem_block

