-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\hdl_model_fixed\TWDLROM_3_1.vhd
-- Created: 2024-12-15 20:50:14
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: TWDLROM_3_1
-- Source Path: hdl_model_fixed/Subsystem1/FFT/TWDLROM_3_1
-- Hierarchy Level: 2
-- Model version: 1.30
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.Subsystem1_pkg.ALL;

ENTITY TWDLROM_3_1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_25_0                        :   IN    std_logic;
        dout_2_1_vld                      :   IN    std_logic;
        syncReset                         :   IN    std_logic;
        twdl_3_1_re                       :   OUT   std_logic_vector(11 DOWNTO 0);  -- sfix12_En10
        twdl_3_1_im                       :   OUT   std_logic_vector(11 DOWNTO 0)  -- sfix12_En10
        );
END TWDLROM_3_1;


ARCHITECTURE rtl OF TWDLROM_3_1 IS

  -- Constants
  CONSTANT Twiddle_re_table_data          : vector_of_signed12(0 TO 255) := 
    (to_signed(16#400#, 12), to_signed(16#400#, 12), to_signed(16#400#, 12), to_signed(16#400#, 12),
     to_signed(16#400#, 12), to_signed(16#400#, 12), to_signed(16#400#, 12), to_signed(16#400#, 12),
     to_signed(16#400#, 12), to_signed(16#400#, 12), to_signed(16#400#, 12), to_signed(16#3FF#, 12),
     to_signed(16#3FF#, 12), to_signed(16#3FF#, 12), to_signed(16#3FF#, 12), to_signed(16#3FF#, 12),
     to_signed(16#3FF#, 12), to_signed(16#3FF#, 12), to_signed(16#3FE#, 12), to_signed(16#3FE#, 12),
     to_signed(16#3FE#, 12), to_signed(16#3FE#, 12), to_signed(16#3FE#, 12), to_signed(16#3FD#, 12),
     to_signed(16#3FD#, 12), to_signed(16#3FD#, 12), to_signed(16#3FD#, 12), to_signed(16#3FC#, 12),
     to_signed(16#3FC#, 12), to_signed(16#3FC#, 12), to_signed(16#3FC#, 12), to_signed(16#3FB#, 12),
     to_signed(16#3FB#, 12), to_signed(16#3FB#, 12), to_signed(16#3FA#, 12), to_signed(16#3FA#, 12),
     to_signed(16#3FA#, 12), to_signed(16#3F9#, 12), to_signed(16#3F9#, 12), to_signed(16#3F9#, 12),
     to_signed(16#3F8#, 12), to_signed(16#3F8#, 12), to_signed(16#3F8#, 12), to_signed(16#3F7#, 12),
     to_signed(16#3F7#, 12), to_signed(16#3F6#, 12), to_signed(16#3F6#, 12), to_signed(16#3F5#, 12),
     to_signed(16#3F5#, 12), to_signed(16#3F4#, 12), to_signed(16#3F4#, 12), to_signed(16#3F3#, 12),
     to_signed(16#3F3#, 12), to_signed(16#3F2#, 12), to_signed(16#3F2#, 12), to_signed(16#3F1#, 12),
     to_signed(16#3F1#, 12), to_signed(16#3F0#, 12), to_signed(16#3F0#, 12), to_signed(16#3EF#, 12),
     to_signed(16#3EF#, 12), to_signed(16#3EE#, 12), to_signed(16#3EE#, 12), to_signed(16#3ED#, 12),
     to_signed(16#3EC#, 12), to_signed(16#3EC#, 12), to_signed(16#3EB#, 12), to_signed(16#3EA#, 12),
     to_signed(16#3EA#, 12), to_signed(16#3E9#, 12), to_signed(16#3E8#, 12), to_signed(16#3E8#, 12),
     to_signed(16#3E7#, 12), to_signed(16#3E6#, 12), to_signed(16#3E6#, 12), to_signed(16#3E5#, 12),
     to_signed(16#3E4#, 12), to_signed(16#3E4#, 12), to_signed(16#3E3#, 12), to_signed(16#3E2#, 12),
     to_signed(16#3E1#, 12), to_signed(16#3E1#, 12), to_signed(16#3E0#, 12), to_signed(16#3DF#, 12),
     to_signed(16#3DE#, 12), to_signed(16#3DD#, 12), to_signed(16#3DD#, 12), to_signed(16#3DC#, 12),
     to_signed(16#3DB#, 12), to_signed(16#3DA#, 12), to_signed(16#3D9#, 12), to_signed(16#3D8#, 12),
     to_signed(16#3D7#, 12), to_signed(16#3D7#, 12), to_signed(16#3D6#, 12), to_signed(16#3D5#, 12),
     to_signed(16#3D4#, 12), to_signed(16#3D3#, 12), to_signed(16#3D2#, 12), to_signed(16#3D1#, 12),
     to_signed(16#3D0#, 12), to_signed(16#3CF#, 12), to_signed(16#3CE#, 12), to_signed(16#3CD#, 12),
     to_signed(16#3CC#, 12), to_signed(16#3CB#, 12), to_signed(16#3CA#, 12), to_signed(16#3C9#, 12),
     to_signed(16#3C8#, 12), to_signed(16#3C7#, 12), to_signed(16#3C6#, 12), to_signed(16#3C5#, 12),
     to_signed(16#3C4#, 12), to_signed(16#3C3#, 12), to_signed(16#3C2#, 12), to_signed(16#3C1#, 12),
     to_signed(16#3C0#, 12), to_signed(16#3BF#, 12), to_signed(16#3BE#, 12), to_signed(16#3BD#, 12),
     to_signed(16#3BB#, 12), to_signed(16#3BA#, 12), to_signed(16#3B9#, 12), to_signed(16#3B8#, 12),
     to_signed(16#3B7#, 12), to_signed(16#3B6#, 12), to_signed(16#3B4#, 12), to_signed(16#3B3#, 12),
     to_signed(16#3B2#, 12), to_signed(16#3B1#, 12), to_signed(16#3B0#, 12), to_signed(16#3AE#, 12),
     to_signed(16#3AD#, 12), to_signed(16#3AC#, 12), to_signed(16#3AB#, 12), to_signed(16#3A9#, 12),
     to_signed(16#3A8#, 12), to_signed(16#3A7#, 12), to_signed(16#3A6#, 12), to_signed(16#3A4#, 12),
     to_signed(16#3A3#, 12), to_signed(16#3A2#, 12), to_signed(16#3A0#, 12), to_signed(16#39F#, 12),
     to_signed(16#39E#, 12), to_signed(16#39C#, 12), to_signed(16#39B#, 12), to_signed(16#39A#, 12),
     to_signed(16#398#, 12), to_signed(16#397#, 12), to_signed(16#395#, 12), to_signed(16#394#, 12),
     to_signed(16#393#, 12), to_signed(16#391#, 12), to_signed(16#390#, 12), to_signed(16#38E#, 12),
     to_signed(16#38D#, 12), to_signed(16#38B#, 12), to_signed(16#38A#, 12), to_signed(16#389#, 12),
     to_signed(16#387#, 12), to_signed(16#386#, 12), to_signed(16#384#, 12), to_signed(16#383#, 12),
     to_signed(16#381#, 12), to_signed(16#380#, 12), to_signed(16#37E#, 12), to_signed(16#37D#, 12),
     to_signed(16#37B#, 12), to_signed(16#379#, 12), to_signed(16#378#, 12), to_signed(16#376#, 12),
     to_signed(16#375#, 12), to_signed(16#373#, 12), to_signed(16#372#, 12), to_signed(16#370#, 12),
     to_signed(16#36E#, 12), to_signed(16#36D#, 12), to_signed(16#36B#, 12), to_signed(16#369#, 12),
     to_signed(16#368#, 12), to_signed(16#366#, 12), to_signed(16#364#, 12), to_signed(16#363#, 12),
     to_signed(16#361#, 12), to_signed(16#35F#, 12), to_signed(16#35E#, 12), to_signed(16#35C#, 12),
     to_signed(16#35A#, 12), to_signed(16#359#, 12), to_signed(16#357#, 12), to_signed(16#355#, 12),
     to_signed(16#353#, 12), to_signed(16#352#, 12), to_signed(16#350#, 12), to_signed(16#34E#, 12),
     to_signed(16#34C#, 12), to_signed(16#34B#, 12), to_signed(16#349#, 12), to_signed(16#347#, 12),
     to_signed(16#345#, 12), to_signed(16#343#, 12), to_signed(16#342#, 12), to_signed(16#340#, 12),
     to_signed(16#33E#, 12), to_signed(16#33C#, 12), to_signed(16#33A#, 12), to_signed(16#338#, 12),
     to_signed(16#336#, 12), to_signed(16#335#, 12), to_signed(16#333#, 12), to_signed(16#331#, 12),
     to_signed(16#32F#, 12), to_signed(16#32D#, 12), to_signed(16#32B#, 12), to_signed(16#329#, 12),
     to_signed(16#327#, 12), to_signed(16#325#, 12), to_signed(16#323#, 12), to_signed(16#321#, 12),
     to_signed(16#31F#, 12), to_signed(16#31E#, 12), to_signed(16#31C#, 12), to_signed(16#31A#, 12),
     to_signed(16#318#, 12), to_signed(16#316#, 12), to_signed(16#314#, 12), to_signed(16#312#, 12),
     to_signed(16#310#, 12), to_signed(16#30E#, 12), to_signed(16#30B#, 12), to_signed(16#309#, 12),
     to_signed(16#307#, 12), to_signed(16#305#, 12), to_signed(16#303#, 12), to_signed(16#301#, 12),
     to_signed(16#2FF#, 12), to_signed(16#2FD#, 12), to_signed(16#2FB#, 12), to_signed(16#2F9#, 12),
     to_signed(16#2F7#, 12), to_signed(16#2F5#, 12), to_signed(16#2F3#, 12), to_signed(16#2F0#, 12),
     to_signed(16#2EE#, 12), to_signed(16#2EC#, 12), to_signed(16#2EA#, 12), to_signed(16#2E8#, 12),
     to_signed(16#2E6#, 12), to_signed(16#2E3#, 12), to_signed(16#2E1#, 12), to_signed(16#2DF#, 12),
     to_signed(16#2DD#, 12), to_signed(16#2DB#, 12), to_signed(16#2D9#, 12), to_signed(16#2D6#, 12));  -- sfix12 [256]
  CONSTANT Twiddle_im_table_data          : vector_of_signed12(0 TO 255) := 
    (to_signed(16#000#, 12), to_signed(-16#003#, 12), to_signed(-16#006#, 12), to_signed(-16#009#, 12),
     to_signed(-16#00D#, 12), to_signed(-16#010#, 12), to_signed(-16#013#, 12), to_signed(-16#016#, 12),
     to_signed(-16#019#, 12), to_signed(-16#01C#, 12), to_signed(-16#01F#, 12), to_signed(-16#023#, 12),
     to_signed(-16#026#, 12), to_signed(-16#029#, 12), to_signed(-16#02C#, 12), to_signed(-16#02F#, 12),
     to_signed(-16#032#, 12), to_signed(-16#035#, 12), to_signed(-16#039#, 12), to_signed(-16#03C#, 12),
     to_signed(-16#03F#, 12), to_signed(-16#042#, 12), to_signed(-16#045#, 12), to_signed(-16#048#, 12),
     to_signed(-16#04B#, 12), to_signed(-16#04E#, 12), to_signed(-16#052#, 12), to_signed(-16#055#, 12),
     to_signed(-16#058#, 12), to_signed(-16#05B#, 12), to_signed(-16#05E#, 12), to_signed(-16#061#, 12),
     to_signed(-16#064#, 12), to_signed(-16#067#, 12), to_signed(-16#06B#, 12), to_signed(-16#06E#, 12),
     to_signed(-16#071#, 12), to_signed(-16#074#, 12), to_signed(-16#077#, 12), to_signed(-16#07A#, 12),
     to_signed(-16#07D#, 12), to_signed(-16#080#, 12), to_signed(-16#084#, 12), to_signed(-16#087#, 12),
     to_signed(-16#08A#, 12), to_signed(-16#08D#, 12), to_signed(-16#090#, 12), to_signed(-16#093#, 12),
     to_signed(-16#096#, 12), to_signed(-16#099#, 12), to_signed(-16#09C#, 12), to_signed(-16#0A0#, 12),
     to_signed(-16#0A3#, 12), to_signed(-16#0A6#, 12), to_signed(-16#0A9#, 12), to_signed(-16#0AC#, 12),
     to_signed(-16#0AF#, 12), to_signed(-16#0B2#, 12), to_signed(-16#0B5#, 12), to_signed(-16#0B8#, 12),
     to_signed(-16#0BB#, 12), to_signed(-16#0BF#, 12), to_signed(-16#0C2#, 12), to_signed(-16#0C5#, 12),
     to_signed(-16#0C8#, 12), to_signed(-16#0CB#, 12), to_signed(-16#0CE#, 12), to_signed(-16#0D1#, 12),
     to_signed(-16#0D4#, 12), to_signed(-16#0D7#, 12), to_signed(-16#0DA#, 12), to_signed(-16#0DD#, 12),
     to_signed(-16#0E0#, 12), to_signed(-16#0E3#, 12), to_signed(-16#0E6#, 12), to_signed(-16#0EA#, 12),
     to_signed(-16#0ED#, 12), to_signed(-16#0F0#, 12), to_signed(-16#0F3#, 12), to_signed(-16#0F6#, 12),
     to_signed(-16#0F9#, 12), to_signed(-16#0FC#, 12), to_signed(-16#0FF#, 12), to_signed(-16#102#, 12),
     to_signed(-16#105#, 12), to_signed(-16#108#, 12), to_signed(-16#10B#, 12), to_signed(-16#10E#, 12),
     to_signed(-16#111#, 12), to_signed(-16#114#, 12), to_signed(-16#117#, 12), to_signed(-16#11A#, 12),
     to_signed(-16#11D#, 12), to_signed(-16#120#, 12), to_signed(-16#123#, 12), to_signed(-16#126#, 12),
     to_signed(-16#129#, 12), to_signed(-16#12C#, 12), to_signed(-16#12F#, 12), to_signed(-16#132#, 12),
     to_signed(-16#135#, 12), to_signed(-16#138#, 12), to_signed(-16#13B#, 12), to_signed(-16#13E#, 12),
     to_signed(-16#141#, 12), to_signed(-16#144#, 12), to_signed(-16#147#, 12), to_signed(-16#14A#, 12),
     to_signed(-16#14D#, 12), to_signed(-16#150#, 12), to_signed(-16#153#, 12), to_signed(-16#156#, 12),
     to_signed(-16#159#, 12), to_signed(-16#15C#, 12), to_signed(-16#15F#, 12), to_signed(-16#162#, 12),
     to_signed(-16#165#, 12), to_signed(-16#168#, 12), to_signed(-16#16B#, 12), to_signed(-16#16E#, 12),
     to_signed(-16#171#, 12), to_signed(-16#173#, 12), to_signed(-16#176#, 12), to_signed(-16#179#, 12),
     to_signed(-16#17C#, 12), to_signed(-16#17F#, 12), to_signed(-16#182#, 12), to_signed(-16#185#, 12),
     to_signed(-16#188#, 12), to_signed(-16#18B#, 12), to_signed(-16#18E#, 12), to_signed(-16#191#, 12),
     to_signed(-16#193#, 12), to_signed(-16#196#, 12), to_signed(-16#199#, 12), to_signed(-16#19C#, 12),
     to_signed(-16#19F#, 12), to_signed(-16#1A2#, 12), to_signed(-16#1A5#, 12), to_signed(-16#1A8#, 12),
     to_signed(-16#1AA#, 12), to_signed(-16#1AD#, 12), to_signed(-16#1B0#, 12), to_signed(-16#1B3#, 12),
     to_signed(-16#1B6#, 12), to_signed(-16#1B9#, 12), to_signed(-16#1BB#, 12), to_signed(-16#1BE#, 12),
     to_signed(-16#1C1#, 12), to_signed(-16#1C4#, 12), to_signed(-16#1C7#, 12), to_signed(-16#1CA#, 12),
     to_signed(-16#1CC#, 12), to_signed(-16#1CF#, 12), to_signed(-16#1D2#, 12), to_signed(-16#1D5#, 12),
     to_signed(-16#1D8#, 12), to_signed(-16#1DA#, 12), to_signed(-16#1DD#, 12), to_signed(-16#1E0#, 12),
     to_signed(-16#1E3#, 12), to_signed(-16#1E5#, 12), to_signed(-16#1E8#, 12), to_signed(-16#1EB#, 12),
     to_signed(-16#1EE#, 12), to_signed(-16#1F1#, 12), to_signed(-16#1F3#, 12), to_signed(-16#1F6#, 12),
     to_signed(-16#1F9#, 12), to_signed(-16#1FB#, 12), to_signed(-16#1FE#, 12), to_signed(-16#201#, 12),
     to_signed(-16#204#, 12), to_signed(-16#206#, 12), to_signed(-16#209#, 12), to_signed(-16#20C#, 12),
     to_signed(-16#20E#, 12), to_signed(-16#211#, 12), to_signed(-16#214#, 12), to_signed(-16#217#, 12),
     to_signed(-16#219#, 12), to_signed(-16#21C#, 12), to_signed(-16#21F#, 12), to_signed(-16#221#, 12),
     to_signed(-16#224#, 12), to_signed(-16#226#, 12), to_signed(-16#229#, 12), to_signed(-16#22C#, 12),
     to_signed(-16#22E#, 12), to_signed(-16#231#, 12), to_signed(-16#234#, 12), to_signed(-16#236#, 12),
     to_signed(-16#239#, 12), to_signed(-16#23C#, 12), to_signed(-16#23E#, 12), to_signed(-16#241#, 12),
     to_signed(-16#243#, 12), to_signed(-16#246#, 12), to_signed(-16#248#, 12), to_signed(-16#24B#, 12),
     to_signed(-16#24E#, 12), to_signed(-16#250#, 12), to_signed(-16#253#, 12), to_signed(-16#255#, 12),
     to_signed(-16#258#, 12), to_signed(-16#25A#, 12), to_signed(-16#25D#, 12), to_signed(-16#25F#, 12),
     to_signed(-16#262#, 12), to_signed(-16#265#, 12), to_signed(-16#267#, 12), to_signed(-16#26A#, 12),
     to_signed(-16#26C#, 12), to_signed(-16#26F#, 12), to_signed(-16#271#, 12), to_signed(-16#274#, 12),
     to_signed(-16#276#, 12), to_signed(-16#278#, 12), to_signed(-16#27B#, 12), to_signed(-16#27D#, 12),
     to_signed(-16#280#, 12), to_signed(-16#282#, 12), to_signed(-16#285#, 12), to_signed(-16#287#, 12),
     to_signed(-16#28A#, 12), to_signed(-16#28C#, 12), to_signed(-16#28E#, 12), to_signed(-16#291#, 12),
     to_signed(-16#293#, 12), to_signed(-16#296#, 12), to_signed(-16#298#, 12), to_signed(-16#29A#, 12),
     to_signed(-16#29D#, 12), to_signed(-16#29F#, 12), to_signed(-16#2A2#, 12), to_signed(-16#2A4#, 12),
     to_signed(-16#2A6#, 12), to_signed(-16#2A9#, 12), to_signed(-16#2AB#, 12), to_signed(-16#2AD#, 12),
     to_signed(-16#2B0#, 12), to_signed(-16#2B2#, 12), to_signed(-16#2B4#, 12), to_signed(-16#2B7#, 12),
     to_signed(-16#2B9#, 12), to_signed(-16#2BB#, 12), to_signed(-16#2BE#, 12), to_signed(-16#2C0#, 12),
     to_signed(-16#2C2#, 12), to_signed(-16#2C4#, 12), to_signed(-16#2C7#, 12), to_signed(-16#2C9#, 12),
     to_signed(-16#2CB#, 12), to_signed(-16#2CD#, 12), to_signed(-16#2D0#, 12), to_signed(-16#2D2#, 12));  -- sfix12 [256]

  -- Signals
  SIGNAL Radix22TwdlMapping_cnt           : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL Radix22TwdlMapping_phase         : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL Radix22TwdlMapping_octantReg1    : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL Radix22TwdlMapping_twdlAddr_raw  : unsigned(10 DOWNTO 0);  -- ufix11
  SIGNAL Radix22TwdlMapping_twdlAddrMap   : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL Radix22TwdlMapping_twdl45Reg     : std_logic;
  SIGNAL Radix22TwdlMapping_dvldReg1      : std_logic;
  SIGNAL Radix22TwdlMapping_dvldReg2      : std_logic;
  SIGNAL Radix22TwdlMapping_cnt_next      : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL Radix22TwdlMapping_phase_next    : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL Radix22TwdlMapping_octantReg1_next : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL Radix22TwdlMapping_twdlAddr_raw_next : unsigned(10 DOWNTO 0);  -- ufix11
  SIGNAL Radix22TwdlMapping_twdlAddrMap_next : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL Radix22TwdlMapping_twdl45Reg_next : std_logic;
  SIGNAL Radix22TwdlMapping_dvldReg1_next : std_logic;
  SIGNAL Radix22TwdlMapping_dvldReg2_next : std_logic;
  SIGNAL twdlAddr                         : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL twdlAddrVld                      : std_logic;
  SIGNAL twdlOctant                       : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL twdl45                           : std_logic;
  SIGNAL twiddleS_re                      : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL twiddleReg_re                    : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL twiddleS_im                      : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL twiddleReg_im                    : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL twdlOctantReg                    : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL twdl45Reg                        : std_logic;
  SIGNAL twdl_3_1_re_tmp                  : signed(11 DOWNTO 0);  -- sfix12_En10
  SIGNAL twdl_3_1_im_tmp                  : signed(11 DOWNTO 0);  -- sfix12_En10

BEGIN
  -- Radix22TwdlMapping
  Radix22TwdlMapping_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Radix22TwdlMapping_octantReg1 <= to_unsigned(16#0#, 3);
      Radix22TwdlMapping_twdlAddr_raw <= to_unsigned(16#000#, 11);
      Radix22TwdlMapping_twdlAddrMap <= to_unsigned(16#00#, 8);
      Radix22TwdlMapping_twdl45Reg <= '0';
      Radix22TwdlMapping_dvldReg1 <= '0';
      Radix22TwdlMapping_dvldReg2 <= '0';
      Radix22TwdlMapping_cnt <= to_unsigned(16#000#, 9);
      Radix22TwdlMapping_phase <= to_unsigned(16#0#, 2);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_25_0 = '1' THEN
        IF syncReset = '1' THEN
          Radix22TwdlMapping_octantReg1 <= to_unsigned(16#0#, 3);
          Radix22TwdlMapping_twdlAddr_raw <= to_unsigned(16#000#, 11);
          Radix22TwdlMapping_twdlAddrMap <= to_unsigned(16#00#, 8);
          Radix22TwdlMapping_twdl45Reg <= '0';
          Radix22TwdlMapping_dvldReg1 <= '0';
          Radix22TwdlMapping_dvldReg2 <= '0';
          Radix22TwdlMapping_cnt <= to_unsigned(16#000#, 9);
          Radix22TwdlMapping_phase <= to_unsigned(16#0#, 2);
        ELSE 
          Radix22TwdlMapping_cnt <= Radix22TwdlMapping_cnt_next;
          Radix22TwdlMapping_phase <= Radix22TwdlMapping_phase_next;
          Radix22TwdlMapping_octantReg1 <= Radix22TwdlMapping_octantReg1_next;
          Radix22TwdlMapping_twdlAddr_raw <= Radix22TwdlMapping_twdlAddr_raw_next;
          Radix22TwdlMapping_twdlAddrMap <= Radix22TwdlMapping_twdlAddrMap_next;
          Radix22TwdlMapping_twdl45Reg <= Radix22TwdlMapping_twdl45Reg_next;
          Radix22TwdlMapping_dvldReg1 <= Radix22TwdlMapping_dvldReg1_next;
          Radix22TwdlMapping_dvldReg2 <= Radix22TwdlMapping_dvldReg2_next;
        END IF;
      END IF;
    END IF;
  END PROCESS Radix22TwdlMapping_process;

  Radix22TwdlMapping_output : PROCESS (Radix22TwdlMapping_cnt, Radix22TwdlMapping_dvldReg1,
       Radix22TwdlMapping_dvldReg2, Radix22TwdlMapping_octantReg1,
       Radix22TwdlMapping_phase, Radix22TwdlMapping_twdl45Reg,
       Radix22TwdlMapping_twdlAddrMap, Radix22TwdlMapping_twdlAddr_raw,
       dout_2_1_vld)
    VARIABLE octant : unsigned(2 DOWNTO 0);
    VARIABLE cnt_cast : unsigned(10 DOWNTO 0);
    VARIABLE sub_cast : signed(23 DOWNTO 0);
    VARIABLE sub_temp : signed(23 DOWNTO 0);
    VARIABLE sub_cast_0 : signed(12 DOWNTO 0);
    VARIABLE sub_temp_0 : signed(12 DOWNTO 0);
    VARIABLE sub_cast_1 : signed(12 DOWNTO 0);
    VARIABLE sub_temp_1 : signed(12 DOWNTO 0);
    VARIABLE sub_cast_2 : signed(23 DOWNTO 0);
    VARIABLE sub_temp_2 : signed(23 DOWNTO 0);
    VARIABLE sub_cast_3 : signed(23 DOWNTO 0);
    VARIABLE sub_temp_3 : signed(23 DOWNTO 0);
  BEGIN
    sub_temp := to_signed(16#000000#, 24);
    sub_temp_0 := to_signed(16#0000#, 13);
    sub_temp_1 := to_signed(16#0000#, 13);
    sub_temp_2 := to_signed(16#000000#, 24);
    sub_temp_3 := to_signed(16#000000#, 24);
    sub_cast_3 := to_signed(16#000000#, 24);
    cnt_cast := to_unsigned(16#000#, 11);
    sub_cast_2 := to_signed(16#000000#, 24);
    sub_cast_1 := to_signed(16#0000#, 13);
    sub_cast_0 := to_signed(16#0000#, 13);
    sub_cast := to_signed(16#000000#, 24);
    Radix22TwdlMapping_cnt_next <= Radix22TwdlMapping_cnt;
    Radix22TwdlMapping_phase_next <= Radix22TwdlMapping_phase;
    Radix22TwdlMapping_dvldReg2_next <= Radix22TwdlMapping_dvldReg1;
    Radix22TwdlMapping_dvldReg1_next <= dout_2_1_vld;
    CASE Radix22TwdlMapping_twdlAddr_raw IS
      WHEN "00100000000" =>
        octant := to_unsigned(16#0#, 3);
        Radix22TwdlMapping_twdl45Reg_next <= '1';
      WHEN "01000000000" =>
        octant := to_unsigned(16#1#, 3);
        Radix22TwdlMapping_twdl45Reg_next <= '0';
      WHEN "01100000000" =>
        octant := to_unsigned(16#2#, 3);
        Radix22TwdlMapping_twdl45Reg_next <= '1';
      WHEN "10000000000" =>
        octant := to_unsigned(16#3#, 3);
        Radix22TwdlMapping_twdl45Reg_next <= '0';
      WHEN "10100000000" =>
        octant := to_unsigned(16#4#, 3);
        Radix22TwdlMapping_twdl45Reg_next <= '1';
      WHEN OTHERS => 
        octant := Radix22TwdlMapping_twdlAddr_raw(10 DOWNTO 8);
        Radix22TwdlMapping_twdl45Reg_next <= '0';
    END CASE;
    Radix22TwdlMapping_octantReg1_next <= octant;
    CASE octant IS
      WHEN "000" =>
        Radix22TwdlMapping_twdlAddrMap_next <= Radix22TwdlMapping_twdlAddr_raw(7 DOWNTO 0);
      WHEN "001" =>
        sub_cast_0 := signed(resize(Radix22TwdlMapping_twdlAddr_raw, 13));
        sub_temp_0 := to_signed(16#0200#, 13) - sub_cast_0;
        Radix22TwdlMapping_twdlAddrMap_next <= unsigned(sub_temp_0(7 DOWNTO 0));
      WHEN "010" =>
        sub_cast_1 := signed(resize(Radix22TwdlMapping_twdlAddr_raw, 13));
        sub_temp_1 := sub_cast_1 - to_signed(16#0200#, 13);
        Radix22TwdlMapping_twdlAddrMap_next <= unsigned(sub_temp_1(7 DOWNTO 0));
      WHEN "011" =>
        sub_cast_2 := signed(resize(Radix22TwdlMapping_twdlAddr_raw & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 24));
        sub_temp_2 := to_signed(16#040000#, 24) - sub_cast_2;
        Radix22TwdlMapping_twdlAddrMap_next <= unsigned(sub_temp_2(15 DOWNTO 8));
      WHEN "100" =>
        sub_cast_3 := signed(resize(Radix22TwdlMapping_twdlAddr_raw & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 24));
        sub_temp_3 := sub_cast_3 - to_signed(16#040000#, 24);
        Radix22TwdlMapping_twdlAddrMap_next <= unsigned(sub_temp_3(15 DOWNTO 8));
      WHEN OTHERS => 
        sub_cast := signed(resize(Radix22TwdlMapping_twdlAddr_raw & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 24));
        sub_temp := to_signed(16#060000#, 24) - sub_cast;
        Radix22TwdlMapping_twdlAddrMap_next <= unsigned(sub_temp(15 DOWNTO 8));
    END CASE;
    IF Radix22TwdlMapping_phase = to_unsigned(16#0#, 2) THEN 
      Radix22TwdlMapping_twdlAddr_raw_next <= to_unsigned(16#000#, 11);
    ELSIF Radix22TwdlMapping_phase = to_unsigned(16#1#, 2) THEN 
      Radix22TwdlMapping_twdlAddr_raw_next <= resize(Radix22TwdlMapping_cnt, 11) sll 1;
    ELSIF Radix22TwdlMapping_phase = to_unsigned(16#2#, 2) THEN 
      Radix22TwdlMapping_twdlAddr_raw_next <= resize(Radix22TwdlMapping_cnt, 11);
    ELSE 
      cnt_cast := resize(Radix22TwdlMapping_cnt, 11);
      Radix22TwdlMapping_twdlAddr_raw_next <= (cnt_cast sll 1) + cnt_cast;
    END IF;
    IF dout_2_1_vld = '1' AND (Radix22TwdlMapping_cnt > to_unsigned(16#1FE#, 9)) THEN 
      Radix22TwdlMapping_phase_next <= Radix22TwdlMapping_phase + to_unsigned(16#1#, 2);
    END IF;
    IF dout_2_1_vld = '1' THEN 
      Radix22TwdlMapping_cnt_next <= Radix22TwdlMapping_cnt + to_unsigned(16#001#, 9);
    END IF;
    twdlAddr <= Radix22TwdlMapping_twdlAddrMap;
    twdlAddrVld <= Radix22TwdlMapping_dvldReg2;
    twdlOctant <= Radix22TwdlMapping_octantReg1;
    twdl45 <= Radix22TwdlMapping_twdl45Reg;
  END PROCESS Radix22TwdlMapping_output;


  -- Twiddle ROM1
  twiddleS_re <= Twiddle_re_table_data(to_integer(twdlAddr));

  TWIDDLEROM_RE_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      twiddleReg_re <= to_signed(16#000#, 12);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_25_0 = '1' THEN
        twiddleReg_re <= twiddleS_re;
      END IF;
    END IF;
  END PROCESS TWIDDLEROM_RE_process;


  -- Twiddle ROM2
  twiddleS_im <= Twiddle_im_table_data(to_integer(twdlAddr));

  TWIDDLEROM_IM_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      twiddleReg_im <= to_signed(16#000#, 12);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_25_0 = '1' THEN
        twiddleReg_im <= twiddleS_im;
      END IF;
    END IF;
  END PROCESS TWIDDLEROM_IM_process;


  intdelay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      twdlOctantReg <= to_unsigned(16#0#, 3);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_25_0 = '1' THEN
        IF syncReset = '1' THEN
          twdlOctantReg <= to_unsigned(16#0#, 3);
        ELSE 
          twdlOctantReg <= twdlOctant;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_process;


  intdelay_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      twdl45Reg <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_25_0 = '1' THEN
        IF syncReset = '1' THEN
          twdl45Reg <= '0';
        ELSE 
          twdl45Reg <= twdl45;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_1_process;


  -- Radix22TwdlOctCorr
  Radix22TwdlOctCorr_output : PROCESS (twdl45Reg, twdlOctantReg, twiddleReg_im, twiddleReg_re)
    VARIABLE twdlIn_re : signed(11 DOWNTO 0);
    VARIABLE twdlIn_im : signed(11 DOWNTO 0);
    VARIABLE cast : signed(12 DOWNTO 0);
    VARIABLE cast_0 : signed(12 DOWNTO 0);
    VARIABLE cast_1 : signed(12 DOWNTO 0);
    VARIABLE cast_2 : signed(12 DOWNTO 0);
    VARIABLE cast_3 : signed(12 DOWNTO 0);
    VARIABLE cast_4 : signed(12 DOWNTO 0);
    VARIABLE cast_5 : signed(12 DOWNTO 0);
    VARIABLE cast_6 : signed(12 DOWNTO 0);
    VARIABLE cast_7 : signed(12 DOWNTO 0);
    VARIABLE cast_8 : signed(12 DOWNTO 0);
    VARIABLE cast_9 : signed(12 DOWNTO 0);
    VARIABLE cast_10 : signed(12 DOWNTO 0);
  BEGIN
    cast_0 := to_signed(16#0000#, 13);
    cast_2 := to_signed(16#0000#, 13);
    cast_4 := to_signed(16#0000#, 13);
    cast_6 := to_signed(16#0000#, 13);
    cast_8 := to_signed(16#0000#, 13);
    cast_10 := to_signed(16#0000#, 13);
    cast_3 := to_signed(16#0000#, 13);
    cast_9 := to_signed(16#0000#, 13);
    cast_1 := to_signed(16#0000#, 13);
    cast_7 := to_signed(16#0000#, 13);
    cast := to_signed(16#0000#, 13);
    cast_5 := to_signed(16#0000#, 13);
    twdlIn_re := twiddleReg_re;
    twdlIn_im := twiddleReg_im;
    IF twdl45Reg = '1' THEN 
      CASE twdlOctantReg IS
        WHEN "000" =>
          twdlIn_re := to_signed(16#2D4#, 12);
          twdlIn_im := to_signed(-16#2D4#, 12);
        WHEN "010" =>
          twdlIn_re := to_signed(-16#2D4#, 12);
          twdlIn_im := to_signed(-16#2D4#, 12);
        WHEN "100" =>
          twdlIn_re := to_signed(-16#2D4#, 12);
          twdlIn_im := to_signed(16#2D4#, 12);
        WHEN OTHERS => 
          twdlIn_re := to_signed(16#2D4#, 12);
          twdlIn_im := to_signed(-16#2D4#, 12);
      END CASE;
    ELSE 
      CASE twdlOctantReg IS
        WHEN "000" =>
          NULL;
        WHEN "001" =>
          cast := resize(twiddleReg_im, 13);
          cast_0 :=  - (cast);
          twdlIn_re := cast_0(11 DOWNTO 0);
          cast_5 := resize(twiddleReg_re, 13);
          cast_6 :=  - (cast_5);
          twdlIn_im := cast_6(11 DOWNTO 0);
        WHEN "010" =>
          twdlIn_re := twiddleReg_im;
          cast_7 := resize(twiddleReg_re, 13);
          cast_8 :=  - (cast_7);
          twdlIn_im := cast_8(11 DOWNTO 0);
        WHEN "011" =>
          cast_1 := resize(twiddleReg_re, 13);
          cast_2 :=  - (cast_1);
          twdlIn_re := cast_2(11 DOWNTO 0);
          twdlIn_im := twiddleReg_im;
        WHEN "100" =>
          cast_3 := resize(twiddleReg_re, 13);
          cast_4 :=  - (cast_3);
          twdlIn_re := cast_4(11 DOWNTO 0);
          cast_9 := resize(twiddleReg_im, 13);
          cast_10 :=  - (cast_9);
          twdlIn_im := cast_10(11 DOWNTO 0);
        WHEN OTHERS => 
          twdlIn_re := twiddleReg_im;
          twdlIn_im := twiddleReg_re;
      END CASE;
    END IF;
    twdl_3_1_re_tmp <= twdlIn_re;
    twdl_3_1_im_tmp <= twdlIn_im;
  END PROCESS Radix22TwdlOctCorr_output;


  twdl_3_1_re <= std_logic_vector(twdl_3_1_re_tmp);

  twdl_3_1_im <= std_logic_vector(twdl_3_1_im_tmp);

END rtl;

