-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\hdl_model_fixed\Verify_divide_sizes.vhd
-- Created: 2024-12-15 20:50:14
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Verify_divide_sizes
-- Source Path: hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/Verify divide sizes
-- Hierarchy Level: 3
-- Model version: 1.30
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Verify_divide_sizes IS
  PORT( denominator                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        numerator                         :   IN    std_logic_vector(21 DOWNTO 0);  -- sfix22_En20
        den                               :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        num                               :   OUT   std_logic_vector(21 DOWNTO 0)  -- sfix22_En20
        );
END Verify_divide_sizes;


ARCHITECTURE rtl OF Verify_divide_sizes IS

  -- Signals
  SIGNAL denominator_signed               : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL numerator_signed                 : signed(21 DOWNTO 0);  -- sfix22_En20
  SIGNAL den_tmp                          : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL num_tmp                          : signed(21 DOWNTO 0);  -- sfix22_En20

BEGIN
  denominator_signed <= signed(denominator);

  numerator_signed <= signed(numerator);

  -- Verify that the dimensions of the input arrays match, and then reshape
  -- them.
  den_tmp <= denominator_signed;
  num_tmp <= numerator_signed;

  den <= std_logic_vector(den_tmp);

  num <= std_logic_vector(num_tmp);

END rtl;

