// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdl_model_fixed\Subsystem_ip2_src_ForEach_Real_Divide.v
// Created: 2024-12-16 16:15:42
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_ip2_src_ForEach_Real_Divide
// Source Path: hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide
// Hierarchy Level: 3
// Model version: 1.55
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_ip2_src_ForEach_Real_Divide
          (clk,
           reset,
           enb_1_2_0,
           enb_1_2_1,
           den,
           num,
           validIn,
           y,
           validOut);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   enb_1_2_1;
  input   signed [16:0] den;  // sfix17_En14
  input   signed [16:0] num;  // sfix17_En14
  input   validIn;
  output  signed [17:0] y;  // sfix18_En10
  output  validOut;


  wire signed [16:0] u;  // sfix17_En14
  wire signed [16:0] v;  // sfix17_En14
  reg signed [16:0] Delay14_bypass_reg;  // sfix17
  wire signed [16:0] Delay14_out1;  // sfix17_En14
  wire validIn_1;
  reg  Delay15_bypass_reg;  // ufix1
  wire Delay15_out1;
  wire signed [16:0] x;  // sfix17_En15
  wire signed [31:0] e;  // int32
  wire isNegative;
  reg signed [16:0] Delay25_out1;  // sfix17_En15
  reg signed [31:0] Delay26_out1;  // int32
  wire signed [16:0] num_out;  // sfix17_En15
  wire signed [32:0] t_num_out;  // sfix33
  reg signed [16:0] Delay16_out1;  // sfix17_En15
  reg signed [32:0] Delay17_out1;  // sfix33
  reg signed [16:0] Delay4_bypass_reg;  // sfix17
  wire signed [16:0] Delay4_out1;  // sfix17_En14
  wire signed [16:0] x_1;  // sfix17_En15
  wire signed [31:0] e_1;  // int32
  wire isNegative_1;
  wire validOut_1;
  reg signed [16:0] Delay9_reg [0:1];  // sfix17 [2]
  wire signed [16:0] Delay9_reg_next [0:1];  // sfix17_En15 [2]
  wire signed [16:0] Delay9_out1;  // sfix17_En15
  reg signed [31:0] Delay10_reg [0:1];  // sfix32 [2]
  wire signed [31:0] Delay10_reg_next [0:1];  // sfix32 [2]
  wire signed [31:0] Delay10_out1;  // int32
  reg  [1:0] Delay18_reg;  // ufix1 [2]
  wire Delay18_out1;
  reg  [1:0] Delay11_reg;  // ufix1 [2]
  wire Delay11_out1;
  reg  [1:0] Delay12_reg;  // ufix1 [2]
  wire Delay12_out1;
  wire signed [16:0] y_1;  // sfix17_En15
  wire signed [33:0] t;  // sfix34
  wire isDenZeroOut;
  wire validOut_2;
  reg  Unit_Delay_Enabled_Synchronous2_out1;
  wire Unit_Delay_Enabled_Synchronous2_ectrl;
  reg  [1:0] Delay2_reg;  // ufix1 [2]
  wire Delay2_out1;
  reg signed [16:0] Unit_Delay_Enabled_Synchronous_out1;  // sfix17_En15
  wire signed [16:0] Unit_Delay_Enabled_Synchronous_ectrl;  // sfix17_En15
  reg signed [33:0] Unit_Delay_Enabled_Synchronous1_out1;  // sfix34
  wire signed [33:0] Unit_Delay_Enabled_Synchronous1_ectrl;  // sfix34
  wire signed [17:0] Shift_and_cast_to_output_type_out1;  // sfix18_En10
  wire signed [17:0] Divide_by_zero_handler_out1;  // sfix18_En10
  wire signed [17:0] Switch_out1;  // sfix18_En10
  reg signed [17:0] Delay1_out1;  // sfix18_En10
  reg  Delay5_out1;
  reg  [1:0] Delay6_reg;  // ufix1 [2]
  wire Delay6_out1;
  reg  Delay7_out1;
  reg signed [31:0] Delay9_t_0_0;  // int32
  reg signed [31:0] Delay9_t_1;  // int32
  reg signed [31:0] Delay10_t_0_0;  // int32
  reg signed [31:0] Delay10_t_1;  // int32


  Subsystem_ip2_src_Upcast_Wordlength u_Upcast_Wordlength (.x(den),  // sfix17_En14
                                                           .y(num),  // sfix17_En14
                                                           .u(u),  // sfix17_En14
                                                           .v(v)  // sfix17_En14
                                                           );

  always @(posedge clk)
    begin : Delay14_bypass_process
      if (reset == 1'b1) begin
        Delay14_bypass_reg <= 17'sb00000000000000000;
      end
      else begin
        if (enb_1_2_1) begin
          Delay14_bypass_reg <= v;
        end
      end
    end

  assign Delay14_out1 = (enb_1_2_1 == 1'b1 ? v :
              Delay14_bypass_reg);



  assign validIn_1 = validIn;

  always @(posedge clk)
    begin : Delay15_bypass_process
      if (reset == 1'b1) begin
        Delay15_bypass_reg <= 1'b0;
      end
      else begin
        if (enb_1_2_1) begin
          Delay15_bypass_reg <= validIn_1;
        end
      end
    end

  assign Delay15_out1 = (enb_1_2_1 == 1'b1 ? validIn_1 :
              Delay15_bypass_reg);



  Subsystem_ip2_src_Normalize_numerator u_Normalize_numerator (.clk(clk),
                                                               .reset(reset),
                                                               .enb_1_2_0(enb_1_2_0),
                                                               .u(Delay14_out1),  // sfix17_En14
                                                               .validIn(Delay15_out1),
                                                               .x(x),  // sfix17_En15
                                                               .e(e),  // int32
                                                               .isNegative(isNegative)
                                                               );

  always @(posedge clk)
    begin : Delay25_process
      if (reset == 1'b1) begin
        Delay25_out1 <= 17'sb00000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay25_out1 <= x;
        end
      end
    end



  always @(posedge clk)
    begin : Delay26_process
      if (reset == 1'b1) begin
        Delay26_out1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay26_out1 <= e;
        end
      end
    end



  Subsystem_ip2_src_MATLAB_Function u_MATLAB_Function (.num(Delay25_out1),  // sfix17_En15
                                                       .t_num(Delay26_out1),  // int32
                                                       .num_out(num_out),  // sfix17_En15
                                                       .t_num_out(t_num_out)  // sfix33
                                                       );

  always @(posedge clk)
    begin : Delay16_process
      if (reset == 1'b1) begin
        Delay16_out1 <= 17'sb00000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay16_out1 <= num_out;
        end
      end
    end



  always @(posedge clk)
    begin : Delay17_process
      if (reset == 1'b1) begin
        Delay17_out1 <= 33'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay17_out1 <= t_num_out;
        end
      end
    end



  always @(posedge clk)
    begin : Delay4_bypass_process
      if (reset == 1'b1) begin
        Delay4_bypass_reg <= 17'sb00000000000000000;
      end
      else begin
        if (enb_1_2_1) begin
          Delay4_bypass_reg <= u;
        end
      end
    end

  assign Delay4_out1 = (enb_1_2_1 == 1'b1 ? u :
              Delay4_bypass_reg);



  Subsystem_ip2_src_Normalize_denominator u_Normalize_denominator (.clk(clk),
                                                                   .reset(reset),
                                                                   .enb_1_2_0(enb_1_2_0),
                                                                   .u(Delay4_out1),  // sfix17_En14
                                                                   .validIn(Delay15_out1),
                                                                   .x(x_1),  // sfix17_En15
                                                                   .e(e_1),  // int32
                                                                   .isNegative(isNegative_1),
                                                                   .validOut(validOut_1)
                                                                   );

  always @(posedge clk)
    begin : Delay9_process
      if (reset == 1'b1) begin
        for(Delay9_t_1 = 32'sd0; Delay9_t_1 <= 32'sd1; Delay9_t_1 = Delay9_t_1 + 32'sd1) begin
          Delay9_reg[Delay9_t_1] <= 17'sb00000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(Delay9_t_0_0 = 32'sd0; Delay9_t_0_0 <= 32'sd1; Delay9_t_0_0 = Delay9_t_0_0 + 32'sd1) begin
            Delay9_reg[Delay9_t_0_0] <= Delay9_reg_next[Delay9_t_0_0];
          end
        end
      end
    end

  assign Delay9_out1 = Delay9_reg[1];
  assign Delay9_reg_next[0] = x_1;
  assign Delay9_reg_next[1] = Delay9_reg[0];



  always @(posedge clk)
    begin : Delay10_process
      if (reset == 1'b1) begin
        for(Delay10_t_1 = 32'sd0; Delay10_t_1 <= 32'sd1; Delay10_t_1 = Delay10_t_1 + 32'sd1) begin
          Delay10_reg[Delay10_t_1] <= 32'sb00000000000000000000000000000000;
        end
      end
      else begin
        if (enb_1_2_0) begin
          for(Delay10_t_0_0 = 32'sd0; Delay10_t_0_0 <= 32'sd1; Delay10_t_0_0 = Delay10_t_0_0 + 32'sd1) begin
            Delay10_reg[Delay10_t_0_0] <= Delay10_reg_next[Delay10_t_0_0];
          end
        end
      end
    end

  assign Delay10_out1 = Delay10_reg[1];
  assign Delay10_reg_next[0] = e_1;
  assign Delay10_reg_next[1] = Delay10_reg[0];



  always @(posedge clk)
    begin : Delay18_process
      if (reset == 1'b1) begin
        Delay18_reg <= {2{1'b0}};
      end
      else begin
        if (enb_1_2_0) begin
          Delay18_reg[0] <= isNegative;
          Delay18_reg[1] <= Delay18_reg[0];
        end
      end
    end

  assign Delay18_out1 = Delay18_reg[1];



  always @(posedge clk)
    begin : Delay11_process
      if (reset == 1'b1) begin
        Delay11_reg <= {2{1'b0}};
      end
      else begin
        if (enb_1_2_0) begin
          Delay11_reg[0] <= isNegative_1;
          Delay11_reg[1] <= Delay11_reg[0];
        end
      end
    end

  assign Delay11_out1 = Delay11_reg[1];



  always @(posedge clk)
    begin : Delay12_process
      if (reset == 1'b1) begin
        Delay12_reg <= {2{1'b0}};
      end
      else begin
        if (enb_1_2_0) begin
          Delay12_reg[0] <= validOut_1;
          Delay12_reg[1] <= Delay12_reg[0];
        end
      end
    end

  assign Delay12_out1 = Delay12_reg[1];



  Subsystem_ip2_src_Divide_real_numerator_by_denominator u_Divide_real_numerator_by_denominator (.clk(clk),
                                                                                                 .reset(reset),
                                                                                                 .enb_1_2_0(enb_1_2_0),
                                                                                                 .num(Delay16_out1),  // sfix17_En15
                                                                                                 .tNum(Delay17_out1),  // sfix33
                                                                                                 .den(Delay9_out1),  // sfix17_En15
                                                                                                 .tDen(Delay10_out1),  // int32
                                                                                                 .isNumNegative(Delay18_out1),
                                                                                                 .isDenNegative(Delay11_out1),
                                                                                                 .validIn(Delay12_out1),
                                                                                                 .y(y_1),  // sfix17_En15
                                                                                                 .e(t),  // sfix34
                                                                                                 .isDenZero(isDenZeroOut),
                                                                                                 .validOut(validOut_2)
                                                                                                 );

  assign Unit_Delay_Enabled_Synchronous2_ectrl = (validOut_2 == 1'b0 ? Unit_Delay_Enabled_Synchronous2_out1 :
              isDenZeroOut);



  always @(posedge clk)
    begin : Unit_Delay_Enabled_Synchronous2_lowered_process
      if (reset == 1'b1) begin
        Unit_Delay_Enabled_Synchronous2_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Unit_Delay_Enabled_Synchronous2_out1 <= Unit_Delay_Enabled_Synchronous2_ectrl;
        end
      end
    end



  always @(posedge clk)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_reg <= {2{1'b0}};
      end
      else begin
        if (enb_1_2_0) begin
          Delay2_reg[0] <= Unit_Delay_Enabled_Synchronous2_out1;
          Delay2_reg[1] <= Delay2_reg[0];
        end
      end
    end

  assign Delay2_out1 = Delay2_reg[1];



  assign Unit_Delay_Enabled_Synchronous_ectrl = (validOut_2 == 1'b0 ? Unit_Delay_Enabled_Synchronous_out1 :
              y_1);



  always @(posedge clk)
    begin : Unit_Delay_Enabled_Synchronous_lowered_process
      if (reset == 1'b1) begin
        Unit_Delay_Enabled_Synchronous_out1 <= 17'sb00000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Unit_Delay_Enabled_Synchronous_out1 <= Unit_Delay_Enabled_Synchronous_ectrl;
        end
      end
    end



  assign Unit_Delay_Enabled_Synchronous1_ectrl = (validOut_2 == 1'b0 ? Unit_Delay_Enabled_Synchronous1_out1 :
              t);



  always @(posedge clk)
    begin : Unit_Delay_Enabled_Synchronous1_lowered_process
      if (reset == 1'b1) begin
        Unit_Delay_Enabled_Synchronous1_out1 <= 34'sh000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Unit_Delay_Enabled_Synchronous1_out1 <= Unit_Delay_Enabled_Synchronous1_ectrl;
        end
      end
    end



  Subsystem_ip2_src_Shift_and_cast_to_output_type u_Shift_and_cast_to_output_type (.clk(clk),
                                                                                   .reset(reset),
                                                                                   .enb_1_2_0(enb_1_2_0),
                                                                                   .x(Unit_Delay_Enabled_Synchronous_out1),  // sfix17_En15
                                                                                   .shiftValue(Unit_Delay_Enabled_Synchronous1_out1),  // sfix34
                                                                                   .y(Shift_and_cast_to_output_type_out1)  // sfix18_En10
                                                                                   );

  Subsystem_ip2_src_Divide_by_zero_handler u_Divide_by_zero_handler (.clk(clk),
                                                                     .reset(reset),
                                                                     .enb_1_2_0(enb_1_2_0),
                                                                     .yIn(Unit_Delay_Enabled_Synchronous_out1),  // sfix17_En15
                                                                     .yOut(Divide_by_zero_handler_out1)  // sfix18_En10
                                                                     );

  assign Switch_out1 = (Delay2_out1 == 1'b0 ? Shift_and_cast_to_output_type_out1 :
              Divide_by_zero_handler_out1);



  always @(posedge clk)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1 <= 18'sb000000000000000000;
      end
      else begin
        if (enb_1_2_0) begin
          Delay1_out1 <= Switch_out1;
        end
      end
    end



  assign y = Delay1_out1;

  always @(posedge clk)
    begin : Delay5_process
      if (reset == 1'b1) begin
        Delay5_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Delay5_out1 <= validOut_2;
        end
      end
    end



  always @(posedge clk)
    begin : Delay6_process
      if (reset == 1'b1) begin
        Delay6_reg <= {2{1'b0}};
      end
      else begin
        if (enb_1_2_0) begin
          Delay6_reg[0] <= Delay5_out1;
          Delay6_reg[1] <= Delay6_reg[0];
        end
      end
    end

  assign Delay6_out1 = Delay6_reg[1];



  always @(posedge clk)
    begin : Delay7_process
      if (reset == 1'b1) begin
        Delay7_out1 <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          Delay7_out1 <= Delay6_out1;
        end
      end
    end



  assign validOut = Delay7_out1;

endmodule  // Subsystem_ip2_src_ForEach_Real_Divide

