// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdl_model_fixed\Subsystem_ip2_src_BUF_MIN_MAX_AVG_tc.v
// Created: 2024-12-16 14:48:48
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_ip2_src_BUF_MIN_MAX_AVG_tc
// Source Path: BUF_MIN_MAX_AVG_tc
// Hierarchy Level: 1
// 
// Master clock enable input: clk_enable
// 
// enb         : identical to clk_enable
// enb_1_1_1   : identical to clk_enable
// enb_1_2048_0: 2048x slower than clk with last phase
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_ip2_src_BUF_MIN_MAX_AVG_tc
          (clk,
           reset,
           clk_enable,
           enb,
           enb_1_1_1,
           enb_1_2048_0);


  input   clk;
  input   reset;
  input   clk_enable;
  output  enb;
  output  enb_1_1_1;
  output  enb_1_2048_0;


  reg [10:0] count2048;  // ufix11
  wire comp_0_tmp;
  wire phase_0_tmp;
  reg  phase_0;
  wire enb_1_2048_0_1;


  assign enb = clk_enable;

  assign enb_1_1_1 = clk_enable;

  // Count limited, Unsigned Counter
  //  initial value   = 1
  //  step value      = 1
  //  count to value  = 2047
  always @(posedge clk)
    begin : counter_2048_process
      if (reset == 1'b1) begin
        count2048 <= 11'b00000000001;
      end
      else begin
        if (clk_enable) begin
          count2048 <= count2048 + 11'b00000000001;
        end
      end
    end



  assign comp_0_tmp = count2048 == 11'b11111111111;



  assign phase_0_tmp = comp_0_tmp & clk_enable;



  always @(posedge clk)
    begin : phase_delay_process
      if (reset == 1'b1) begin
        phase_0 <= 1'b0;
      end
      else begin
        if (clk_enable) begin
          phase_0 <= phase_0_tmp;
        end
      end
    end



  assign enb_1_2048_0_1 = phase_0 & clk_enable;



  assign enb_1_2048_0 = enb_1_2048_0_1;

endmodule  // Subsystem_ip2_src_BUF_MIN_MAX_AVG_tc

