// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdl_model_fixed\Subsystem_ip2_src_RADIX22FFT_CTRL1_5.v
// Created: 2024-12-16 16:15:42
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_ip2_src_RADIX22FFT_CTRL1_5
// Source Path: hdl_model_fixed/Subsystem1/FFT/RADIX22FFT_CTRL1_5
// Hierarchy Level: 2
// Model version: 1.55
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_ip2_src_RADIX22FFT_CTRL1_5
          (clk,
           reset,
           enb_1_2_0,
           dinXTwdl_5_1_vld,
           dinXTwdl_5_1_vld_1,
           syncReset,
           rd_5_Addr,
           rd_5_Enb,
           proc_5_enb);


  input   clk;
  input   reset;
  input   enb_1_2_0;
  input   dinXTwdl_5_1_vld;
  input   dinXTwdl_5_1_vld_1;
  input   syncReset;
  output  [5:0] rd_5_Addr;  // ufix6
  output  rd_5_Enb;
  output  proc_5_enb;


  reg [5:0] SDFController_wrCount;  // ufix6
  reg [1:0] SDFController_wrState;  // ufix2
  reg [1:0] SDFController_rdState;  // ufix2
  reg [5:0] SDFController_rdAddr_reg;  // ufix6
  reg  SDFController_procEnb_reg;
  reg [1:0] SDFController_multjState;  // ufix2
  reg  SDFController_multiply_J_reg;
  reg [5:0] SDFController_wrCount_next;  // ufix6
  reg [1:0] SDFController_wrState_next;  // ufix2
  reg [1:0] SDFController_rdState_next;  // ufix2
  reg [5:0] SDFController_rdAddr_reg_next;  // ufix6
  reg  SDFController_procEnb_reg_next;
  reg [1:0] SDFController_multjState_next;  // ufix2
  reg  SDFController_multiply_J_reg_next;
  reg [5:0] rd_5_Addr_1;  // ufix6
  reg  rd_5_Enb_1;
  reg  proc_5_enb_1;
  reg  multiply_5_J;


  // SDFController
  always @(posedge clk)
    begin : SDFController_process
      if (reset == 1'b1) begin
        SDFController_wrCount <= 6'b000000;
        SDFController_rdAddr_reg <= 6'b000000;
        SDFController_wrState <= 2'b00;
        SDFController_rdState <= 2'b00;
        SDFController_multjState <= 2'b00;
        SDFController_procEnb_reg <= 1'b0;
        SDFController_multiply_J_reg <= 1'b0;
      end
      else begin
        if (enb_1_2_0) begin
          if (syncReset == 1'b1) begin
            SDFController_wrCount <= 6'b000000;
            SDFController_rdAddr_reg <= 6'b000000;
            SDFController_wrState <= 2'b00;
            SDFController_rdState <= 2'b00;
            SDFController_multjState <= 2'b00;
            SDFController_procEnb_reg <= 1'b0;
            SDFController_multiply_J_reg <= 1'b0;
          end
          else begin
            SDFController_wrCount <= SDFController_wrCount_next;
            SDFController_wrState <= SDFController_wrState_next;
            SDFController_rdState <= SDFController_rdState_next;
            SDFController_rdAddr_reg <= SDFController_rdAddr_reg_next;
            SDFController_procEnb_reg <= SDFController_procEnb_reg_next;
            SDFController_multjState <= SDFController_multjState_next;
            SDFController_multiply_J_reg <= SDFController_multiply_J_reg_next;
          end
        end
      end
    end

  always @(SDFController_multiply_J_reg, SDFController_multjState,
       SDFController_procEnb_reg, SDFController_rdAddr_reg,
       SDFController_rdState, SDFController_wrCount, SDFController_wrState,
       dinXTwdl_5_1_vld, dinXTwdl_5_1_vld_1) begin
    SDFController_wrCount_next = SDFController_wrCount;
    SDFController_rdState_next = SDFController_rdState;
    SDFController_rdAddr_reg_next = SDFController_rdAddr_reg;
    SDFController_procEnb_reg_next = SDFController_procEnb_reg;
    SDFController_multjState_next = SDFController_multjState;
    case ( SDFController_multjState)
      2'b00 :
        begin
          SDFController_multjState_next = 2'b00;
          SDFController_multiply_J_reg_next = 1'b0;
          if (SDFController_rdState == 2'b01) begin
            SDFController_multjState_next = 2'b01;
          end
        end
      2'b01 :
        begin
          SDFController_multiply_J_reg_next = 1'b0;
          if (SDFController_rdState == 2'b10) begin
            SDFController_multjState_next = 2'b10;
          end
        end
      2'b10 :
        begin
          SDFController_multiply_J_reg_next = 1'b0;
          if (SDFController_rdState == 2'b01) begin
            SDFController_multjState_next = 2'b11;
            SDFController_multiply_J_reg_next = 1'b1;
          end
        end
      2'b11 :
        begin
          if (SDFController_rdState == 2'b01) begin
            SDFController_multjState_next = 2'b11;
            SDFController_multiply_J_reg_next = 1'b1;
          end
          else begin
            SDFController_multiply_J_reg_next = 1'b0;
            SDFController_multjState_next = 2'b00;
          end
        end
      default :
        begin
          SDFController_multjState_next = 2'b00;
          SDFController_multiply_J_reg_next = 1'b0;
        end
    endcase
    case ( SDFController_rdState)
      2'b00 :
        begin
          SDFController_rdState_next = 2'b00;
          SDFController_rdAddr_reg_next = 6'b000000;
          rd_5_Enb_1 = 1'b0;
          if (dinXTwdl_5_1_vld && (SDFController_wrCount == 6'b111111)) begin
            SDFController_rdState_next = 2'b01;
          end
        end
      2'b01 :
        begin
          SDFController_rdState_next = 2'b01;
          rd_5_Enb_1 = dinXTwdl_5_1_vld_1;
          if (dinXTwdl_5_1_vld_1) begin
            if (SDFController_rdAddr_reg == 6'b111111) begin
              SDFController_rdState_next = 2'b10;
            end
            SDFController_rdAddr_reg_next = SDFController_rdAddr_reg + 6'b000001;
          end
        end
      2'b10 :
        begin
          rd_5_Enb_1 = 1'b1;
          if (SDFController_rdAddr_reg == 6'b111111) begin
            if (dinXTwdl_5_1_vld && (SDFController_wrCount == 6'b111111)) begin
              SDFController_rdState_next = 2'b01;
            end
            else begin
              SDFController_rdState_next = 2'b00;
            end
          end
          SDFController_rdAddr_reg_next = SDFController_rdAddr_reg + 6'b000001;
        end
      default :
        begin
          SDFController_rdState_next = 2'b00;
          SDFController_rdAddr_reg_next = 6'b000000;
          rd_5_Enb_1 = 1'b0;
        end
    endcase
    case ( SDFController_wrState)
      2'b00 :
        begin
          SDFController_wrState_next = 2'b00;
          SDFController_wrCount_next = 6'b000000;
          SDFController_procEnb_reg_next = 1'b0;
          if (dinXTwdl_5_1_vld) begin
            SDFController_wrState_next = 2'b01;
            SDFController_wrCount_next = 6'b000001;
          end
        end
      2'b01 :
        begin
          SDFController_wrState_next = 2'b01;
          SDFController_procEnb_reg_next = 1'b0;
          if (dinXTwdl_5_1_vld) begin
            if (SDFController_wrCount == 6'b111111) begin
              SDFController_wrState_next = 2'b10;
              SDFController_procEnb_reg_next = 1'b1;
            end
            else begin
              SDFController_wrState_next = 2'b01;
            end
            SDFController_wrCount_next = SDFController_wrCount + 6'b000001;
          end
        end
      2'b10 :
        begin
          SDFController_wrState_next = 2'b10;
          if (dinXTwdl_5_1_vld) begin
            if (SDFController_wrCount == 6'b111111) begin
              SDFController_wrState_next = 2'b01;
              SDFController_procEnb_reg_next = 1'b0;
            end
            else begin
              SDFController_wrState_next = 2'b10;
              SDFController_procEnb_reg_next = 1'b1;
            end
            SDFController_wrCount_next = SDFController_wrCount + 6'b000001;
          end
        end
      default :
        begin
          SDFController_wrState_next = 2'b00;
          SDFController_wrCount_next = 6'b111111;
          SDFController_procEnb_reg_next = 1'b0;
        end
    endcase
    rd_5_Addr_1 = SDFController_rdAddr_reg;
    proc_5_enb_1 = SDFController_procEnb_reg;
    multiply_5_J = SDFController_multiply_J_reg;
  end



  assign rd_5_Addr = rd_5_Addr_1;

  assign rd_5_Enb = rd_5_Enb_1;

  assign proc_5_enb = proc_5_enb_1;

endmodule  // Subsystem_ip2_src_RADIX22FFT_CTRL1_5

