// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdl_model_fixed\Subsystem_ip2_dut.v
// Created: 2024-12-16 16:16:05
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_ip2_dut
// Source Path: Subsystem_ip2/Subsystem_ip2_dut
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_ip2_dut
          (clk,
           reset,
           dut_enable,
           Buffer,
           data_valid,
           user_reset,
           ce_out,
           FFT_Dat,
           FFT_Val,
           MAX,
           MIN,
           THD,
           RMS,
           VAL_OUT);


  input   clk;
  input   reset;
  input   dut_enable;  // ufix1
  input   signed [11:0] Buffer;  // sfix12_En11
  input   data_valid;  // ufix1
  input   user_reset;  // ufix1
  output  ce_out;  // ufix1
  output  signed [15:0] FFT_Dat;  // sfix16_En11
  output  FFT_Val;  // ufix1
  output  [15:0] MAX;  // ufix16_En16
  output  signed [15:0] MIN;  // sfix16_En15
  output  signed [17:0] THD;  // sfix18_En10
  output  [15:0] RMS;  // ufix16_En7
  output  VAL_OUT;  // ufix1


  wire enb;
  wire ce_out_sig;  // ufix1
  wire signed [15:0] FFT_Dat_sig;  // sfix16_En11
  wire FFT_Val_sig;  // ufix1
  wire [15:0] MAX_sig;  // ufix16_En16
  wire signed [15:0] MIN_sig;  // sfix16_En15
  wire signed [17:0] THD_sig;  // sfix18_En10
  wire [15:0] RMS_sig;  // ufix16_En7
  wire VAL_OUT_sig;  // ufix1


  assign enb = dut_enable;

  Subsystem_ip2_src_Subsystem1 u_Subsystem_ip2_src_Subsystem1 (.clk(clk),
                                                               .clk_enable(enb),
                                                               .reset(reset),
                                                               .Buffer(Buffer),  // sfix12_En11
                                                               .data_valid(data_valid),  // ufix1
                                                               .user_reset(user_reset),  // ufix1
                                                               .ce_out(ce_out_sig),  // ufix1
                                                               .FFT_Dat(FFT_Dat_sig),  // sfix16_En11
                                                               .FFT_Val(FFT_Val_sig),  // ufix1
                                                               .MAX(MAX_sig),  // ufix16_En16
                                                               .MIN(MIN_sig),  // sfix16_En15
                                                               .THD(THD_sig),  // sfix18_En10
                                                               .RMS(RMS_sig),  // ufix16_En7
                                                               .VAL_OUT(VAL_OUT_sig)  // ufix1
                                                               );

  assign ce_out = ce_out_sig;

  assign FFT_Dat = FFT_Dat_sig;

  assign FFT_Val = FFT_Val_sig;

  assign MAX = MAX_sig;

  assign MIN = MIN_sig;

  assign THD = THD_sig;

  assign RMS = RMS_sig;

  assign VAL_OUT = VAL_OUT_sig;

endmodule  // Subsystem_ip2_dut

