open_system('hdl_model_fixed');
open_system('gm_hdl_model_fixed');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
hilite_system('hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem Reference', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem Reference', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/myRMS', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/myRMS', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
hilite_system('hdl_model_fixed/Subsystem1/myRMS', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/myRMS', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('hdl_model_fixed/Subsystem1/S-R Flip-Flop', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/S-R Flip-Flop', 0, 1, 'Delays not moved across an unsupported block');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/S-R Flip-Flop', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/S-R Flip-Flop', 0, 1, 'Delays not moved across an unsupported block');
hilite_system('hdl_model_fixed/Subsystem1/S-R Flip-Flop', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/S-R Flip-Flop', 0, 1, 'Delays not moved across an unsupported block');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/Sample and Hold1', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/Sample and Hold1', 0, 1, 'Delays not moved into or out of a triggered subsystem');
hilite_system('hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/Sample and Hold1', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/Sample and Hold1', 0, 1, 'Delays not moved into or out of a triggered subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/Sample and Hold2', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/Sample and Hold2', 0, 1, 'Delays not moved into or out of a triggered subsystem');
hilite_system('hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/Sample and Hold2', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/Sample and Hold2', 0, 1, 'Delays not moved into or out of a triggered subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/MATLAB Function', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/MATLAB Function', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
hilite_system('hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/MATLAB Function', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/MATLAB Function', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/MATLAB Function1', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/MATLAB Function1', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
hilite_system('hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/MATLAB Function1', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/MATLAB Function1', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/NOT', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/NOT', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/NOT', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/NOT', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/S-R Flip-Flop', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/S-R Flip-Flop', 0, 1, 'Delays not moved across an unsupported block');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/S-R Flip-Flop', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/S-R Flip-Flop', 0, 1, 'Delays not moved across an unsupported block');
hilite_system('hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/S-R Flip-Flop', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/BUF_MIN_MAX_AVG/S-R Flip-Flop', 0, 1, 'Delays not moved across an unsupported block');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem/FFT', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem/FFT', 0, 1, 'Delays not moved across an unsupported block');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem/FFT', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem/FFT', 0, 1, 'Delays not moved across an unsupported block');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem/FFT', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem/FFT', 0, 1, 'Delays not moved across an unsupported block');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem/FFT', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem/FFT', 0, 1, 'Delays not moved across an unsupported block');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/CORDIC Square Root HDL Optimized', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/CORDIC Square Root HDL Optimized', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem Reference/CORDIC Square Root HDL Optimized', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/CORDIC Square Root HDL Optimized', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Sample and Hold', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Sample and Hold', 0, 1, 'Delays not moved into or out of a triggered subsystem');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem Reference/Sample and Hold', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Sample and Hold', 0, 1, 'Delays not moved into or out of a triggered subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Sample and Hold1', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Sample and Hold1', 0, 1, 'Delays not moved into or out of a triggered subsystem');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem Reference/Sample and Hold1', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Sample and Hold1', 0, 1, 'Delays not moved into or out of a triggered subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Sample and Hold2', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Sample and Hold2', 0, 1, 'Delays not moved into or out of a triggered subsystem');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem Reference/Sample and Hold2', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Sample and Hold2', 0, 1, 'Delays not moved into or out of a triggered subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Select_Freq', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Select_Freq', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem Reference/Select_Freq', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Select_Freq', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Multiply-Accumulate', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Multiply-Accumulate', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem Reference/Multiply-Accumulate', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Multiply-Accumulate', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('hdl_model_fixed/Subsystem1/Subsystem Reference/S-R Flip-Flop', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/S-R Flip-Flop', 0, 1, 'Delays not moved across an unsupported block');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/S-R Flip-Flop', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/S-R Flip-Flop', 0, 1, 'Delays not moved across an unsupported block');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem Reference/S-R Flip-Flop', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/S-R Flip-Flop', 0, 1, 'Delays not moved across an unsupported block');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex/CORDIC Square Root HDL Optimized1', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex/CORDIC Square Root HDL Optimized1', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex/CORDIC Square Root HDL Optimized1', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex/CORDIC Square Root HDL Optimized1', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex/CORDIC Square Root HDL Optimized1/Synchronous Subsystem', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex/CORDIC Square Root HDL Optimized1/Synchronous Subsystem', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex/CORDIC Square Root HDL Optimized1/Synchronous Subsystem', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex/CORDIC Square Root HDL Optimized1/Synchronous Subsystem', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex/CORDIC Square Root HDL Optimized1/Synchronous Subsystem/cordicSquareRootHDL', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex/CORDIC Square Root HDL Optimized1/Synchronous Subsystem/cordicSquareRootHDL', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex/CORDIC Square Root HDL Optimized1/Synchronous Subsystem/cordicSquareRootHDL', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Absolute of Complex/CORDIC Square Root HDL Optimized1/Synchronous Subsystem/cordicSquareRootHDL', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/CORDIC Square Root HDL Optimized/Synchronous Subsystem', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/CORDIC Square Root HDL Optimized/Synchronous Subsystem', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem Reference/CORDIC Square Root HDL Optimized/Synchronous Subsystem', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/CORDIC Square Root HDL Optimized/Synchronous Subsystem', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/CORDIC Square Root HDL Optimized/Synchronous Subsystem/cordicSquareRootHDL', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/CORDIC Square Root HDL Optimized/Synchronous Subsystem/cordicSquareRootHDL', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem Reference/CORDIC Square Root HDL Optimized/Synchronous Subsystem/cordicSquareRootHDL', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/CORDIC Square Root HDL Optimized/Synchronous Subsystem/cordicSquareRootHDL', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/Verify divide sizes', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/Verify divide sizes', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/Verify divide sizes', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/Verify divide sizes', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1/Normalize numerator', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1/Normalize numerator', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Normalize numerator', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Normalize numerator', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1/Normalize denominator', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1/Normalize denominator', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Normalize denominator', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Normalize denominator', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1/Divide real numerator by denominator', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1/Divide real numerator by denominator', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Divide real numerator by denominator', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Divide real numerator by denominator', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1/Divide by zero handler', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1/Divide by zero handler', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Divide by zero handler', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Divide by zero handler', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1/Upcast Wordlength', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1/Upcast Wordlength', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Upcast Wordlength', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Upcast Wordlength', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1/MATLAB Function', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1/MATLAB Function', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/MATLAB Function', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/MATLAB Function', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1/Normalize numerator/positiveRealNormalizer', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1/Normalize numerator/positiveRealNormalizer', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Normalize numerator/positiveRealNormalizer', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Normalize numerator/positiveRealNormalizer', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1/Normalize denominator/positiveRealNormalizer', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1/Normalize denominator/positiveRealNormalizer', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Normalize denominator/positiveRealNormalizer', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Normalize denominator/positiveRealNormalizer', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1/Divide real numerator by denominator/normalizedCORDICDivide', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1/Divide real numerator by denominator/normalizedCORDICDivide', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Divide real numerator by denominator/normalizedCORDICDivide', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Divide real numerator by denominator/normalizedCORDICDivide', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1/Divide by zero handler/Compare To Zero', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1/Divide by zero handler/Compare To Zero', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Divide by zero handler/Compare To Zero', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Divide by zero handler/Compare To Zero', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1/Divide by zero handler/Compare To Zero/Compare', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide_instance1/Divide by zero handler/Compare To Zero/Compare', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Divide by zero handler/Compare To Zero/Compare', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Divide by zero handler/Compare To Zero/Compare', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Select_Freq/NOT', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/Subsystem Reference/Select_Freq/NOT', 0, 1, 'Delays not moved across due to potential numerical mismatch');
hilite_system('hdl_model_fixed/Subsystem1/Subsystem Reference/Select_Freq/NOT', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/Subsystem Reference/Select_Freq/NOT', 0, 1, 'Delays not moved across due to potential numerical mismatch');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/myRMS/CORDIC Square Root HDL Optimized', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/myRMS/CORDIC Square Root HDL Optimized', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
hilite_system('hdl_model_fixed/Subsystem1/myRMS/CORDIC Square Root HDL Optimized', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/myRMS/CORDIC Square Root HDL Optimized', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/myRMS/Sample and Hold', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/myRMS/Sample and Hold', 0, 1, 'Delays not moved into or out of a triggered subsystem');
hilite_system('hdl_model_fixed/Subsystem1/myRMS/Sample and Hold', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/myRMS/Sample and Hold', 0, 1, 'Delays not moved into or out of a triggered subsystem');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/myRMS/Multiply-Accumulate', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/myRMS/Multiply-Accumulate', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
hilite_system('hdl_model_fixed/Subsystem1/myRMS/Multiply-Accumulate', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/myRMS/Multiply-Accumulate', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('hdl_model_fixed/Subsystem1/myRMS/S-R Flip-Flop', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/myRMS/S-R Flip-Flop', 0, 1, 'Delays not moved across an unsupported block');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/myRMS/S-R Flip-Flop', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/myRMS/S-R Flip-Flop', 0, 1, 'Delays not moved across an unsupported block');
hilite_system('hdl_model_fixed/Subsystem1/myRMS/S-R Flip-Flop', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/myRMS/S-R Flip-Flop', 0, 1, 'Delays not moved across an unsupported block');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/myRMS/CORDIC Square Root HDL Optimized/Synchronous Subsystem', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/myRMS/CORDIC Square Root HDL Optimized/Synchronous Subsystem', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
hilite_system('hdl_model_fixed/Subsystem1/myRMS/CORDIC Square Root HDL Optimized/Synchronous Subsystem', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/myRMS/CORDIC Square Root HDL Optimized/Synchronous Subsystem', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_hdl_model_fixed/Subsystem1/myRMS/CORDIC Square Root HDL Optimized/Synchronous Subsystem/cordicSquareRootHDL', 'user1');
annotate_port('gm_hdl_model_fixed/Subsystem1/myRMS/CORDIC Square Root HDL Optimized/Synchronous Subsystem/cordicSquareRootHDL', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
hilite_system('hdl_model_fixed/Subsystem1/myRMS/CORDIC Square Root HDL Optimized/Synchronous Subsystem/cordicSquareRootHDL', 'user1');
annotate_port('hdl_model_fixed/Subsystem1/myRMS/CORDIC Square Root HDL Optimized/Synchronous Subsystem/cordicSquareRootHDL', 0, 1, 'Delays not moved across due to non-zero or unknown initial value');
