// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdl_model_fixed\Subsystem_ip2_src_Divide_rea.v
// Created: 2024-12-20 15:38:10
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_ip2_src_Divide_rea

// Source Path: hdl_model_fixed/Subsystem1/Subsystem Reference/Real Divide HDL Optimized/ForEach - Real Divide/Divide 
// real numerator by denominato
// Hierarchy Level: 4
// Model version: 1.105
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_ip2_src_Divide_rea
          (clk,
           reset,
           enb,
           num,
           tNum,
           den,
           tDen,
           isNumNegative,
           isDenNegative,
           validIn,
           y_y,
           e_e,
           isDenZero,
           validOut);


  input   clk;
  input   reset;
  input   enb;
  input   signed [16:0] num;  // sfix17_En15
  input   signed [32:0] tNum;  // sfix33
  input   signed [16:0] den;  // sfix17_En15
  input   signed [31:0] tDen;  // int32
  input   isNumNegative;
  input   isDenNegative;
  input   validIn;
  output  signed [16:0] y_y;  // sfix17_En15
  output  signed [33:0] e_e;  // sfix34
  output  isDenZero;
  output  validOut;


  wire signed [33:0] t_t;  // sfix34
  wire isDenZeroOut;


  Subsystem_ip2_src_normalized normalizedCORDICDivide_1 (.clk(clk),
                                                         .reset(reset),
                                                         .enb(enb),
                                                         .num(num),  // sfix17_En15
                                                         .den(den),  // sfix17_En15
                                                         .tNum(tNum),  // sfix33
                                                         .tDen(tDen),  // int32
                                                         .isNumNegative(isNumNegative),
                                                         .isDenNegative(isDenNegative),
                                                         .validIn(validIn),
                                                         .y_y(y_y),  // sfix17_En15
                                                         .t_t(t_t),  // sfix34
                                                         .isDenZeroOut(isDenZeroOut),
                                                         .validOut(validOut)
                                                         );

  assign e_e = t_t;

  assign isDenZero = isDenZeroOut;

endmodule  // Subsystem_ip2_src_Divide_rea

