// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdl_model_fixed\Subsystem_ip2_addr_decoder.v
// Created: 2024-12-20 15:38:30
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_ip2_addr_decoder
// Source Path: Subsystem_ip2/Subsystem_ip2_axi_lite/Subsystem_ip2_addr_decoder
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_ip2_addr_decoder
          (clk,
           reset,
           data_write,
           addr_sel,
           wr_enb,
           rd_enb,
           read_ip_timestamp,
           read_MAX,
           read_MIN,
           read_THD,
           read_RMS,
           read_VAL_OUT,
           data_read,
           write_axi_enable,
           write_packet_size_axi4_stream_master,
           write_user_reset);


  input   clk;
  input   reset;
  input   [31:0] data_write;  // ufix32
  input   [13:0] addr_sel;  // ufix14
  input   wr_enb;  // ufix1
  input   rd_enb;  // ufix1
  input   [31:0] read_ip_timestamp;  // ufix32
  input   signed [15:0] read_MAX;  // sfix16_En11
  input   signed [15:0] read_MIN;  // sfix16_En11
  input   signed [15:0] read_THD;  // sfix16_En11
  input   signed [15:0] read_RMS;  // sfix16_En11
  input   read_VAL_OUT;  // ufix1
  output  [31:0] data_read;  // ufix32
  output  write_axi_enable;  // ufix1
  output  [31:0] write_packet_size_axi4_stream_master;  // ufix32
  output  write_user_reset;  // ufix1


  wire enb;
  wire decode_sel_ip_timestamp_1_1;  // ufix1
  wire [31:0] const_0;  // ufix32
  wire const_1;  // ufix1
  wire decode_sel_VAL_OUT_1_1;  // ufix1
  wire decode_sel_RMS_1_1;  // ufix1
  wire decode_sel_THD_1_1;  // ufix1
  wire decode_sel_MIN_1_1;  // ufix1
  wire decode_sel_MAX_1_1;  // ufix1
  reg [31:0] read_reg_ip_timestamp;  // ufix32
  wire [31:0] decode_rd_ip_timestamp_1_1;  // ufix32
  reg signed [15:0] read_reg_MAX;  // sfix16_En11
  wire [31:0] data_slice_MAX_1;  // ufix32
  wire [31:0] decode_rd_MAX_1_1;  // ufix32
  reg signed [15:0] read_reg_MIN;  // sfix16_En11
  wire [31:0] data_slice_MIN_1;  // ufix32
  wire [31:0] decode_rd_MIN_1_1;  // ufix32
  reg signed [15:0] read_reg_THD;  // sfix16_En11
  wire [31:0] data_slice_THD_1;  // ufix32
  wire [31:0] decode_rd_THD_1_1;  // ufix32
  reg signed [15:0] read_reg_RMS;  // sfix16_En11
  wire [31:0] data_slice_RMS_1;  // ufix32
  wire [31:0] decode_rd_RMS_1_1;  // ufix32
  reg  read_reg_VAL_OUT;  // ufix1
  wire [31:0] data_slice_VAL_OUT_1;  // ufix32
  wire [31:0] decode_rd_VAL_OUT_1_1;  // ufix32
  wire decode_sel_axi_enable_1_1;  // ufix1
  wire reg_enb_axi_enable_1_1;  // ufix1
  wire data_in_axi_enable;  // ufix1
  reg  data_reg_axi_enable_1_1;  // ufix1
  wire decode_sel_packet_size_axi4_stream_m;  // ufix1
  wire reg_enb_packet_size_axi4_stream_mast;  // ufix1
  reg [31:0] data_reg_packet_size_axi4_stream_mas;  // ufix32
  wire decode_sel_user_reset_1_1;  // ufix1
  wire reg_enb_user_reset_1_1;  // ufix1
  wire data_in_user_reset;  // ufix1
  reg  data_reg_user_reset_1_1;  // ufix1


  assign decode_sel_ip_timestamp_1_1 = addr_sel == 14'b00000000000011;



  assign const_0 = 32'b00000000000000000000000000000000;



  assign const_1 = 1'b1;



  assign enb = const_1;

  assign decode_sel_VAL_OUT_1_1 = addr_sel == 14'b00000001000101;



  assign decode_sel_RMS_1_1 = addr_sel == 14'b00000001000100;



  assign decode_sel_THD_1_1 = addr_sel == 14'b00000001000011;



  assign decode_sel_MIN_1_1 = addr_sel == 14'b00000001000010;



  assign decode_sel_MAX_1_1 = addr_sel == 14'b00000001000001;



  always @(posedge clk)
    begin : reg_ip_timestamp_process
      if (reset == 1'b1) begin
        read_reg_ip_timestamp <= 32'b00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          read_reg_ip_timestamp <= read_ip_timestamp;
        end
      end
    end



  assign decode_rd_ip_timestamp_1_1 = (decode_sel_ip_timestamp_1_1 == 1'b0 ? const_0 :
              read_reg_ip_timestamp);



  always @(posedge clk)
    begin : reg_MAX_process
      if (reset == 1'b1) begin
        read_reg_MAX <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          read_reg_MAX <= read_MAX;
        end
      end
    end



  assign data_slice_MAX_1 = {{16{read_reg_MAX[15]}}, read_reg_MAX};



  assign decode_rd_MAX_1_1 = (decode_sel_MAX_1_1 == 1'b0 ? decode_rd_ip_timestamp_1_1 :
              data_slice_MAX_1);



  always @(posedge clk)
    begin : reg_MIN_process
      if (reset == 1'b1) begin
        read_reg_MIN <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          read_reg_MIN <= read_MIN;
        end
      end
    end



  assign data_slice_MIN_1 = {{16{read_reg_MIN[15]}}, read_reg_MIN};



  assign decode_rd_MIN_1_1 = (decode_sel_MIN_1_1 == 1'b0 ? decode_rd_MAX_1_1 :
              data_slice_MIN_1);



  always @(posedge clk)
    begin : reg_THD_process
      if (reset == 1'b1) begin
        read_reg_THD <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          read_reg_THD <= read_THD;
        end
      end
    end



  assign data_slice_THD_1 = {{16{read_reg_THD[15]}}, read_reg_THD};



  assign decode_rd_THD_1_1 = (decode_sel_THD_1_1 == 1'b0 ? decode_rd_MIN_1_1 :
              data_slice_THD_1);



  always @(posedge clk)
    begin : reg_RMS_process
      if (reset == 1'b1) begin
        read_reg_RMS <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          read_reg_RMS <= read_RMS;
        end
      end
    end



  assign data_slice_RMS_1 = {{16{read_reg_RMS[15]}}, read_reg_RMS};



  assign decode_rd_RMS_1_1 = (decode_sel_RMS_1_1 == 1'b0 ? decode_rd_THD_1_1 :
              data_slice_RMS_1);



  always @(posedge clk)
    begin : reg_VAL_OUT_process
      if (reset == 1'b1) begin
        read_reg_VAL_OUT <= 1'b0;
      end
      else begin
        if (enb) begin
          read_reg_VAL_OUT <= read_VAL_OUT;
        end
      end
    end



  assign data_slice_VAL_OUT_1 = {31'b0, read_reg_VAL_OUT};



  assign decode_rd_VAL_OUT_1_1 = (decode_sel_VAL_OUT_1_1 == 1'b0 ? decode_rd_RMS_1_1 :
              data_slice_VAL_OUT_1);



  assign data_read = decode_rd_VAL_OUT_1_1;

  assign decode_sel_axi_enable_1_1 = addr_sel == 14'b00000000000001;



  assign reg_enb_axi_enable_1_1 = decode_sel_axi_enable_1_1 & wr_enb;



  assign data_in_axi_enable = data_write[0];



  always @(posedge clk)
    begin : reg_axi_enable_1_1_process
      if (reset == 1'b1) begin
        data_reg_axi_enable_1_1 <= 1'b1;
      end
      else begin
        if (enb && reg_enb_axi_enable_1_1) begin
          data_reg_axi_enable_1_1 <= data_in_axi_enable;
        end
      end
    end



  assign write_axi_enable = data_reg_axi_enable_1_1;

  assign decode_sel_packet_size_axi4_stream_m = addr_sel == 14'b00000000000010;



  assign reg_enb_packet_size_axi4_stream_mast = decode_sel_packet_size_axi4_stream_m & wr_enb;



  always @(posedge clk)
    begin : reg_packet_size_axi4_stream_master_11
      if (reset == 1'b1) begin
        data_reg_packet_size_axi4_stream_mas <= 32'b00000000000000000000100000000000;
      end
      else begin
        if (enb && reg_enb_packet_size_axi4_stream_mast) begin
          data_reg_packet_size_axi4_stream_mas <= data_write;
        end
      end
    end



  assign write_packet_size_axi4_stream_master = data_reg_packet_size_axi4_stream_mas;

  assign decode_sel_user_reset_1_1 = addr_sel == 14'b00000001000000;



  assign reg_enb_user_reset_1_1 = decode_sel_user_reset_1_1 & wr_enb;



  assign data_in_user_reset = data_write[0];



  always @(posedge clk)
    begin : reg_user_reset_1_1_process
      if (reset == 1'b1) begin
        data_reg_user_reset_1_1 <= 1'b0;
      end
      else begin
        if (enb && reg_enb_user_reset_1_1) begin
          data_reg_user_reset_1_1 <= data_in_user_reset;
        end
      end
    end



  assign write_user_reset = data_reg_user_reset_1_1;

endmodule  // Subsystem_ip2_addr_decoder

